### DISCUSSION TITLE
305 REST API Error

### DISCUSSION THREAD

**Discussion by gylraj** [processone/ejabberd#3574] [Questions] [answered]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 9.2`
- OS: Linux (Ubuntu)
- Installed from:  official deb/rpm

Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml
```yaml
language: "en"
hosts:
  - "chat.cs.com"
  - "saucey.cs.com"
  - "testcluster.cs.com"

loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

certfiles:
  - "/opt/ejabberd-18.12.1/conf/server.pem"
##  - "/etc/letsencrypt/live/localhost/fullchain.pem"
##  - "/etc/letsencrypt/live/localhost/privkey.pem"

ca_file: "/opt/ejabberd-18.12.1/conf/cacert.pem"

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: false
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    web_admin: true
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    http_bind: true    
    captcha: false
  -
    port: 5282
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    web_admin: true
    tls: true
    captcha: false
    http_bind: true
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
      "/bosh": mod_bosh
      # "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
    web_admin: true
    captcha: false
    tls: true

s2s_use_starttls: optional



auth_method: sql

# sm_db_type: sql

# default_db: sql

sql_type: mysql
sql_server: "111.11.11.11"
sql_database: "ejabberd"
sql_username: "ejabberd"
sql_password: "ejabberd"

sql_pool_size: 10
sql_keepalive_interval: 28800

new_sql_schema: true

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
  admin:
    user:
      - "admin@chat.cs.com"
      - "admin@testcluster.cs.com"
      - "saucey@testcluster.cs.com"

access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who: all
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
    what:
      - "*"
      - "!stop"
      - "!start"

shaper:
  normal: 50000
  fast: 50000

# shaper:
#   normal: 1000
#   fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - infinity
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast

max_fsm_queue: 10000

use_cache: true
cache_size: 20000
cache_life_time: 3600

acme:
   contact: "mailto:admin@chat.cs.com"
   ca_url: "https://acme-v01.api.letsencrypt.org"

modules:
  mod_offline_post: {}
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
    db_type: sql
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: 
    db_type: sql
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  # mod_fail2ban: {}
  mod_http_api: {}
  # mod_http_upload:
  #   put_url: "https://@HOST@:5443/upload"
  mod_last:
    db_type: sql
  mod_mam:
    db_type: sql
    use_cache: true
    default: always
    request_activates_archiving: false
    assume_mam_usage: false
  mod_muc:
    db_type: sql
    host: "room.@HOST@"
    access:
      - allow: all
    access_admin: ## all
      - allow: admin
    access_create: all
         ## - allow ## muc_create
    access_persistent: all
         ## - allow 
    max_user_conferences: 3000000
    max_users: 10000
    max_users_admin_threshold: 1000
    default_room_options:
      persistent: true
      allow_subscription: true
      allow_query_users: true
      allow_private_messages: true
      allow_user_invites: true
      allow_visitor_nickchange: true
      anonymous: false
      captcha_protected: false
      mam: true
      members_by_default: true
      members_only: false
      public: true
      public_list: true
  mod_muc_admin: {}
  mod_offline:
    db_type: sql
    access_max_user_messages: max_user_offline_messages
  mod_ping:
    send_pings: true
    ping_interval: 5
    ping_ack_timeout: 5
    timeout_action: kill
  mod_privacy:
    db_type: sql
    use_cache: true
    cache_size: 20000
  mod_private:
    db_type: sql
    use_cache: true
    cache_size: 20000
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    db_type: sql
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    max_items_node: 100
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
    force_node_config:
      ## Avoid using OMEMO by default because it
      ## introduces a lot of hard-to-track problems
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      ## Avoid buggy clients to make their bookmarks public
      "storage:bookmarks":
        access_model: whitelist
        max_items: 100
      "urn:xmpp:bookmarks:0":
        access_model: whitelist
        max_items: 100
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    # ip_access: trusted_network
    access: register
  mod_roster:
    versioning: true
    use_cache: true
    cache_size: 20000
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    max_ack_queue: infinity
    resume_timeout: 30
    resend_on_timeout: true
    max_resume_timeout: 30
  mod_time: {}
  mod_vcard:
    db_type: sql
    search: true 
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8
```

error.log

https://gist.githubusercontent.com/gylraj/152bb4a768c06650d51e420d61dd0b50/raw/18779f2de26afa755b4635ecaed10dc97f485732/error.log

https://gist.github.com/gylraj/152bb4a768c06650d51e420d61dd0b50#file-error-log

can you give me some idea to fix this error?
