### DISCUSSION TITLE
XEP-0384: OMEMO Encryption

### DISCUSSION THREAD

**Discussion by member7me** [processone/ejabberd#3575] [Questions] [answered]
Hello!
When generation OMEMO in Conversejs, receive such error

```xml
ERROR: 
<iq xml:lang="ru"
    to="testxmpp@domain.com/13849320229321296733219320483"
    from="testxmpp@domain.com"
    type="error"
    id="fe33e92d-1db3-4244-8cac-165c5aa431db:sendIQ"
    xmlns="jabber:client">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <items node="eu.siacs.conversations.axolotl.devicelist" />
  </pubsub>
  <error code="404"
         type="cancel">
    <item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
    <text xml:lang="ru"
          xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Узел не
          найден</text>
    <text xml:lang="en"
          xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Node not
          found</text>
  </error>
</iq>
```

What does it mean and why it's answering with 404 code? Ejabberd config seems to be correct with https://github.com/processone/ejabberd/issues/2425 (default). Pubsub is enabled.
And omemo seems to be working.
What does it error mean and how to correct it?

**Comment by licaon-kter** [comment]
So you have?
```
modules:
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: open
```

**Comment by member7me** [comment]
Yes, sir. I do.

Also tried default config
```
modules:
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: open
    storage:bookmarks:
        access_model: whitelist
```
It's patch for buggy clients.
