### DISCUSSION TITLE
Docker image: admin user not persistent

### DISCUSSION THREAD

**Discussion by pktl** [processone/ejabberd#3713] [Questions] [answered]
Hi,

I start an ejabberd container and register the admin user (following instructions here: https://hub.docker.com/r/ejabberd/ecs/ ). Actually, I'm splitting this into 2 steps to avoid exposing login credentials in the hosts history:
1. Launch interactive shell `docker exec -it ejabberd_app_1 sh`
2. Create account: `./bin/ejabberdctl register admin ...`

After `docker-compose down` then `docker-compose up -d`, the admin user is gone. Why is the admin account (and presumably any other account) not persistent? Did I miss something?

Also I added `default_db: mnesia` to the default `ejabberd.yml`, hoping that it would solve the issue. It didn't help.

The `docker-compose.yml` that I'm using:
```
version: "3"

volumes:
  conf:
  database:
  logs:
  upload:

networks:
  ejabberd_net:
    external: true

services:
  app:
    image: ejabberd/ecs
    restart: unless-stopped
    networks: ["ejabberd_net"]
    volumes:
      - conf:/home/ejabberd/conf
      - database:/home/ejabberd/database
      - logs:/home/ejabberd/logs
      - upload:/home/ejabberd/upload
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml
      - ./cert/fullchain.pem:/home/ejabberd/cert/fullchain.pem
      - ./cert/privkey.pem:/home/ejabberd/cert/privkey.pem
    ports:
      - "5222:5222"
      - "5443:5443"

```
Any ideas what might be the issue? Thanks!

**Comment by badlop** [comment]
> then docker-compose up -d

When ejabberd is started with an empty mnesia database directory, ejabberd creates the tables. If you start with "docker-compose up", you would see many like this:
```
sudo docker-compose up
Creating network "ecs_default" with the default driver
Creating volume "ecs_conf" with default driver
Creating volume "ecs_database" with default driver
Creating volume "ecs_logs" with default driver
Creating volume "ecs_upload" with default driver
Creating ecs_app_1 ... done
Attaching to ecs_app_1
...
app_1  | 2021-11-17 08:38:21.568820+00:00 [info] Creating Mnesia ram table 'ejabberd_commands'
app_1  | 2021-11-17 08:38:21.731059+00:00 [info] Creating Mnesia ram table 'route'
```

> After docker-compose down then docker-compose up -d, the admin user is gone. Why

Maybe your database volume is removed?
```
❯ docker-compose help down
Stops containers and removes containers, networks, volumes, and images
created by `up`.

By default, the only things removed are:

- Containers for services defined in the Compose file
- Networks defined in the `networks` section of the Compose file
- The default network, if one is used

Networks and volumes defined as `external` are never removed.
```

Check the mnesia spool files still exist in the database volume after you "docker-compose down". In my case it's:
> ls /var/lib/docker/volumes/ecs_database/_data/ejabberd\@localhost/

So, when you "up" again, the volume should be reused, and ejabberd should not recreate the mnesia database:
```
sudo docker-compose up
Creating network "ecs_default" with the default driver
Creating ecs_app_1 ... done
Attaching to ecs_app_1
...
app_1  | 2021-11-17 08:43:12.603062+00:00 [info] ejabberd 21.7.0 is started in the node ejabberd@localhost in 5.81s
```

**Comment by pktl** [comment, marked as answer]
> Check the mnesia spool files still exist in the database volume after you "docker-compose down".

Presumably, the volume is still there, but with every `docker-compose up` a new random nodename is created. This is in my database volume:
```
...
drwxr-sr-x 4 9000 9000  4096 Nov 16 20:56 ejabberd@1e5138ec4eff
drwxr-sr-x 4 9000 9000  4096 Nov 17 20:26 ejabberd@8fe14ffb385b
drwxr-sr-x 4 9000 9000  4096 Nov 16 21:03 ejabberd@bcb14a986921
drwxr-sr-x 4 9000 9000  4096 Nov 16 21:07 ejabberd@efb7640879fb
drwxr-sr-x 4 9000 9000  4096 Nov 16 20:16 ejabberd@f4f3cb50fd3b
...
```
I suppose, I should set `ERLANG_NODE=...` somewhere. Is that a valid variable for `docker-compose.yml`? I can't find any documentation for it here: https://hub.docker.com/r/ejabberd/ecs/

__Edit__: Adding a hostname in `docker-compose.yml` solves the problem.
```
services:
  app:
    image: ejabberd/ecs
    hostname: localhost
```
Found the solution here: https://github.com/processone/docker-ejabberd/issues/27

Thanks for your help!
