### DISCUSSION TITLE
Problems with `mod_pubsub`

### DISCUSSION THREAD

**Discussion by di72nn** [processone/ejabberd#3718] [Questions] [answered]
Hey!

I'm running a personal server (so problems may be detected and addressed quite late) and I've been having weird issues with `mod_pubsub`.
First, there was [this issue](https://github.com/processone/ejabberd/issues/3335) (but disabling `last_item_cache` seems to have solved it at the time).

Now I notice these errors in the log:
```
[error] <0.577.0>@mod_pubsub:get_transaction_response/1:3915 Transaction aborted:
** exception error: no case clause matching {odbc,true}
   in function  pubsub_node_config:'-encode/3-lc$^0/1-0-'/3 (src/pubsub_node_config.erl, line 222)
   in call from pubsub_node_config:'-encode/3-lc$^0/1-0-'/3 (src/pubsub_node_config.erl, line 423)
   in call from pubsub_node_config:encode/3 (src/pubsub_node_config.erl, line 423)
   in call from mod_pubsub:'-get_configure/5-fun-0-'/6 (src/mod_pubsub.erl, line 3302)
   in call from mod_pubsub:'-transaction/4-fun-0-'/3 (src/mod_pubsub.erl, line 3854)
   in call from mod_pubsub:'-do_transaction/4-fun-0-'/3 (src/mod_pubsub.erl, line 3876)
   in call from ejabberd_sql:execute_bloc/1 (src/ejabberd_sql.erl, line 571)
   in call from ejabberd_sql:run_sql_cmd/4 (src/ejabberd_sql.erl, line 488)
```
These appear when I connect with gajim (and presumably it tries to update OMEMO-related pubsub stuff, because other devices seems to quickly "forget" about this client when it leaves).

I'm running ejabberd 21.07, but I can see the errors in the log since at least 21.01 (with slightly different line numbers in different ejabberd versions).

Relevant config parts:
```YAML
default_db: sql
sql_type: mysql
...

modules:
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: false
    last_item_cache: false
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
```

I'm hoping the stacktrace will be enough to start figuring this out.
