### DISCUSSION TITLE
Setting up multi user chat (muc)

### DISCUSSION THREAD

**Discussion by ughstudios** [processone/ejabberd#3770] [Questions] [answered]
How do I setup and configure Ejabberd for MUC? I have been googling this for a few days now but I've found nothing useful. Is there a special setup I need to create for my domain as well?  Here is my xmpp domain: xmpp.ughstudios.com

How do I setup muc at: muc.xmpp.ughstudios.com. For the xmpp subdomain, I had to create some Server dns records. What do I need to do for MUC?

**Comment by badlop** [comment]
This was silently cross-posted at https://stackoverflow.com/questions/71041069/how-to-configure-multi-user-chat-mod-muc-for-ejabberd

**Comment by badlop** [comment, marked as answer]
> How do I setup and configure Ejabberd for MUC?

Usually mod_muc is already enabled and configured in ejabberd configuration file.

> I have been googling this for a few days now but I've found nothing useful. Is there a special setup I need to create for my domain as well? Here is my xmpp domain: xmpp.ughstudios.com How do I setup muc at: muc.xmpp.ughstudios.com. For the xmpp subdomain, I had to create some Server dns records. What do I need to do for MUC?

Right, you must setup DNS for your MUC service, similarly to the Pubsub service, the vjud service...

The exact name that your MUC service will take depends on what you configure. As explained in the [mod_muc documentation](https://docs.ejabberd.im/admin/configuration/modules/#mod-muc):

> hosts: [Host, ...]
> This option defines the Jabber IDs of the service. If the hosts option is not specified, the only Jabber ID will be the hostname of the virtual host with the prefix "conference.". The keyword @HOST@ is replaced with the real virtual host name.

So, by default it would be `conference.xmpp.ughstudios.com`. Probably you want to configure in ejabberd something like:
```yaml
modules:
  mod_muc:
    hosts: [muc.@HOST@]
```

> For the xmpp subdomain, I had to create some Server dns records. What do I need to do for MUC?

This is not a question specific to ejabberd's MUC... it's the same for other services like pubsub, and it's the same for other XMPP servers, and it's the same than any other internet thing. For example, see https://prosody.im/doc/dns#subdomains

**Reply by ughstudios** [reply]
I was able to do it like this (the indentation is off, but you get the point):
```
modules:
    mod_muc:
          hosts:
              - muc.xmpp.ughstudios.com
```

**Reply by badlop** [reply]
Ok, just one note: this works now because you have only one vhost defined in ejabberd.yml

But, if you add more hosts (for example `xmpp.studios.org` or whatever), then this will break ejabberd. Why? Because you are telling the MUC services of both hosts to use the same JID (`muc.xmpp.ughstudios.com`)

In that case, the solution will be to set `muc.@HOST@` instead of `muc.xmpp.ughstudios.com`

**Reply by paulo-roger** [reply]
Related to the `@HOST@` var.
could I do this?
```yml
        mod_disco:
          server_info:
            - modules: all
              name: abuse-addresses
              urls:
                - mailto:abuso@@HOST@
            - modules: all
              name: support-addresses
              urls:
                - mailto:suporte@@HOST@
            - modules: all
              name: admin-addresses
              urls:
                - mailto:ademir@@HOST@
 ```
