### DISCUSSION TITLE
External Auth Script does not start 21.12

### DISCUSSION THREAD

**Discussion by wahur666** [processone/ejabberd#3777] [Questions] [answered]
Hello,

I have some issues with the external auth script execution, with the version 21.12. This script still runs with 21.04 version. I attach an output from the docker container. Some info is redacted, but, if I run the script what should the program execute, it just runs fine outside. Any help would be appreciated.

```
2022-02-16 12:44:00.261282+00:00 [error] Failed to start external authentication program 'python3 /path/to/auth.py args1 args2 args3'
EjabberdService     | 2022-02-16 12:44:00.262018+00:00 [error] SUPERVISOR REPORT:
EjabberdService     |     supervisor: {local,'extauth_pool_<domain>'}
EjabberdService     |     errorContext: child_terminated
EjabberdService     |     reason: normal
EjabberdService     |     offender: [{pid,<0.874.0>},
EjabberdService     |                {id,'extauth_pool_<domain>_1'},
EjabberdService     |                {mfargs,{extauth,start_link,
EjabberdService     |                                 ['extauth_pool_<domain>_1',
EjabberdService     |                                  "python3 /path/to/auth.py args1 args2 args3"]}},
EjabberdService     |                {restart_type,permanent},
EjabberdService     |                {shutdown,5000},
EjabberdService     |                {child_type,worker}]
```

Corresponding ejabberd config section:

```yaml
host_config:
  <domain>:
    auth_method: [external]
    extauth_program: python3 /path/to/auth.py args1 args2 args3
    extauth_instances: 3
    auth_use_cache: false
```

Sincerely.
