### DISCUSSION TITLE
Enable user change password

### DISCUSSION THREAD

**Discussion by sigma2017** [processone/ejabberd#3903] [Questions] [answered]
Hello guys,

I have installed an ejabberd server on a vps  and looks like on the server side the "user change own password" option somehow is disabled.
Already tried conversation (android), gajim and pidgin. In conversation there is no chanage password option, in pidgin I found but is not working.
Can you please explain what I have to do on the server side into ejabberd yml file or maybe an ejabberdctl command to activate this server feature? Is not normal to don't give the user the possibility to change his own password.  I wasn't able to find a clear method, what exactly module to use and how to integrate it into yml file.

Thanks in advance!

**Comment by licaon-kter** [comment]
Can you clean up your config and put it on https://gist.github.com?

A simple setup like:
```
acl:
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128

access_rules:
  trusted_network:
    allow: loopback

mod_register:
  access: none
```
...allows you to keep your server private _(aka add users manually from the web admin or local command line)_ BUT users can change their passwords.

More info: https://docs.ejabberd.im/admin/

**Comment by sigma2017** [comment]
Hello,
Here is my config file:   https://gist.github.com/sigma2017/b355c61a2366705fc45bcf0b35fee947
The only thing which is missing from the config is mod_register:    access: none  as you suggested but even so, the server is private and only from https://example.com:5443/admin/  a new user can be created.
Here is a screenshot from conversations where from I suppose to find the option to change my password but is not there:
https://i.imgur.com/BCkzgGT.jpg

Any advice into the right direction will be much appreciated.

Thanks in advance.

**Comment by licaon-kter** [comment]
So you've added `mod_register` etc, then restarted the server, and on reconnect Conversations menu does not have that?

**Reply by sigma2017** [reply]
Exactly, I have added mod_register:    access: none , restarted ejabberd service and nothing happens.
I am using conversation 2.10.10.
Maybe an additional access_rule or api_permission is required in order to be able to change password, I really don't know :(

LE: It worked, thanks so much!

**Reply by badlop** [reply]
Can you add a response with the solution, so you can mark it as the solution (for anybody else that may find this problem)?

**Reply by sigma2017** [reply]
Adding mod_register:    access: none  solved the issue:
https://i.imgur.com/9Omp4sE.jpg
Just added it into modules section, just under mod_admin_extra, you may see the entire file above:
```
modules:
  mod_proxy65: {}
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_register:
    access: none
  mod_announce:
    access: announce
  mod_avatar: {}
```
I had to completely close the app and reopen it again in order to see the option.
You can mark this thread as answered / resolved.

Thanks for your support!
