### DISCUSSION TITLE
Disabling seemingly default services

### DISCUSSION THREAD

**Discussion by emilyyyylime** [processone/ejabberd#4076] [Questions] [answered]
I only need ejabberd's SIP support, but it seemed to be a great choice for my use case because it is well maintained, modern, and has the official `ejabberd/ecs` Docker image on DockerHub. I managed to configure ejabberd for SIP and it seems to work; but when I ran `docker ps` I was surprised to see despite my very minimal config the container is listening on more than just the SIP ports:
```
[...]   ejabberd/ecs:23.04   "/sbin/tini -- /home…"   38 minutes ago   Up 38 minutes   
 1883/tcp,
 4369-4399/tcp,
 5222/tcp,
 5269/tcp,
 5280/tcp, 5443/tcp,
 0.0.0.0:5060-5061->5060-5061/tcp,
 0.0.0.0:5060->5060/udp,
 :::5060-5061->5060-5061/tcp,
 :::5060->5060/udp
 [...]
```
I am assuming this is the result of the wide range of services supported by ejabberd, but I'd really prefer to have those disabled, as I have no use for them.

For reference, my config in its entirety is:
```yaml
hosts:
  - 0.0.0.0

modules:
  mod_sip: {}

listen:
  - port: 5060
    transport: udp
    module: ejabberd_sip
  - port: 5060
    module: ejabberd_sip
  - port: 5061
    module: ejabberd_sip
    tls: true
    certfile: /home/ejabberd/conf/server.pem
```
Any help would be greatly appreciated
