### DISCUSSION TITLE
Ejabberd 24.02, startup route_multicast warning

### DISCUSSION THREAD

**Discussion by firecow** [processone/ejabberd#4224] [Questions]
Hey, I'm getting this weird warning about `route_multicast` after upgrading from Ejabberd 23.10 to 24.02.

```
2024-05-23 06:55:40.147340+00:00 [info] Loading configuration from /opt/ejabberd/conf/ejabberd.yml
2024-05-23 06:55:45.394025+00:00 [warning] Unexpected info:
 {mnesia_table_event,
   {delete_object,
     {route_multicast,<<"example.com">>,<0.636.0>}, {tid,3356,<0.636.0>}}}
```

Here is my config.

<details>

```yml
# ejabberd-config.yml.j2
---
### https://docs.ejabberd.im/admin/configuration
hosts: ["{{ EJABBERD_HOST }}"]

loglevel: warning

auth_method: sql
auth_use_cache: false
auth_password_format: plain

sql_type: mysql
sql_server: "mysql"
sql_username: "ejabberd"
sql_password: "{{ DB_PASSWORD }}"
sql_keepalive_interval: 10
sql_pool_size: 5

host_config:
  "{{ EJABBERD_HOST }}":
    sql_database: "ejabberd"

acme:
  auto: false

listen:
  - port: 5282
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/": ejabberd_web_admin
  - port: 5281
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
      "/": mod_http_api
  - port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/": ejabberd_http_ws

acl:
  admin:
    user: ["admin@localhost"]

modules:
  mod_adhoc: { }
  mod_announce:
    access: [{ allow: admin }]
  mod_multicast: { }
  mod_muc:
    db_type: sql
    max_users: 100000
    access_admin: [{ allow: admin }]
    access_create: [{ allow: admin }]
    access_persistent: [{ allow: admin }]
    default_room_options:
      max_users: 100000
      allow_change_subj: false
      allowpm: 'none'
      allow_visitor_status: false
      allow_subscription: false
      allow_query_users: false
      allow_user_invites: false
      persistent: true
  mod_muc_admin: { }
  mod_mam:
    default: always
    db_type: sql
    clear_archive_on_room_destroy: false
  mod_admin_extra: { }
  mod_ping:
    send_pings: true
    ping_interval: 45s
    timeout_action: kill
  mod_http_api: { }

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
      - mod_http_api
    who: all
    what: "*"
  "admin access":
    who: all
    what:
      - "*"
```

</details>

 We use `mod_multicast` quite extensively.

Do I have any config errors? 
Should I just ignore this error?
