### DISCUSSION TITLE
Setting up an XMPP-Matrix bridge

### DISCUSSION THREAD

**Discussion by Eirikr70** [processone/ejabberd#4298] [Questions] [answered]
Hello,
I run a Docker-ECS XMPP setup that works fine. I am trying to set up a bridge with Matrix. I have followed [this blog post](https://www.process-one.net/blog/matrix-gateway-setup-with-ejabberd/), and that step is ok. I have declared SRV directives ... But the federation tester shows `Get "https://xx.xx.xx.xx:8448/_matrix/key/v2/server": dial tcp xx.xx.xx.xx:8448: connect: connection refused`.
I suppose I have further steps to go but I don't know which. Could someone show me the way ?
My docker-compose.yaml
```
services:
  ejabberd:
    image: ejabberd/ecs
    container_name: jabber
    environment:
      - TZ="Europe/Paris"
      - PUID=1000
      - PGID=1000
    ports:
      - 3479:3478/tcp
      - 3479:3478/udp
      - 5222:5222
      - 5223:5223
      - 5269:5269
      - 5280:5280
      - 5443:5443
      - 49273-49393:49273-49393/udp
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml
      - /srv/nas/ejabberd/database:/home/ejabberd/database
      - ./logrotate:/etc/logrotate.d
      - /home/eric/swag/config/etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      jabber:
        ipv4_address: 10.10.11.2
networks:
  jabber:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.11.0/24
          gateway: 10.10.11.1
```
My ejabberd.yml
```
###
###              ejabberd configuration file
###
### The parameters used in this configuration file are explained at
###
###       https://docs.ejabberd.im/admin/configuration
###
### The configuration file is written in YAML.
### *******************************************************
### *******           !!! WARNING !!!               *******
### *******     YAML IS INDENTATION SENSITIVE       *******
### ******* MAKE SURE YOU INDENT SECTIONS CORRECTLY *******
### *******************************************************
### Refer to http://en.wikipedia.org/wiki/YAML for the brief description.
###

hosts:
  - jabber.mydomain.tld

loglevel: info

language: fr

## If you already have certificates, list them here
certfiles:
  - /etc/letsencrypt/archive/mydomain.tld/fullchain1.pem
  - /etc/letsencrypt/archive/mydomain.tld/privkey1.pem
  - /etc/letsencrypt/archive/mydomain.tld/cert1.pem
  - /etc/letsencrypt/archive/mydomain.tld/chain1.pem

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5223
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    tls: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
    shaper: s2s_shaper
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      /admin: ejabberd_web_admin
      /api: mod_http_api
      /bosh: mod_bosh
      /captcha: ejabberd_captcha
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /.well-known/acme-challenge: ejabberd_acme
  -
    port: 3478
    ip: "::"
    transport: udp
    module: ejabberd_stun
    use_turn: true
    ## The server's public IPv4 address:
    turn_ipv4_address: "xx.xx.xx.xx"
    ## The server's public IPv6 address:
#     turn_ipv6_address: "xx:xx:xx"
    turn_min_port: 49273
    turn_max_port: 49393
#     turn_blacklist:
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000
  -
    port: 8448
    module: ejabberd_http
    tls: true
    request_handlers:
      "/_matrix": mod_matrix_gw

s2s_access: s2s

s2s_use_starttls: required

######################

acme:
  auto: true

# auth_method:
#  - mnesia

######################

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
  s2s:
    - allow # to allow Matrix federation

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          - acl: loopback
          - acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number

shaper:
  normal:
    rate: 3000
    burst_size: 20000
  fast: 100000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban:
    c2s_auth_ban_lifetime: 14400
    c2s_max_auth_failures: 5
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
    custom_headers:
      "Access-Control-Allow-Origin": "https://@HOST@"
      "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type"
  mod_last: {}
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    ## db_type: sql
    assume_mam_usage: true
    default: always
###
  mod_matrix_gw:
    matrix_domain: "matrix.jabber.mydomain.tld"
    key_name: "key1"
    key: "my_very_secret_key"
###
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      mam: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_stun_disco: {}
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8
```
And my init logs
```
jabber  | 
jabber  | 15:01:13.893 [info] Loading configuration from /home/ejabberd/conf/ejabberd.yml
jabber  | 
jabber  | 15:01:13.914 [notice] Changing loglevel from 'debug' to 'info'
jabber  | 
jabber  | 15:01:14.264 [info] Configuration loaded successfully
jabber  | 
jabber  | 15:01:14.739 [info] Got no NOTIFY_SOCKET, notifications disabled
jabber  | 
jabber  | 15:01:15.174 [info] Loading modules for jabber.mydomain.tld
jabber  | 
jabber  | 15:01:15.178 [warning] Mnesia backend for mod_mam is not recommended: it's limited to 2GB and often gets corrupted when reaching this limit. SQL backend is recommended. Namely, for small servers SQLite is a preferred choice because it's very easy to configure.
jabber  | 
jabber  | 15:01:15.283 [info] Going to offer STUN/TURN service: xx.xx.xx.xx:3478 (udp)
jabber  | 
jabber  | 15:01:15.445 [info] Building MQTT cache for jabber.mydomain.tld, this may take a while
jabber  | 
jabber  | 15:01:15.452 [warning] The option captcha_cmd is not configured, but some module wants to use the CAPTCHA feature.
jabber  | 
jabber  | 15:01:15.519 [info] Waiting for Mnesia synchronization to complete
jabber  | 
jabber  | 15:01:15.601 [info] ejabberd 24.7.0 is started in the node :ejabberd@localhost in 1.79s
jabber  | 
jabber  | 15:01:15.655 [info] Start accepting TCP connections at [::]:5222 for :ejabberd_c2s
jabber  | 
jabber  | 15:01:15.655 [info] Start accepting TLS connections at [::]:5223 for :ejabberd_c2s
jabber  | 
jabber  | 15:01:15.655 [info] Start accepting UDP connections at [::]:3478 for :ejabberd_stun
jabber  | 
jabber  | 15:01:15.655 [info] Start accepting TLS connections at [::]:5443 for :ejabberd_http
jabber  | 
jabber  | 15:01:15.655 [info] Start accepting TCP connections at [::]:5269 for :ejabberd_s2s_in
jabber  | 
jabber  | 15:01:15.655 [info] Start accepting TCP connections at [::]:5280 for :ejabberd_http
jabber  | 
jabber  | 15:01:15.655 [info] Start accepting TCP connections at 0.0.0.0:8448 for :ejabberd_http
jabber  | 
jabber  | 15:01:15.655 [info] Start accepting TCP connections at 10.10.11.2:7777 for :mod_proxy65_stream
jabber  | 
jabber  | 15:01:15.655 [info] Start accepting TCP connections at [::]:1883 for :mod_mqtt
jabber  | 
jabber  | 15:01:28.797 [info] (#PID<0.755.0>) Accepted connection [::ffff:yy.yy.yy.yy]:43536 -> [::ffff:10.10.11.2]:5223
```
