### DISCUSSION TITLE
ejabberdctl not showing vcard command

### DISCUSSION THREAD

**Discussion by schoerg** [processone/ejabberd#4363] [Questions] [answered]
I have Debian 12 with ejabberd 23.01-1 running, but ejabberctl is not showing the vcard command:

```
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
```

I run this command as root:

```
chat01:~# ejabberdctl help commands
Available tags and commands details:

  accounts
    register user host password
    registered_users host
    unregister user host

  acme
    list_certificates
    request_certificate domains
    revoke_certificate file

  cluster
    join_cluster node
    leave_cluster node
    list_cluster
    set_master nodename

  config
    convert_to_yaml in out
    dump_config out
    reload_config

  documentation
    gen_html_doc_for_commands file regexp examples
    gen_markdown_doc_for_commands file regexp examples
    gen_markdown_doc_for_tags file
    man

  logs
    get_loglevel
    reopen_log
    rotate_log
    set_loglevel loglevel

  mam
    remove_mam_for_user user host
    remove_mam_for_user_with_peer user host with

  mnesia
    backup file
    delete_mnesia host
    dump file
    dump_table file table
    export2sql host file
    export_piefxis dir
    export_piefxis_host dir host
    import_dir file
    import_file file
    import_piefxis file
    import_prosody dir
    install_fallback file
    load file
    mnesia_change_nodename oldnodename newnodename oldbackup newbackup
    mnesia_info
    mnesia_table_info table
    restore file

  modules
    module_check module
    module_install module
    module_uninstall module
    module_upgrade module
    modules_available
    modules_installed
    modules_update_specs

  muc
    create_rooms_file file
    destroy_rooms_file file
    get_user_rooms user host
    get_user_subscriptions user host
    muc_online_rooms service
    muc_online_rooms_by_regex service regex
    muc_register_nick nick jid service
    muc_unregister_nick jid service
    rooms_empty_destroy service
    rooms_empty_list service
    rooms_unused_destroy service days
    rooms_unused_list service days

  muc_room
    change_room_option name service option value
    create_room name service host
    create_room_with_opts name service host options
    destroy_room name service
    get_room_affiliation name service jid
    get_room_affiliations name service
    get_room_occupants name service
    get_room_occupants_number name service
    get_room_options name service
    get_subscribers name service
    send_direct_invitation name service password reason users
    set_room_affiliation name service jid affiliation
    subscribe_room user nick room nodes
    subscribe_room_many users room nodes
    unsubscribe_room user room

  oauth
    oauth_add_client_implicit client_id client_name redirect_uri
    oauth_add_client_password client_id client_name secret
    oauth_issue_token jid ttl scopes
    oauth_list_tokens
    oauth_remove_client client_id
    oauth_revoke_token token

  private
    bookmarks_to_pep user host

  purge
    abort_delete_old_mam_messages host
    abort_delete_old_messages host
    delete_expired_messages
    delete_expired_pubsub_items
    delete_old_mam_messages type days
    delete_old_mam_messages_batch host type days batch_size rate
    delete_old_mam_messages_status host
    delete_old_messages days
    delete_old_messages_batch host days batch_size rate
    delete_old_messages_status host
    delete_old_pubsub_items number
    delete_old_push_sessions days

  s2s
    incoming_s2s_number
    outgoing_s2s_number
    stop_s2s_connections

  server
    clear_cache
    gc
    registered_vhosts
    restart
    status
    stop
    stop_kindly delay announcement
    update module
    update_list

  session
    connected_users
    connected_users_number
    kick_user user host
    user_resources user host

  sql
    convert_to_scram host
    import_prosody dir

  statistics
    connected_users_number
    incoming_s2s_number
    outgoing_s2s_number

```

```
modules: 
  mod_adhoc: []
  mod_announce: 
    access: announce
  mod_carboncopy: []
  mod_caps: []
  mod_configure: []
  mod_client_state: []
  mod_disco: []
  mod_bosh: []
  mod_last: []
  mod_muc: 
    access: muc
    access_create: muc
    access_persistent: muc
    access_admin: muc_admin
    max_users: 500
  mod_offline: []
  mod_privacy: []
  mod_private: []
  mod_proxy65: 
    access: local
    shaper: c2s_shaper
  mod_pubsub: []
  mod_mam: []
  mod_register: 
    welcome_message: 
      subject: "Welcome!"
      body: "Welcome to a Jabber service powered by Debian. For information about Jabber visit http://www.jabber.org"
    access: register
  mod_roster: []
  mod_shared_roster: []
  mod_stats: []
  mod_time: []
  mod_vcard: []
  mod_version: []
  mod_vcard_xupdate: {}
  mod_muc_admin: {}
  mod_push: {}
  mod_stream_mgmt: {}

```

What seems to be the issue here?
