### ISSUE TITLE
undefined function mod_shared_roster_ldap:is_user_in_group

### ISSUE THREAD

**Issue by rhansen** [processone/ejabberd#1012]
I configured my ejabberd server with `mod_shared_roster_ldap`, which works great.  I tried to set up an ACL for one of the shared roster groups and use it for `mod_muc`'s `access_admin` setting, but that caused a crash:

```
2016-03-15 16:22:56.595 [info] <0.1881.0>@mod_muc_room:terminate:856
 Stopping MUC room chat@conference.example.com
2016-03-15 16:22:56.596 [error] <0.1881.0> gen_fsm <0.1881.0> in state normal_state terminated with reason:
 call to undefined function mod_shared_roster_ldap:is_user_in_group/3 from lists:any/2 line 1210
2016-03-15 16:22:56.596 [error] <0.1881.0> CRASH REPORT Process <0.1881.0> with 0 neighbours exited with reason:
 call to undefined function mod_shared_roster_ldap:is_user_in_group({<<"username">>,<<"example.com">>}, <<"groupname">>, <<"example.com">>)
 in gen_fsm:terminate/7 line 622
2016-03-15 16:22:56.596 [error] <0.384.0> Supervisor 'ejabberd_mod_muc_sup_example.com' had child undefined
 started with {mod_muc_room,start_link,undefined} at <0.1881.0>
 exit with reason call to undefined function mod_shared_roster_ldap:is_user_in_group({<<"username">>,<<"example.com">>}, <<"groupname">>, <<"example.com">>)
 in context child_terminated
```

After that the room no longer existed and I couldn't join it.

Here are the relevant parts of my config:

```
auth_method: ldap
ldap_servers:
  - "ldap.example.com"
ldap_tls_verify: hard
ldap_tls_cacertfile: "/etc/ssl/certs/ca-certificates.crt"
ldap_rootdn: "cn=xmpp,ou=computers,dc=example,dc=com"
ldap_password: "secret"
ldap_base: "ou=users,dc=example,dc=com"
ldap_filter: "(!(|(shadowLastChange=0)(loginShell=/usr/sbin/nologin)(loginShell=/bin/false)))"

acl:
  chatadmins:
    shared_group: "chat-admins"

access:
  muc_admin:
    admin: allow
    chatadmins: allow

modules:
  mod_muc:
    access_admin: muc_admin
  mod_shared_roster: {}
  mod_shared_roster_ldap:
    # use defaults for ldap_base, ldap_ufilter, ldap_gfilter,
    # ldap_filter, ldap_groupdesc, ldap_memberattr_format
    ldap_rfilter: "(&(objectClass=inetOrgPerson)(ou=*))"
    ldap_groupattr: "ou"
    ldap_memberattr: "uid"
    ldap_userdesc: "displayName"
    ldap_useruid: "uid"
    ldap_auth_check: off
```

Here's an example LDIF:

```
# example.com
dn: dc=example,dc=com
dc: example
o: example.com
objectClass: dcObject
objectClass: organization
objectClass: top

# users, example.com
dn: ou=users,dc=example,dc=com
objectClass: organizationalUnit
objectClass: top
ou: users

# foobar, users, example.com
dn: cn=foobar,ou=users,dc=example,dc=com
cn: foobar
displayName: Foo Bar
gecos: Foo Bar
gidNumber: 1000
givenName: Foo
homeDirectory: /home/foobar
loginShell: /bin/bash
mail: foobar@example.com
o: Example, Inc.
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
objectClass: top
ou: Group 1
shadowLastChange: 16676
sn: Bar
uid: foobar
uidNumber: 1000
userPassword:: e0NSWVBUfSQ2JG8xTHR3YUgub2ZMUjhlYXQkcDhxSVNoNC9LZkVHYjUvaUsyVm9Ua2FWTE1QMTZZempqTXlZYnhvNXouZ2pSclBlbkhqZ1JFTTNvd2VTeWJubDdQUjdUYzZMdlVJLnlTb3NJMnlLbi4=

# asdfjkl, users, example.com
dn: cn=asdfjkl,ou=users,dc=example,dc=com
cn: asdfjkl
displayName: Asdf Jkl
gecos: Asdf Jkl
gidNumber: 1001
givenName: Asdf
homeDirectory: /home/asdfjkl
loginShell: /bin/bash
mail: asdfjkl@example.com
o: Example, Inc.
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
objectClass: top
ou: Group 2
shadowLastChange: 0
sn: Jkl
uid: asdfjkl
uidNumber: 1001
userPassword:: e0NSWVBUfSQ2JG8xTHR3YUgub2ZMUjhlYXQkcDhxSVNoNC9LZkVHYjUvaUsyVm9Ua2FWTE1QMTZZempqTXlZYnhvNXouZ2pSclBlbkhqZ1JFTTNvd2VTeWJubDdQUjdUYzZMdlVJLnlTb3NJMnlLbi4=

# quiop, users, example.com
dn: cn=quiop,ou=users,dc=example,dc=com
cn: quiop
displayName: Qwerty Uiop
gecos: Qwerty Uiop
gidNumber: 1002
givenName: Qwerty
homeDirectory: /home/quiop
loginShell: /bin/bash
mail: quiop@example.com
o: Example, Inc.
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
objectClass: top
ou: Group 2
shadowLastChange: 12345
sn: Uiop
uid: quiop
uidNumber: 1002
userPassword:: e0NSWVBUfSQ2JG8xTHR3YUgub2ZMUjhlYXQkcDhxSVNoNC9LZkVHYjUvaUsyVm9Ua2FWTE1QMTZZempqTXlZYnhvNXouZ2pSclBlbkhqZ1JFTTNvd2VTeWJubDdQUjdUYzZMdlVJLnlTb3NJMnlLbi4=
```

> What version of ejabberd are you using?

15.03

> What operating system (version) are you using?

Ubuntu 14.04 (Trusty) 64-bit server

> How did you install ejabberd (source, package, distribution)?

Ubuntu 15.10 (Wily) packages backported to 14.04 (Trusty) and uploaded to my PPA:
https://launchpad.net/~rhansen/+archive/ubuntu/ejabberd

> What did not work as expected? Are there error messages in the log? What was the unexpected behavior? What was the expected result?

I expected users in the "chat-admins" shared roster group to be given admin access to all chat rooms.  Instead, once one of the users in the "chat-admins" group tried listing available rooms the chat room stopped working (it didn't appear in the room list and nobody was able to join or create it).
