### ISSUE TITLE
mod_http_upload_quota error log

### ISSUE THREAD

**Issue by suchatorg** [processone/ejabberd#1025]
> What version of ejabberd are you using?

Ejabberd Master (17/03/2016)

> What operating system (version) are you using?

Debian 7

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What

```
2016-03-19 00:37:57.560 [error] <0.490.0>@mod_http_upload_quota:handle_info:234
 Cannot open document root /root/upload: no such file or directory
```
Config:
```
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    certfile: "/etc/ejabberd/server.pem"
    request_handlers:
      "": mod_http_upload
....
access:
  soft_upload_quota:
    all: 400
  hard_upload_quota:
    all: 500
....
  mod_http_upload: 
    docroot: "/home/yo/upload"
    put_url: "https://@HOST@:5443"
  mod_http_upload_quota: 
    max_days: 100
......
```

**Comment by badlop** [comment]
I configured the modules like you did. I also applied this patch:
```
--- a/src/mod_http_upload_quota.erl
+++ b/src/mod_http_upload_quota.erl
@@ -133,6 +133,7 @@ init({ServerHost, Opts}) ->
                                      <<"@HOME@/upload">>),
     DocRoot2 = mod_http_upload:expand_home(str:strip(DocRoot1, right, $/)),
     DocRoot3 = mod_http_upload:expand_host(DocRoot2, ServerHost),
+    ?INFO_MSG("DocRoot3 for host '~p': ~p", [ServerHost, DocRoot3]),
     Timers = if MaxDays == infinity -> [];
                true ->
                     {ok, T1} = timer:send_after(?INITIAL_TIMEOUT, sweep),
```

and this is what I get in the log file:
```
...
18:10:12.299 [info] DocRoot3 for host '<<"header1.org">>': <<"/home/yo/upload">>
18:10:12.429 [info] DocRoot3 for host '<<"header2.org">>': <<"/home/yo/upload">>
18:10:12.501 [info] DocRoot3 for host '<<"localhost">>': <<"/home/yo/upload">>
18:10:12.607 [info] DocRoot3 for host '<<"noheader.org">>': <<"/home/yo/upload">>
18:10:12.645 [info] ejabberd 16.02.74 is started in the node ejabberd@localhost
18:10:12.645 [info] Application ejabberd started on node ejabberd@localhost
```

In your case, the docroot option isn't read from your configuration file when starting the module for one of your vhosts, so the default option value is used (which is a path that doesn't exist in your machine).

Try to add the debug line like I did, recompile ejabberd, start it, see what your log provides, and maybe it gives you some clue why your option isn't read.

If you still have no clue, post here your full configuration file and I'll try to reproduce the problem in my server.

**Comment by suchatorg** [comment]
[info] <0.484.0>@mod_http_upload_quota:init:136 DocRoot3 for host '<<"suchat.org">>': <<"/root/upload">>
[info] <0.7.0> Application iconv started on node ejabberd@localhost

ejabberd run in root

**Comment by suchatorg** [comment]
```
###
###               ejabberd configuration file
###
###
loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

hosts:
  - "suchat.org"
listen: 
  - 
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 131072
    shaper: c2s_shaper
    access: c2s
    starttls: true
    ## starttls_required: true
    certfile: "/etc/ejabberd/server.pem"
    dhfile: "/etc/ejabberd/dhparams.pem"
    resend_on_timeout: if_offline
    zlib: true

    ## Custom OpenSSL options
    ##
    protocol_options:
    - "no_sslv3"
    ##   - "no_tlsv1"
    ciphers: "HIGH+kEDH:HIGH+kEECDH:HIGH:!PSK:!SRP:!3DES:!aNULL"
  - 
    port: 443
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 131072
    shaper: c2s_shaper
    access: c2s
    starttls: true
    ## starttls_required: true
    certfile: "/etc/ejabberd/server.pem"
    dhfile: "/etc/ejabberd/dhparams.pem"
    resend_on_timeout: if_offline
    zlib: true

    ## Custom OpenSSL options
    ##
    protocol_options:
    - "no_sslv3"
    ##   - "no_tlsv1"
    ciphers: "HIGH+kEDH:HIGH+kEECDH:HIGH:!PSK:!SRP:!3DES:!aNULL"
  - 
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    shaper: s2s_shaper
  - 
    port: 3478
    ip: "::"
    module: ejabberd_stun
    transport: udp
    use_turn: true
    turn_ip: "84.39.103.247"
    turn_min_port: 49152
    turn_max_port: 50000
  - 
    port: 3478
    ip: "::"
    module: ejabberd_stun
    use_turn: true
    turn_ip: "84.39.103.247"
    turn_min_port: 49152
    turn_max_port: 50000
  - 
    port: 5349
    ip: "::"
    module: ejabberd_stun
    tls: true
    use_turn: true
    turn_ip: "84.39.103.247"
    turn_min_port: 49152
    turn_max_port: 50000
    certfile: "/etc/ejabberd/server.pem"
  -
    port: 5060
    ip: "::"
    module: ejabberd_sip
    transport: udp
  -
    port: 5060
    ip: "::"
    module: ejabberd_sip
  -
    port: 5061
    ip: "::"
    module: ejabberd_sip
    tls: true
    certfile: "/etc/ejabberd/server.pem"
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    certfile: "/etc/ejabberd/server.pem"
    request_handlers:
      "": mod_http_upload
     "presence": mod_webpresence
  - 
    port: 5281
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
    captcha: true
    register: true
    certfile: "/etc/ejabberd/server.pem"
    tls: true
    websocket_timeout: 3600

s2s_use_starttls: optional
s2s_ciphers: "HIGH+kEDH:HIGH+kEECDH:HIGH:!PSK:!SRP:!3DES:!aNULL"
s2s_tls_compression: false
##
## s2s_certfile: Specify a certificate file.
##
s2s_certfile: "/etc/ejabberd/server.pem"
s2s_dhfile: "/etc/ejabberd/dhparams.pem"
## Custom OpenSSL options
##
s2s_protocol_options:
- "no_sslv3"

outgoing_s2s_families:
  - ipv4
  - ipv6
outgoing_s2s_timeout: 10000

auth_method: odbc
odbc_type: mysql
odbc_server: "localhost"
odbc_database: "ejabberd"
odbc_username: "user"
odbc_password: "******"
odbc_port: 3306
odbc_pool_size: 10
odbc_keepalive_interval: 28800
shaper:
  normal: 2000
  fast: 50000
max_fsm_queue: 1000
acl:
  admin:
    user:
      - "carlos": "suchat.org"
  proxy_users: 
    server: 
      - "suchat.org"
  paying_customers:
    server: 
      - "suchat.org"
  local: 
    user_regexp: ""
  loopback: 
    ip:
      - "127.0.0.0/8"
      - "::1"
access:
  soft_upload_quota:
    all: 400
  hard_upload_quota:
    all: 500
  announce:
    admin: allow
  irc_users:
    paying_customers: allow
    all: deny
  proxy65_access: 
    proxy_users: allow
    all: deny
  proxy65_shaper: 
    admin: none
    proxy_users: proxyrate
  max_user_sessions: 
    all: 10
  max_user_offline_messages: 
    admin: 5000
    all: 100
  local: 
    local: allow
  c2s: 
    blocked: deny
    all: allow
  c2s_shaper: 
    admin: none
    all: normal
  s2s_shaper: 
    all: fast
  announce: 
    admin: allow
  configure: 
    admin: allow
  muc_admin: 
    admin: allow
  muc_create: 
    local: allow
  muc: 
    all: allow
  pubsub_createnode: 
    local: allow
  register: 
    all: allow
  trusted_network: 
    loopback: allow
registration_timeout: 600
language: "es"
captcha_cmd: "/lib/ejabberd-0.0/priv/bin/captcha.sh"
captcha_host: "https://suchat.org:5281"
captcha_limit: 5
modules: 
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    db_type: odbc
    access: announce
  mod_blocking: {} # requires mod_privacy  
  mod_caps: 
    db_type: odbc
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  ## mod_echo: {}
  mod_irc:  
    db_type: odbc
    access: irc_users
  ## mod_http_fileserver:
  ##   docroot: "/var/www"
  ##   accesslog: "/opt/ejabberd-0.0/logs/access.log"
  mod_last:
    db_type: odbc
  mod_muc: 
    db_type: odbc
    host: "salas.@HOST@"
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
  ## mod_muc_log: {}
  mod_offline: 
    db_type: odbc
    access_max_user_messages: max_user_offline_messages
  mod_ping: 
    send_pings: true
    ping_interval: 900
    timeout_action: kill
  mod_pres_counter: 
    count: 5
    interval: 60
  mod_privacy: 
    db_type: odbc  
  mod_private: 
    db_type: odbc  
  mod_proxy65: 
    max_connections: 20
    access: proxy65_access
    shaper: proxy65_shaper
  mod_pubsub: 
    db_type: odbc  
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    plugins: 
      - "flat"
      - "hometree"
      - "pep"
  mod_mix: {}
  mod_register: 
    captcha_protected: true
    welcome_message: 
      subject: "Bienvenida!"
      body: |-
        Hola.
        En SUChat.org te damos la bienvenida.
    access: register
  mod_roster: 
    db_type: odbc
    versioning: true
    store_current_id: true
  mod_stats: {}
  mod_time: {}
  mod_mam: 
    db_type: odbc
    default: roster
  mod_vcard_xupdate: 
    db_type: odbc
  mod_vcard: 
    db_type: odbc
    search: false
  mod_version: {}
  mod_sic: {}
  mod_sip: {}
  mod_fail2ban: {}
  mod_http_upload: 
    docroot: "/home/suso/upload"
    put_url: "https://@HOST@:5443"
  mod_http_upload_quota: 
    max_days: 100
allow_contrib_modules: true
### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8
```

**Comment by weiss** [comment]
`mod_http_upload` was previously available as an ejabberd-contrib module.  Did you install that?  If so, an old configuration snippet might be used.  If that's the issue, running `ejabberdctl module_uninstall mod_http_upload` and restarting ejabberd would help.

**Comment by suchatorg** [comment]
No utilice el mod_http_upload ejabberd-contrib.

ejabberdctl module_uninstall mod_http_upload
Error: not_installed

I use Erlang / OTP 18.3, can be the problem?

**Comment by suchatorg** [comment]
I did not use the mod_http_upload ejabberd-contrib.

ejabberdctl module_uninstall mod_http_upload
Error: not_installed

I use Erlang / OTP 18.3, can be the problem?

**Comment by suchatorg** [comment]
I did not use the mod_http_upload ejabberd-contrib.

ejabberdctl module_uninstall mod_http_upload
Error: not_installed

I use Erlang / OTP 18.3, can be the problem?

**Comment by suchatorg** [comment]
I did not use the mod_http_upload ejabberd-contrib.

ejabberdctl module_uninstall mod_http_upload
Error: not_installed

I use Erlang / OTP 18.3, can be the problem?

**Comment by suchatorg** [comment]
Temporarily solved by the following change mod_http_upload_quota.erl.

-  DocRoot1 = gen_mod:get_module_opt(ServerHost, mod_http_upload, docroot,
+ DocRoot1= gen_mod:get_module_opt(ServerHost, ?MODULE, docroot,


```
  mod_http_upload: 
    docroot: "/home/yo/upload"
    put_url: "https://@HOST@:5443"
  mod_http_upload_quota: 
    max_days: 100
    docroot: "/home/yo/upload"
```

Result log:
[info] <0.484.0>@mod_http_upload_quota:init:136 DocRoot3 for host '<<"suchat.org">>': <<"/home/yo/upload">>
