### ISSUE TITLE
mod_shared_roster_ldap broken in ejabberd 16.02

### ISSUE THREAD

**Issue by debalance** [processone/ejabberd#1034]
Hi,

it seems that with ejabberd 16.02 mod_shared_roster_ldap got broken.

2 completely independent cases are described here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818931

In both cases a temporary workaround was to use mod_shared_roster_ldap.beam from 16.01

**Comment by mremond** [comment]
Do you have a ldif and configuration we can use to troubleshot the issue ?

**Comment by debalance** [comment]
I can give you my config but I'm not sure how to create an appropriate ldif:
 ```
 mod_shared_roster_ldap:
    ldap_auth_check: off
    ldap_base: "dc=my-company,dc=com"
    ldap_rfilter: "(&(objectClass=posixGroup)(cn=ihiwis))"
    ldap_gfilter: "(&(objectClass=posixGroup)(cn=%g))"
    ldap_groupdesc: "cn"
    ldap_groupattr: "cn"
    ldap_memberattr: "memberUid"
    ldap_ufilter: "(cn=%u)"
    ldap_userdesc: "gecos"
    ldap_useruid: "cn"
```
