### ISSUE TITLE
mod_http_api and basic authentication (no OAuth)

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#1042]
> What version of ejabberd are you using?

16.02

> What operating system (version) are you using?

Debian 8.3

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I trying to use mod_http_api without OAuth, only with basic authentication and I always have error "400 Bad Request". I configured mod_http_api just like here https://github.com/processone/ejabberd-contrib/issues/153#issuecomment-195083275 and https://github.com/processone/ejabberd-contrib/issues/159#issuecomment-201061774 :
```
listen:
  - ip: "::"
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api

access:
  rest:
    rest: allow

acl:
  rest:
    user:
      - "bot": "domain.tld"

commands_admin_access: rest
commands:
  add_commands:
    - status
    - send_message
```

There is no errors in log, I don't know what I doing wrong :(
