### ISSUE TITLE
muc messages are not stored via mam

### ISSUE THREAD

**Issue by mapama** [processone/ejabberd#1081]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

Debian jessie (backports)

For some of my rooms, conversations shows in the conference details "XEP-0313: MAM" yes, for some others no. It seems that for those rooms created before mam was configured there is a no displayed, while for those created afterwards there is a yes. So is this as expected? Do I have to recreate a room in order to have mam running for this room?

mod_muc is configured like this:
```
mod_muc:
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
    default_room_options:
      mam: true
```

Maybe this is similar to #1058. I don't know.

Thank you very much.

Patrik
