### ISSUE TITLE
ejabberd occasionally loses database communication

### ISSUE THREAD

**Issue by systemidx** [processone/ejabberd#1149]
**> What version of ejabberd are you using?**
16.04

**> What operating system (version) are you using?**
Windows 2008r2

**> How did you install ejabberd (source, package, distribution)?**
Installer

**> What did not work as expected? Are there error messages in the log? What was the unexpected behavior? What was the expected result?**
Occasionally, ejabberd will become unresponsive and need to be restarted. This is the stacktrace that is found in the logs:

```
Problem 'error {case_clause,
                   [{xmlel,<<>>,[],[]},
                    {xmlel,<<"error">>,
                        [{<<"code">>,<<"500">>},{<<"type">>,<<"wait">>}],
                        [{xmlel,<<"internal-server-error">>,
                             [{<<"xmlns">>,
                               <<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],
                             []},
                         {xmlel,<<"text">>,
                             [{<<"xmlns">>,
                               <<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],
                             [{xmlcdata,<<"Database failure">>}]}]}]}' occurred executing the command.
Stacktrace: [{mod_admin_extra,set_vcard_content,4,
                              [{file,"src/mod_admin_extra.erl"},{line,1006}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,324}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,247}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,225}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,206}]}]
```

Here is the configuration:
```
loglevel: 4
log_rotate_size: 0
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 1000

hosts:
  - "hostname"

listen:
  -
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
    web_admin: true
    http_bind: true
    tls: true
    certfile: "C:\\path\\to\\server.pem"
    captcha: false

auth_password_format: plain
disable_sasl_mechanisms:
    - "digest-md5"
    - "scram-sha-1"

auth_method: http
auth_opts:
  host: "https://somehost"
  connection_pool_size: 10
  connection_opts: []
  basic_auth: ""
  path_prefix: "/v1/"

default_db: sql
sql_type: odbc
sql_server: "DSN=ejabberd64;UID=something;PWD=something"
sql_database: "jabber"
sql_pool_size: 10
sql_keepalive_interval: 60

shaper:
  normal: 10000
  fast: 100000

max_fsm_queue: 1000

acl:
  admin:
    user:
      - "admin": "hostname"

  local:
    user_regexp: ""

  loopback:
    ip:
      - "127.0.0.0/8"

access:
  ## Maximum number of simultaneous sessions allowed for a single user:
  max_user_sessions:
    all: 10
  ## Maximum number of offline messages that users can have:
  max_user_offline_messages:
    admin: 5000
    all: 100
  ## This rule allows access only for local users:
  local:
    local: allow
  ## Only non-blocked users can use c2s connections:
  c2s:
    blocked: deny
    all: allow
  ## For C2S connections, all users except admins use the "normal" shaper
  c2s_shaper:
    admin: none
    all: normal
  ## All S2S connections use the "fast" shaper
  s2s_shaper:
    all: fast
  ## Only admins can send announcement messages:
  announce:
    admin: allow
  ## Only admins can use the configuration interface:
  configure:
    admin: allow
  ## Admins of this server are also admins of the MUC service:
  muc_admin:
    admin: allow
  ## Only accounts of the local ejabberd server can create rooms:
  muc_create:
    local: allow
  ## All users are allowed to use the MUC service:
  muc:
    all: allow
  ## Only accounts on the local ejabberd server can create Pubsub nodes:
  pubsub_createnode:
    local: allow
  ## In-band registration allows registration of any possible username.
  ## To disable in-band registration, replace 'allow' with 'deny'.
  register:
    all: allow
  ## Only allow to register from localhost
  trusted_network:
    loopback: allow

language: "en"

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy:
    db_type: mnesia
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  ## mod_echo: {}
  ## mod_irc: {}
  mod_http_bind: {}
  ## mod_http_fileserver:
  ##   docroot: "/var/www"
  ##   accesslog: "C:\\Program Files\\ejabberd-16.04\\logs\\access.log"
  mod_last: {}
  mod_mam:
    default: always
    db_type: sql
    assume_mam_usage: if_enabled
  mod_muc:
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
    default_room_options:
      mam: true
  mod_muc_admin: {}
  ## mod_muc_log: {}
  ## mod_multicast: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  ## mod_pres_counter:
  ##   count: 5
  ##   interval: 60
  mod_privacy: {}
  mod_private: {}
  ## mod_proxy65: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ##ignore_pep_from_offline: false
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
  mod_register: {}
  # ejabberd_auth_http: {}
  mod_roster: {}
  # mod_roster:
  #   db_type: odbc
  mod_shared_roster: {}
  ## mod_stats: {}
  ## mod_time: {}
  mod_vcard: {}
  mod_version: {}

allow_contrib_modules: true
```

We are currently using MS SQL as our backend store. This issue used to be much more frequent until I added the keep alive with a 60 second interval. It happens less frequently now, but is still problematic when it does occur.
