### ISSUE TITLE
Ejabberd crashes trying to access web admin

### ISSUE THREAD

**Issue by Sagnaic** [processone/ejabberd#1171]
Hi
   All
        I am trying to access ejabberd web admin by visiting http://mydomain:5280/admin and i get a blank page. After checking the log file, i found that ejabberd crashes. The crash is immediate after visiting the web admin URL. This happens when i commented **## access: register in mod_register: block.**

**The crash report->**

2016-06-25 08:35:24 =CRASH REPORT====
crasher:
initial call: application_master:init/4
pid: <0.37.0>
registered_name: []
exception exit:
{{bad_return,{{ejabberd_app,start,[normal,[]]},{'EXIT',{function_clause,[{lists,map,[#Fun,register],[{file,"lists.erl"},{line,1237}]},{ejabberd_config,transform_module_options,2,[{file,"src/ejabberd_config.erl"},{line,1095}]},{ejabberd_config,'-replace_modules/1-fun-0-',1,[{file,"src/ejabberd_config.erl"},{line,993}]},{lists,map,2,[{file,"lists.erl"},{line,1238}]},{ejabberd_config,process_host_term,4,[{file,"src/ejabberd_config.erl"},{line,646}]},{lists,foldl,3,[{file,"lists.erl"},{line,1262}]},{ejabberd_config,read_file,2,[{file,"src/ejabberd_config.erl"},{line,162}]},{ejabberd_config,start,0,[{file,"src/ejabberd_config.erl"},{line,60}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
ancestors: [<0.36.0>]
messages: []
links: [<0.36.0>,<0.38.0>,<0.7.0>]
dictionary: []
trap_exit: true
status: running
heap_size: 1598
stack_size: 27
reductions: 189
neighbours:

But when i enable the **access: register in mod_register: block** , i get the following error and ejabberd does not start at all.

2016-06-25 08:35:24.452 [error] <0.37.0> CRASH REPORT Process <0.37.0> with 0 neighbours exited with reason: no function clause matching lists:map(#Fun, register) line 1237 in
application_master:init/4 line 134

I have installed latest ejabberd(**ejabberd-16.04) through installer** in Ubuntu 14 and using mysql as database.

**ejabberd config file ejabberd.yml**

Attached
[ejabberd.txt](https://github.com/processone/ejabberd/files/339519/ejabberd.txt)

Thanks
Sagnaic

**Comment by badlop** [comment]
In line 532, fix indentation, it should be something like
```
host_config:
  "mydomain":
```

In line 654, fix indentation when you enable the access option, it should be inside the mod_register:
```
  mod_register:
    ##
    ## Only clients in the server machine can register accounts
    ##
    ip_access: trusted_network

    ##
    ## Local c2s or remote s2s users cannot register accounts
    ##
    ## access_from: deny

    ##access: register
    access: register
  mod_roster:
```
