### ISSUE TITLE
http admin api always returns "Unauthorized: Account Unpriviledged" response

### ISSUE THREAD

**Issue by themaverick777** [processone/ejabberd#1190]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Windows 8.1

> How did you install ejabberd (source, package, distribution)?

ejabberd windows installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am new to ejabberd. I have enabled xmlrpc api for server administration. But I need to get response in Json format for parsing the result. So i tried using the rest http admin api using basic
authentication mode, but i'm always getting 'Unauthorized: Account Unpriviledged' response when 
calling the Api. I'm using Postman for testing the endpoints and my configuration is as below:
```
  - 
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/log": mod_log_http
      # OAuth support:
      "/oauth": ejabberd_oauth
      # ReST API:
      "/api": mod_http_api
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    register: true
    captcha: false
    commands_admin_access: configure
    commands:
      add_commands: user
    oauth_expire: 3600
    oauth_access: all	
```

ACL:
```
acl:
  admin:
    user:
      - "admin": "myserver" 
  local: 
    user_regexp: ""

  loopback:
    ip:
      - "127.0.0.0/8"
```

Access rules:
```
access:
  ...
  configure: 
    admin: allow
  register: 
    all: allow
  trusted_network: 
    loopback: allow
  xmlrpc:
    admin: allow	
  ...
```
I'm not sure if the configuration is correct, in case I missed anything...but after testing different configurations still no luck.
