### ISSUE TITLE
Websocket disconnects.

### ISSUE THREAD

**Issue by ggozad** [processone/ejabberd#1215]
> What version of ejabberd are you using?

16.06 

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

Source.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Using a websocket connection, the connection is dropped every 4 min. During that time the app sends a ping to a component every minute so there should be traffic (which I can verify in the logs) through ejabberd.

Tried setting ``websocket_ping_interval`` and ``websocket_timeout`` but it does not seem to help.

Here's a excerpt
```
loglevel: 5

hosts:
  - "test.com"

host_config:
  "test.com":
    acl:
      admin:
        user:
          - "admin": "test.com"

websocket_ping_interval: 0
websocket_timeout: 3600

....


listen:
  -
    port: 5222
    module: ejabberd_c2s
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    ip: "127.0.0.1"
    port: 5347
    module: ejabberd_service
    hosts:
      "test.test.com":
        password: "password"
    ip: "127.0.0.1"
    shaper_rule: fast
    access: all
  -
    port: 5280
    module: ejabberd_http
    http_bind: true
    request_handlers:
      "/http-bind": mod_http_bind
      "/xmpp": ejabberd_http_ws
```
