### ISSUE TITLE
pubsub node configuration: SQL syntax error returned

### ISSUE THREAD

**Issue by Trim** [processone/ejabberd#1219]
Hello,

I'm running ejabberd 16.06 installed with Debian [jessie-backports package](https://packages.debian.org/jessie-backports/ejabberd). My server is runing Debian Jessie 64 bits with backports enabled.

I'm using pubsub module with PostgreSQL data storage (`pgsql` module, not `odbc`).
My module configuration is:

```yaml
access_rules:
  ## This rule allows access only for local users:
  local:
    - allow: local
  ## Only accounts on the local ejabberd server can create Pubsub nodes:
  pubsub_createnode:
    - allow: local

modules:
  mod_caps: {}
  mod_pubsub:
    host: "pubsub.@HOST@"
    db_type: sql
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: false
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: true
    max_items_node: 1000
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
    pep_mapping:
      "urn:xmpp:microblog:0": "mb"
```

I've followed the Movim client [recommendations](https://github.com/movim/movim/wiki/Configure%20ejabberd) to know which configuration I should apply.

My goal is to increase the number of elements stored on my `urn:xmpp:microblog:0` node from `1` to `1000` to see if it can solve this Movim bug movim/movim#149   .

I'm using Gajim 0.16 to make this modification.
Gajim don't show me any error when I validate, but when I open configuration again nothing happend.

My ejabberd server show me errors in log files:

ejabberd.log:
```
2016-07-29 15:46:29.544 [error] <0.315.0>@ejabberd_sql:sql_query_internal:532 PREPARE failed for SQL query at {nodetree_tree_sql,79}: [{severity,'ERREUR'},{code,<<"42601">>},{message,<<"erreur de syntaxe sur ou prÃ¨s de Â« node Â»">>},{position,32},{file,<<"scan.l">>},{line,1052},{routine,<<"scanner_yyerror">>}]
```

The French message seems to come from PostgreSQL and it says there's a syntax error near "node". Postgresql log confirm this to me:

```
2016-07-29 15:46:29 CEST [6666-4] ejabberd@ejabberd ERREUR:  erreur de syntaxe sur ou près de « node » au caractère 32
2016-07-29 15:46:29 CEST [6666-5] ejabberd@ejabberd INSTRUCTION :  update pubsub_node set host=$1 node=$2 parent=$3 type=$4 where nodeid=$5
2016-07-29 15:46:29 CEST [6666-6] ejabberd@ejabberd ERREUR:  erreur de syntaxe sur ou près de « node » au caractère 49
2016-07-29 15:46:29 CEST [6666-7] ejabberd@ejabberd INSTRUCTION :  update pubsub_node set host='adrien@adorsaz.ch' node='urn:xmpp:microblog:0' parent='' type='pep' where nodeid=17
2016-07-29 15:46:29 CEST [6666-8] ejabberd@ejabberd ATTENTION:  aucune transaction en cours
```

I've checked the database contains this informations currently:

```
ejabberd=# select * from pubsub_node where nodeid=17;
       host        |         node         | parent | type | nodeid 
-------------------+----------------------+--------+------+--------
 adrien@adorsaz.ch | urn:xmpp:microblog:0 |        | pep  |     17
(1 row)
```

I've tried to apply the update instructions and I've found the error:

```
ejabberd=# update pubsub_node set host='adrien@adorsaz.ch' node='urn:xmpp:microblog:0' parent='' type='pep' where nodeid=17;
ERREUR:  erreur de syntaxe sur ou près de « node »
LIGNE 1 : update pubsub_node set host='adrien@adorsaz.ch' node='urn:xm...
                                                          ^
ejabberd=# update pubsub_node set host='adrien@adorsaz.ch', node='urn:xmpp:microblog:0', parent='' type='pep' where nodeid=17;
ERREUR:  erreur de syntaxe sur ou près de « type »
LIGNE 1 : ...orsaz.ch', node='urn:xmpp:microblog:0', parent='' type='pep'...
                                                               ^
ejabberd=# update pubsub_node set host='adrien@adorsaz.ch', node='urn:xmpp:microblog:0', parent='', type='pep' where nodeid=17;
UPDATE 1
ejabberd=# 
```
The SQL instruction need coma between each updated fields for PostgreSQL.
I've never written Erlang code, so I think I'm not able to confirm if this bug still exists in the current master ejabberd code. Could you check please ?
