### ISSUE TITLE
Online presence of user is sometimes not accurately reflected in user list.

### ISSUE THREAD

**Issue by systemidx** [processone/ejabberd#1226]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Windows Server 2008

> How did you install ejabberd (source, package, distribution)?

Installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Expected Results:**  As Johnny, I would be able to see Kurt's online status accurately reflect him as being "Available" and be able to communicate with Kurt.

**Actual Results:**  Kurt was shown as Offline, but was still able to send me a message.

Configuration: [ejabberd.txt](https://github.com/processone/ejabberd/files/394430/ejabberd.txt)

**Comment by zinid** [comment]
Well this is a serious issue, but without any info we cannot help.

**Comment by systemidx** [comment]
I included the configuration we're using with the issue. Could you please let me know what else you think may be helpful for us to include?

**Comment by systemidx** [comment]
Just in case GitHub's blob storage fails:
```
## Coment to test ejabberd cycling
loglevel: 4

log_rotate_size: 0
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 1000

hosts:
  - "<%= @dnsName %>"

listen:
  -
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    port: 5280
    module: ejabberd_http
    web_admin: true
    http_bind: true
    http_poll: true
    tls: true
    certfile: "<%= certPath %>\\server.pem"
    captcha: false

auth_password_format: plain
disable_sasl_mechanisms:
    - "digest-md5"
    - "scram-sha-1"

auth_method: http
auth_opts:
  host: "https://<% if !@environment.eql? "production" %><%= @environment + "-" %><% end %>ejabberdauthservice.<%= @dnsZone %>"
  connection_pool_size: 100
  connection_opts: []
  basic_auth: ""
  path_prefix: "/v1/"

default_db: sql
sql_type: mysql
sql_server: "<%= @dbServer %>"
sql_database: "<%= @dbName %>"
sql_username: "<%= @dbUser %>"
sql_password: "<%= @dbPassword %>"
sql_port: 3306

##
## Number of connections to open to the database for each virtual host
##
## odbc_pool_size: 10

##
## Interval to make a dummy SQL request to keep the connections to the
## database alive. Specify in seconds: for example 28800 means 8 hours
##
## odbc_keepalive_interval: 60

###.  ===============
###'  TRAFFIC SHAPERS

shaper:
  ##
  ## The "normal" shaper limits traffic speed to 1000 B/s
  ##
  normal: 10000

  ##
  ## The "fast" shaper limits traffic speed to 50000 B/s
  ##
  fast: 100000

##
## This option specifies the maximum number of elements in the queue
## of the FSM. Refer to the documentation for details.
##
max_fsm_queue: 1000

###.   ====================
###'   ACCESS CONTROL LISTS
acl:
  admin:
    user:
      - "admin": "<%= @dnsName %>"

  local:
    user_regexp: ""

  loopback:
    ip:
      - "127.0.0.0/8"

access:
  ## Maximum number of simultaneous sessions allowed for a single user:
  max_user_sessions:
    all: 100
  ## Maximum number of offline messages that users can have:
  max_user_offline_messages:
    admin: 5000
    all: 100
  ## This rule allows access only for local users:
  local:
    local: allow
  ## Only non-blocked users can use c2s connections:
  c2s:
    blocked: deny
    all: allow
  ## For C2S connections, all users except admins use the "normal" shaper
  c2s_shaper:
    admin: none
    all: normal
  ## All S2S connections use the "fast" shaper
  s2s_shaper:
    all: fast
  ## Only admins can send announcement messages:
  announce:
    admin: allow
  ## Only admins can use the configuration interface:
  configure:
    admin: allow
  ## Admins of this server are also admins of the MUC service:
  muc_admin:
    admin: allow
  ## Only accounts of the local ejabberd server can create rooms:
  muc_create:
    local: allow
  ## All users are allowed to use the MUC service:
  muc:
    all: allow
  ## Only accounts on the local ejabberd server can create Pubsub nodes:
  pubsub_createnode:
    local: allow
  ## In-band registration allows registration of any possible username.
  ## To disable in-band registration, replace 'allow' with 'deny'.
  register:
    all: allow
  ## Only allow to register from localhost
  trusted_network:
    loopback: allow

language: "en"

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  ## mod_echo: {}
  ## mod_irc: {}
  mod_http_bind:
    max_inactivity: 60
  ## mod_http_fileserver:
  ##   docroot: "/var/www"
  ##   accesslog: "C:\\Program Files\\ejabberd-16.04\\logs\\access.log"
  mod_last: {}
  mod_mam:
    default: always
    db_type: sql
    assume_mam_usage: if_enabled
  mod_muc:
    ## host: "conference.@HOST@"
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
    default_room_options:
      mam: true
  mod_muc_admin: {}
  ## mod_muc_log: {}
  ## mod_multicast: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  ## mod_pres_counter:
  ##   count: 5
  ##   interval: 60
  mod_privacy: {}
  mod_private: {}
  ## mod_proxy65: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
  mod_register: {}
  # ejabberd_auth_http: {}
  mod_roster: {}
  # mod_roster:
  #   db_type: odbc
  mod_shared_roster: {}
  ## mod_stats: {}
  ## mod_time: {}
  mod_vcard: {}
  mod_version: {}

allow_contrib_modules: true
```

We use Chef to deploy our configurations, so what appears as variables gets replaced with proper text.
