### ISSUE TITLE
Can't disable Stream Management feature for the websocket connections

### ISSUE THREAD

**Issue by iAchilles** [processone/ejabberd#1260]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I did try to disable Stream Management (XEP-0198). To achieve that, I specified false for the stream_management option in the config file.
But it doesn't make any effect when a client opens XMPP session via websockets. 
When a client (Gajm, Pidgin) establishes connection directly, it works like expected.

**Comment by iAchilles** [comment]
I found a typo in the Stream Management option name.
Now, if you need to disable XEP-0198 for the websocket connections, the following settings do the trick:

```
port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws-chat": ejabberd_http_ws
    stream_management: false
```
