### ISSUE TITLE
Wrong certificate for services on subdomains

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#1292]
> What version of ejabberd are you using?

ejabberd 16.04

> What operating system (version) are you using?

Debian 8.5

> How did you install ejabberd (source, package, distribution)?

jabbet.at repository

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

SNI doesn't work for services on subdomains (e.g. muc). I have vhost domain.tld with valid certificate, I added SRV record for MUC service to enable connections from other servers:
```
_xmpp-server._tcp.muc.domain.tld.	 SRV	10 0 5269 xmpp.domain.tld.
```
MUC is now available from other XMPP servers but return default certificate, not that I set for this vhost.

**Comment by badlop** [comment]
Show your config, or the relevant parts, describe which cert is returned, and which one you expected to be returned.

**Comment by beherit** [comment]
I have something like that (fragments):
```
define_macro:
  'CERT_LOCATION': "/etc/ejabberd/certs/ejabberd.pem"
  'CERT_LOCATION_DOMAIN_TLD': "/etc/ejabberd/certs/domain.tld.pem"
  'DHPARAM_LOCATION': "/etc/ejabberd/certs/dh.pem"

listen:
  - ip: "::"
    port: 5222
    module: ejabberd_c2s
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: local
    starttls_required: true
    protocol_options: 'TLS_OPTIONS'
    ciphers: 'TLS_CIPHERS'
    dhfile: 'DHPARAM_LOCATION'
    zlib: true
    resend_on_timeout: if_offline
  - ip: "::"
    port: 5269
    module: ejabberd_s2s_in
    shaper: s2s_shaper

outgoing_s2s_families:
  - ipv6
  - ipv4

outgoing_s2s_port: 5269
outgoing_s2s_timeout: 10000
s2s_access: authenticated
s2s_certfile: 'CERT_LOCATION'
s2s_use_starttls: required
s2s_protocol_options: 'TLS_OPTIONS'
s2s_ciphers: 'TLS_CIPHERS'
s2s_dhfile: 'DHPARAM_LOCATION'

host_config:
  "domain.tld":
    domain_certfile: 'CERT_LOCATION_DOMAIN_TLD'

append_host_config:
  "domain.tld":
    modules:
      mod_disco: {}
      mod_irc:
        access: local
        default_encoding: "utf-8"
      mod_muc:
        host: "muc.@HOST@"
        access: everybody
        access_create: everybody
        access_persistent: muc_admin
        access_admin: muc_admin
        history_size: 20
        max_users: 50
        max_room_id: 20
        max_room_name: 40
        max_room_desc: 300
        min_message_interval: 1
        min_presence_interval: 5
```

And then when I check subdomain muc.domain.tld ejabberd return cert ejabberd.pem not domain.tld.pem.

**Comment by badlop** [comment]
> when I check subdomain muc.domain.tld ejabberd return cert ejabberd.pem not domain.tld.pem.

And how exactly do you check? Or better, is there a simple command that I can run to provoke ejabberd to provide the cert? I want to reproduce the problem easily, so I can investigate the code at runtime.

It may happen that ejabberd only checks strictly the domain in domain_certfile option, and doesn't consider subdomains. Can you try adding another domain_certfile option the muc domain? Like
```
host_config:
  "domain.tld":
    domain_certfile: 'CERT_LOCATION_DOMAIN_TLD'
  "muc.domain.tld":
    domain_certfile: 'CERT_LOCATION_DOMAIN_TLD'
```
