### ISSUE TITLE
Mod_sip behind a load balancer.

### ISSUE THREAD

**Issue by Polidore22** [processone/ejabberd#1390]
> What version of ejabberd are you using?

latest

> What operating system (version) are you using?

Ubuntu Xenial

> How did you install ejabberd (source, package, distribution)?

ProcessOne distribution

Hey guys! I am using mod_sip for a voip solution and we are having some problems behind a load balancer on aws. XMPP works as expected, but when enabling mod_sip we are getting 10.x.x.x ips back in the client logs when trying to send invites/acknowledgements. We are registering fine with sip, but usually timing out on the handshaking of calls etc. When connecting directly to EC2 instance it works fine.

I tried using the 'via' settings as such:
```
mod_sip:
        via:
          -
            type: tcp
            host: "url-of-load-balancer"
            port: 5060
```
Am I doing something wrong? Do I need one of the other mod_sip settings?

Thank you very much.

-Andy
