### ISSUE TITLE
SIP with LDAP Authentication

### ISSUE THREAD

**Issue by jacksgt** [processone/ejabberd#1419]
Hi,

I'm using ejabberd `16.09` compiled from source on Debian Jessie (stable).
(inside this Docker: https://github.com/rroemhild/docker-ejabberd)

I'm currently trying to get SIP working. I have followed [the documentation](https://docs.ejabberd.im/admin/configuration/#sip) and set up my SRV-Records as well as my listeners and mod_sip:
```yaml
listen:
...
  -
    port: 5060
    transport: udp
    module: ejabberd_sip
  -
    port: 5060
    module: ejabberd_sip
  -
    port: 5061
    module: ejabberd_sip
    tls: true
    certfile: "/opt/ejabberd/ssl/host.pem"
...
auth_method:
  - ldap
  - anonymous
anonymous_protocol: login_anon
allow_multiple_connections: true
ldap_servers:
  - "ldap.example.com"
ldap_encrypt: none
ldap_tls_verify: false
ldap_tls_depth: 1
ldap_deref_aliases: never
ldap_base: "dc=example,dc=com"
...
modules:
  mod_sip: {}
```

I know LDAP authentication is functional, because authentication for XMPP/Jabber works just fine.
But with various SIP clients (Jitsi Desktop, Linphone Desktop and Mobile) I'm getting errrors like "Registration Failed" or "Not Authorized".
By the way, I can see these clients connecting on the correct ports in my ejabberd log.

The documentation mentions that "SIP authentication does not support SCRAM", however I'm not using SCRAM (or at least I don't think I do...)

Any ideas on how to get this working?
