### ISSUE TITLE
XML RPC denying access to admin user

### ISSUE THREAD

**Issue by ncioj10** [processone/ejabberd#1430]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Ubuntu Linux 16 LTS

> How did you install ejabberd (source, package, distribution)?

Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Ejabberd does currently not allow me to access any commands via XML RPC.
I get the error {error,account_unprivileged} back for every command I enter. 

Attached you can find my [configuration](https://github.com/processone/ejabberd/files/669403/ejabberd.txt)(anonymized) and the Java Code I execute. 

My problem is, that the documentation has now changed to OAuth, which I don't want to use, so I didn't find any up-to date best practice for basic auth anywhere.

```
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import org.apache.xmlrpc.client.XmlRpcClient;
import org.apache.xmlrpc.client.XmlRpcClientConfigImpl;

    public static void main(String[] args) {
        try {
            XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();
            config.setServerURL(new URL("http://sub.domain.com:4560"));

            XmlRpcClient client = new XmlRpcClient();
            client.setConfig(config);

		    /* Command string */
            String command = "num_active_users";
            Map struct = new HashMap();
            struct.put("user", "superuser@sub.domain.com);
            struct.put("server", "sub.domain.com");
            struct.put("password", "pass");
            struct.put("admin", true);
		    /* Parameters as struct */

            Map struct2 = new HashMap();

            struct2.put("host", "sub.domain.com");
            struct2.put("days", 2);


            Object[] params = new Object[]{struct,struct2};
            Integer result = (Integer) client.execute(command, params);
            System.out.println(result);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
```

Thank you in advance and merry christmas to all of you!

**Comment by badlop** [comment]
Looking at your config file, you have something like this:
```
listen:
  - 
     port: 4560
     module: ejabberd_xmlrpc
     maxsessions: 10
     timeout: 5000
     access_commands:
       admin:
         commands: all
         options: []

commands_admin_access:   xmlrpc_access

acl:
  admin:
    xmlrpc_acl:
      - "superuser@sub.domain.com"
      - "superuser"

access:
  xmlrpc_access:
    xmlrpc_acl: allow
```

Try with something like:

```
listen:
  - 
    port: 4560
    module: ejabberd_xmlrpc
    access_commands:
      xmlrpc_access:
        commands: all
        options: []

commands_admin_access:   xmlrpc_access

acl:
  xmlrpc_acl:
    user:
      - "superuser@sub.domain.com"
      - "superuser"

access_rules:
  xmlrpc_access:
    - allow: xmlrpc_acl
```
Now you can use a client like this (I have only a Python example, I hope it helps you):
```
import xmlrpclib

server_url = 'http://127.0.0.1:4560'
server = xmlrpclib.ServerProxy(server_url)

EJABBERD_XMLRPC_LOGIN = {'user': 'superuser', 'server': 'sub.domain.com', 'password': 'mypass11', 'admin': True}

def ejabberdctl(command, data):
    fn = getattr(server, command)
    return fn(EJABBERD_XMLRPC_LOGIN, data)

result = ejabberdctl('registered_users', {'host':'localhost'})
print result
```
