### ISSUE TITLE
remote roster :"Query to another users is forbidden" when host is in managers in mod_roster

### ISSUE THREAD

**Issue by alexandrelb** [processone/ejabberd#1443]
> What version of ejabberd are you using?

16.12

> What operating system (version) are you using?

Debian 8

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I try to configure gateways with spectrum2 but remote_roster doesn't work : 
ejabberd debug(5) log : 
[debug] <0.3809.0>@ejabberd_receiver:process_data:284 Received XML on stream = <<"<iq from=\"facebook.mydomain\" id=\"0896737f-b6aa-48b0-90a1-d3b97d708a2a\" to=\"alexandre@mydomain\" type=\"get\"><query xmlns=\"jabber:iq:roster\"/></iq><iq from=\"facebook.mydomain\" id=\"LxWQ9C\" to=\"alexandre@mydomain/16165713786511869431483126849847755\" type=\"result\"/>">>
	packet {iq,<<"0896737f-b6aa-48b0-90a1-d3b97d708a2a">>,get,<<>>,{jid,<<>>,<<"facebook.mydomain">>,<<>>,<<>>,<<"facebook.mydomain">>,<<>>},{jid,<<"alexandre">>,<<"mydomain">>,<<>>,<<"alexandre">>,<<"mydomain">>,<<>>},[{xmlel,<<"query">>,[{<<"xmlns">>,<<"jabber:iq:roster">>}],[]}],#{}}
    [{xmlel,<<"query">>,[{<<"xmlns">>,<<"jabber:iq:roster">>}],[]}],
	packet {iq,<<"0896737f-b6aa-48b0-90a1-d3b97d708a2a">>,error,<<>>,{jid,<<"alexandre">>,<<"mydomain">>,<<>>,<<"alexandre">>,<<"mydomain">>,<<>>},{jid,<<>>,<<"facebook.mydomain">>,<<>>,<<>>,<<"facebook.mydomain">>,<<>>},[{roster_query,[],undefined},{stanza_error,auth,403,<<>>,forbidden,{text,<<>>,<<"Query to another users is forbidden">>},[]}],#{}}

mod_roster configuration : 
```
mod_roster:
    versioning: true
    store_current_id: true
    managers:
     - "facebook.mydomain"
     - "skype.mydomain"
```
I compare my configuration with ejabberd documentation, the syntax seems good

**Comment by alexandrelb** [comment]
Hi !
Someone have an idea for this issue? I tested with version 16.09 and 17.1, and I have the same problem.
Thanks

**Comment by cromain** [comment]
XEP-0321 is deprecated for several years. we have no plans to support this feature.
Any PR is welcome if needed.

**Comment by vitalyster** [comment]
> is deprecated
It isn't
> we have no plans
But it worked before and was broken, while it still mentioned in documentation and code is present

**Comment by zinid** [comment]
> It isn't

It was deferred due to author inactivity

> But it worked before and was broken recently, while it still mentioned in documentation and code is present

We probably should fix the documentation, indeed.

**Comment by alexandrelb** [comment]
there is a alternative for this ? because spectrum2, and I think any gateway program, is useless without remote roster. Maybe mod_privilege, I try it but it don't work (maybe my bad) 

The gateway is useful for coming people who want discover XMPP but don't know no one people on network for this moment.

**Comment by badlop** [comment]
> We probably should fix the documentation, indeed.

Ok, I've removed the remaining bits of 'managers' option from documentation and code.

> Maybe mod_privilege, I try it but it don't work (maybe my bad)

Maybe it's required the transports also implement that new XEP...

**Comment by vitalyster** [comment]
> that new XEP

... which is also didn't updated for years and will be deferred and then removed from ejabberd

**Comment by zinid** [comment]
@vitalyster I know you're actually using prosody, why do you care? :)
I don't think this issue tracker is the correct place for trolling.

**Comment by vitalyster** [comment]
@zinid I'm care about ejabberd users, and this XEP support was added long time ago, already was broken and revived by me - https://support.process-one.net/browse/EJAB-1381
And now you are removing it just because of your laziness, but I am "trolling", great

**Comment by vitalyster** [comment]
> there were no users

You forgot to check the date of issue and issue reporter - it was reported by user in a few days after broken release but you didn't care about it about a year

> you can put it back

I'm just checked the "successor" XEP and they are compatible in the roster management part, no need to change anything. But will it remain after "deprecation"?

**Comment by zinid** [comment]
> But will it remain after "deprecation"?

I cannot say, this depends on the factors I listed above.
Also, you can always restore the XEP and take the authorship, you're not lazy like me after all :)

**Comment by thundergreen** [comment]
Please re add this.I get crazy here with my transports. It opens new backends which leads to crashes of all my transport's

**Comment by himselfv** [comment]
Sooo how do you configure ejabberd to allow transports to manage some part of rosters, now? What's the official working solution?

I've added "roster: both" for a spectrum2 transport but it still gets 403 and complains. Other transports I've seen (vk4xmpp) force you to manually re-authorize the whole contact list.

**Comment by vitalyster** [comment]
@himselfv "roster: both" works for me last time I have checked, maybe they break new module too :P

**Comment by mremond** [comment]
@vitalyster Please, stop being rude. This is not funny.

**Comment by himselfv** [comment]
@vitalyster: It doesn't for me! *sigh*

```
    module: ejabberd_service
    access: all
    shaper_rule: fast
    service_check_from: false
    privilege_access:
      roster: "both"
```

```
2018-01-09 13:21:23,227 INFO  Component.RAW: RAW DATA IN <iq to='transport.domain' from='my_account@ejabberd.domain' type='error' id='[...]'><query xmlns='jabber:iq:roster'/><error code='403' type='auth'><forbidden xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Query to another users is forbidden</text></error></iq>
2018-01-09 13:21:23,227 INFO  XMPPRosterManager: my_account@ejabberd.domain: This server does not support remote roster protoXEP
```

**Comment by prefiks** [comment]
Could you please see if adding this to modules section helps:
``
  mod_privilege:
    roster:
      both:
        - allow:
            - server: "service.example.org"
    message:
      outgoing:
        - allow:
            - server: "service.example.org"
    presence:
      roster:
        - allow:
            - server: "service.example.org"

``
just please change service.example.org in that to what is used by your server

**Comment by himselfv** [comment]
Thank you, but nope, that didn't help. I've done some more simplification. Here's my setup now:

ejabberd.yml:
```
[...]
  mod_privacy: {}
  mod_private: {}
  mod_privilege:
    roster:
      both:
        - allow:
          - server: "transport.example.org"
    message:
      outgoing:
        - allow:
          - server: "transport.example.org"
    presence:
      roster:
        - allow:
          - server: "transport.example.org"

[...]

  ## spectrum transport
  -
    port: 15235
    ip: "::"
    module: ejabberd_service
    access: all
    shaper_rule: fast
    password: "PASSWORD_FOR_TRANSPORT"
    service_check_from: false
    hosts:
      "transport.example.org":
        password: "PASSWORD_FOR_TRANSPORT"
    privilege_access:
      roster: "both"
      message: "outgoing"
      presence: "roster"

```


spectrum-transport.cfg
```
[service]
jid = transport.example.org
password = PASSWORD_FOR_TRANSPORT
server = example.org
port = 15235
[identity]
name=Spectrum Transport
type=xmpp
category=gateway
```

(Transports connects to the server fine and even allows conversations with people from the legacy network, if they initiate it)

Transport log:
```
2018-01-10 13:36:56,268 INFO  Component.RAW: RAW DATA OUT <iq from="transport.example.org"id="941cd58d-c5cc-433e-844f-20471819b46a" to="user@example.org" type="get"><query xmlns="jabber:iq:roster"/></iq>

2018-01-10 13:36:56,295 INFO  Component.RAW: RAW DATA IN <iq to='transport.example.org' from='user@example.org' type='error' id='941cd58d-c5cc-433e-844f-20471819b46a'><query xmlns='jabber:iq:roster'/><error code='403' type='auth'><forbidden xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Query to another users is forbidden</text></error></iq>
2018-01-10 13:36:56,295 INFO  XMPPRosterManager: user@example.org: This server does not support remote roster protoXEP
```

**Comment by prefiks** [comment]
Can you set ejabberd loglevel to 5 and see what mod_priviliege logs after your service connects?

**Comment by himselfv** [comment]
It says this when reading the transport configuration:
```
2018-01-10 13:34:33.796 [debug] <0.329.0> Supervisor ejabberd_listener started ejabberd_listener:start({15235,{0,0,0,0,0,0,0,0},tcp}, ejabberd_service, [{privilege_access,[{roster,<<"both">>},{message,<<"outgoing">>},{presence,<<"roster">>}]},{hosts,...},...]) at pid <0.335.0>
```

This when accepting transport connection:
```
2018-01-10 13:36:56.259 [warning] <0.427.0>@ejabberd_config:prepare_opt_val:834 incorrect value '[{allow,[{server,"transport.example.org"}]}]' of option 'roster', using '[]' as fallback
2018-01-10 13:36:56.259 [warning] <0.427.0>@ejabberd_config:prepare_opt_val:834 incorrect value '[{allow,[{server,"transport.example.org"}]}]' of option 'presence', using '[]' as fallback
2018-01-10 13:36:56.259 [warning] <0.427.0>@ejabberd_config:prepare_opt_val:834 incorrect value '[{allow,[{server,"transport.example.org"}]}]' of option 'message', using '[]' as fallback
2018-01-10 13:36:56.259 [info] <0.427.0>@mod_privilege:handle_cast:231 Granting no permissions to external component 'transport.example.org'
```

And then nothing special when refusing the request, it's just the request and the 403 response dumped one after another.

**Comment by himselfv** [comment]
I'm using ejabberd 17.04 if that matters. (I see there's 17.12, if it has anything to do I can update)

**Comment by prefiks** [comment]
So it looks there is problem with parsing that rule, it works for me with newer version, but maybe this version will work for you:
```
access_rules:
  transport_access:
    - allow:
      - server: "transport.example.org"
[...]
modules:
  mod_privilege:
    roster:
      both: transport_access
    message:
      outgoing: transport_access
    presence:
      roster: transport_access
```
