### ISSUE TITLE
Use relative paths

### ISSUE THREAD

**Issue by rugk** [processone/ejabberd#1449]
In the web UI (e.g. admin and registration part) often absolute paths (`admin/additions.js`) are used.
Now when you e.g. run a reverse proxy (in my case nginx) in front of these and put it into a subdirectory (e.g. `https://server.example/ejabberd`) many files are tried to be served from the root dir instead of the actual subdir (`https://server.example/admin/additions.js`).

That's why you should rather use relative paths, so it works in all cases.

**Comment by badlop** [comment]
Using relative paths would require to know in what sublevel the code that generates a link is, in order to set the proper relative path. As this is the first question about this topic, I provide you a quick and dirty patch that should solve it for you:

```
diff --git a/src/ejabberd_web_admin.erl b/src/ejabberd_web_admin.erl
index be3c543..1fc4517 100644
--- a/src/ejabberd_web_admin.erl
+++ b/src/ejabberd_web_admin.erl
@@ -357,14 +357,19 @@ direction(ltr) -> [{<<"dir">>, <<"ltr">>}];
 direction(<<"he">>) -> [{<<"dir">>, <<"rtl">>}];
 direction(_) -> [].
 
-get_base_path(global, cluster) -> <<"/admin/">>;
+get_base_path() ->
+    WAB = ejabberd_config:get_option(web_admin_base, fun(V) -> V end, <<"/admin/">>),
+    iolist_to_binary(WAB).
+
+get_base_path(global, cluster) ->
+    get_base_path();
 get_base_path(Host, cluster) ->
-    <<"/admin/server/", Host/binary, "/">>;
+    <<(get_base_path())/binary, "server/", Host/binary, "/">>;
 get_base_path(global, Node) ->
-    <<"/admin/node/",
+    <<(get_base_path())/binary, "node/",
       (iolist_to_binary(atom_to_list(Node)))/binary, "/">>;
 get_base_path(Host, Node) ->
-    <<"/admin/server/", Host/binary, "/node/",
+    <<(get_base_path())/binary, "server/", Host/binary, "/node/",
       (iolist_to_binary(atom_to_list(Node)))/binary, "/">>.
 
 %%%==================================
```

Now you can configure like this, a different base path instead of "admin":
```
listen:
  - 
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/admin2": ejabberd_web_admin
    captcha: true

web_admin_base: "/admin2/"
```
And something like this in your case (I couldn't test this):
```
listen:
  - 
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
    captcha: true

web_admin_base: "/ejabberd/admin/"
```
