### ISSUE TITLE
Registration issue using HTTP rest API

### ISSUE THREAD

**Issue by Hamdy** [processone/ejabberd#1491]
> What version of ejabberd are you using?

16.12

> What operating system (version) are you using?

buntu 16.04.1 LTS

> How did you install ejabberd (source, package, distribution)?

package (.deb)

> Auth method

sql

> Configuration

```
 - 
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    ## register: true
    captcha: false
    tls: true
    certfile: "/opt/ejabberd-16.12/conf/server.pem"

commands_admin_access: configure
commands:
    - add_commands: [status, register]

# Tokens are valid for a year as default:
oauth_expire: 31536000
oauth_access: all

```

> and I have admin defined

```
  admin:
    user:
      - "admin@chat.hamdy.net"

```

> Issue

I can retrieve the OAUTH token successfully, but I can't use it to register a new user.
I can authenticate and register a new user using (Basic Authentication) though

```python
headers = {'Authorization': 'Bearer lB26WcNGMpUGNXdiWp3fn775wH5zZXXI', 'X-Admin': 'true'}
data = {'host': 'chat.hamdy.net', 'password': 'password', 'user': 'user'}
requests.post("https://192.168.50.56:5280/api/register/", json=data, verify=False, headers=headers)

Result: 
{"status":"error","code":32,"message":"AccessRules: Account does not have the right to perform the operation."}'
```

> However the following succeeds

```python
headers = {'Authorization': 'Basic base64userpass',  'X-Admin': 'true'}
data = {'host': 'chat.hamdy.net', 'password': 'password', 'user': 'user'}
requests.post("https://192.168.50.56:5280/api/register/", json=data, verify=False, headers=headers)

Result
'"User user@chat.hamdy.net successfully registered"'
```

```

What I'm missing there?
