### ISSUE TITLE
red cross in xabber beta on file sharing

### ISSUE THREAD

**Issue by burhanahmed** [processone/ejabberd#1517]
> What version of ejabberd are you using?

    ejabberd 16.12.beta1

> What operating system (version) are you using?

    ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

    pakage

hello 
the problem is when i upload an image file in xabber beta app it gives
![whatsapp image 2017-02-06 at 12 43 57 am](https://cloud.githubusercontent.com/assets/14816520/22629381/8dd64e54-ec06-11e6-995e-83934845e80c.jpeg)
red cross on bottom

these type of errors i got in error log file
```
2017-02-05 16:05:22.011 [error] <0.567.0>@mod_http_upload:init:307
 Cannot find 'identify' command, please install ImageMagick or disable thumbnail creation

2017-02-05 17:38:02.888 [error] <0.647.0>@ejabberd_sql:log:910 p1_mysql_recv:
 Failed connecting to "localhost":3306 : {error,econnrefused
```

and this my ejabberd.yml
Listening ports:
```
port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    ## register: true
    captcha: false
  -
    port: 5443
    module: ejabberd_http
    tls: true
    certfile: "/opt/ejabberd-16.12.beta1/conf/server.pem"
    request_handlers:
      "upload": mod_http_upload
```
Module:
```
mod_http_fileserver:
    docroot: "/var/www"
    accesslog: "/opt/ejabberd-16.12.beta1/logs/access.log"
    directory_indices:
      - "index.html"
      - "main.htm"
    custom_headers:
      "X-Powered-By": "Erlang/OTP"
      "X-Fry": "It's a widely-believed fact!"
    content_types:
      ".ogg": "audio/ogg"
      ".png": "image/png"
      ".jpg": "image/jpg"
      ".jpeg": "image/jpeg"
    default_content_type: "text/html"
  mod_http_upload:
    docroot: "/home" 
    put_url: "https://@HOST@:5443/upload"
    access: local
```
Plz help me. i have to present my final year project which uses ejabberd as a server. and client app I’m
using is Xabber beta...

((and one more thing guide me about how to define content types for all extensions
``` {  content_types:
      ".ogg": "audio/ogg"
      ".png": "image/png"
      ".jpg": "image/jpg"
      ".jpeg": "image/jpeg"
    default_content_type: "text/html"
}
```
so I can send any file(.zip, word file e.t.c

sincerely thankful for helping me.....
