### ISSUE TITLE
Pubsub error that breaks OMEMO

### ISSUE THREAD

**Issue by Ashaman-** [processone/ejabberd#1531]
> What version of ejabberd are you using?

Ejabberd-17.01, however this error has been occuring since either 16.04 or 16.06.

> What operating system (version) are you using?

CentOS 7 x86_64

> How did you install ejabberd (source, package, distribution)?

RPM package from process-one.net

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The following error message when XMPP clients that support Omemo (Conversations and Gajim) connects. Users have reported intermittent difficulties establishing OMEMO encrypted chats.

`[error] <0.18281.0>@mod_pubsub:transaction_retry:3680 transaction return internal error: {aborted,{badarg,[{erlang,binary_to_list,[null],[]},{str,tokens,2,[{file,"src/str.erl"},{line,246}]},{node_flat_sql,decode_subscriptions,1,[{file,"src/node_flat_sql.erl"},{line,987}]},{node_flat_sql,get_subscriptions,2,[{file,"src/node_flat_sql.erl"},{line,489}]},{node_flat_sql,select_affiliation_subscriptions,3,[{file,"src/node_flat_sql.erl"},{line,935}]},{node_flat_sql,publish_item,7,[{file,"src/node_flat_sql.erl"},{line,238}]},{mod_pubsub,node_call,4,[{file,"src/mod_pubsub.erl"},{line,3607}]},{mod_pubsub,'-transaction/4-fun-0-',3,[{file,"src/mod_pubsub.erl"},{line,3635}]}]}}`

Checking server info in Conversations shows that XEP-0164: PEP (Avatars / OMEMO) is Broken. 

Using PostgreSQL as db backend.
mod_pubsub configuration is as follows:

```
  mod_pubsub:
    access_createnode: pubsub_createnode
    db_type: sql
    max_items_node: 100
    nodetree: "tree"
    ignore_pep_from_offline: false
    last_item_cache: true
    plugins:
      - "push"
      - "mix"
      - "hometree"
      - "pep" # pep requires mod_caps
      - "flat"
```
I've tried commenting hometree and flat plugins out, but it had no effect.

Expected behavior is no error message in log file, and for Conversations not to report XEP-0164 as broken, and OMEMO works.
