### ISSUE TITLE
add access rules to banned servers 

### ISSUE THREAD

**Issue by suchatorg** [processone/ejabberd#1533]
What version of ejabberd are you using?
ejabberd 17.01 released

What operating system (version) are you using?
Debian Jessie 64bits.

How did you install ejabberd (source, package, distribution)?
source

configuración:
```
listen: 
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    access: s2s_access
    shaper: s2s_shaper
    max_stanza_size: 131072
	
acl:	
  bad_servers:
    server:
      - "dmvu.de"
      - "xmpp.su"

	  
access_rules:
  s2s_access:
    - deny: bad_servers
    - allow
```
Restart the server ejabberd and continue to enter the servers.
I do something wrong?

Log:
`@ejabberd_s2s_out:log_s2s_out:1006 Trying to open s2s connection: suchat.org -> dmvu.de with TLS=true`

Thank you.

**Comment by zinid** [comment]
`s2s_access` is a top-level option, you cannot include it inside listener's options. So you should write something like:
```yaml
...
s2s_access: server_access
...
access_rules:
  server_access:
    - deny: bad_servers
    - allow
...
```
And remove `access` option from the listener section.
