### ISSUE TITLE
Denied by ACL ejabberd 17.01

### ISSUE THREAD

**Issue by caiopinheiro** [processone/ejabberd#1542]
I'm getting the error response.

```
<iq to="admin@myserver/desktop" from="myserver" type="error" id="reg1" xmlns:stream="http://etherx.jabber.org/streams">
  <query xmlns="jabber:iq:register">
    <username>someuser</username>
    <name>some_user</name>
    <password>some_pass</password>
  </query>
  <error code="403" type="auth">
    <forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
    <text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Denied by ACL</text>
  </error>
</iq>
```

Some of my settings in the .yml file:

```
ip_access: 
   trusted_network

trusted_network:
    - allow: loopback

loopback:
    ip:
      - "127.0.0.0/8"

mod_register:
    ip_access: trusted_network
    access: register

```

I'm trying to insert by node-XMPP, using the admin client.
Here's my stanza:

```
let stanza = new Client.Stanza('iq', {type: 'set', id: 'reg1', to: 'myserver'})
        .c('query', {xmlns: 'jabber:iq:register'})
        .c('username').t(newUserId).up()  // Give a new username
        .c('name').t(newUserName).up()  // Give a new user's password
        .c('password').t(newUserPass).up()  // Give a new user's password
    _connection.send(stanza);

```
Where the _connection variable is the connection instantiated with the admin account.

Can anyone help me?
