### ISSUE TITLE
mod_muc configuration parameter "host" not taken into account

### ISSUE THREAD

**Issue by fpiecka** [processone/ejabberd#1544]
Ejabberd 17.01 on Debian 8 amd64 installed using a 64-bit DEB package.

I configured ejabberd.yml like this:

```
  mod_muc:
    host: jabbermuc.example.com
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
```
I expected to be served MUC functionality by a jabber ID jabbermuc.example.com.

The MUC functionality jabber ID is instead conference.example.com as if the setting wasn't present.
