### ISSUE TITLE
When trying to use module mod_proxy65 the service does not start and crashes

### ISSUE THREAD

**Issue by gsas93** [processone/ejabberd#1614]
> What version of ejabberd are you using?_

ejabberd 16.06 (archive https://www.process-one.net/en/ejabberd/archive/)
Also tried ejabberd 16.12 (archive https://www.process-one.net/en/ejabberd/archive/)

> What operating system (version) are you using?_

Oracle Linux Server release 6.8

> How did you install ejabberd (source, package, distribution)?_

ejabberd-16.06-linux-x86_64-installer.run
Also tried ejabberd-16.12-linux-x86_64-installer.run
using mysql database and LDAP auth

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I made the configuration with all the modules and services I needed (before trying mod_proxy65) with no problem whatsoever. Everything works as expected.
However, when I tried to enable the mod_proxy65 module, the service crashes without even starting, showing me a function clause error.
This is appears with any configuration for the module.
These are the configs I tried:

1 - Simplest possible:
```yaml
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_http_bind: {}
  mod_last: {}
  mod_muc:
    db_type: sql
    host: "cr.@HOST@"
    access: all
    access_admin: muc_admin
    access_create: muc_admin
    access_persistent: muc_admin
    history_size: 1000
    default_room_options: 
      allow_change_subj: false
      anonymous: false
      logging: true
      public_list: false
  mod_muc_admin: {}
  mod_muc_log: 
    access_log: muc_log
    dirtype: plain
    dirname: room_name
    outdir: "/etc/ejabberd/logs/muc-logs"
    file_format: plaintext
    timezone: universal
    file_permissions:
      mode: 640
      group: 33
    spam_prevention: true
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
```
2 - With more parameters:
```yaml
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_http_bind: {}
  mod_last: {}
  mod_muc:
    db_type: sql
    host: "cr.@HOST@"
    access: all
    access_admin: muc_admin
    access_create: muc_admin
    access_persistent: muc_admin
    history_size: 1000
    default_room_options: 
      allow_change_subj: false
      anonymous: false
      logging: true
      public_list: false
  mod_muc_admin: {}
  mod_muc_log: 
    access_log: muc_log
    dirtype: plain
    dirname: room_name
    outdir: "/etc/ejabberd/logs/muc-logs"
    file_format: plaintext
    timezone: universal
    file_permissions:
      mode: 640
      group: 33
    spam_prevention: true
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    host: "proxy.@HOST@"
    name: "File Transfer Proxy"
    port: 7777
  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
```
When I try to start the service in live mode, this is the output:
```
11:12:52.980 [info] LDAP connection on ldap.domain.com:636
11:12:52.980 [info] LDAP connection on ldap.domain.com:636
11:12:53.041 [warning] module 'mod_mam' is recommended for module 'mod_muc' but is not found in the config
**11:12:53.878 [critical] Problem starting the module mod_proxy65 for host <<"server.domain.com">>
 options: [{host,<<"proxy.@HOST@">>},
           {name,<<"File Transfer Proxy">>},
           {port,7777}]**
 **error: function_clause**
[{lists,map,
        [#Fun<ejabberd_http.29.64172553>,<<>>],
        [{file,"lists.erl"},{line,1237}]},
 {ejabberd_http,transform_listen_option,2,
                [{file,"src/ejabberd_http.erl"},{line,884}]},
 {ejabberd_listener,'-transform_option/1-fun-1-',3,
                    [{file,"src/ejabberd_listener.erl"},{line,638}]},
 {lists,foldl,3,[{file,"lists.erl"},{line,1262}]},
 {ejabberd_listener,transform_option,1,
                    [{file,"src/ejabberd_listener.erl"},{line,635}]},
 {lists,map,2,[{file,"lists.erl"},{line,1238}]},
 {lists,map,2,[{file,"lists.erl"},{line,1238}]},
 {ejabberd_listener,add_listener,3,
                    [{file,"src/ejabberd_listener.erl"},{line,456}]}]
11:12:53.878 [critical] ejabberd initialization was aborted because a module start failed.

Crash dump is being written to: /opt/ejabberd-16.12/logs/erl_crash_20170317-111249.dump...done
Problem starting the module mod_proxy65 for host <<"server.domain.com">>
 options: [{host,<<"proxy.@HOST@">>},
           {name,<<"File Transfer Proxy">>},
           {port,7777}]
 error: function
```
Any idea what could be happening? I made the config exactly like in the ejabberd website guides, however it doesn't seem to work.

**Comment by badlop** [comment]
```
 **error: function_clause**
[{lists,map,
        [#Fun<ejabberd_http.29.64172553>,<<>>],
        [{file,"lists.erl"},{line,1237}]},
```
This means that erlang can't find the definition of a function called map in module lists.beam accepting two arguments.

This is a more simple way to get that error. Try it yourself manually to confirm that's the problem:
```
$ erl
Erlang/OTP 18 [erts-7.3.1.2] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]
Eshell V7.3.1.2  (abort with ^G)
1> lists:map(fun(X) -> X*2 end, [1,2,3]).
[2,4,6]
```
In my case, that call runs correctly. Apparently, in your case it should crash.

I have no idea why erlang can't find such file, if you installed ejabberd with an erlang version included, which should include all the required modules (including lists.beam). Do you have installed erlang manually? That isn't required.

**Comment by zinid** [comment]
@badlop, no, that means `<<>>` is provided as a second argument to `lists:map/2`, which is wrong and is clearly a bug.

**Comment by zinid** [comment]
I actually think the problem is in `listen` section, most likely in `request_handlers` option.

**Comment by badlop** [comment]
Ah, right! @gsas93, can you show the `listen`section of your config file?

**Comment by gsas93** [comment]
Okay then!

Here's the listen section of the config file:

```
listen:
  -
    port: 5222
    module: ejabberd_c2s
    certfile: "/opt/ejabberd-16.12/conf/certs/server_2048.pem"
    dhfile: "/etc/ejabberd/conf/certs/dh1024.pem"
    starttls: true
    ## To enforce TLS encryption for client connections,
    ## use this instead of the "starttls" option:
    ## starttls_required: true
    ##
    ## Custom OpenSSL options
    ##
    protocol_options:
      - "no_sslv3"
    ##   - "no_tlsv1"
    ciphers: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5223
    module: ejabberd_c2s
    certfile: "/opt/ejabberd-16.12/conf/certs/server_2048.pem"
    dhfile: "/etc/ejabberd/conf/certs/dh1024.pem"
    tls: true
    ## To enforce TLS encryption for client connections,
    ## use this instead of the "starttls" option:
    ## starttls_required: true
    ##
    ## Custom OpenSSL options
    ##
    protocol_options:
      - "no_sslv3"
    ##   - "no_tlsv1"
    ciphers: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  ##
  ## ejabberd_service: Interact with external components (transports, ...)
  ##
  ## -
  ##   port: 8888
  ##   module: ejabberd_service
  ##   access: all
  ##   shaper_rule: fast
  ##   ip: "127.0.0.1"
  ##   hosts:
  ##     "icq.example.org":
  ##       password: "secret"
  ##     "sms.example.org":
  ##       password: "secret"

  ##
  ## ejabberd_stun: Handles STUN Binding requests
  ##
  ## -
  ##   port: 3478
  ##   transport: udp
  ##   module: ejabberd_stun

  ##
  ## To handle XML-RPC requests that provide admin credentials:
  ##
  ## -
  ##   port: 4560
  ##   module: ejabberd_xmlrpc
  ##   maxsessions: 10
  ##   timeout: 5000
  ##   access_commands:
  ##     admin:
  ##       commands: all
  ##       options: []
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
    ##  "/websocket": ejabberd_http_ws
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    register: false
    captcha: false

###.  ==================
###'  S2S GLOBAL OPTIONS

s2s_use_starttls: required
s2s_certfile: "/opt/ejabberd-16.12/conf/certs/server_4096.pem"
s2s_protocol_options:
      - "no_sslv2"
      - "no_sslv3"
s2s_ciphers: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"

##
## s2s_use_starttls: Enable STARTTLS + Dialback for S2S connections.
## Allowed values are: false optional required required_trusted
## You must specify a certificate file.
##
## s2s_use_starttls: optional

##
## s2s_certfile: Specify a certificate file.
##
## s2s_certfile: "/opt/ejabberd-16.12/conf/server.pem"

## Custom OpenSSL options
##
## s2s_protocol_options:
##   - "no_sslv3"
##   - "no_tlsv1"

##
## domain_certfile: Specify a different certificate for each served hostname.
##
## host_config:
##   "example.org":
##     domain_certfile: "/opt/ejabberd-16.12/conf/example_org.pem"
##   "example.com":
##     domain_certfile: "/opt/ejabberd-16.12/conf/example_com.pem"

##
## S2S whitelist or blacklist
##
## Default s2s policy for undefined hosts.
##
## s2s_access: s2s

##
## Outgoing S2S options
##
## Preferred address families (which to try first) and connect timeout
## in milliseconds.
##
## outgoing_s2s_families:
##   - ipv4
##   - ipv6
## outgoing_s2s_timeout: 10000
```

**Comment by zinid** [comment]
So do you find `request_handlers` definition to be correct?

**Comment by gsas93** [comment]
Well, I was not sure if it was a config issue or a installation issue, since everything else works fine.
You mean this part? Not sure why this would make any difference for something that's not running on the http administration part of the service.

```
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
    ##  "/websocket": ejabberd_http_ws
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    register: false
    captcha: false
```

Should I change something? add a option ?
If I already knew the problem, I wouldn't have openned the issue, you know.

**Comment by badlop** [comment]
This is an acceptably formatted option definition, with two values:
```yaml
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/pub/archive": mod_http_fileserver
```
This is acceptable, as it is just comments:
```yaml
    ## request_handlers:
    ##  "/websocket": ejabberd_http_ws
    ##  "/pub/archive": mod_http_fileserver
```
And what you have is this, an option definition with no values at all. Then what's the point of defining the option?
```yaml
    request_handlers:
    ##  "/websocket": ejabberd_http_ws
    ##  "/pub/archive": mod_http_fileserver
```

**Comment by gsas93** [comment]
I see...
If I leave it like this:

    request_handlers:
      "/websocket": ejabberd_http_ws
    ##  "/pub/archive": mod_http_fileserver

Would that be okay? 
I'll read more about the functionality of those options and see if I actually need them or not....

**Comment by zinid** [comment]
@gsas93 yes, that would be okay

**Comment by gsas93** [comment]
Okay then, thanks!

Regarding the config of the mod_proxy65 module, shouldn't this config open port 7777? should I expect some change on the client side configuration?

```
  mod_proxy65:
    host: "proxy.@HOST@"
    name: "File Transfer Proxy"
    port: 7777
```

Thanks in advance!
