### ISSUE TITLE
http upload

### ISSUE THREAD

**Issue by Thomas301263** [processone/ejabberd#1621]
> What version of ejabberd are you using?

16.01

> What operating system (version) are you using?

Ubuntu 16.04
NGINX 1.10.0

> How did you install ejabberd (source, package, distribution)?

Installed from source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

http upload is not working.
If am using gajim it is starting the upload but comes up with timeout. 
Also in upload directory there is nothing. 
I send all files in the *.zip 
[ejabberd_nginx_ejabberd.log_file.zip](https://github.com/processone/ejabberd/files/852607/ejabberd_nginx_ejabberd.log_file.zip)

**Comment by suchatorg** [comment]
You have to delete the letter "s" in uploads
ejabber.yml
```
  mod_http_upload:
    docroot: "/home/sielstetten/uploads"
    put_url: "https://sielstetten.selfhost.me:5443/**upload**"
    access: local
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
```

**Comment by suchatorg** [comment]
Try this configuration for mod_http_upload, you have a "s" of more in 5443/uploads

ejabberd.yml
```
  mod_http_upload:
    docroot: "/home/sielstetten/uploads"
    put_url: "https://sielstetten.selfhost.me:5443/upload"
    access: local
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
```
