### ISSUE TITLE
How to allow s2s communication between specific domains

### ISSUE THREAD

**Issue by rahul-l** [processone/ejabberd#1631]
I have created 2 ejabberd servers with different domains say
1. one.example.com
2. two.example.com

Now I  have successfully establish the connection using s2s settings. I was able to communicate with user from one domain to other domain.
For that I have enable the setting access s2s: all: allow
but due to this now my server will allow to connect to any ejabberd server I want s2s communication should happen only between these two settings only.

How to specify access of s2s to particular server and not with all servers

**Comment by zinid** [comment]
```yaml
s2s_access: s2s

access_rules:
  s2s:
    - allow:
      - server: "two.example.com"
    - deny
```
