### ISSUE TITLE
virtual hosts modules configuration

### ISSUE THREAD

**Issue by dorsegal** [processone/ejabberd#1632]
Hi,

Im using a module the require to define url in ejabberd.yml and it looks like this.

```
modules:
  my_module:
    url: http://...
########
All other modules are here
########
```

and I'm also using virtual hosts because for each domain this url is different.
so my real configuration looks like this:

```
########
All modules are here
########
host_config:
"domain1"
    modules:
      my_module:
        url: http://...
"domain2"
    modules:
      my_module:
        url: http://...
```
**The problem:**
once its defined like this all other modules are not working for those virtual hosts. is there any way to set the modules out side the host_config to be global for all hosts even the virtual ones?

**ejabberd 15.11**

Thanks.
