### ISSUE TITLE
pubsub events does not sent to clients

### ISSUE THREAD

**Issue by sss123next** [processone/ejabberd#1636]
> What version of ejabberd are you using?

17.03.3

> What operating system (version) are you using?

Linux 4.10.1

> How did you install ejabberd (source, package, distribution)?

cave resovle -zx1 ejabberd (latest git  [ebuild](http://sss.chaoslab.ru/git/?p=sss_overlay.git;a=blob;f=net-im/ejabberd/ejabberd-scm.ebuild;h=add257fb3ecb2f38ed17202d6fb2511304a6a2b9;hb=d75f96dea025efec732ef8469ea9b3bb30e722f0))

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

client does not receiving pubsub events at all.
client successfully publishing pubsub node:

```
 <!-- Out Пт 24 мар 2017 20:31:53 -->
<iq xmlns="jabber:client" type="set" id="18">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<publish node="http://jabber.org/protocol/activity">
<item id="0">
<activity xmlns="http://jabber.org/protocol/activity">
<working>
<in_a_meeting />
</working>
<text>00</text>
</activity>
</item>
</publish>
</pubsub>
</iq>

<!-- Out Пт 24 мар 2017 20:31:53 -->
<iq xmlns="jabber:client" type="set" id="19">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<publish node="http://jabber.org/protocol/mood">
<item id="0">
<mood xmlns="http://jabber.org/protocol/mood">
<afraid />
<text>??</text>
</mood>
</item>
</publish>
</pubsub>
</iq>

<!-- In Пт 24 мар 2017 20:32:01 -->
<iq xml:lang='ru' to='tst1@dark-alexandr.net/Gajim' from='tst1@dark-alexandr.net' type='result' id='18'>
<pubsub xmlns='http://jabber.org/protocol/pubsub'>
<publish node='http://jabber.org/protocol/activity'>
<item id='0'/>
</publish>
</pubsub>
</iq>

<!-- In Пт 24 мар 2017 20:32:01 -->
<iq xml:lang='ru' to='tst1@dark-alexandr.net/Gajim' from='tst1@dark-alexandr.net' type='result' id='19'>
<pubsub xmlns='http://jabber.org/protocol/pubsub'>
<publish node='http://jabber.org/protocol/mood'>
<item id='0'/>
</publish>
</pubsub>
</iq>

```
but it's never sent back to client via event message mechanism.
it's also does not sent to contacts in roster which have subscription.
no errors or warnings in ejabberd.log
this maybe configuration issue.

```
loglevel: 4
default_db: sql
route_subdomains: local
sql_type: mysql
sql_server: "server_address"
sql_database: "db_name"
sql_username: "db_username"
sql_password: "db_password"
acl:
 admin:
  user:
   "user": "hostname"
 local:
  user_regexp: ""

  loopback:
    ip:
      - "127.0.0.0/8"

access:
  max_user_sessions: 
    all: 10
  max_user_offline_messages: 
    admin: 5000
    all: 500
  local: 
    local: allow
  c2s: 
    blocked: deny
    all: allow
  c2s_shaper: 
    admin: none
    all: normal
  s2s_shaper: 
    all: fast
  announce: 
    admin: allow
  configure: 
    admin: allow
  muc_admin: 
    admin: allow
  muc_create: 
    local: allow
  muc: 
    all: allow
  pubsub_createnode:
    local: allow
  register: 
    all: deny
  trusted_network: 
    loopback: allow

language: "en"


modules:
  mod_adhoc: {}
  mod_blocking: {} # requires mod_privacy
  mod_privacy: {}
  mod_caps: {}
  mod_carboncopy:
    db_type: internal
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_last: {}
  mod_muc: 
    ## host: "conference.@HOST@"
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
  mod_muc_admin: {}
  mod_offline: 
    access_max_user_messages: max_user_offline_messages
  mod_private: {}
  mod_pubsub:
#    db_type: mnesia  #checked with mnesia db backend, same problem
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: false
    last_item_cache: true
    max_subscriptions_node: 100
#    default_node_config:
#      notification_type: normal
#      notify_retract: false
#      max_items: 4
    plugins: 
      - "flat"
#      - "hometree" #checked also with 'hometree' enabled, same problem
      - "pep"
  mod_roster:
    iqdisc: 4
    versioning: true
    store_current_id: true
    managers:
     - "icq.hostname"
  mod_time: {}
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_mam: 
   default: always
  mod_fail2ban:
    c2s_auth_ban_lifetime: 7200
    c2s_max_auth_failures: 50
  mod_legacy_auth: {}
  mod_s2s_dialback: {}

allow_contrib_modules: true

```

i can provide more info, but do not know which info required.
