### ISSUE TITLE
oauth_list_tokens and oauth_revoke_token not working with mysql database backend

### ISSUE THREAD

**Issue by algore** [processone/ejabberd#1644]
> What version of ejabberd are you using?

17.03

> What operating system (version) are you using?

CentOS (AMI)

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

My ejabberd.yml oauth section looks like that:

```yaml
oauth_db_type: sql
commands_admin_access: configure
commands:
    - add_commands:
    - user
oauth_expire: 31536000

oauth_access: all
```

I can create oauth tokens on database with the command
> ejabberdctl oauth_issue_token "user@example.org" 31536000 "sasl_auth"

But the commands
> ejabberdctl oauth_list_tokens
> ejabberdctl oauth_revoke_token

are not working with MySql database.
Its supposed to be like that? Or i am missing something in my ejabberd.yml configuration file?
