### ISSUE TITLE
Unable to Register SIP client with IPv6

### ISSUE THREAD

**Issue by Andy-2639** [processone/ejabberd#1668]
> What version of ejabberd are you using?
> How did you install ejabberd (source, package, distribution)?

https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/17.03/ejabberd-17.03-windows-installer.exe

> What operating system (version) are you using?

Windows 10 Pro x64 Anniversary Update (Version 1607 Build 14393.969)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

My SIP client (Phoner Lite 2.47, http://www.phonerlite.de/ ) can register to my ejabberd SIP server via IPv4 (TCP and UDP) without problems.
When I try to use IPv6, the register fails and PhonerLite says a timeout occurred. This happens with TCP and UDP.

SIP client and ejabberd are running on different maschines in the same LAN. No firewall is enabled on either maschine.

I attached the logs of the connections (ejabberd log, PhonerLite debug output and wireshark packet captures) zipped. Wireshark ran on the same maschine on which ejabberd runs.
[logs_pcaps.zip](https://github.com/processone/ejabberd/files/908101/logs_pcaps.zip)

SIP configuration in my ejabberd.yml:
```yaml
listen: 
  - 
    ip: "0.0.0.0"
    port: 65060
    transport: udp
    module: ejabberd_sip
  - 
    ip: "::"
    port: 65060
    transport: udp
    module: ejabberd_sip
  - 
    ip: "0.0.0.0"
    port: 65060
    module: ejabberd_sip
  - 
    ip: "::"
    port: 65060
    module: ejabberd_sip
modules: 
  mod_sip: []
```

**Comment by zinid** [comment]
Don't you have any errors in the log? It's not always possible to define the same port globally to both IP protocols. Do you see the ports are opened on all IP interfaces?

**Comment by Andy-2639** [comment]
> Don't you have any errors in the log?

No, there are no errors in the log.
The ejabberd logs are in logs_pcaps.zip "ejabberd [tcp/udp] v[4/6].log". For every protocol combination, I deleted the old logs and started a fresh ejabberd instance.

> It's not always possible to define the same port globally to both IP protocols. Do you see the ports are opened on all IP interfaces?

I tested it again with port 5060 for IPv4 TCP/UDP and port 65060 for IPv6 TCP/UDP. This gives the same behavior. I also testes the bahavior of Phoner Lite 2.47: when the SIP server is not reacheable I get an connection error message instead of an timeout.
Also wireshark indicates that the ports are open: no TCP RST packets. In the ejabberd logs, I can see the REGISTER messages from Phoner Lite, too (ejabberd tcp v6.log, line 327; ejabbers udp v6.log, 326 - 509).
XMPP works fine with IPv4 and IPv6 on the same port number.

**Comment by zinid** [comment]
> I tested it again with port 5060 for IPv4 TCP/UDP and port 65060 for IPv6 TCP/UDP.

Do you mean to say you disabled ipv4 listener and still don't have it working with ipv6 listener?

**Comment by Andy-2639** [comment]
Neighter
```yaml
listen: 
  - 
    ip: "0.0.0.0"
    port: 5060
    transport: udp
    module: ejabberd_sip
  - 
    ip: "::"
    port: 65060
    transport: udp
    module: ejabberd_sip
  - 
    ip: "0.0.0.0"
    port: 5060
    module: ejabberd_sip
  - 
    ip: "::"
    port: 65060
    module: ejabberd_sip
```

nor

```yaml
listen: 
  - 
    ip: "::"
    port: 5060
    transport: udp
    module: ejabberd_sip
  - 
    ip: "::"
    port: 5060
    module: ejabberd_sip
```

works on my system.

**Comment by Andy-2639** [comment]
I tested SIP with IPv6 again with ejabberd 17.08. It still fails.
The logs of phonerlite and ejabberd and the complete ejabberd configuration is in the zip:
[logs_config.zip](https://github.com/processone/ejabberd/files/1254233/logs_config.zip)

SIP with IPv4 works fine. I enabled listening only on one IP version at a time.

It seems that ejabberd is receiving the requests vom the SIP client but just does not send a reply.

The test ran in a VM with a newly installed Windows 10 Pro x64 and a newly installed ejabberd 17.08. The windows firewall was deactivated and phonelite and ejabberd ran on the same VM.

**Comment by zinid** [comment]
I'm not sure I can help because I don't have windows installed and IPv6 works fine for me on Linux.

**Comment by aylesm** [comment]
Any progress with this?  I'm running centos and have enabled IPv6.  I can see from the logs the server receives the SIP REGISTER message.  But never responds.

**Comment by zinid** [comment]
I still have it working:
```
$ telnet ::1 5060
Trying ::1...
Connected to ::1.
Escape character is '^]'.
REGISTER sip:zinid.ru SIP/2.0
Via: SIP/2.0/TCP 198.211.126.52:43403;branch=z9hG4bK.23e5441e;rport;alias
From: sip:xram@zinid.ru;tag=4cc1fd1f
To: sip:xram@zinid.ru
Call-ID: 1287781663@198.211.126.52
CSeq: 1 REGISTER
Content-Length: 0
Max-Forwards: 70
User-Agent: sipsak 0.9.7pre
Expires: 15
Contact: sip:xram@198.211.126.52:43403;transport=TCP

SIP/2.0 401 Unauthorized
Via: SIP/2.0/TCP 198.211.126.52:43403;branch=z9hG4bK.23e5441e;alias;received=[::1];rport=54724
From: <sip:xram@zinid.ru>;tag=4cc1fd1f
Call-ID: 1287781663@198.211.126.52
CSeq: 1 REGISTER
Max-Forwards: 70
To: <sip:xram@zinid.ru>;tag=2332915767-1429473788
Server: ejabberd 17.09.121
WWW-Authenticate: Digest realm="zinid.ru", qop="auth", nonce="8aa552d7fd797fec03f613ef91f856859d72ec97"
Content-Length: 0

```

**Comment by zinid** [comment]
I have tried on two Linux machines, btw.

**Comment by aylesm** [comment]
Have you tested over TLS?

**Comment by zinid** [comment]
Yes, it works as well.

**Comment by zinid** [comment]
Have you enabled debug (`loglevel: 5`)? What do you see there?

**Comment by aylesm** [comment]
I see the incoming request in the logs.  But I don't see the response.  So it feels like this is an outbound issue in my setup.  Not sure if I've waited long enough to see a timeout or other relevant log msg.

**Comment by zinid** [comment]
This is strange because you should see `data_out` log message within 32 seconds max.

**Comment by zinid** [comment]
Also, what if you don't use TLS? Does plain TCP or UDP work with IPv6?

**Comment by aylesm** [comment]
Same result with UDP.  Haven't tried TCP at this point.

**Comment by aylesm** [comment]
@zinid do you have a sample ejabberd.yml I can take a look at to see if I've setup my instance correctly for IPv6?

**Comment by aylesm** [comment]
I've also reproduced this same behaviour on MacOS.  Which by default has IPv6 switched on.  So the only thing I can think of is that my yml is wrong.  The only other thing I can think of is trying to setup the same type of linux box as you to see if that's the issue.

**Comment by zinid** [comment]
> do you have a sample ejabberd.yml

Sure, here is the listening section
```yaml
listen:
  - 
    port: 3478
    module: ejabberd_stun
    transport: udp
    use_turn: true
    auth_type: user
    turn_ip: "198.211.126.52"
  - 
    port: 5060
    ip: "::"
    module: ejabberd_sip
    transport: udp
  - 
    port: 5060
    ip: "::"
    module: ejabberd_sip
  -
    port: 5061
    ip: "::"
    module: ejabberd_sip
    tls: true
    certfile: "/path/to/cert.pem"
```

And modules section:
```yaml
modules:
  mod_sip: {}
```
