### ISSUE TITLE
How to enable mucsub in ejabberd 17.01

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1689]
**1**
I read that muc_sub should be available in ejabberd 17.01.
But how do we enable muc-sub in Ejabberd 17.01.
The iOS client can not discover the mucsub feature.

**2**
And where in the ejabberd.yml must i add the allow_subscription: true, i added this, don't know if it's ok though

```
mod_muc:
    default_room_options:
        allow_subscription: true
        persistent: true
        mam: true

```

**3**
Can each user get the list of subscribers or only moderator. And if so can each user be a moderator?
