### ISSUE TITLE
Adding IP address as authentication parameter

### ISSUE THREAD

**Issue by dancvrcek** [processone/ejabberd#1731]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Centos

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We use ejabberd inside a VPN with public-key authentication and want to avoid additional passwords. As we can already associate user accounts with IP addresses, I wonder if there's any chance to have the IP address available for authentication.

I noticed there's an old PR #25 - mixing 2 issues into one, with this commit https://github.com/processone/ejabberd/pull/25/commits/1afc08eeddeb38a6866ddd2dcbdc6b321c771782 adding the IP address (what it seems to do, at least).

I appreciate the single-sign-on inside a VPN is not something most people would do.

If it's far-fetched, can you please also let us know?

Cheers
  Dan

**Comment by badlop** [comment]
Something like this allows to login user2 from 127.0.0.2, allows user3 from 127.0.0.3, and denies any other possibilities:
```yaml
access_rules:
  c2s:
    - allow:
      - user: "user2@localhost"
      - ip: "127.0.0.2"
    - allow:
      - user: "user3@localhost"
      - ip: "127.0.0.3"
    - deny
```
That works for me. You also need to configure a stupid auth method that accepts any password, because auth is already done by ACL. You can try extauth with the example perl script.
