### ISSUE TITLE
mod_shared_roster_ldap doesn't work

### ISSUE THREAD

**Issue by BesatZardosht** [processone/ejabberd#1806]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

OSX

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I would like to use ldap groups to create roster for my users in ejebberd. I am using ejabberd 17.04 and ldap open directory.

This is the configuration for my ldap groups:

```
dn: cn=my_group,cn=groups,dc=dev,dc=myserver,dc=com
cn: my_group
apple-generateduid: 123123123123123
gidNumber: 123
apple-group-realname: My Group
objectClass: top
objectClass: posixGroup
objectClass: extensibleObject
objectClass: apple-group
myserver-type: office_t
memberUid: user1
memberUid: user2
apple-group-memberguid: 234234234234234234234234234
apple-group-memberguid: 345345345345345345345345345
```

This is my users config for ldap:

```
dn: uid=user1,cn=users,dc=dev,dc=myserver,dc=com
objectClass: person
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: posixAccount
objectClass: shadowAccount
objectClass: extensibleObject
objectClass: apple-user
uid: user1
apple-generateduid: 234234234234234234234234234
mail: user1mail@mail.com
givenName: User
sn: One
cn: User One
```

And this is my ejabberd config:

```
  mod_roster: {}
  ## mod_shared_roster: {}
  mod_shared_roster_ldap:
    ldap_base: "dc=dev,dc=myserver,dc=com"
    ldap_rfilter: "(myserver-type=office_t)"
    ldap_gfilter: "(&(myserver-type=office_t)(cn=%g))"
    ldap_groupattr: "cn"
    ldap_groupdesc: "apple-group-realname"
    ldap_memberattr: "memberUid"
    ldap_memberattr_format: "%u"
    ldap_ufilter: "(uid=%u)"
    ldap_useruid: "uid"
    ldap_userdesc: "cn"
    ldap_auth_check: off
```

But I cannot see user2 in user1's roster or vice versa. It doesn't populate any roster for any user.

I would appreciate any help.
