### ISSUE TITLE
Rest API auth on vhost with external authentication

### ISSUE THREAD

**Issue by tquackenbush** [processone/ejabberd#1820]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

debian jesse

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have a virtual host configured with external authentication.
I'm trying to expose the Rest API on this host to allow external administration.

I have been able to successfully auth to the Rest API by including credentials in an HTTP Basic auth header when using internal authentication, but have failed using the same HTTP Basic auth credentials with external authentication turned on. (normal chat authentication works with external auth enabled)

When I make Rest API calls, I do not see the ejabberd server trying to invoke the external script:
```
ejabberd_1  | 18:01:02.191 [info] (<0.884.0>) Accepted connection 172.17.0.1:58242 -> 172.17.0.2:5281
ejabberd_1  | 18:01:02.191 [info] started: {gen_tcp,#Port<0.20733>}
ejabberd_1  | 18:01:02.230 [info] API call ban_account [{<<"user">>,<<"foo">>},{<<"host">>,<<"xyz.io">>},{<<"reason">>,<<"Spaming other users">>}] from 172.17.0.1:58242
ejabberd_1  | 18:22:13.244 [info] (<0.906.0>) Accepted connection 172.17.0.1:58248 -> 172.17.0.2:5281
ejabberd_1  | 18:22:13.245 [info] started: {gen_tcp,#Port<0.20765>}
ejabberd_1  | 18:22:13.245 [info] API call ban_account [{<<"user">>,<<"foo">>},{<<"host">>,<<"xyz.io">>},{<<"reason">>,<<"Spaming other users">>}] from 172.17.0.1:58248
```

I would expect the credientials sent in the HTTP Basic auth header to be passed the the external auth script for verification.

Am I missing something simple?

**Comment by badlop** [comment]
Can you show the relevant information about that Rest api, and the access configuration?

**Comment by tquackenbush** [comment]
```


###   ================
###   SERVED HOSTNAMES

hosts:
  - "xyz.io"

###   ===============
###   LISTENING PORTS

listen:
  -
    port: 5281
    module: ejabberd_http
    request_handlers:
      "/api/v2": mod_http_api
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
    http_bind: true
    captcha: false

###   ==============
###   AUTHENTICATION

auth_method:
  - external
extauth_program: "/opt/ejabberd/scripts/lib/authorize.py"
extauth_instances: 3
extauth_cache: 600

###   ====================
###   ACCESS CONTROL LISTS

acl:
  admin:
    user:
      - "admin": "xyz.io"
  local:
    user_regexp: ""

###   ============
###   ACCESS RULES

access:
  ## Only admins can use the configuration interface:
  configure:
    admin: allow

api_permissions:
  "API used from localhost allows all calls":
    - who:
      - access: configure
    - what:
      - "*"
      - "!stop"
      - "!start"

###   =======
###   MODULES

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_configure: {} # requires mod_adhoc
  mod_bosh: {}

###   ============
###   HOST CONFIG

host_config:
  "xyz.io":
    domain_certfile: "/opt/ejabberd/ssl/xyz.io.pem"
```
