### ISSUE TITLE
How to use different mysql databases per vhost

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1852]
> What version of ejabberd are you using?

17.04

How do i configure the yml file so i can use a different mysql database per vhost?
I assume something like this?
```yaml
host_config:
  "site1.domain.com"  
         sql_database: "ejabberd1"  
  "site2.domain.com"  
         sql_database: "ejabberd2"  
```
Thank you in advance.

**Comment by zinid** [comment]
You have forgotten a colon:
```yaml
host_config:
  "site1.domain.com":
    sql_database: "ejabberd1"
  "site2.domain.com":
    sql_database: "ejabberd2"
```
