### ISSUE TITLE
protocol_options have zero effect

### ISSUE THREAD

**Issue by johndoe334344** [processone/ejabberd#1863]
> What version of ejabberd are you using?

17.07, the deb package
https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/17.07/ejabberd_17.07-0_amd64.deb

> What operating system (version) are you using?

debian jessie

> How did you install ejabberd (source, package, distribution)?

https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/17.07/ejabberd_17.07-0_amd64.deb

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

no error messages whatsoever, even with debug enabled

```
define_macro:
  'CERTFILE': "/opt/ejabberd-17.07/conf/server.pem"
  'CIPHERS': "HIGH:!MEDIUM:!LOW:!3DES:!CAMELLIA:!aNULL:!RSA@STRENGTH"
  'TLSOPTS':
    - "no_sslv2"
    - "no_sslv3"
    - "no_tlsv1"
    - "no_tlsv1_1"

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    protocol_options: 'TLSOPTS'
    certfile: 'CERTFILE'
    ciphers: 'CIPHERS'
    starttls: true
    starttls_required: true
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
    tls_compression: false
    dhfile: "/opt/ejabberd-17.07/conf/dh2048-ejabberd.pem"

```

IM observatory shows that ejabberd does not follow the protocol options at all. It accepts sslv3 and all the others.

I ran out of ideas. Any help from the pros? Is this a bug?
