### ISSUE TITLE
mod_http_upload with virtual hosts only works on one host

### ISSUE THREAD

**Issue by iainspacegen** [processone/ejabberd#1915]
> What version of ejabberd are you using?
16.01

> What operating system (version) are you using?
Linux 16.04

> How did you install ejabberd (source, package, distribution)?
distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
I have configured 2 virtual domains. One has internal authentication and the other one is using LDAP authentication
The mod_http_upload component has been configured globally using:
  ```
mod_http_upload:
    host: "upload.@HOST@"
    docroot: "@HOME@/upload"
    put_url: "https://chat.trybetv.com:5443/upload"
    thumbnail: true
    max_size: 10000000
    access: local
```
However, the HTTP File Upload service is only available on one virtual host, the one using internal authentication. See screenshots from the Pidgin Service Discovery tool.
When only have one virtual host then the HTTP File Upload service is displayed.
For now I'm using 
```
append_host_config:
  "spacegenerators.org":
    modules: 
```
to enable it one of the hosts as a workaround.
No errors in any logs (syslog and ejabberd logs) Have turned on debug logs and ejabberd only creates one instance of mod_http_upload. Attached as well.

[ejabberd._debug.log.txt](https://github.com/processone/ejabberd/files/1203056/ejabberd._debug.log.txt)
[ejabberd.yml.txt](https://github.com/processone/ejabberd/files/1203058/ejabberd.yml.txt)
[ejabberd.log.txt](https://github.com/processone/ejabberd/files/1203057/ejabberd.log.txt)

![screenshot_2017-08-06_13-16-49](https://user-images.githubusercontent.com/30771703/29003221-828c6ece-7aaa-11e7-8da0-51a9a87cf95e.png)
![screenshot_2017-08-06_13-17-28](https://user-images.githubusercontent.com/30771703/29003220-828c4002-7aaa-11e7-9740-ed023812efd4.png)
