### ISSUE TITLE
mod-multicast failed to start with bad match error

### ISSUE THREAD

**Issue by Murad-Dry** [processone/ejabberd#1949]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

oracle linux

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
mod-multicast failed to start, bad match error.
> was the unexpected behavior? What was the expected result?

**Comment by badlop** [comment]
Problem confirmed. I introduced the bug in two recent commits, 05346780283b02f459f539bd63a45879a5f7cc5b and https://github.com/processone/ejabberd/commit/4ef1cdec12a56d7a1d3908d66182362d59677393

The bug produces two problems:
1. The module, and ejabberd, do not start, as you reported
2. The module limits configuration is not read correctly, and only the default values are used.

I've committed the fix for all it.

You have two solutions: 
A) you can download the source code from git, compile it, and copy the modified mod_multicast.beam
B) Wait for next release, until then you can solve problem 1 by configuring in mod_multicast all the limits, for example:
```yaml
  mod_multicast:
     limits:
       local:
         message: 100
         presence: 100
       remote:
         message: 20
         presence: 20
```
Problem 2 remains: mod_multicast uses the default limit values, regardless what you configure, sorry.  This can only be solved by applying the fix.
