### ISSUE TITLE
mod_shared_roster_ldap not working after upgrade to 16.01

### ISSUE THREAD

**Issue by bwaldvogel** [processone/ejabberd#1951]
> What version of ejabberd are you using?

16.01

> What operating system (version) are you using?

Ubuntu 16.04 (LTS)

> How did you install ejabberd (source, package, distribution)?

`apt-get install ejabberd`

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I’ve upgraded Ubuntu from 14.04 to 16.04.
While `mod_shared_roster_ldap` worked perfectly for a long time in Ubuntu 14.04, it basically stopped working after the upgrade.
Users do not see other online users anymore, the rosters seem to be empty.
I cannot see any errors or other hints for the problem in the logfiles.

The old configuration was:
```
  […]
  {mod_roster,   []},
  {mod_shared_roster_ldap, [
          {ldap_groupattr, "cn"},
          {ldap_groupdesc, "description"},
          {ldap_memberattr, "uniqueMember"},
          {ldap_memberattr_format, "cn=%u,dc=company,dc=domain"},
          {ldap_useruid, "cn"},
          {ldap_userdesc, "displayName"},
          {ldap_rfilter, "(&(objectClass=groupOfUniqueNames)(info=jabber-group))"},
          {ldap_gfilter, "(&(objectClass=groupOfUniqueNames)(info=jabber-group)(cn=%g))"},
          {ldap_ufilter, "(&(objectClass=person)(cn=%u))"},
          {ldap_filter, ""}
          ]},
   […]
```

The new configuration is:
```
  mod_roster: {}
  mod_shared_roster_ldap:
    ldap_groupattr: "cn"
    ldap_groupdesc: "description"
    ldap_memberattr: "uniqueMember"
    ldap_memberattr_format: "cn=%u,dc=company,dc=domain"
    ldap_useruid: "cn"
    ldap_userdesc: "displayName"
    ldap_rfilter: "(&(objectClass=groupOfUniqueNames)(info=jabber-group))"
    ldap_gfilter: "(&(objectClass=groupOfUniqueNames)(info=jabber-group)(cn=%g))"
    ldap_ufilter: "(&(objectClass=person)(cn=%u))"
```

LDAP authentication itself is working properly.
