### ISSUE TITLE
Shared Roster Group for Virtual Hosts not working

### ISSUE THREAD

**Issue by erdna1982** [processone/ejabberd#1961]
> What version of ejabberd are you using?

17.08
> What operating system (version) are you using?

debian:jessie
> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
Hello.

I have three different virtual hosts:
VH1 - some.example1.de
VH2 - some.example2.de
VH3 - some.example3.de

For every host there is an Moderator in a Moderator shared roster group. There also a Visitors shared roster group for each visitor in each VH.

The moderator group for the VH1:
Name: Moderator_VH1
Members: Mod1@some.example1.de
Displayed Groups: Visitors_VH1

The visitors group for VH1:
Name: Visitors_VH1
Members: @online@
Displayed Groups: Moderator_VH1

expected behaviour:
Mod1 from VH1 should only see the online users from VH1 & the visitor from VH1 should only see Mod1 from VH1.

actual behaviour:
All Mods see all other Mods and every online User from all VHs & all Visitors from each VH see all Mods from all VHs

cheers
Andre

**Comment by erdna1982** [comment]
I using a postgres DB and the output from the sr_group table doesn' show me any virtual host for the groups. It seems that the configuration for shared roster groups on the Admin-GUI configured global shared roster groups!? But in the ejabberd.yml i configured the mod_shared_roster: {} for each VH.

modules:
      mod_adhoc: {}
      mod_caps: {}
      mod_carboncopy: {}
      mod_configure: {}
       ...
       ....
append_host_config:
    "some.example1.de":
           modules:
                ...
                ...
                ...
                mod_shared_roster: {}
                ...
                ...
                ...
append_host_config:
    "some.example2.de":
           modules:
               ...
                ...
                ...
                mod_shared_roster: {}
                ...
                ...
                ...

**Comment by badlop** [comment]
If you configure something like this, all the vhosts will use that database, sharing the same tables. And the tables do not differentiate from each vhost. This means that all the vhosts will be essentially clones one of each other. You have two options, either define a different database for each vhost, or use Mnesia.

```yaml
hosts:
  - "localhost"
  - "example.com"

sql_type: mysql
sql_server: "localhost"
sql_database: "ejabberd_test"
sql_username: "ejabberd_test"
sql_password: "ejabberd_test"
```

**Comment by erdna1982** [comment]
ahhh, thank you bradlop :) I did not think of that. But I thought it was not possible to configure different databases to different hosts like:

_hosts:
  - "example1.com"
  - "example2.com"
  - "example3.com"

host_config:
  - "example1.com"
            auth_method: sql

sql_type: pgsql
sql_server: "ejbdpg"
sql_database: "example1"
sql_username: "user"
sql_password: "password"
  
- "example2.com"
            auth_method: sql

sql_type: pgsql
sql_server: "ejbdpg"
sql_database: "example2"
sql_username: "user"
sql_password: "password"
 


 - "example3.com"
            auth_method: sql

sql_type: pgsql
sql_server: "ejbdpg"
sql_database: "example3"
sql_username: "user"
sql_password: "password"_

**Should that work?**

Thanks in advance :)

**Comment by erdna1982** [comment]
Sorry for the bad formated text before...I think I use Mnesia and configure every VH to use anonymous and internal auth_method. Thanks!

**Comment by badlop** [comment]
Just for curiosity, I think the correct formatting for what you want would be this, looking at
https://docs.ejabberd.im/admin/configuration/#database-and-ldap-configuration

```yaml
hosts:
  - "example1.com"
  - "example2.com"
  - "example3.com"

host_config:
  "example1.com":
    auth_method: sql
    sql_type: pgsql
    sql_server: "ejbdpg"
    sql_database: "example1"
    sql_username: "user"
    sql_password: "password"
  "example2.com":
    auth_method: sql
    sql_type: pgsql
    sql_server: "ejbdpg"
    sql_database: "example2"
    sql_username: "user"
    sql_password: "password"
  "example3.com":
    auth_method: sql
    sql_type: pgsql
    sql_server: "ejbdpg"
    sql_database: "example3"
    sql_username: "user"
    sql_password: "password"
```
