### ISSUE TITLE
PEP stopped working when after the upgrade from ejabberd 16 to 17

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [processone/ejabberd#1974]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Debian Jessie (olstable)

> How did you install ejabberd (source, package, distribution)?

Debian Unstable repo

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Since upgrade from some 16 version, PEP stopped working, although config changed very little. `mod_pubsub` section didn't change at all, here it is:

```
  mod_pubsub:
    db_type: sql
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep"
```

`mod_caps` is enabled and works, judging by new entries in the `caps_features` table in the Postgre:

```
  mod_caps:
    db_type: sql
```

The most wanted feature which PEP enables is OMEMO. Now I can't use this feature in Conversations, and this app clearly shows that `XEP-0163: PEP (Avatars / OMEMO): unavailable`.

I've recreated all pubsub tables from scratch using your latest `pg.sql`.

This is known bug or some additional configuration required when migrating from ejabberd 16?
