### ISSUE TITLE
【Generic server <0.19101.3> terminating 】

### ISSUE THREAD

**Issue by jhaoheng** [processone/ejabberd#1997]
> What version of ejabberd are you using?
ejabberd 17.07

> What operating system (version) are you using?
ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?
package

----

Hi 

My module conf is 

```
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_bosh: {}
  mod_last: {}
  mod_muc:
    ## host: "conference.@HOST@"
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping:     
    send_pings: true
    ping_interval: 5
    timeout_action: kill
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    registration_watchers:
      - "admin"
    ip_access: trusted_network=
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard:
    search: false
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
  mod_http_api: {}
  mod_service_log: {}
```

The sys crash log are below and how i fix this issue?
This crash issue happened many times.(about every week twice)
Does anyone have any suggestion? thank you.

```
2017-09-11 18:54:42 =ERROR REPORT====
** Generic server <0.19101.3> terminating 
** Last message in was {'$gen_event',{xmlstreamelement,{xmlel,<<"iq">>,[{<<"xmlns">>,<<"jabber:client">>},{<<"id">>,<<"2372103458598276926">>},{<<"type">>,<<"result">>},{<<"to">>,<<"xmpp.sample.com">>}],[]}}}
** When Server state == #{resource => <<>>,xmlns => <<"jabber:client">>,mgmt_timeout => 300,mgmt_stanzas_in => 0,stream_restarted => true,mgmt_queue_type => ram,tls_required => false,auth_module => ejabberd_auth_sql,pres_a => {0,nil},stream_state => wait_for_stream,tls_verify => false,server => <<"xmpp.sample.com">>,mgmt_resend => false,mgmt_stanzas_req => 0,mgmt_ack_timeout => 60000,mgmt_state => inactive,stream_compressed => false,user => <<"48679">>,stream_authenticated => true,ip => {{172,31,18,179},61946},stream_header_sent => false,socket_monitor => #Ref<0.0.6553601.80670>,tls_options => [compression_none],stream_encrypted => false,lserver => <<"xmpp.sample.com">>,mgmt_stanzas_out => 0,stream_version => {1,0},mgmt_max_timeout => 300,sockmod => ejabberd_socket,stream_timeout => {30000,-576446904642},mod => ejabberd_c2s,lang => <<"en">>,mgmt_max_queue => 1000,socket => {socket_state,ejabberd_bosh,{http_bind,<0.19100.3>,{{172,31,18,179},61946}},ejabberd_bosh},owner => <0.19101.3>,tls_enabled => false,shaper => c2s_shaper,stream_direction => in,stream_id => <<"7494620191320711576">>,zlib => false,access => c2s}
** Reason for termination == 
** {{case_clause,{iq,<<"2372103458598276926">>,result,<<>>,undefined,{jid,<<>>,<<"xmpp.sample.com">>,<<>>,<<>>,<<"xmpp.sample.com">>,<<>>},[],#{}}},[{xmpp_stream_in,process_element,2,[{file,"src/xmpp_stream_in.erl"},{line,528}]},{xmpp_stream_in,handle_info,2,[{file,"src/xmpp_stream_in.erl"},{line,341}]},{p1_server,handle_msg,8,[{file,"src/p1_server.erl"},{line,696}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2017-09-11 18:54:42 =CRASH REPORT====
  crasher:
    initial call: xmpp_stream_in:init/1
    pid: <0.19101.3>
    registered_name: []
    exception exit: {{{case_clause,{iq,<<"2372103458598276926">>,result,<<>>,undefined,{jid,<<>>,<<"xmpp.sample.com">>,<<>>,<<>>,<<"xmpp.sample.com">>,<<>>},[],#{}}},[{xmpp_stream_in,process_element,2,[{file,"src/xmpp_stream_in.erl"},{line,528}]},{xmpp_stream_in,handle_info,2,[{file,"src/xmpp_stream_in.erl"},{line,341}]},{p1_server,handle_msg,8,[{file,"src/p1_server.erl"},{line,696}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},[{p1_server,terminate,7,[{file,"src/p1_server.erl"},{line,878}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [ejabberd_c2s_sup,ejabberd_sup,<0.62.0>]
    messages: [{'$gen_event',{xmlstreamelement,{xmlel,<<"iq">>,[{<<"xmlns">>,<<"jabber:client">>},{<<"id">>,<<"2372103458598276926">>},{<<"type">>,<<"result">>},{<<"to">>,<<"xmpp.sample.com">>}],[]}}}]
    links: [<0.645.0>]
    dictionary: [{'$internal_queue_len',1},{already_terminated,true}]
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 64192
  neighbours:
```
