### ISSUE TITLE
Register in band not allowed

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#2040]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I get an error for register in band:

_{"code":"403","type":"auth"}
Access denied by service policy_

Using the 17.01 ejabberd version it works fine.
The config is the same for both versions and the application too:
```yaml
acl:
  loopback:
    ip:
      - "xxx.xxx.xxx.xxx"
      - "yyy.yyy.yyy.yyy"
      - "zzz.zzz.zzz.zzz"

access_rules:
  register:
    - allow
  trusted_network:
    - allow: loopback

modules:
  mod_register:
    ip_access: trusted_network
    access: register
    access_from: register
```
Is there anything I should change in the config?
Any advice?

**Comment by badlop** [comment]
With your version and configuration, I can easily reproduce the error if I attempt to register the account from an IP not in the loopback. First my client tries unsuccesfully to login:
```
20:17:57.901 [info] (<0.521.0>) Accepted connection ::FFFF:127.0.0.1:46076 -> ::FFFF:127.0.0.1:5222
20:17:57.965 [info] (tcp|<0.521.0>) Failed c2s SCRAM-SHA-1 authentication
 for user1zz7@localhost from ::FFFF:127.0.0.1: Invalid username or password
```
And later it tries to register the account, but also fails. That doesn't generate log lines in the loglevel 4.

Remove the ip_access option, does registration work? Then check what IP address your client uses, is that in the allowed range?

**Comment by Emilio-Gonzalez** [comment]
If I remove the ip_access option the registration do work.

But I need to specify the IPs authorized to register in band, so I specify each IP inside the option
_acl:
  loopback:
    ip:_

The IP addresses my clients use aren´t specified in a range.
Don`t know what I'm doing wrong. Is a range required?

**Comment by badlop** [comment]
I tried to login, but the account didn't exist, and registration was rejected due to IP not allowed:
```
12:32:08.563 [info] (tcp|<0.499.0>) Failed c2s SCRAM-SHA-1 authentication
 for user1zz9@localhost from ::FFFF:127.0.0.1: Invalid username or password
```

So I added that specific IPv6 address:
```yaml
acl:
  loopback:
    ip:
      - "::FFFF:127.0.0.1"
```

After restarting, registration from that address was allowed.

So, I recommend you to try to login, and let ejabberd log the failed loggin attempt like in my case. Look what IP address the client is using. Maybe it's IPv4, or it's IPv6 like in my case. Then put that same address in the config file.
