### ISSUE TITLE
I keep getting 503: service unavailable when i try to send a stream initiation

### ISSUE THREAD

**Issue by oladipo** [processone/ejabberd#2068]
> What version of ejabberd are you using?

ejabberd 17.08.44

> What operating system (version) are you using?
Ubuntu Xenial 

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
no error message in logs just that it says ""No module is handling this query"".

my config:
```yaml
  mod_proxy65:
    host: "proxy.@HOST@"
    name: "File Transfer Proxy"
    ip: "192.34.60.212"
    port: 7777
    max_connections: 10
    access:
      - allow
```
