### ISSUE TITLE
non-combined certs and keys

### ISSUE THREAD

**Issue by pacija** [processone/ejabberd#2076]
Hi,

are there any plans to support non-combined certificates in ejabberd configuration? Perhaps something similar to Apache (SSLCertificateFile, SSLCertificateKeyFile, SSLCertificateChainFile)?

I'm asking because most of the services I provide have the ability for this, including Apache, Dovecot and Postfix, so I can point those services to read certificates directly from Let'sEncrypt's certs directory.

Something like:
```
listen:
  -
  ...
    port: 5222
    module: ejabberd_c2s
    certfile: "/usr/local/etc/dehydrated/certs/example.org/cert.pem"
    chainfile: "/usr/local/etc/dehydrated/certs/example.org/fullchain.pem"
    cafile: "/usr/local/etc/dehydrated/certs/example.org/privkey.pem"
    starttls: true
...
```

Thank you in advance.
