### ISSUE TITLE
Send file with mod_http_upload

### ISSUE THREAD

**Issue by Xoner94** [processone/ejabberd#2095]
> What version of ejabberd are you using?
17.07

> What operating system (version) are you using?
Debian

> How did you install ejabberd (source, package, distribution)?
From source

I'm currently trying to build a mobile app that includes a chat. I picked Ejabberd as Instant Messaging server, and managed to configure it to work with texts, audio and video chats.
I am now I trying to use it to send files between users, using the "mod_http_upload", but I'm not able to configure it correctly. 
When I try to send a file, here is what I get : 

```
FileTransferError {code: 1, source: "file:///data/user/0/com.ionicframework.wuddoc169369/files/1510218264211.jpg", target: "http://172.16.15.147:5444/upload/1c02ec3606b53d19f…1NROUdhktvk8AKFnkE/received_10211301731719177.png", http_status: 500, body: "Internal server error."…}
1.	body:"Internal server error."
2.	code:1
3.	exception:"http://172.16.15.147:5444/upload/1c02ec3606b53d19f2390a19e3c67771ffc8a07c/imwrOcP4Sjesk9PW8Cw48S1NROUdhktvk8AKFnkE/received_10211301731719177.png"
4.	http_status:500
5.	source:"file:///data/user/0/com.ionicframework.wuddoc169369/files/1510218264211.jpg"
6.	target:"http://172.16.15.147:5444/upload/1c02ec3606b53d19f2390a19e3c67771ffc8a07c/imwrOcP4Sjesk9PW8Cw48S1NROUdhktvk8AKFnkE/received_10211301731719177.png"
7.	__proto__:Object
```

Here is the module configuration I wrote : 
In listening :  
```
port: 5444
     module: ejabberd_http
     request_handlers:
       "/upload": mod_http_upload
     tls: false
```

In modules : 
 ```
mod_http_upload:
    docroot: "@HOME@/upload"
    put_url: "http://@HOST@:5444/upload"
    thumbnail: false # otherwise needs the identify command from ImageMagick installed
    custom_headers: 
        "Access-Control-Allow-Origin": "*"   
        "Access-Control-Allow-Methods": "*"  
        "Access-Control-Allow-Headers": "content-type" 
```

Finally, in the ejabberd.log file, I get this line : 
`2017-11-09 10:04:59.819 [error] <0.423.0>@mod_http_upload:process:380 Cannot handle PUT request from 172.16.23.155 for 172.16.15.147: {'EXIT',{noproc,{gen_server,call,['mod_http_upload_172.16.15.147/upload',{use_slot,[<<"1c02ec3606b53d19f2390a19e3c67771ffc8a07c">>,<<"imwrOcP4Sjesk9PW8Cw48S1NROUdhktvk8AKFnkE">>,<<"received_10211301731719177.png">>],414446}]}}}`

I tried to use the "ejabberdctl debug" command, to get more infos, and here is what I get : 
`(ejabberd@localhost)1> process_info(list_to_pid("<0.380.0>"), registered_name). {registered_name,'mod_http_upload_ejabberd/upload'}`

Right now I'm a bit confused, if someone could help me understand what's wrong with my setup, I would be grateful.

Thank you for your time and help !
