### ISSUE TITLE
HTTP upload broken in 17.11

### ISSUE THREAD

**Issue by sander85** [processone/ejabberd#2127]
> What version of ejabberd are you using?
17.11

> What operating system (version) are you using?
CentOS 7

> How did you install ejabberd (source, package, distribution)?
RPM from Your homepage.

> What did not work as expected?
I'm unable to use HTTP upload after upgrading to 17.11

> Are there error messages in the log?
Yes:
```
2017-11-26 16:36:10.525 [warning] <0.246.0>@ejabberd_pkix:handle_call:210 No certificate found matching 'upload.mydomain.eu': strictly configured clients or servers will reject connections with this host; obtain a certificate for this (sub)domain from any trusted CA such as Let's Encrypt (www.letsencrypt.org)
2017-11-26 17:02:01.355 [error] <0.532.0>@ejabberd_http:init:114 CRASH REPORT Process <0.532.0> with 0 neighbours crashed with reason: no match of right hand value {error,no_certfile} in ejabberd_http:init/2 line 114
```
> What was the unexpected behavior?
Depending on the way my mod_http_upload is configured ejabberd shouldn't fail when someone is uploading files/images.

This is how my mod_http_upload is configured:
```
  mod_http_upload:
    max_size: 20971520
    file_mode: "0640"
    dir_mode: "0750"
    docroot: "/var/lib/ejabberd/upload"
    put_url: "https://conference.@HOST@:5280/upload"
```
This was working at least in 17.08. Now it seems ejabberd expects that I should connect to upload.mydomain.eu.

> What was the expected result?
mod_http_upload should check if put_url is used and if it has valid certificate for that domain. If yes, then there is no need to warn about upload.mydomain.eu or force user to use this domain for uploading.
