### ISSUE TITLE
"ERROR:cannot_register" when admin user being created in v17.11.20

### ISSUE THREAD

**Issue by myluckyapps** [processone/ejabberd#2141]
> What version of ejabberd are you using?

17.11.20

> What operating system (version) are you using?

Ubuntu 16.04.2

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What

admin user registration is not working. Error message is when execusting below command: 

```
ejabberd@ip-xxx:~$ /usr/local/sbin/ejabberdctl register admin ec2-35-167-159-255.us-west-2.compute.amazonaws.com password
Error: cannot_register
```

Help Needed: 

Sorry for lame question - but I am not sure if its latest source code issue or mod_registration issue or api permission issue. But I was not able to register admin user. I have spent lot of time already by using mod_register but in vain. Can you help me to point out if any issue with config? Any other hack also appreciated.

Configuration: 
```yaml
loglevel: 5
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "ec2-34-XXXXX.us-west-2.compute.amazonaws.com"
  - "localhost"
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/api": mod_http_api
    web_admin: true
    captcha: true
auth_method: internal
shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 10000
acl:
  admin:
    user:
      - "admin@ec2-XXXXXXXX.us-west-2.compute.amazonaws.com"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow: all
  trusted_network:
    - allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"
language: "en"
acme:
   contact: "mailto:example-admin@example.com"
   ca_url: "https://acme-v01.api.letsencrypt.org"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
    access: announce
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_disco: {}
  mod_echo: {}
  mod_irc: {}
  mod_bosh: {}
  mod_last: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_avatar:
    convert:
      webp: jpeg
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
  mod_http_api: {}
allow_contrib_modules: true
```

ejabberd logs: 
```
2017-12-02 14:57:08.173 [debug] <0.305.0>@ejabberd_access_permissions:handle_call:139
 Command 'register' execution allowed by rule 'console commands'
 (CallerInfo=#{caller_module => ejabberd_ctl})
2017-12-02 14:57:08.173 [debug] <0.508.0>@ejabberd_commands:do_execute_command
:495 Executing command ejabberd_admin:register with Args
=[<<"admin">>,<<"ec2-xxxus-west-2.compute.amazonaws.com">>,<<"password">>]
```
