### ISSUE TITLE
Not using Postgres

### ISSUE THREAD

**Issue by melvinkcx** [processone/ejabberd#2172]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Docker on Ubuntu 16

> How did you install ejabberd (source, package, distribution)?

Docker image: rroemhild/ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am configuring Ejabberd to use my Postgres as backend. It seems that Ejabberd is not using it since I cant find my registered users in my DB. 

Meanwhile, I dont see any logs regarding failure to connect to my DB. How do I know if Ejabberd is using my Postgres exactly? 

This is my ejabberd.yml: 
```yaml
###
###               ejabberd configuration file
###
###

### The parameters used in this configuration file are explained in more detail
### in the ejabberd Installation and Operation Guide.
### Please consult the Guide in case of doubts, it is included with
### your copy of ejabberd, and is also available online at
### http://www.process-one.net/en/ejabberd/docs/

###   =======
###   LOGGING

loglevel: 4
log_rotate_size: 10485760
log_rotate_count: 0
log_rate_limit: 100

## watchdog_admins:
##   - "bob@example.com"

###   ================
###   SERVED HOSTNAMES

hosts:
  - "localhost"
  - "ec2-xxxxxxxxxxx.ap-southeast-1.compute.amazonaws.com"

##
## route_subdomains: Delegate subdomains to other XMPP servers.
## For example, if this ejabberd serves example.org and you want
## to allow communication with an XMPP server called im.example.org.
##
## route_subdomains: s2s

###   ===============
###   LISTENING PORTS

listen:
  -
    port: 5222
    module: ejabberd_c2s
    starttls_required: true
    protocol_options:
      - "no_sslv3"
      - "no_tlsv1"
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
    ciphers: "HIGH:!aNULL:!3DES"
  -
    port: 5269
    module: ejabberd_s2s_in
  -
    port: 4560
    module: ejabberd_xmlrpc
    access_commands:
      configure:
        all: []

  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    ## register: true
    captcha: true
    tls: true
    certfile: "/opt/ejabberd/ssl/host.pem"
    
  -
    port: 5443
    module: ejabberd_http
    request_handlers:
      "": mod_http_upload
    tls: true
    certfile: "/opt/ejabberd/ssl/host.pem"
    


###   SERVER TO SERVER
###   ================
s2s_use_starttls: required
s2s_certfile: "/opt/ejabberd/ssl/host.pem"
s2s_protocol_options:
  - "no_sslv3"
  - "no_tlsv1"
s2s_ciphers: "HIGH:!aNULL:!3DES"


###   ==============
###   AUTHENTICATION

auth_method:
  - internal

auth_password_format: scram


## LDAP authentication

###   ===============
###   TRAFFIC SHAPERS

shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 1000

###   ====================
###   ACCESS CONTROL LISTS

acl:
  admin:
    user:
      - "xxxxx": "localhost"
  local:
    user_regexp: ""

###   ============
###   ACCESS RULES

access:
  ## Maximum number of simultaneous sessions allowed for a single user:
  max_user_sessions:
    all: 10
  ## Maximum number of offline messages that users can have:
  max_user_offline_messages:
    admin: 5000
    all: 100
  ## This rule allows access only for local users:
  local:
    local: allow
  ## Only non-blocked users can use c2s connections:
  c2s:
    blocked: deny
    all: allow
  ## For C2S connections, all users except admins use the "normal" shaper
  c2s_shaper:
    admin: none
    all: normal
  ## All S2S connections use the "fast" shaper
  s2s_shaper:
    all: fast
  ## Only admins can send announcement messages:
  announce:
    admin: allow
  ## Only admins can use the configuration interface:
  configure:
    admin: allow
  ## Admins of this server are also admins of the MUC service:
  muc_admin:
    admin: allow
  ## Only accounts of the local ejabberd server, or only admins can create rooms, depending on environment variable:
  muc_create:
    local: allow
    
  ## All users are allowed to use the MUC service:
  muc:
    all: allow
  ## Only accounts on the local ejabberd server can create Pubsub nodes:
  pubsub_createnode:
    local: allow
  ## In-band registration allows registration of any possible username.
  register:
    all: allow
    
  ## Only allow to register from localhost
  trusted_network:
    loopback: allow
  soft_upload_quota:
    all: 400 # MiB
  hard_upload_quota:
    all: 500 # MiB


language: "en"

###   =======
###   MODULES

modules:
  mod_adhoc: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state:
    queue_chat_states: true
    queue_presence: false
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  ## mod_echo: {}
  mod_irc: {}
  mod_http_bind: {}
  ## mod_http_fileserver:
  ##   docroot: "/var/www"
  ##   accesslog: "/var/log/ejabberd/access.log"
  mod_last: {}
  mod_mam:
    default: always
  mod_muc:
    host: "conference.@HOST@"
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
    history_size: 50
    default_room_options:
      persistent: true
  ## mod_muc_log: {}
  ## mod_multicast: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  ## mod_pres_counter:
  ##   count: 5
  ##   interval: 60
  mod_privacy: {}
  mod_private: {}
  ## mod_proxy65: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ##
    ## Protect In-Band account registrations with CAPTCHA.
    ##
    ## captcha_protected: true

    ##
    ## Set the minimum informational entropy for passwords.
    ##
    ## password_strength: 32

    ##
    ## After successful registration, the user receives
    ## a message with this subject and body.
    ##
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.

    ##
    ## Only clients in the server machine can register accounts
    ##

    access: register
  mod_roster: {}
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard: {}
  
  mod_http_upload:
    docroot: "/opt/ejabberd/upload"
    put_url: "https://@HOST@:5443"
  mod_http_upload_quota:
    max_days: 10

###   ============
###   HOST CONFIG

host_config:
  "localhost":
    domain_certfile: "/opt/ejabberd/ssl/localhost.pem"
    sql_type: pgsql
    sql_server: xxxxxxxxxxx.ap-southeast-1.rds.amazonaws.com
    sql_port: 5432
    sql_database: xxxx
    sql_username: xxxxxxxx
    sql_password: xxxxxxxxxxxxxx
    sql_pool_size: 5
    auth_method: [sql]
  "ec2-xxxxxxxxx.ap-southeast-1.compute.amazonaws.com":
    domain_certfile: "/opt/ejabberd/ssl/ec2-xxxxxxxx.ap-southeast-1.compute.amazonaws.com.pem"
    sql_type: pgsql
    sql_server: xxxxxxxxxxxxxxx.ap-southeast-1.rds.amazonaws.com
    sql_port: 5432
    sql_database: xxxxx
    sql_username: xxxxxxx
    sql_password: xxxxxxx
    sql_pool_size: 5
    auth_method: [sql]



###   =====================
###   SESSION MANAGEMENT DB
sm_db_type: mnesia
```

**Comment by badlop** [comment]
> I am configuring Ejabberd to use my Postgres as backend. 
> Meanwhile, I dont see any logs regarding failure to connect to my DB. How do I know if Ejabberd is using my Postgres exactly?

First of all, make sure ejabberd is reading the configuration file that you edited, and not any other. For this, setup incorrectly your SQL, or set a wrong path to the certificate file... something that should break ejabberd start, and will surely show in the log file. If ejabberd complains about the problem you provoked, then it is using the config file you are editing.

Second, set the config file correctly, then try to login to localhost with an inexistent account, it should complain. Then register that account and try to login again. In the logs is it accepted by mnesia, or by other backend?

> It seems that Ejabberd is not using it since I cant find my registered users in my DB.

Notice that, if you created the accounts in Mnesia first, they aren't automatically migrated to SQL.

With my default config, that uses internal auth, when I login I see a reference to mnesia:
```
11:55:11.170 [info] (<0.493.0>) Accepted connection ::FFFF:127.0.0.1:39101 -> ::FFFF:127.0.0.1:5222
11:55:16.526 [info] (tcp|<0.493.0>) Accepted c2s SCRAM-SHA-1 authentication
 for user1@localhost by mnesia backend from ::FFFF:127.0.0.1
11:55:16.613 [info] (tcp|<0.493.0>) Opened c2s session for user1@localhost/tka1
```
In your case, with your config, it should say "sql backend" or something like that.

> This is my ejabberd.yml:

It seems configured correctly. Just for curiosity, try to remove those lines:
```yaml
auth_method:
  - internal

auth_password_format: scram
```
