### ISSUE TITLE
store group message in mysql database

### ISSUE THREAD

**Issue by pratikshivlab** [processone/ejabberd#2199]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

Ubuntu 16.04

Hello,
i want to store group message in database.
i have already enabled MAM in mod_muc in ylm file still i am not able to store messages in databse.
my yml file setting is below:
```yaml
mod_mam:
     iqdisc: one_queue    
     db_type: sql
     default: always    
     request_activates_archiving: false    
     assume_mam_usage: true

  mod_muc:
    host : "conference.@HOST@"
    db_type: sql
    access : muc
    access_create : muc
    access_persistent : muc
    access_admin : muc_admin
    history_size : 50
    max_users : 500
    default_room_options : 
      allow_change_subj : true
      allow_private_messages : true
      allow_user_invites : true
      anonymous : true
      logging : true
      mam : true
      members_by_default : true
      persistent : true
      public : true
      public_list : false
```

**Comment by badlop** [comment]
Your configuration was problematic in my test: the chatroom service didn't show in service disco. And the rooms didn't start.

I reduced it to the minimum:
```yaml
  mod_mam:
     default: always
     db_type: sql
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      mam: true
      persistent: true
```
Now the chat service shows, I can login to a room, send a message, and it is stored in the Archive table. Copy that config to your configuration file, and try again.
