### ISSUE TITLE
[error] failed to route packet: (new API for IQ routing)

### ISSUE THREAD

**Issue by anghiloglu-dmitrii** [processone/ejabberd#2209]
> What version of ejabberd are you using?
ejabberd 17.11, 17.12

> What operating system (version) are you using?
ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
Configuration:
2 ejabberd nodes(ejabberd1, ejabberd2) in cluster behind haproxy
db_type: tested only mnesia and riak

Use case:
 1. User connects to the node ejabberd2
 2. Admin sets node ejabberd2 to maintenance from haproxy.
 3. User reconnects to the node ejabberd1, session is resumed.
 4. No errors on client side packets are sent and received. But we see errors in the ejabberd1's logs 

20:32:35.189 [error] failed to route packet:
first
> #iq{id = <<"rr-1515090814957-12874876770418569217-rAvV5xLrs66EFY82f4YkHjf6cJM=-ejabberd1@localhost">>,
>     type = result,lang = <<"en">>,
>     from = {jid,<<"550500">>,<<"replacedhost">>,
>                 <<"7929d7b3-7254-4395-9a71-ee770dfc29eb">>,<<"550500">>,
>                 <<"replacedhost">>,<<"7929d7b3-7254-4395-9a71-ee770dfc29eb">>},
>     to = {jid,<<"550500">>,<<"replacedhost">>,<<>>,<<"550500">>,<<"replacedhost">>,<<>>},
>     sub_els = [],
>     meta = #{ip => {0,0,0,0,0,65535,49320,425}}}
> Reason = {error,{{case_clause,{route,{iq,<<"rr-1515090814957-12874876770418569217-rAvV5xLrs66EFY82f4YkHjf6cJM=-ejabberd1@localhost">>,result,<<"en">>,{jid,<<"550500">>,<<"replacedhost">>,<<"7929d7b3-7254-4395-9a71-ee770dfc29eb">>,<<"550500">>,<<"replacedhost">>,<<"7929d7b3-7254-4395-9a71-ee770dfc29eb">>},{jid,<<"550500">>,<<"replacedhost">>,<<>>,<<"550500">>,<<"replacedhost">>,<<>>},[],#{ip => {0,0,0,0,0,65535,49320,425}}},{1515090814957,<<"12874876770418569217">>}}},[{ejabberd_router,do_route,1,[{file,"src/ejabberd_router.erl"},{line,362}]},{ejabberd_router,route,1,[{file,"src/ejabberd_router.erl"},{line,93}]},{ejabberd_c2s,check_privacy_then_route,2,[{file,"src/ejabberd_c2s.erl"},{line,813}]},{xmpp_stream_in,process_authenticated_packet,2,[{file,"src/xmpp_stream_in.erl"},{line,596}]},{xmpp_stream_in,handle_info,2,[{file,"src/xmpp_stream_in.erl"},{line,341}]},{p1_server,handle_msg,8,[{file,"src/p1_server.erl"},{line,696}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}

second
> 20:33:35.095 [error] failed to route packet:
> #iq{id = <<"rr-1515090874962-1973831066989768961-kfMphDyaDMP+V0Hkb4H98B2nz/U=-ejabberd1@localhost">>,
>     type = result,lang = <<"en">>,
>     from = {jid,<<"550500">>,<<"youchat">>,
>                 <<"7929d7b3-7254-4395-9a71-ee770dfc29eb">>,<<"550500">>,
>                 <<"youchat">>,<<"7929d7b3-7254-4395-9a71-ee770dfc29eb">>},
>     to = {jid,<<"550500">>,<<"youchat">>,<<>>,<<"550500">>,<<"youchat">>,<<>>},
>     sub_els = [],
>     meta = #{ip => {0,0,0,0,0,65535,49320,425}}}
> Reason = {error,{{case_clause,{route,{iq,<<"rr-1515090874962-1973831066989768961-kfMphDyaDMP+V0Hkb4H98B2nz/U=-ejabberd1@localhost">>,result,<<"en">>,{jid,<<"550500">>,<<"youchat">>,<<"7929d7b3-7254-4395-9a71-ee770dfc29eb">>,<<"550500">>,<<"youchat">>,<<"7929d7b3-7254-4395-9a71-ee770dfc29eb">>},{jid,<<"550500">>,<<"youchat">>,<<>>,<<"550500">>,<<"youchat">>,<<>>},[],#{ip => {0,0,0,0,0,65535,49320,425}}},{1515090874962,<<"1973831066989768961">>}}},[{ejabberd_router,do_route,1,[{file,"src/ejabberd_router.erl"},{line,362}]},{ejabberd_router,route,1,[{file,"src/ejabberd_router.erl"},{line,93}]},{ejabberd_c2s,check_privacy_then_route,2,[{file,"src/ejabberd_c2s.erl"},{line,813}]},{xmpp_stream_in,process_authenticated_packet,2,[{file,"src/xmpp_stream_in.erl"},{line,596}]},{xmpp_stream_in,handle_info,2,[{file,"src/xmpp_stream_in.erl"},{line,341}]},{p1_server,handle_msg,8,[{file,"src/p1_server.erl"},{line,696}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}

The error occurs periodically, see timestamps bellow
20:32:35.189
20:33:35.095
20:34:35.300
20:35:36.003
20:36:35.117
...

I tried to debug the issue, I found that the issue reproduces only for ejabberd 17.11, 17.12. No repro for ejabberd 17.09. 
Starting from ejabberd 17.11 a new API for routing is used.
The issue must be in function `ejabberd_cluster:send({?MODULE, Node}, {route, IQ, {Expire, Rnd}});` inside `ejabberd_iq:dispatch(Packet)` in function `do_route/1` from module ejabberd_router 
It must return true or false but in fact it returns for some usecases a tuple like this 
` {route,{iq,<<"rr-1515091054975-5477599767000784897-LUCKDw0MMy2EF261Il10kTAcezE=-ejabberd1@localhost">>,result,<<"en">>,{jid,<<"550500">>,<<"replacedhost">>,<<"7929d7b3-7254-4395-9a71-ee770dfc29eb">>,<<"550500">>,<<"replacedhost">>,<<"7929d7b3-7254-4395-9a71-ee770dfc29eb">>},{jid,<<"550500">>,<<"replacedhost">>,<<>>,<<"550500">>,<<"replacedhost">>,<<>>},[],#{ip => {0,0,0,0,0,65535,49320,425}}},{1515091054975,<<"5477599767000784897">>}}}`

I tried to understand the reason of such behaviour but without success. I continue trying to understand how it works and how to fix it correctly.
As a workaround I found a solution, I replaced the case clause from `false ->` to `_->` but I am not sure if it is a good workaround.
```erlang
do_route(OrigPacket) ->
    ?DEBUG("route:~n~s", [xmpp:pp(OrigPacket)]),
    case ejabberd_hooks:run_fold(filter_packet, OrigPacket, []) of
	drop ->
	    ok;
	Packet ->
	    case ejabberd_iq:dispatch(Packet) of
		true ->
		    ok;
	        _ ->
		    To = xmpp:get_to(Packet),
		    LDstDomain = To#jid.lserver,
		    case find_routes(LDstDomain) of
			[] ->
			    ejabberd_s2s:route(Packet);
			[Route] ->
			    do_route(Packet, Route);
			Routes ->
			    From = xmpp:get_from(Packet),
			    balancing_route(From, To, Packet, Routes)
		    end,
		    ok
	    end
    end.
```
Here my ejabberd.yml
```yaml
loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "replacedhost"
listen:
  -
    port: 5221
    ip: "::"
    module: ejabberd_c2s
    starttls_required: false
    zlib: false
    max_stanza_size: 131072
    shaper: c2s_shaper
    access: c2s
  -
     port: 3480
     transport: udp
     module: ejabberd_stun
     turn_ip: "192.168.1.169"
     auth_realm: "replacedhost"
     auth_type: user
     use_turn: true
     shaper: turn_shaper
  -
     port: 4561
     ip: "192.168.1.169"
     module: ejabberd_xmlrpc
     maxsessions: 1000
     timeout: 15000
     access_commands:
       xmlrpc:
        commands: all
auth_method: riak
riak_server: "127.0.0.1"
riak_port: 8087
riak_pool_size: 20
riak_start_interval: 10
shaper:
  normal: 400000
  fast: 50000000
max_fsm_queue: 10000
acl:
  admin:
    user:
      - "admin@replacedhost"
  xmlrpc:
    user:
      - "admin@replacedhost"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 10000
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback
  xmlrpc:
    - allow: xmlrpc
  xmlrpc_access:
    - allow: xmlrpc
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"
language: "en"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_last:
   db_type: riak
   use_cache: true
   cache_size: 10000
   cache_life_time: 7200
  mod_offline:
    db_type: riak
    store_empty_body: unless_chat_state
    access_max_user_messages: max_user_offline_messages
  mod_ping:
    send_pings: true
    ping_ack_timeout: 60
    timeout_action: kill
  mod_privacy:
    db_type: riak
    use_cache: true
    cache_size: 10000
    cache_life_time: 7200
  mod_private: {}
  mod_roster:
    db_type: riak
    versioning: true
    store_current_id: true
    use_cache: true
    cache_size: 200000
    cache_life_time: 3600
  mod_vcard:
    db_type: riak
    search: false
    use_cache: true
    cache_size: 10000
    cache_life_time: 3600
  mod_version: {}
  mod_stream_mgmt:
    resend_on_timeout: true
    resume_timeout: 180
    max_resume_timeout: 180
allow_contrib_modules: true
```
Thank you.
