### ISSUE TITLE
docker version of ejabberd ecs will not connect to mysql hosted in another docker container when started with docker compose

### ISSUE THREAD

**Issue by jtvilm** [processone/ejabberd#2242]
> What version of ejabberd are you using?

[Latest ejabberd ecs docker image](https://hub.docker.com/r/ejabberd/ecs/) available on dockerhub.

> What operating system (version) are you using?

Docker image based on ejabberd/ecs

> How did you install ejabberd (source, package, distribution)?

run the docker container as part of docker compose with mounted configuration and database volumes.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

ejabberd tries to connect to a mysql database only when the configuration property sql_server is "localhost" in ejabberd.yml (see below). 

However, ejabbed cannot find the mysql server under "localhost", as it is available in another docker container reachable under the host name db as defined in the docker compose file(see below). 

Because it is not available, the following log output will reappear every 30s.  
```txt
10:40:38.062 [error] p1_mysql_conn: Failed connecting to "localhost":3306 : {error,"connect failed : {error,econnrefused}"}
10:40:38.062 [error] p1_mysql_conn: post_start error connect_failed
10:40:38.062 [info] mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
```

The problem is that ejabberd will not attempt to connect to mysql if the sql_server propery is set to a host name other than "localhost". Instead it will default to the internal mnesia database. 

Did I missconfigure anything in the ejabberd.yml? Or how do I need to specify which host mysql is running on?

#### ejabberd.yml
```yaml
###
###'              ejabberd configuration file
###
###

###.  =======
###'  LOGGING
loglevel: 4

log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1

log_rate_limit: 100

hosts:
  - "localhost"

certfiles:
  - "/home/ejabberd/conf/server.pem"
##   - "/etc/letsencrypt/live/example.org/*.pem"
##   - "/etc/letsencrypt/live/example.com/*.pem"

ca_file: "/home/ejabberd/conf/cacert.pem"

##
## listen: The ports ejabberd will listen on, which service each is handled
## by and what options to start it with.
##
listen:
  -
    port: 5222
    ip: "0.0.0.0"
    module: ejabberd_c2s
    ## starttls: true
    ##
    ## To enforce TLS encryption for client connections,
    ## use this instead of the "starttls" option:
    ##
    starttls_required: true
    ##
    ## Stream compression
    ##
    ## zlib: true
    ##
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    ip: "0.0.0.0"
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    port: 5280
    ip: "0.0.0.0"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    ## register: true
    captcha: false


##
## Store the plain passwords or hashed for SCRAM:
## auth_password_format: plain
## auth_password_format: scram
auth_password_format: scram

##
## Authentication using SQL
## Remember to setup a database in the next section.
##
auth_method: sql


###.  ==============
###'  DATABASE SETUP

default_db: sql

##
## MySQL server:
##
sql_type: mysql
sql_server: "db"
sql_database: "ejabberd"
sql_username: "ejabberd"
sql_password: "password"
##
## If you want to specify the port:
sql_port: 3306

###.   ====================
###'   ACCESS CONTROL LISTS
acl:
  ##
  ## The 'admin' ACL grants administrative privileges to XMPP accounts.
  ## You can put here as many accounts as you want.
  ##
  admin:
    user:
      - "admin": "localhost"

  ## Local users: don't modify this.
  ##
  local:
    user_regexp: ""

  ##
  ## Loopback network
  ##
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"

###.  ============
###'  ACCESS RULES
access_rules:
  ## This rule allows access only for local users:
  local:
    - allow: local
  ## Only non-blocked users can use c2s connections:
  c2s:
    - deny: blocked
    - allow
  ## Only admins can send announcement messages:
  announce:
    - allow: admin
  ## Only admins can use the configuration interface:
  configure:
    - allow: admin
  ## Only accounts of the local ejabberd server can create rooms:
  muc_create:
    - allow: local
  ## Only accounts on the local ejabberd server can create Pubsub nodes:
  pubsub_createnode:
    - allow: local
  ## In-band registration allows registration of any possible username.
  ## To disable in-band registration, replace 'allow' with 'deny'.
  register:
    - allow
  ## Only allow to register from localhost
  trusted_network:
    - allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"

language: "en"

host_config:
  "localhost":
    auth_method: sql

```

#### docker-compose.yaml
```yaml
version: '3'

services:
  db:
    image: "mysql"
    container_name: "db-mysql"
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - /path/to/data:/var/lib/mysql
      - /path/to/conf:/etc/mysql/conf.d

  adminer:
    image: "adminer"
    container_name: "db-adminer"
    restart: "unless-stopped"
    ports:
      - "8080:8080"
    depends_on:
      - db

  xmpp-ejabberd:
    image: "ejabberd/ecs"
    container_name: "xmpp-ejabberd"
    restart: "unless-stopped"
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
    depends_on:
      - db
    volumes:
      - path/to/conf:/home/ejabberd/conf
      - path/to/data:/home/ejabberd/database
      - path/to/logs:/home/ejabberd/logs
      - path/to/backup:/home/ejabberd/backup
      - path/to/ssl:/home/ejabberd/ssl
      - path/to/upload:/home/ejabberd/upload
```
