### ISSUE TITLE
Enable registration for movim

### ISSUE THREAD

**Issue by DanielnetoDotCom** [processone/ejabberd#2258]
I am trying to enable registration for my movim installation.

I follow many different tutorials and it still not working, I opened an issue in movim and they said it is an ejabberd issue , not them.

Could you please tell me what I am missing ...
my ejabberd.yml file : https://ziyoushejiao.com/ejabberd.yml
the movim installation: https://ziyoushejiao.com/

Very thanks in advance

**Comment by zinid** [comment]
You should configure `mod_register` properly. Currently you have:
```yaml
  mod_register:
    access_from: allow
    access: register 
    welcome_message: 
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    ip_access: trusted_network
    access_from: allow
    access: register
```
And your `trusted_network` is `loopback` which means only registrations from localhost are allowed. Please read documentation or join ejabberd@conference.process-one.net room to ask questions.
I close the issue as it's not a bug.
