### ISSUE TITLE
I got error when run api : srg_get_info

### ISSUE THREAD

**Issue by Viraljadav** [processone/ejabberd#2264]
Hello
Ejabberd

I get below error when run api:srg_get_info

```
{
    "status": "error",
    "code": 32,
    "message": "AccessRules: Account does not have the right to perform the operation."
}
```

When i run api register, get_connected_users, get_roster its working fine.

Please help me.

Below setting i have done in ejabberd.yml
```
access_rules:
  ## This rule allows access only for local users:
  local:
    - allow: local
  ## Only non-blocked users can use c2s connections:
  c2s:
    - deny: blocked
    - allow
  ## Only admins can send announcement messages:
  announce:
    - allow: admin
  ## Only admins can use the configuration interface:
  configure:
    - allow: admin
  ## Only accounts of the local ejabberd server can create rooms:
  muc_create:
    ## - allow: local
    - allow: all
  ## Only accounts on the local ejabberd server can create Pubsub nodes:
  pubsub_createnode:
    - allow: local
  ## In-band registration allows registration of any possible username.
  ## To disable in-band registration, replace 'allow' with 'deny'.
  register:
    - allow: all
  ## Only allow to register from localhost
  trusted_network:
    - allow: loopback
                      
modules:
  mod_mam:
    db_type: sql
    default: always

  mod_adhoc: {}
  mod_admin_extra: {}
  access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  ## mod_echo: {}
  mod_http_bind: {}
  ## mod_http_fileserver:
     ## docroot: "/opt/ejabberd-16.12/upload/"
     ## accesslog: "/opt/ejabberd-16.12/logs/access.log"
     ## custom_headers:
         ##  "X-Powered-By": "Erlang/OTP"
         ##  "X-Fry": "It's a widely-believed fact!"
     ## content_types:
         ##  ".ogg": "audio/ogg"
         ##  ".png": "image/png"
         ##  ".jpg": undefined
  ## mod_http_upload:
    ## docroot: "/opt/ejabberd-16.12/upload/"
    ## put_url: "https://192.168.1.28:5443/upload"
    ## thumbnail: false
  ## mod_http_upload_quota:
     ## max_days: 100
  ## mod_irc: {}
  mod_last: {}
  mod_muc:
    ## host: "conference.@HOST@"
    access:
      - allow
    access_admin:

    - allow: admin
    access_create: muc_create
    access_persistent: muc_create
  mod_muc_admin: {}
  ## mod_muc_log: {}
  ## mod_multicast: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  ## mod_pres_counter:
  ##   count: 5
  ##   interval: 60
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    ## ip: "proxi.localhost"
    hostname: "localhost"
    port: 7777
    access: all
    shaper: c2s_shaper

  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
  mod_register:

    ## After successful registration, the user receives
    ## a message with this subject and body.
    ##
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    ##
    ## When a user registers, send a notification to
    ## these XMPP accounts.
    ##
    ##   registration_watchers:
    ##     - "admin1@example.org"
    ##
    ## Only clients in the server machine can register accounts
    ##
    ip_access: trusted_network
    ##
    ## Local c2s or remote s2s users cannot register accounts
    ##
    ##   access_from: deny
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  ## mod_stats: {}
  ## mod_time: {}
  mod_vcard:
    search: false
  mod_version: {}


api_permissions:
  "admin access":
    - who:
      ## - all
      - ip: "127.0.0.1/8"
    - what
      - "*"
      - "!stop"
  "public commands":
    ## who: all
    who: all
    what:
      - "*"
      - "!stop"
      - "!start"
```
