### ISSUE TITLE
[QUESTION/SUGGESTION] Configuring ejabberd via environment variables

### ISSUE THREAD

**Issue by mieciu** [processone/ejabberd#2268]
I'm installing ejabberd as a dependency (ref: https://blog.process-one.net/how-to-use-ejabberd-as-an-elixir-application-dependency/ ) and I've been recently trying to bundle it into a docker container.

First problem I've encountered was a static configuration file in yaml. I'd like some parameters to be passed as environment variables (like database credentials). I thought it could be solved with bit of Erlang  magic, but unfortunately only terms are supported. Following snipped placed in `ejabberd.yml`:
```
sql_password: "> os:getenv(\"DB_PASS\", \"defaultpassword\")."
```
results in:
```
** (MatchError) no match of right hand side value: {:error, {1, :erl_parse, 'bad term'}}
```

Maybe I'm missing something, but **is there any way to inject configuration parameters from env vars?**

BTW: if not, this is a nice example on how it could work in ideal world: https://www.elastic.co/guide/en/beats/winlogbeat/current/using-environ-vars.html
Maybe it sounds like a good feature idea? 🤔

**Comment by badlop** [comment]
So, you already have environment variables. And you expect ejabberd to accept them somehow. The reality is that ejabberd reads configuration from a config file.

Have you tried to produce the config file immediately before you start ejabberd?

For example, in your ejabberd.yml you could add those lines:
```yaml
sql_type: mysql
sql_server: "localhost"
include_config_file:
  "/tmp/ejabberd-database.yml":
    allow_only:
      - sql_database
      - sql_username
      - sql_password
```

Then, write a small script that produces a small config file /tmp/ejabberd-database.yml like this using your evironment variables:
```yaml
sql_database: "ejabberd_test_db"
sql_username: "myuser11"
sql_password: "somepass66"
```
Then, first call that script to produce that small file, and then start ejabberd.
