### ISSUE TITLE
Cannot execute API command with Basic Authentication.

### ISSUE THREAD

**Issue by kabirhaxor** [processone/ejabberd#2281]
> What version of ejabberd are you using?

Ejabberd 18.01

> What operating system (version) are you using?

Ubuntu

> How did you install ejabberd (source, package, distribution)?

package.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When im executing the change_password command with basic authentication (user:password) then i got error
```
{
    "status": "error",
    "code": 10,
    "message": "You are not authorized to call this command."
}
```

**My ejabberd.yml file config**
```
`###'  ACCESS RULES
access_rules:
  ## This rule allows access only for local users:
  local:
    - allow: local
  ## Only non-blocked users can use c2s connections:
  c2s:
    - deny: blocked
    - allow
  ## Only admins can send announcement messages:
  announce:
    - allow: admin
  ## Only admins can use the configuration interface:
  configure:
    - allow: admin
  ## Only accounts of the local ejabberd server can create rooms:
  muc_create:
    - allow: local
  ## Only accounts on the local ejabberd server can create Pubsub nodes:
  pubsub_createnode:
    - allow: local
  ## In-band registration allows registration of any possible username.
  ## To disable in-band registration, replace 'allow' with 'deny'.
  register:
    - allow
  ## Only allow to register from localhost
  trusted_network:
    - allow: loopback
  ## Do not establish S2S connections with bad servers
  ## If you enable this you also have to uncomment "s2s_access: s2s"
  ## s2s:
  ##   - deny:
  ##     - ip: "XXX.XXX.XXX.XXX/32"
  ##   - deny:
  ##     - ip: "XXX.XXX.XXX.XXX/32"
  ##   - allow

## ===============
## API PERMISSIONS
## ===============
##
## This section allows you to define who and using what method
## can execute commands offered by ejabberd.
##
## By default "console commands" section allow executing all commands
## issued using ejabberdctl command, and "admin access" section allows
## users in admin acl that connect from 127.0.0.1 to  execute all
## commands except start and stop with any available access method
## (ejabberdctl, http-api, xmlrpc depending what is enabled on server).
##
## If you remove "console commands" there will be one added by
## default allowing executing all commands, but if you just change
## permissions in it, version from config file will be used instead
## of default one.
##
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - all
    what:
      - "status"
      - "connected_users_number"
      - "check_account"
      - "register"
  "local commands":
    who:
      - access:
        - allow:
          - acl: local
    what:
     - "change_password"
     - "get_last"
     - "get_presence"
```
I create custom API Permission with the name "local commands" whom using these commands with Basic authentication. But got error. Please help me to fix this. Thank you.
