### ISSUE TITLE
Keep getting 'access_rules_unauthorized' for xmlrpc.

### ISSUE THREAD

**Issue by ajm113** [processone/ejabberd#2292]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Container (Debian Jessie): Linux 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 GNU/Linux

Host: Centos 7 (64bit)

> How did you install ejabberd (source, package, distribution)?

Using Dockerfile.
https://github.com/rroemhild/docker-ejabberd/blob/master/Dockerfile

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When running a HTTP request to 'register'. `{error,access_rules_unauthorized}` is returned running the following in the HTTP request body. The expected result was a success message.

```
register user ajm password mypassword host domain.com
```

I'm assuming this has to do with my PHP/Apache container making the cURL request to the Ejabberd container since they both don't live on the same domain as 'localhost'. Since they are almost both two machines running on a host machine. So perhaps I'm missing a permission setting? -- of course, I would be setting up certain firewall so only those two containers can talk on the XMLRPC port, but that's just a guess on what the problem is. I've tried searching around, but I'm not exactly sure what I'm looking for to accomplish this. I'll post my access list settings and relevant ejabber.yml.

Access Rules:
``` erlang
[{access,announce,[{allow,[{acl,admin}]},{deny,[all]}]},
 {access,c2s,[{deny,[{acl,blocked}]},{allow,[{acl,all}]},{deny,[all]}]},
 {access,c2s_shaper,[{none,[{acl,admin}]},{normal,[{acl,all}]},{deny,[all]}]},
 {access,configure,[{allow,[{acl,admin}]},{deny,[all]}]},
 {access,hard_upload_quota,[{500,[{acl,all}]},{deny,[all]}]},
 {access,local,[{allow,[{acl,local}]},{deny,[all]}]},
 {access,max_user_offline_messages,
         [{5000,[{acl,admin}]},{100,[{acl,all}]},{deny,[all]}]},
 {access,max_user_sessions,[{10,[{acl,all}]},{deny,[all]}]},
 {access,muc,[{allow,[{acl,all}]},{deny,[all]}]},
 {access,muc_admin,[{allow,[{acl,admin}]},{deny,[all]}]},
 {access,muc_create,[{allow,[{acl,local}]},{deny,[all]}]},
 {access,pubsub_createnode,[{allow,[{acl,local}]},{deny,[all]}]},
 {access,register,[{allow,[{acl,all}]}]},
 {access,s2s_shaper,[{fast,[{acl,all}]},{deny,[all]}]},
 {access,soft_upload_quota,[{400,[{acl,all}]},{deny,[all]}]},
 {access,trusted_network,[{allow,[{acl,loopback}]},{deny,[all]}]}].
```
ejabberd.yml

``` yml
listen:
  -
    port: 4560
    module: ejabberd_xmlrpc

###   ====================
###   ACCESS CONTROL LISTS

acl:
  admin:
    user:
      - "admin": "domain.com"
  local:
    user_regexp: ""

###   ============
###   ACCESS RULES

access:
  ## Maximum number of simultaneous sessions allowed for a single user:
  max_user_sessions:
    all: 10
  ## Maximum number of offline messages that users can have:
  max_user_offline_messages:
    admin: 5000
    all: 100
  ## This rule allows access only for local users:
  local:
    local: allow
  ## Only non-blocked users can use c2s connections:
  c2s:
    blocked: deny
    all: allow
  ## For C2S connections, all users except admins use the "normal" shaper
  c2s_shaper:
    admin: none
    all: normal
  ## All S2S connections use the "fast" shaper
  s2s_shaper:
    all: fast
  ## Only admins can send announcement messages:
  announce:
    admin: allow
  ## Only admins can use the configuration interface:
  configure:
    admin: allow
  ## Admins of this server are also admins of the MUC service:
  muc_admin:
    admin: allow
  ## Only accounts of the local ejabberd server, or only admins can create rooms, depending on environment variable:
  muc_create:
    local: allow
```

**Comment by prefiks** [comment]
Please show api_permission from your config

**Comment by ajm113** [comment]
I don't have 'api_permissions' in my ejabberd.yml. ... I assume this is required? .. If so example?

**Comment by ajm113** [comment]
Ah sorry, I figured it out.

I used this:

``` yml
api_permissions:
  "xmlrpc commands":
    from:
      - ejabberd_xmlrpc
    who: all
    what: "*"
```
