### ISSUE TITLE
MUC Room access_admin and owner works together?

### ISSUE THREAD

**Issue by zgrdmr** [processone/ejabberd#2313]
> What version of ejabberd are you using?

ejabberd-17.12

> What operating system (version) are you using?

Ubuntu 14.04.5 LTS 

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log?
---

> Doc. says:
 **access_admin**: AccessName: This option specifies who is allowed to administrate the Multi-User Chat service. The default value is none, which means that only the room creator can administer his room. The administrators can send a normal message to the service JID, and it will be shown in all active rooms as a service message. The administrators can send a groupchat message to the JID of an active room, and the message will be shown in the room as a service message.

So I created MUC room with these options:

```
mod_muc:
   access:
     - allow
   access_admin: muc_admin    <-- this line
   access_create: muc_create    
   access_persistent: muc_create
   max_user_conferences: 1000
   max_users_admin_threshold: 5000
   max_users: 5000
   default_room_options:
       persistent: true
       allow_subscription: true
       members_only: true
       mam: true
```
I expect room **owner** and **muc_admin** can:
 - Create muc room
 - **Change affiliation,** 
 - Send message to muc room

**muc_admin** works as expected but **owner** cannot change affiliation.

I tried to change **muc_admin** to [ `allow: all, allow: local, allow: admin`], nothing changes for **owner**.

When I delete this line:
`access_admin: muc_admin`
**Owner** works as expected but of course **muc_admin** not working.
Actually, (for muc_admin) only room message fails in this case.

---

> What was the expected result?

**muc_admin**  is server admin, will never be in a room.

**muc_admin** can create muc room, change affiliations in rooms, send message to muc room and owner is an owner.

Can **access_admin** and **owner** work at the same time?

Am I missing something or any other way?

Thanks.

**Comment by badlop** [comment]
See this in https://xmpp.org/extensions/xep-0045.html#revokeowner
> A service MUST NOT allow an owner to revoke his or her own owner status if there are no other owners; if an owner attempts to do this, the service MUST return a <conflict/> error to the owner. However, a service SHOULD allow an owner to revoke his or her own owner status if there are other owners.

In my tests with ejabberd 18.01, the room creator (and owner alone) is not allowed do revoke its ownership, regardless of what I set in the muc_admin option.

**Comment by zgrdmr** [comment]
In my case owner is not trying to revoke his ownership, he is trying to grant a new member or revoke admin to member.

**Comment by badlop** [comment]
I've downloaded ejabberd rd 17.12  from git, compiled, installed, configured like this:
```yaml
  mod_muc:
    host: "muc.@HOST@"
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      allow_subscription: true
      persistent: true
```
Then created two user accounts (without admin rights in the configuration). One of them user3 joins a new room (so he becomes room owner). The other user6 joins that room. Then the room owner grants membership:
```xml
<!-- 15:17:23.626 OUT (::xmpp::2, user3@localhost/tka1) -->
<iq id='51:198087'
	xml:lang='es'
	type='set'
	to='sala5@muc.localhost'>
  <query xmlns='http://jabber.org/protocol/muc#admin'>
    <item nick='user6'
	affiliation='member'/>
  </query>
</iq>

<!-- 15:17:23.696 IN (::xmpp::2, user3@localhost/tka1) -->
<iq xml:lang='es'
	to='user3@localhost/tka1'
	from='sala5@muc.localhost'
	type='result'
	id='51:198087'/>
```
The log shows:
```
15:17:23.636 [info] Processing MUC admin query from user3@localhost/tka1 in room sala5@muc.localhost:
 [{{jid,<<"user6">>,<<"localhost">>,<<>>,<<"user6">>,<<"localhost">>,<<>>},
affiliation,member,<<>>}]
```
All looks correct. Do you get some error? Is there any difference between your setup and mine? How can I reproduce your problem?
