### ISSUE TITLE
PubSub with MySQL is only keeping 10 items per node per publisher

### ISSUE THREAD

**Issue by ServiceTo** [processone/ejabberd#2320]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

CentOS 7.4

> How did you install ejabberd (source, package, distribution)?

yum package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

despite setting `max_items_node: 10000` (and many variations in between), I'm only ever able to have 10 items per node per publisher in the `pubsub_item` table.

Also as things are purged, the client I'm using can't process the `<retract` messages (I also need all of the available items, regardless of the quantity.

I've tried running live and as as service and I tried updating `/opt/ejabberd-18.01/lib/ejabberd-18.01/include/pubsub.hrl` and changing `-define(MAXITEMS, 10).` but i'm not sure that get's re-read when ejabberd starts.

ejabberd.yml
```
default_db: sql
modules:
<snip>
  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    max_items_node: 100000
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
```
