### ISSUE TITLE
Empty search result

### ISSUE THREAD

**Issue by 5kr1p7** [processone/ejabberd#2335]
> What version of ejabberd are you using?

17.07 (also tested on 18.01)

> What operating system (version) are you using?

Ubuntu 17.10

> How did you install ejabberd (source, package, distribution)?

apt

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Authentication via LDAP (AD) is working.
User info (vCard) is ok.
Search a user via vjud.DOMAIN service always return no results.

[ejabberd.yml](https://github.com/processone/ejabberd/files/1837103/ejabberd.yml.txt)

```
...
  mod_vcard_ldap:
    ldap_servers: ["192.168.0.100"]
    ldap_port: 389
    ldap_rootdn: "CN=ldap_search,CN=Users,DC=office,DC=ru"
    ldap_password: "***"
    ldap_base: "dc=office,dc=ru"
    ldap_uids:
      - "userPrincipalName": "%u@office.ru"
    ldap_filter: "(&(objectCategory=person)(objectClass=user)(givenName=*)(sn=*)(!(userAccountControl=514))(!(userAccountControl=546))(!(userAccountControl=66050))(!(userAccountControl=66082))(lastLogonTimeStamp>=131486868000000000))"
    search: true
    matches: 30
    ldap_vcard_map:
      "NICKNAME": {"%s": ["displayName"]}
      "GIVEN": {"%s": ["givenName"]}
      "MIDDLE": {"%s": ["initials"]}
      "FAMILY": {"%s": ["sn"]}
      "FN": {"%s %s": ["sn", "givenName"]}
      "EMAIL": {"%s": ["mail"]}
      "ORGNAME": {"%s": ["company"]}
      "ORGUNIT": {"%s": ["department"]}
      "CTRY": {"%s": ["c"]}
      "LOCALITY": {"%s": ["l"]}
      "STREET": {"%s": ["streetAddress"]}
      "REGION": {"%s": ["st"]}
      "PCODE": {"%s": ["postalCode"]}
      "TITLE": {"%s": ["title"]}
      "URL": {"%s": ["wWWHomePage"]}
      "DESC": {"%s\n\n%s (%s)\nPhone: %s": ["description", "title", "department", "telephoneNumber"]}
      "TEL": {"%s": ["telephoneNumber"]}
      "BDAY": {"%s": ["birthDay"]}
    ldap_search_fields:
      "User": "%u"
      "Family Name": "sn"
      "Email": "mail"
    ldap_search_reported:
      "Full Name": "FN"
      "Nickname": "NICKNAME"
...
```

In live console I see this and error in client if enter in for example "Last Name":
```
Reason = {error,{function_clause,[{io_lib_pretty,cind_tag_tuple,7,[{file,"io_lib_pretty.erl"},{line,718}]},{io_lib_pretty,cind_element,7,[{file,"io_lib_pretty.erl"},{line,849}]},{io_lib_pretty,cind_tail,8,[{file,"io_lib_pretty.erl"},{line,832}]},{io_lib_pretty,cind_element,7,[{file,"io_lib_pretty.erl"},{line,849}]},{io_lib_pretty,cind_tail,8,[{file,"io_lib_pretty.erl"},{line,832}]},{io_lib_pretty,cind_element,7,[{file,"io_lib_pretty.erl"},{line,849}]},{io_lib_pretty,cind_tail,8,[{file,"io_lib_pretty.erl"},{line,832}]},{io_lib_pretty,cind_element,7,[{file,"io_lib_pretty.erl"},{line,849}]}]}}
```

On empty search fields:
```
Reason = {error,{function_clause,[{mod_vcard,'-item_to_field/1-lc$^0/1-0-',[{<<"jid">>,<<"30SaltanovaIS@jabber.office.ru">>}],[{file,"src/mod_vcard.erl"},{line,445}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{mod_vcard,search_result,4,[{file,"src/mod_vcard.erl"},{line,440}]},{mod_vcard,process_search,1,[{file,"src/mod_vcard.erl"},{line,251}]},{gen_iq_handler,process_iq,3,[{file,"src/gen_iq_handler.erl"},{line,165}]},{gen_iq_handler,process_iq,4,[{file,"src/gen_iq_handler.erl"},{line,138}]},{mod_vcard,handle_info,2,[{file,"src/mod_vcard.erl"},{line,138}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]}]}}
```
