### ISSUE TITLE
Empty search result

### ISSUE THREAD

**Issue by 5kr1p7** [processone/ejabberd#2347]
> What version of ejabberd are you using?

Compiled sources from github

> What operating system (version) are you using?

Ubuntu 17.10

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Commit from Issue #2335 did not fix my problem. No errors now, but still search result is empty.

Authentication via LDAP (AD) is working.
User info (vCard) is ok.
Search a user via vjud.DOMAIN service always return no results.

[ejabberd.yml](https://github.com/processone/ejabberd/files/1837103/ejabberd.yml.txt)

```
...
  mod_vcard_ldap:
    ldap_servers: ["192.168.0.100"]
    ldap_port: 389
    ldap_rootdn: "CN=ldap_search,CN=Users,DC=office,DC=ru"
    ldap_password: "***"
    ldap_base: "dc=office,dc=ru"
    ldap_uids:
      - "userPrincipalName": "%u@office.ru"
    ldap_filter: "(&(objectCategory=person)(objectClass=user)(givenName=*)(sn=*)(!(userAccountControl=514))(!(userAccountControl=546))(!(userAccountControl=66050))(!(userAccountControl=66082))(lastLogonTimeStamp>=131486868000000000))"
    search: true
    matches: 30
    ldap_vcard_map:
      "NICKNAME": {"%s": ["displayName"]}
      "GIVEN": {"%s": ["givenName"]}
      "MIDDLE": {"%s": ["initials"]}
      "FAMILY": {"%s": ["sn"]}
      "FN": {"%s %s": ["sn", "givenName"]}
      "EMAIL": {"%s": ["mail"]}
      "ORGNAME": {"%s": ["company"]}
      "ORGUNIT": {"%s": ["department"]}
      "CTRY": {"%s": ["c"]}
      "LOCALITY": {"%s": ["l"]}
      "STREET": {"%s": ["streetAddress"]}
      "REGION": {"%s": ["st"]}
      "PCODE": {"%s": ["postalCode"]}
      "TITLE": {"%s": ["title"]}
      "URL": {"%s": ["wWWHomePage"]}
      "DESC": {"%s\n\n%s (%s)\nPhone: %s": ["description", "title", "department", "telephoneNumber"]}
      "TEL": {"%s": ["telephoneNumber"]}
      "BDAY": {"%s": ["birthDay"]}
    ldap_search_fields:
      "User": "%u"
      "Family Name": "sn"
      "Email": "mail"
    ldap_search_reported:
      "Full Name": "FN"
      "Nickname": "NICKNAME"
...
```
