### ISSUE TITLE
Constant Redis reconnections

### ISSUE THREAD

**Issue by richp10** [processone/ejabberd#2354]
> What version of ejabberd are you using?

18.03

> What operating system (version) are you using?

Alpine Linux / Docker

> How did you install ejabberd (source, package, distribution)?

Compiled all from source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

At loglevel 5, it *appears* that Ejabberd is reconnecting to Redis every couple of seconds - with the following log lines: 

```
15:07:54.104 [debug] Connection #3 established to Redis at 172.17.**:6379
15:07:54.304 [debug] Connection #4 established to Redis at 172.17.**:6379
15:07:55.005 [debug] Connection #9 established to Redis at 172.17.**:6379
15:07:55.508 [debug] Connection #10 established to Redis at 172.17.**:6379
```
This just keeps repeating - with connection numbers from about 2 to 10

Some relevant settings
```yaml
redis_server: "172.17.**"
redis_db: 1
sm_db_type: redis # cache session management
sm_use_cache: true
router_db_type: redis # cache router
router_use_cache: true
```
Redis seems to be working fine and I ma not seeing other e
