### ISSUE TITLE
Messages are not being saved into mysql

### ISSUE THREAD

**Issue by muazzamazaz** [processone/ejabberd#2410]
> What version of ejabberd are you using?
17.01

> What operating system (version) are you using?

> How did you install ejabberd (source, package, distribution)?

My ejabbard.yml

```yaml
loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "localhost"
listen:
  - 
    port: 5222
    module: ejabberd_c2s
    certfile: "/opt/ejabberd-17.01/conf/server.pem"
    starttls: true
    protocol_options:
      - "no_sslv3"
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  - 
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  - 
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
    web_admin: true
    http_bind: true
    captcha: false
auth_method: sql
sql_type: mysql
sql_server: "localhost"
sql_database: "******"
sql_username: "*******"
sql_password: "*******"
sql_port: 3306
mod_mam: 
  default: always
  enforce_default_auto_save: true
  request_activates_archiving: true
  assume_mam_usage: if_enabled  
db_type: mysql
shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 1000
acl:
  admin:
    user:
      - "admin1@localhost"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow: all
  trusted_network:
    - allow: all
registration_timeout: infinity
  
language: "en"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_http_bind: {}
  mod_last: {}
  mod_muc:
    
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
       mam: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    ip_access: trusted_network
    access: register
  mod_roster: 
        db_type: sql
  
  mod_shared_roster: {}
  mod_vcard:
    search: false
  mod_version: {}
allow_contrib_modules: true
```
Messages are not being saved into database and there is not error in log.
