### ISSUE TITLE
muc_register_nick returns error even when works correctly

### ISSUE THREAD

**Issue by Jack12816** [processone/ejabberd#2415]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Ubuntu 18.04

> How did you install ejabberd (source, package, distribution)?

distribution package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Looks like I do not get the `muc_register_nick` admin command to play well. The command fails with exit code 1 on an `ejabberdctl` call and on the Admin REST API, too.

[The docs](https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#muc-register-nick) states the following signature: 

```json
    {
      "nick": "Tim",
      "jid": "tim@example.org",
      "serverhost": "example.org"
    }
```

Here comes my request/response pair:

```yaml
---
http_interactions:
- request:
    method: post
    uri: http://jabber/api/muc_register_nick
    body:
      encoding: UTF-8
      string: '{"nick":"TomTom","jid":"tom@ejabberd.local","serverhost":"ejabberd.local"}'
    headers:
      Accept:
      - "*/*"
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (linux-gnu x86_64) ruby/2.3.7p456
      Content-Length:
      - '74'
      Host:
      - jabber
      Authorization:
      - Basic YWRtaW5AZWphYmJlcmQubG9jYWw6ZGVmYXVsdHB3
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Length:
      - '1'
      Content-Type:
      - application/json
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Headers:
      - Content-Type, Authorization, X-Admin
    body:
      encoding: UTF-8
      string: '1'
    http_version: 
  recorded_at: Sun, 13 May 2018 13:12:11 GMT
recorded_with: VCR 3.0.3
```

Don't mind the `http://jabber/` base URL, I'm inside a container to access it. Other commands like creating rooms or registering new users works fine the same way.

Do I miss something here, or is this a bug?
