### ISSUE TITLE
ACME configuration help

### ISSUE THREAD

**Issue by AlexRudd** [processone/ejabberd#2418]
Hi there,

> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Amazon Linux 4.9.76-3.78.amzn1.x86_64

> How did you install ejabberd (source, package, distribution)?

Binary installer

> What did not work as expected?

Ejabberd ACME support

> Are there error messages in the log?

Not explicit errors. Here are the only relevant log lines:

```
...
2018-05-16 12:48:41.362 [debug] <0.330.0> Supervisor ejabberd_sup started ejabberd_acme:start_link() at pid <0.361.0>
...
2018-05-16 12:48:41.388 [warning] <0.354.0>@ejabberd_pkix:handle_call:255 No certificate found matching 'chat-test.example.com': strictly configured clients or servers will reject connections with this host; obtain a certificate for this (sub)domain from any trusted CA such as Let's Encrypt (www.letsencrypt.org)
```

> What was the unexpected behavior?

Based on the example config comments I created a config with the following key parts:

```
hosts:
  - "chat-test.example.com"
...
listen:
  -
    port: 5222
    ip: "0.0.0.0"
    module: ejabberd_c2s
    starttls: true
    starttls_required: true
    access: c2s
  -
    port: 5280
    ip: "0.0.0.0"
    module: ejabberd_http
...
acme:
   contact: "mailto:admin@chat-test.example.com"
   ca_url: "https://acme-v01.api.letsencrypt.org"
```
I excluded the `certfiles` and `ca_file` options from my config as I assume acme takes care of these?

I have also setup and tested port forwarding on the host so that `http://chat-test.example.com:80/` goes to the `ejabberd_http` module running on 5280.

I'm unsure what's supposed to happen, or what other tls options might be needed. Any advice would be much appreciated!

Thanks,
Alex
