### ISSUE TITLE
AccessRules: Account does not have the right to perform the operation

### ISSUE THREAD

**Issue by bp91** [processone/ejabberd#2458]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I've configured my ejabberd.yml file in this way:

```
listen:
  port: 5821
  ip: "::"
  module: ejabberd_http
  request_handlers:
     "/api": mod_http_api

....

acl:
   admin:
      user:
          - "admin@emailtest.com"

....

api_permissions:
   "admin access":
       who:
           - admin
```

I tried to perform a GET call to the service get_loglevel and I received the following response:

`
{
   "status": "error",
   "code": 32,
   "message": "AccessRules: Account does not have the right to perform the operation"
}
`

So I tried to perform a sort of authentication, passing into header: X-Admin: true and user=admin@testemail.com and pass=password as queryString, but I received the same error.

If I change this 
`
api_permissions:
   "admin access":
       who:
           - all
`

Everything it's ok.

My question is:

I want to perform REST call using registered admin username and password. How can I do?
Thank you

**Comment by prefiks** [comment]
You probably need to add
```
- what:
  - "register"
```
To that api_permission you have, i am guessing your second form is not recognized and generate warning when loading config, so default value for that option is used that allow admin execute some commands.

**Comment by bp91** [comment]
Hi @prefiks,

I'll try to add:

`- what:
  - "register"`

but how I have to pass the auth parameters? Or if u have a link to the documentation part that explains this thing, because I didn't find it.
Thank you

**Comment by prefiks** [comment]
mod_http_api recognizes http basic auth so you need to have something like this:
```
Authorization: Basic ....
```
in your request header.

**Comment by bp91** [comment]
Ok, but how can I generate that token? I've followed this guide

https://docs.ejabberd.im/developer/ejabberd-api/oauth/#list-of-commands-available-with-oauth-support

But it's not clear:

I have the admin user as I said before, I want to test the rest api (before testing with Postman, later into java/nodejs), so:

* I need an auth token
** If I follow the guide, I have this page: http://myDomain:5280/oauth/authorization_token?response_type=token&client_id=testApp
*** When I try to log in, I receive an **access_denied**

After following the guide, I've updated my yml file:

```
port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    web_admin: true
    register: true
    captcha: false

....

api_permissions:
  "admin access":
    who:
      - access:
          - allow:
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"

...

acl:
  admin:
    user:
      - "admin": "myDomain.com"
```

Is there a part into the Documentation that explain this? And If I'll create an user from the admin interface (example user@myDomain.com and password=password), how can I have to authenticate the user in order to make call to the REST api? Thanks
