### ISSUE TITLE
internet offline directly, jid/resource still online

### ISSUE THREAD

**Issue by jhaoheng** [processone/ejabberd#2462]
> What version of ejabberd are you using?

17.09 -> 18.04

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

form 'Downloads Archive'

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

1. client login to ejabberd => online success
2. Direct close internet connect
3. Client still online in ejabberd

my conf about mod_ping
```
  mod_ping:     
    send_pings: true
    ping_interval: 5
    ping_ack_timeout: 10
    timeout_action: kill
```

in 17.08, this `mod_ping` is working.
the correct log is `08:59:22.877 [info] (tcp|<0.680.0>) Closing c2s session for ejabberd@localhost/Client-638: Connection failed: ping_timeout`
