### ISSUE TITLE
API for invite MUC room

### ISSUE THREAD

**Issue by arpitvaishnav** [processone/ejabberd#2464]
> What version of ejabberd are you using?
17.11

> What operating system (version) are you using?
ubuntu 16.04
DB : mysql

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
MUC invitation with API not working
> was the unexpected behavior? What was the expected result?
Even passing stanza of invitation dose not help.

> Is the functionality available?
I am working on ejabberd api to invite users to MUC room. I have setup oauth for api. I have tested oauth with get_room_occupants and its working fine.

Now, I am trying to access `/api/send_direct_invitation`, but as per logs, I don't have permission to access this api

I have generated oauth with command line  
`ejabberdctl oauth_issue_token admin@host 31540000 "ejabberd:admin"`

Here is a Ejabberd yml file
```
api_permissions:
    "console commands":
      from:
        - ejabberd_ctl
      who: all
      what: "*"
    "admin access":
      who:
        - access:
            - allow:
              - user: admin@host
        - oauth:
          - scope: "ejabberd:admin"
          - access:
            - allow:
              - user: admin@host
      what:
        - "*"
        - "!stop"
        - "!start"
    "public commands":
      who:
        - ip: "127.0.0.1/8"
      what:
        - "status"
        - "connected_users_number"
  commands_admin_access:
    - allow:
      - user: "admin@host"
  commands:
    add_commands:
      - status
      - registered_users
      - register
      - unregister
      - get_roster
      - connected_users
      - send_stanza_c2s
      - send_stanza
      - join_cluster
      - send_direct_invitation
  oauth_expire: 3600
  oauth_access: all
```

Can we send stanza to a API for MUC invitation to join?
