### ISSUE TITLE
Allow API calls from other Docker containers

### ISSUE THREAD

**Issue by stevenroose** [processone/ejabberd#2475]
> What version of ejabberd are you using?

`ejabbers/ecs:18.04` Docker image

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

Docker

-------

I'm trying to give access to a small program running in another Docker containers. The containers all have IP addresses in the `172.*.*.*` space.

I have the following relevant sections in my `ejabberd.yml` file:
```yaml
acl:
  docker:
    ip: "172.0.0.0/8"

api_permissions:
  "register api":
    who: 
      - access:
        - allow:
          - acl: docker
    what:
      - "register"

listen:
  - port: 5281
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
```

I call the register endpoint (`http://ejabberd:5281/api/register`), with this POST body:
```json
{"host":"myserver.net","password":"superpass","user":"newuser"}
```

The server logs show that the originating IP is `172.18.0.6` which should be allowed as per ACL:
```
19:22:53.089 [info] API call register [{<<"host">>,<<"myserver.net">>},{<<"password">>,<<"superpass">>},{<<"user">>,<<"newuser">>}] from 172.18.0.6:38424
```

And the response ejabberd gives is 
```json
{"status":"error","code":32,"message":"AccessRules: Account does not have the right to perform the operation."}
```

What does it mean "account"? I don't use any authentication in the API call. The API is not accessible from outside my VPS.

**Comment by stevenroose** [comment]
So, apparently what I needed was:
```yaml
api_permissions:
  "register api":
    who: 
      - access:
        - allow:
          - acl: docker
      - all
    what:
      - "register"
```

With emphasis on the **`- all`** there.
