### ISSUE TITLE
The module http_upload doesn't work like expected - empty files

### ISSUE THREAD

**Issue by maitrenageur** [processone/ejabberd#2478]
> What version of ejabberd are you using?
18.04

> What operating system (version) are you using?
CentOS 6

> How did you install ejabberd (source, package, distribution)?
From source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I configured the http_upload environment with:

```yaml
listen:
-
  port: 62241
  ip: "::"
  module: ejabberd_http
  request_handlers:
  "": mod_http_upload
  tls: true

mod_http_upload:
  name: "HTTP File Upload"
  host: "upload.@HOST@"
  access: local
  max_size: 52428800 # 50 MiB
  ##file_mode: "0640"
  ##dir_mode: "2750"
  docroot: "/home/user/var/ejabberd/data/upload/"
  put_url: "https://@HOST@:62241"
  get_url: "https://@HOST@:62241"
  thumbnail: false
```

But the client Conversation (Android) uploaded the file without any errors, but the file itself is empty on the server. And ChatSecure (iOS) stoped the upload at 50%.

The log shows no errors or something else.

Any idea?

**Comment by weiss** [comment]
The indentation after `request_handlers:` is missing, but maybe that's just a copy-paste error?

Other than that, maybe your systemd unit (or some other mechanism) is prohibiting access to `/home`?

If this doesn't help, I'd enable debug output (`ejabberdctl set-loglevel 5`) and if that gives no hints, watch with `tcpdump`.

**Comment by maitrenageur** [comment]
Sorry,

the complete block is:

listen:
-
  port: 62241
  ip: "::"
  module: ejabberd_http
  request_handlers:
  "": mod_http_upload
  tls: true
  protocol_options: 'TLS_OPTIONS'                                                                           
  dhfile: '/home/username/dh-4096.pem'                                                           
  ## dhfile: 'DH_FILE'                                                                                        
  ciphers: 'TLS_CIPHERS'

**Comment by weiss** [comment]
I still don't see the necessary indentation after `request_handlers:`:

```yaml
listen:
-
  port: 62241
  ip: "::"
  module: ejabberd_http
  request_handlers:
    "": mod_http_upload
  tls: true
  protocol_options: 'TLS_OPTIONS'                                                                           
  dhfile: '/home/username/dh-4096.pem'                                                           
  ## dhfile: 'DH_FILE'                                                                                        
  ciphers: 'TLS_CIPHERS'
```
