### ISSUE TITLE
MUC/Sub Affiliation change info for muc room

### ISSUE THREAD

**Issue by zgrdmr** [processone/ejabberd#2507]
> What version of ejabberd are you using?

ejabberd-17.12

> What operating system (version) are you using?

Ubuntu 14.04.5 LTS

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Followed [MUC/Sub Doc](https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/)

Created MUC room options:

```
mod_muc:
   access:
     - allow
   access_admin: muc_admin 
   access_create: muc_create    
   access_persistent: muc_create
   max_user_conferences: 1000
   max_users_admin_threshold: 5000
   max_users: 5000
   default_room_options:
       persistent: true
       allow_subscription: true
       members_only: true
       mam: true
```
Options in database:
```
[{title,<<"test">>},
 {description,<<>>},
 {allow_change_subj,true},
 {allow_query_users,true},
 {allow_private_messages,true},
 {allow_private_messages_from_visitors,anyone},
 {allow_visitor_status,true},
 {allow_visitor_nickchange,true},
 {public,true},
 {public_list,true},
 {persistent,true},
 {moderated,true},
 {members_by_default,true},
 {members_only,true},
 {allow_user_invites,true},
 {password_protected,false},
 {captcha_protected,false},
 {password,<<>>},
 {anonymous,false},
 {logging,false},
 {max_users,200},
 {allow_voice_requests,true},
 {allow_subscription,true},
 {mam,true},
 {presence_broadcast,[moderator,participant,visitor]},
 {voice_request_min_interval,1800},
...
```
Subscribed nodes by clients (every client have same subscriptions):
```
<event node='urn:xmpp:mucsub:nodes:messages' />
<event node='urn:xmpp:mucsub:nodes:affiliations' />
<event node='urn:xmpp:mucsub:nodes:subject' />
<event node='urn:xmpp:mucsub:nodes:config' />
```

Case:
Owner creates a conference, invite users and subscribes them to above nodes. Every other users become a member. After that, owner sets as admin one of them. 
At this point **I expect affiliations node sends message to conference** that action. But nothing happens.

Tried:
I suspected, members not joined room in my case (Because doc says, we don't have to join to conference to do actions -messages, subscriptions, affiliations-).
Than for change, every member and owner joined to room and retried the case. And again nothing from affiliations node.

Am I missing something?

Thanks.
