### ISSUE TITLE
question mod_http_upload 

### ISSUE THREAD

**Issue by dverdugo85** [processone/ejabberd#2520]
> What version of ejabberd are you using?
ejabberd 16.06

> What operating system (version) are you using?

Ubuntu 16.06 lts

> What did not work as expected? Are there error messages in the log? What

I configure the mod_http_upload 
```yaml
listen: 
  -
    port: 5443
    module: ejabberd_http
    ##tls: true
    ##certfile: "/etc/ejabberd/servidor.pem"
    access: all
    request_handlers:
      "upload": mod_http_upload
``` 
```yaml
modules: 
  mod_http_upload_quota:
    max_days: 100
  
  mod_http_upload:
    docroot: "/home/xmpp/upload"
    put_url: "http://@HOST@:5443/upload"
    access: all
    jid_in_url: node
    max_size: 500000000
    file_mode: "0644"
    dir_mode: "0744"
    thumbnail: true`
```
I try to send picture with postman but show  the error "405 Method Not Allowed"

<img width="958" alt="captura de pantalla 2018-07-09 a la s 12 36 29" src="https://user-images.githubusercontent.com/5117517/42463871-71f1661c-8375-11e8-8d6c-bc74285ec998.png">

I hope you can help me!!!!

Regards
