### ISSUE TITLE
Is it possible to subscribe to conference in other XMPP server?

### ISSUE THREAD

**Issue by raym0n** [processone/ejabberd#2536]
> What version of ejabberd are you using?
ejabberd 18.04

> How did you install ejabberd (source, package, distribution)?
docker

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Two different XMPP servers exist - xmpp.server1 and xmpp.server2.

When I create the room@conference.xmpp.server1 on the first server, I can join to this room from user@xmpp.server1 and from user@xmpp.server2. And users can talk in this room.

So, now I want to subscribe user@xmpp.server2 to this room@conference.xmpp.server1 through API on xmpp.server2
and here I getting this error: **Bad Request: {unregistered_route,<<"conference.xmpp.server1">>}**

Here is xmpp.server2 log:
```
[debug] (#Port<0.18298>) http query: 'POST' <<"/api/subscribe_room">>

[debug] client data: <<"{\"user\":\"user@xmpp.server2/mac2\",\"nick\":\"User\",\"room\":\"room@conference.xmpp.server1\",\"nodes\":\"urn:xmpp:mucsub:nodes:messages,urn:xmpp:mucsub:nodes:affiliations\"}">>

[debug] [<<"api">>,<<"subscribe_room">>] matches [<<"api">>]

[info] API call subscribe_room [{<<"user">>,<<"user@xmpp.server2/mac2">>},{<<"nick">>,<<"User">>},{<<"room">>,<<"room@conference.xmpp.server1">>},{<<"nodes">>,<<"urn:xmpp:mucsub:nodes:messages,urn:xmpp:mucsub:nodes:affiliations">>}] from ::ffff:10.0.0.1:41550

[debug] Command 'subscribe_room' execution allowed by rule 'public commands' (CallerInfo=#{caller_module => mod_http_api,caller_server => <<"xmpp.server2">>,ip => {0,0,0,0,0,65535,2560,1},usr => {<<"admin">>,<<"xmpp.server2">>,<<>>}})

[debug] Executing command mod_muc_admin:subscribe_room with Args=[<<"user@xmpp.server2/mac2">>,<<"User">>,<<"room@conference.xmpp.server1">>,<<"urn:xmpp:mucsub:nodes:messages,urn:xmpp:mucsub:nodes:affiliations">>]

[debug] Bad Request: {unregistered_route,<<"conference.xmpp.server1">>} [{ejabberd_router,host_of_route,1,[{file,"src/ejabberd_router.erl"},{line,283}]},{mod_muc,find_online_room,2,[{file,"src/mod_muc.erl"},{line,189}]},{mod_muc_admin,get_room_pid,2,[{file,"src/mod_muc_admin.erl"},{line,959}]},{mod_muc_admin,subscribe_room,4,[{file,"src/mod_muc_admin.erl"},{line,1103}]},{mod_http_api,handle2,4,[{file,"src/mod_http_api.erl"},{line,332}]},{mod_http_api,handle,4,[{file,"src/mod_http_api.erl"},{line,290}]},{mod_http_api,perform_call,4,[{file,"src/mod_http_api.erl"},{line,235}]},{mod_http_api,process,2,[{file,"src/mod_http_api.erl"},{line,188}]}]
```

![image](https://user-images.githubusercontent.com/6609148/42879078-02d36288-8a98-11e8-9b78-4009610876a1.png)

```
loglevel: 5

log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1

log_rate_limit: 100

hosts:
  - "xmpp.server2"

certfiles:
  - "/home/ejabberd/conf/server.pem"

ca_file: "/home/ejabberd/conf/cacert.pem"

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
      "/bosh": mod_bosh
      "/api": mod_http_api
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    ## register: true
    captcha: false

s2s_use_starttls: optional
# s2s_use_starttls: false

s2s_access: s2s

shaper:
  normal: 1000
  fast: 50000

max_fsm_queue: 10000

acl:
  admin:
    user:
      - "admin@xmpp.server2"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast

access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback
  ## Do not establish S2S connections with bad servers
  ## If you enable this you also have to uncomment "s2s_access: s2s"
  s2s:
    - allow

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - access:
        - allow:
          - acl: admin
    what:
      - "status"
      - "connected_users_number"
      - "create_room"
      - "create_room_with_opts"
      - "subscribe_room"

language: "en"

acme:
   contact: "mailto:example-admin@example.com"
   ca_url: "https://acme-v01.api.letsencrypt.org"

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  ## mod_delegation: {} # for xep0356
  mod_disco: {}
  mod_bosh: {}
  mod_last: {}
  ## XEP-0313: Message Archive Management
  ## You might want to setup a SQL backend for MAM because the mnesia database is
  ## limited to 2GB which might be exceeded on large servers
  mod_mam: #{} # for xep0313, mnesia is limited to 2GB, better use an SQL backend
    default: always
  mod_muc:
    host: "conference.xmpp.server2"
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      persistent: true
      allow_subscription: true
      mam: true
  mod_muc_admin: {}
  ## mod_muc_log: {}
  ## mod_multicast: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  ## mod_pres_counter:
  ##   count: 5
  ##   interval: 60
  mod_privacy: {}
  mod_private: {}
  ## mod_proxy65: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    max_items_node: 10
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    ip_access: trusted_network
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  ## mod_stats: {}
  ## mod_time: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
  mod_http_api: {}

allow_contrib_modules: true

host_config:
  "xmpp.server2":
    auth_method: anonymous
    anonymous_protocol: both
    allow_multiple_connections: true
```
