### ISSUE TITLE
MySQL and ejabberd on different hosts

### ISSUE THREAD

**Issue by tallesl** [processone/ejabberd#2543]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

Windows 7 and Windows Server 2012

> How did you install ejabberd (source, package, distribution)?

[Windows 64-bit installer](https://www.process-one.net/en/ejabberd/downloads/)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have two machines, let's say MYSQL_SERVER and NOT_MYSQL_SERVER.

If I install ejabberd on MYSQL_SERVER with the following configuration everything works:

```yaml
## auth_method: internal
default_db: sql

sql_type: mysql
sql_server: "MYSQL_SERVER"
sql_database: "ejabberd_database"
sql_username: "mysql_user"
sql_password: "mysql_password"
```

However, the same `ejabberd.yaml` on NOT_MYSQL_SERVER fails:

```
2018-07-24 10:37:21.782 [error] <0.572.0>@ejabberd_sql:log:949 p1_mysql_conn: init error 1045: "#28000Access denied for user 'mysql_user'@'NOT_MYSQL_SERVER' (using password: YES)"
2018-07-24 10:37:21.782 [error] <0.408.0>@ejabberd_sql:log:949 p1_mysql_conn: post_start error login_failed
```

Looks like it's trying to access a local MySQL, despite have set `sql_server: "MYSQL_SERVER"`.

Is this a bug? Am I doing something wrong?
