### ISSUE TITLE
Chatstates (XEP-0085) trigger MUC rate limiting (min_message_interval)?

### ISSUE THREAD

**Issue by michalrus** [processone/ejabberd#2555]
> What version of ejabberd are you using?

17.07.

> What operating system (version) are you using?

NixOS.

> How did you install ejabberd (source, package, distribution)?

Package.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

* When I set the recommended value of:

    ```yaml
            modules:
              mod_muc:
                min_message_interval: 0.4
    ```

* … and use a client implementing XEP-0085 (Converse.js),
* and send a real message to a MUC,
* the client sends two `<message/>`s — one with actual content, and the second one meaning “X stopped typing”,
* and the second one triggers rate limiter.

I would expect that I could have both rate limiting and XEP-0085 — how can this be achieved?
