### ISSUE TITLE
mod_ping/timeout_action: kill not working correctly

### ISSUE THREAD

**Issue by AlexCloudDev** [processone/ejabberd#2579]
> What version of ejabberd are you using?

18.04-0

> What operating system (version) are you using?

stretch

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

"Timeout_action: kill" does not kill the session after a client has lost connection.
mod_ping is enabled, pings are sent.

ejabberd.yml:

...
```
mod_ping:
    send_pings: true
    ping_interval: 59
    ping_ack_timeout: 31
    timeout_action: kill
```
...
