### ISSUE TITLE
Unable to get subscription request from other users.

### ISSUE THREAD

**Issue by ravikantmishra** [processone/ejabberd#2583]
> What version of ejabberd are you using?

18.03

> What operating system (version) are you using?

CentOS

> How did you install ejabberd (source, package, distribution)?

Docker

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behaviour? What was the expected result?

I am using external authentication with `stanza.io` client. I also tried with `pidgin` but unable to get subscription request. I have installed ejabberd on my server and also registered few domains and their sub-domains. Below is my config file and error log. Almost all the functionalities are working fine except user subscription. I am unable to subscribe with any user. Whenever I am sending subscription request to any user he never receives my requests. that's why we are unable to subscribe. 
 
I am unable to understand whats the error in ejabberd log file. Can someone point me right direction.  
```yaml
hosts:
  - "abcxyz.com"
  - "ejabberd.pwg.development.abcxyz.com"
loglevel: 5
listen:
  - port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  - port: 5269
    ip: "::"
    module: ejabberd_s2s_in
  - port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/api": mod_http_api
    web_admin: true
    captcha: true
auth_method: external
extauth_program: "/opt/ejabberd/bin/auth.py"
auth_use_cache: false
shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 10000
acl:
  admin:
    user:
      - "admin@abcxyz.com"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_echo: {}
  mod_bosh: {}
  mod_last: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      "storage:bookmarks":
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_roster: {}
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_avatar: {}
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
  mod_http_api: {}
  mod_fail2ban: {}
```
---------------------------------EJABBERD LOG FILE------------------------------------------------

```
10:01:19.163 [debug] sending to process <0.14187.0>:
#iq{id = <<"7439cba7-0e83-4847-8bc1-7c908297098b">>,type = result,
    lang = <<"en">>,
    from =
        #jid{
            user = <<"75817891-b354-4e1e-84a8-c5bba0b1d07c">>,
            server = <<"ejabberd.pwg.development.abcxyz.com">>,
            resource = <<>>,
            luser = <<"75817891-b354-4e1e-84a8-c5bba0b1d07c">>,
            lserver = <<"ejabberd.pwg.development.abcxyz.com">>,
            lresource = <<>>},
    to =
        #jid{
            user = <<"75817891-b354-4e1e-84a8-c5bba0b1d07c">>,
            server = <<"ejabberd.pwg.development.abcxyz.com">>,
            resource = <<"abc">>,
            luser = <<"75817891-b354-4e1e-84a8-c5bba0b1d07c">>,
            lserver = <<"ejabberd.pwg.development.abcxyz.com">>,
            lresource = <<"abc">>},
    sub_els =
        [#roster_query{
             items =
                 [#roster_item{
                      jid =
                          #jid{
                              user =
                                  <<"ed16118a-6e37-4acc-98da-db86b91c6df5">>,
                              server =
                                  <<"ejabberd.pwg.development.abcxyz.com">>,
                              resource = <<>>,
                              luser =
                                  <<"ed16118a-6e37-4acc-98da-db86b91c6df5">>,
                              lserver =
                                  <<"ejabberd.pwg.development.abcxyz.com">>,
                              lresource = <<>>},
                      name = <<>>,groups = [],subscription = none,
                      ask = subscribe},
                  #roster_item{
                      jid =
                          #jid{
                              user =
                                  <<"f4d27ef9-7d06-4d13-9b29-84c385510d13">>,
                              server =
                                  <<"ejabberd.pwg.development.abcxyz.com">>,
                              resource = <<>>,
                              luser =
                                  <<"f4d27ef9-7d06-4d13-9b29-84c385510d13">>,
                              lserver =
                                  <<"ejabberd.pwg.development.abcxyz.com">>,
                              lresource = <<>>},
                      name = <<>>,groups = [],subscription = none,
                      ask = subscribe}],
             ver = undefined}],
    meta = #{ip => {0,0,0,0,0,65535,49320,25918}}}
10:01:19.163 [debug] Stream management with resumption enabled for 75817891-b354-4e1e-84a8-c5bba0b1d07c@ejabberd.pwg.development.abcxyz.com/abc
10:01:19.163 [debug] Won't add stanza for 75817891-b354-4e1e-84a8-c5bba0b1d07c@ejabberd.pwg.development.abcxyz.com/abc to CSI queue
10:01:19.163 [debug] Flushing packets of 75817891-b354-4e1e-84a8-c5bba0b1d07c@ejabberd.pwg.development.abcxyz.com from CSI queue of 75817891-b354-4e1e-84a8-c5bba0b1d07c@ejabberd.pwg.development.abcxyz.com/abc
10:01:19.164 [debug] Won't add stanza for 75817891-b354-4e1e-84a8-c5bba0b1d07c@ejabberd.pwg.development.abcxyz.com/abc to CSI queue
10:01:19.164 [debug] Flushing packets of 75817891-b354-4e1e-84a8-c5bba0b1d07c@ejabberd.pwg.development.abcxyz.com from CSI queue of 75817891-b354-4e1e-84a8-c5bba0b1d07c@ejabberd.pwg.development.abcxyz.com/abc
10:01:19.420 [debug] 75817891-b354-4e1e-84a8-c5bba0b1d07c@ejabberd.pwg.development.abcxyz.com/abc acknowledged 1 of 2 stanzas
10:01:19.507 [debug] route:
#iq{id = <<"push15369036286390952822">>,type = set,lang = <<>>,
    from =
        #jid{
            user = <<"75817891-b354-4e1e-84a8-c5bba0b1d07c">>,
            server = <<"ejabberd.pwg.development.abcxyz.com">>,
            resource = <<>>,
            luser = <<"75817891-b354-4e1e-84a8-c5bba0b1d07c">>,
            lserver = <<"ejabberd.pwg.development.abcxyz.com">>,
            lresource = <<>>},
    to =
        #jid{
            user = <<"75817891-b354-4e1e-84a8-c5bba0b1d07c">>,
            server = <<"ejabberd.pwg.development.abcxyz.com">>,
            resource = <<"abc">>,
            luser = <<"75817891-b354-4e1e-84a8-c5bba0b1d07c">>,
            lserver = <<"ejabberd.pwg.development.abcxyz.com">>,
            lresource = <<"abc">>},
```
