### ISSUE TITLE
get ERR_EMPTY_RESPONSE error when i want get authorization_token after submiting

### ISSUE THREAD

**Issue by armindev22** [processone/ejabberd#2603]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

 ubuntu 18.04 

> How did you install ejabberd (source, package, distribution)?

apt-get install ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

hello , when i want to get token from https://my-ip:5280/oauth/authorization_token i get ERR_EMPTY_RESPONSE after submiting account data 

![capture](https://user-images.githubusercontent.com/30066883/45451063-39534e80-b6ef-11e8-92f6-976243f1ea13.JPG)

**Comment by badlop** [comment]
Using ejabberd 18.06, I configure like this:
```yaml
acl:
  admin:
    user:
      - "user1@localhost"

access_rules:
  configure:
    - allow: admin

commands_admin_access: configure
commands:
  - add_commands:
    - user
    - get_roster
    - sasl_auth
oauth_expire: 3600
oauth_access: all
```

Then I register the account user1@localhost and visit the page 
http://localhost:5280/oauth/authorization_token
filling the fields with user1@localhost and its password.

And the page goes to
http://localhost:5280/oauth/authorization_token?access_token=MBWAlXZy3rzBLII8L74iCm0UlxlElyB5&token_type=bearer&expires_in=31536000&scope=&state=
