### ISSUE TITLE
Ejabberd api set_vcard database_failure

### ISSUE THREAD

**Issue by devfubar** [processone/ejabberd#2629]
Environment
-----------
- ejabberd version: 18.4.0 (tried 18.09 but same issue)
- OS: Linux (Debian)
- Installed from: Docker (https://hub.docker.com/r/ejabberd/ecs/)

Configuration
---------------------------------------------------------------------------
```yaml
loglevel: 5
...
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    # register: true
    captcha: false
    tls: true
...
sql_type: mysql
sql_server: "db"
sql_database: "ejab"
sql_username: "root"
sql_password: "changeme"
default_db: sql
...
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_vcard:
    search: false
...
```

Errors from error.log/crash.log
-------------------------------
No errors

Log output
-------------------------------
```
[info] (<0.607.0>) Accepted connection ::ffff:172.18.0.1:46622 -> ::ffff:172.18.0.3:5280
[debug] S: [{[<<"ws">>],ejabberd_http_ws},{[<<"bosh">>],mod_bosh},{[<<"oauth">>],ejabberd_oauth},{[<<"api">>],mod_http_api},{[<<"admin">>],ejabberd_web_admin}]
[debug] ({tlssock,#Port<0.18819>,#Ref<0.650175335.3240493057.203147>}) http query: 'POST' <<"/api/set_vcard">>
[debug] client data: <<"{\"user\":\"foo\",\"host\":\"example.com\",\"contents\":[\"FN:foobar\"]}">>
[debug] [<<"api">>,<<"set_vcard">>] matches [<<"api">>]
[info] API call set_vcard [{<<"user">>,<<"foo">>},{<<"host">>,<<"example.com">>},{<<"contents">>,[<<"FN:foobar">>]}] from ::ffff:172.18.0.1:46622
[debug] Command 'set_vcard' execution allowed by rule 'api service' (CallerInfo=#{caller_module => mod_http_api,caller_server => <<"example.com">>,ip => {0,0,0,0,0,65535,44050,1},oauth_scope => [<<"ejabberd:api-service">>],usr => {<<"admin">>,<<"example.com">>,<<>>}})
[debug] Executing command mod_admin_extra:set_vcard with Args=[<<"foo">>,<<"example.com">>,<<>>,<<>>,[<<"FN:foobar">>]]
```

Bug description
---------------
Full disclosure I asked this on stackoverflow but not much interest (https://stackoverflow.com/questions/52707070/ejabberd-api-set-vcard-database-failure);

When I use the following command for the ejabberd API I get the following response;
```
$ curl -ik -X POST -H 'Authorization: Bearer xxxxxxxxxxx' https://localhost:5280/api/set_vcard -d '{"user":"foo","host":"example.com","name":"FN","content":"foobar"}'

HTTP/1.1 400 Bad Request
Content-Length: 18
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type, Authorization, X-Admin

"database_failure"
```

It is using MySQL as a database (working fine for everything else) however when I watch the database general query log I dont see my API request trigger any queiries. I see all the other normal ejabberd queries so there isn't a problem with the db connection (I therefore assume) and as mentioned earlier everything else works including other API calls. Same issue for set_vcard2 and set_vcard2_multi.

Does anyone have any clues they can throw my way? I've ran out of leads on what could be the issue.

**Comment by techman83** [comment]
I ran into something like this recently. The API would let me set anything, valid or not. After which it would respond with 'database_failure' on any further attempts to read/update the data. Your post data looks like it might be the culprit. The `name` is the field you want to update and `content` is what you want in that field.
```json
    {
      "user": "catman",
      "host": "the.host",
      "name": "FN",
      "content": "Cat Man"
    }
```

**Comment by devfubar** [comment]
@techman83 Thanks for your reply. Your problem sounds exactly the same as mine. You are also right that my command was wrong. After using the correct command (edited the initial comment as a result) the problem is still the same one that both you and I seem to experience. Did you figure out what was wrong?

**Comment by techman83** [comment]
@devfubar, query caching bit me as well. You can restart the daemon or disable the caching while your figure it out. (Can't recall the exact config line right now).

 But if the record is barred I had to pop into SQL and drop it out edit the field to remove the crud.

**Comment by devfubar** [comment]
@techman83 You were correct again, it is a cache issue. Thank you. I cleared my vcard table and changed my config to;
```yaml
...
mod_vcard:
  search: false
  use_cache: false
...
```
If you want some stackoverflow points add an answer there and I will mark it as correct.
