### ISSUE TITLE
Error: create_new_account when trying to get_certificates

### ISSUE THREAD

**Issue by mbirth** [processone/ejabberd#2638]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.1` (bundled)
- OS: Linux (Ubuntu Server ARM64)
- Installed from: official binary installer

Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml
---------------------------------------------------------------------------
```yaml
acme:
  ca_url: "https://acme-v01.api.letsencrypt.org"
  contact: "mailto:my@mail.address"
```

Errors from error.log/crash.log
-------------------------------
```
2018-10-18 00:02:58.559 [error] <0.482.0>@ejabberd_acme:create_new_account:286 Error: {error,badarg} creating an account for contact: <<"mailto:my@mail.address">>
```

Bug description
---------------
```
$ bin/ejabberdctl get_certificates all
Error: create_new_account
```

What does it want to tell me here? How can I make it get LetsEncrypt certificates?
