### ISSUE TITLE
Connection failed: connection closed http-bind

### ISSUE THREAD

**Issue by bp91** [processone/ejabberd#2639]
Environment
-----------
- ejabberd version: 18.04
- Erlang version: `erl +V`
- OS: Linux (CentOS)
- Installed from: official deb/rpm

No errors

Bug description
---------------
Hi, for some clients I've seen that there are a lot of connection closed problems. This is the log from ejabberd.log
```
2018-10-19 10:16:29.350 [info] <0.14491.26>@ejabberd_c2s:process_terminated:271 (http_bind|<0.14497.26>) Closing c2s session for agent_1@unyco.net/euphonia: Connection failed: connection closed
2018-10-19 10:16:29.350 [debug] <0.14491.26>@mod_carboncopy:disable:263 disabling for <<"agent_1">>
```
and these are the modules used into the ejabberd.yml:
```
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_avatar: {}
  mod_blocking: {} # requires mod_privacy
  mod_bosh:
    max_inactivity: 6
  mod_caps: {}
  mod_carboncopy: {}
  mod_configure: {} # requires mod_adhoc
  mod_fail2ban: 
    c2s_auth_ban_lifetime: 1
    c2s_max_auth_failures: 1000
  mod_http_api: {}
  mod_last: {}
  mod_muc:
    ## host: "conference.@HOST@"
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      allow_subscription: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: 
    send_pings: true
    ping_interval: 4
    ping_ack_timeout: 6
    timeout_action: kill
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    max_items_node: 10
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      "storage:bookmarks":
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    ip_access: trusted_network
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  mod_stream_mgmt: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
```
I know that mod_ping is really low, but the client can't take again an existing resource, but if the client loses the connection, it will do a login again, so I have thought to use a ping every **4 seconds** to client and to wait for **6 seconds**. If the server (ejabberd) doesn't receive response, it will destroy the resource.
Then I have used also **mod_bosh** with max_inactivity of **6 seconds** (like **ping_ack_timeout**).
Is this a good configuration? How I can avoid these connection closed events? Thanks for the help
