### ISSUE TITLE
Session ID mismatch

### ISSUE THREAD

**Issue by bp91** [processone/ejabberd#2657]
Environment
-----------
- ejabberd version: 18.09
- OS: Linux (CentOS)
- Installed from: official rpm

Configuration ejabberd.yml
---------------------------------------------------------------------------
```
loglevel: 4

log_rotate_size: 50485760
log_rotate_date: "$D0"
log_rotate_count: 10

log_rate_limit: 100

hosts:
  - "wcs.eudata.biz"

certfiles:
  - "/opt/ejabberd-18.09/conf/server.pem"

ca_file: "/opt/ejabberd-18.09/conf/cacert.pem"

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    access: s2s
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/http-bind": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    web_admin: false
    ## register: true
    captcha: false
  -
    port: 7070
    ip: "::"
    tls: true
    certfile:
      "/opt/ejabberd/certs/xip.io.pem"
    module: ejabberd_http
    request_handlers:
      "/http-bind": mod_bosh
    web_admin: false
    ## register: true
    captcha: false
  -
    port: 9090
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
    web_admin: true
    http_bind: true
    captcha: false
 
s2s_use_starttls: optional

auth_method: internal
resource_conflict: closeold

shaper:
  normal: 4000000
  fast: 8000000

max_fsm_queue: 10000

acl:
  admin:
    user:
      - "admin": "wcs.eudata.biz"

  local:
    user_regexp: ""

  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"

shaper_rules:
  ## Maximum number of simultaneous sessions allowed for a single user:
  max_user_sessions: infinity
  ## Maximum number of offline messages that users can have:
  max_user_offline_messages:
    - 50000: admin
    - 50000
  ## For C2S connections, all users except admins use the "normal" shaper
  c2s_shaper: normal
  ## All S2S connections use the "fast" shaper
  s2s_shaper: fast

###.  ============
###'  ACCESS RULES
access_rules:
  ## This rule allows access only for local users:
  local:
    - allow: local
  ## Only non-blocked users can use c2s connections:
  c2s:
    - deny: blocked
    - allow
  s2s:
    - deny: blocked
    - allow
  ## Only admins can send announcement messages:
  announce:
    - allow: admin
  ## Only admins can use the configuration interface:
  configure:
    - allow: admin
  ## Only accounts of the local ejabberd server can create rooms:
  muc_create:
    - allow: local
  register:
    - allow
  ## Only allow to register from localhost
  trusted_network:
    - allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - admin
      - users
    what:
      - "*"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"

language: "en"

acme:

   ## A contact mail that the ACME Certificate Authority can contact in case of
   ## an authorization issue, such as a server-initiated certificate revocation.
   ## It is not mandatory to provide an email address but it is highly suggested.
   contact: "mailto:admin@localhost"


   ## The ACME Certificate Authority URL.
   ## This could either be:
   ##   - https://acme-v01.api.letsencrypt.org - (Default) for the production CA
   ##   - https://acme-staging.api.letsencrypt.org - for the staging CA
   ##   - http://localhost:4000 - for a local version of the CA
   ca_url: "https://acme-v01.api.letsencrypt.org"

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_bosh:
    max_inactivity: 4
  mod_caps: {}
  mod_carboncopy: {}
  mod_configure: {} # requires mod_adhoc
  mod_fail2ban: 
    c2s_auth_ban_lifetime: 1
    c2s_max_auth_failures: 1000
  mod_http_api: {}
  mod_last: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      allow_subscription: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: 
    send_pings: true
    ping_interval: 30
    ping_ack_timeout: 4
    timeout_action: kill
  mod_privacy: {}
  mod_private: {}
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    ip_access: trusted_network
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  mod_stream_mgmt: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}

allow_contrib_modules: true
```
Hi, with the configuration written before, I really continue to have **Session ID mismatch** received from the bosh call during the communication from the client to the server.
This problem cause frequently disconnections to the client side. I have to exclude that these problems are not caused by my ejabberd configuration.
Can anyone help me on this? Thanks

**Comment by bp91** [comment]
I really don't know where is the problem: I need this
```
mod_bosh:
  max_inactivity: 4s
...
mod_ping: 
    send_pings: true
    ping_interval: 30
    ping_ack_timeout: 4
    timeout_action: kill
```
Because I need to kill the resource really fast, in order to not incur **into connection-conflict problems**, and this is because from the client side each time there is a network problem, they try to open a new connection instead of restore the old one.
