### ISSUE TITLE
Invalid value for option 'certfiles'

### ISSUE THREAD

**Issue by kaizushi** [processone/ejabberd#2666]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: `erl +V`
- OS: Linux (Gentoo)
- Installed from: source

Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml
---------------------------------------------------------------------------
```
loglevel: 5
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "infantilefb6ovh4.onion"
certfiles:
  - "/etc/ssl/ejabberd/infantilefb6ovh4.onion.pem"
route_subdomains: s2s
listen: 
  - 
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  - 
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
  - 
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/api": mod_http_api
    web_admin: false
    http_bind: true
    register: true
    captcha: true
host_config:
  "infantilefb6ovh4.onion":
     domain_certfile: "/etc/ssl/ejabberd/server.pem"
auth_method: internal
fqdn: "infantilefb6ovh4.onion"
shaper:
  normal: 10000
  fast: 100000
max_fsm_queue: 1000
acl:
  admin:
    user:
      - "kaizushi@infantilefb6ovh4.onion"
      - "cyrus559@infantilefb6ovh4.onion"
  local: 
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
shaper_rules:
  max_user_sessions: 500
  max_user_offline_messages:
    - 5000: admin
    - 1000
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure: 
    - allow: admin
  muc_create: 
    - allow: local
  pubsub_createnode: 
    - allow: local
  register: 
    - allow
  trusted_network: 
    - allow: loopback
  s2s: 
    - allow
registration_timeout: infinity
  
language: "en"
captcha_cmd: "/usr/lib64/captcha.sh"
captcha_host: "infantilefb6ovh4.onion:5280"
modules: 
  mod_adhoc: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_last: {}
  mod_muc: 
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
  mod_offline: 
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pubsub: 
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins: 
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
  mod_register:
    captcha_protected: true
    password_strength: 256
    welcome_message: {subject: Welcome to Infantile, body: Welcome to the Infantile XMPP service, we really don't care what you do with it but please don't cause us trouble}
    access_from: allow
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard:
    search: false
  mod_version: {}
allow_contrib_modules: true
```

Errors from error.log/crash.log
-------------------------------
2018-11-05 06:17:45.766 [error] <0.64.0>@ejabberd_config:validate_opts:1087 Invalid value for option 'certfiles': /etc/ssl/ejabberd/infantilefb6ovh4.onion.pem

Bug description
---------------
The config looks fine but I was told to use certfiles instead of certfile in the listen block by the error log, and it doesn't like the certfiles option either. I don't know what I'm doing here, and all the documentation is out of date. I based my changes to the config so I'm using certfiles on the example config provided with the new version.
