### ISSUE TITLE
Password protect room does not work as expected

### ISSUE THREAD

**Issue by AlexSoloviov** [processone/ejabberd#2668]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 8.2.1
- OS: Linux (Debian)
- Installed from: official deb

Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml
---------------------------------------------------------------------------
```yaml
...
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_bosh: {}
  mod_last: {}
  mod_mam: {} # for xep0313, mnesia is limited to 2GB, better use an SQL backend
  mod_muc:
    host: "chats.@HOST@"
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: all
    access_persistent: muc_create
    default_room_options:
      max_users: 2000
      allow_change_subj: true
      allow_private_messages: false
      allow_private_messages_from_visitors: nobody
      allow_query_users: true
      allow_user_invites: true
      allow_visitor_nickchange: true
      allow_visitor_status: true
      anonymous: false
      captcha_protected: false
      logging: false
      members_by_default: true
      members_only: true
      moderated: true
      password_protected: true
      persistent: true
      public: false
      public_list: false
      mam: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    max_items_node: 10
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      "storage:bookmarks":
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    ip_access: all
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_avatar: {}
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
  mod_http_api: {}
  mod_fail2ban: {}
allow_contrib_modules: true

...
```

Errors from error.log/crash.log
-------------------------------
No errors

Bug description
---------------
I have configured my server with password_protected option as true
I trying to create MUC room with password via Psy client and always see the 'Incorrect password'

```xml
<presence to="mytestroom1@chats.wildix.com/user03">
  <priority>50</priority>
  <c xmlns="http://jabber.org/protocol/caps" hash="sha-1" ver="ZkAQJ811gxDNXrRQSX0pxzsE/O4=" 
    node="http://psi-im.org"/>
  <x xmlns="http://jabber.org/protocol/muc">
    <password>pass123</password>
  </x>
</presence>

<r xmlns="urn:xmpp:sm:3"/>

<a xmlns="urn:xmpp:sm:3" h="10"/>

<presence to="user03@03.chats.wildix.com/MacBook-Pro-admin"
   xml:lang="en" type="error" from="mytestroom1@chats.wildix.com/user03">
  <c xmlns="http://jabber.org/protocol/caps" hash="sha-1" ver="ZkAQJ811gxDNXrRQSX0pxzsE/O4=" 
    node="http://psi-im.org"/>
  <x xmlns="http://jabber.org/protocol/muc">
    <password>pass123</password>
  </x>
  <x xmlns="vcard-temp:x:update"/>
    <error code="401" type="auth">
      <not-authorized xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
      <text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">Incorrect password</text>
    </error>
  <priority>50</priority>
</presence>
```

In database in muc_room I see the following record

```yaml
| mytestroom1             | chats.wildix.com |             | [{title,<<>>},
 {description,<<>>},
 {allow_change_subj,true},
 {allow_query_users,true},
 {allow_private_messages,false},
 {allow_private_messages_from_visitors,nobody},
 {allow_visitor_status,true},
 {allow_visitor_nickchange,true},
 {public,false},
 {public_list,false},
 {persistent,true},
 {moderated,true},
 {members_by_default,true},
 {members_only,true},
 {allow_user_invites,true},
 {password_protected,true},
 {captcha_protected,false},
 {password,<<>>},
 {anonymous,false},
 {logging,false},
 {max_users,200},
 {allow_voice_requests,true},
 {allow_subscription,false},
 {mam,true},
 {presence_broadcast,[moderator,participant,visitor]},
 {voice_request_min_interval,1800},
 {vcard,<<>>},
 {vcard_xupdate,undefined},
 {pubsub,<<>>},
 {lang,<<>>},
 {captcha_whitelist,[]},
 {affiliations,[{{<<"user03">>,<<"03.chats.wildix.com">>,<<>>},{owner,<<>>}}]},
 {subject,[]},
 {subject_author,<<>>}]                                                                                                                             | 2018-11-05 13:33:19 |

```

After creation I cannot connect to this room anymore.
Could you please help/clarify what is going on or what have I done wrong?
