### ISSUE TITLE
mod_http_upload 408 Serving file not found

### ISSUE THREAD

**Issue by ndlrx** [processone/ejabberd#2673]
Environment
-----------
- ejabberd version: 18.01
- Erlang version: `20.2.2`
- OS: Linux (Ubuntu)
- Installed from: distro package

Below is my `mod_http_upload` configuration at the ejabberdejabberd.yml
---------------------------------------------------------------------------
```yaml
...
  mod_http_upload:
    docroot: "/opt/upload"
    put_url: "https://@HOST@:5444/upload"
    host: "upload.@HOST@"
    thumbnail: true
    max_size: infinity
...
```

Errors from ejabberd.log
-------------------------------
@mod_http_upload:process:408 Serving /opt/upload/b69b30fe5d4134151cabd20b5f936725a431f9b7/Xky7L6jFKNRCXjXiT3GsqjXouEUuiWlOzx3azUrH/S75GmVFtSySszfIRuBvMaA.jpg to 192.168.2.18

Bug description
---------------
When trying to download the file, I get `file not found` results.

I've checked the file on my server:

```
ls -lah /opt/upload/b69b30fe5d4134151cabd20b5f936725a431f9b7/Xky7L6jFKNRCXjXiT3GsqjXouEUuiWlOzx3azUrH/S75GmVFtSySszfIRuBvMaA.jpg
```

The file is available on the upload directory.
