### ISSUE TITLE
ejabberd 18.04 + ejabberdctl subscribe muc group + error

### ISSUE THREAD

**Issue by jigsp26** [processone/ejabberd#2710]
**ejabberd version : 18.04**

**ejabberd.yml**
```
mod_muc:
    access: muc
    access_create: muc
    access_persistent: muc
    access_admin: muc_admin
    default_room_options:
      allow_change_subj: true
      allow_private_messages: true
      allow_user_invites: true
      allow_subscription: true
      logging: true
      members_by_default: true
      persistent: true
      public: true
      public_list: false
  mod_muc_log:
      access_log: muc
      dirtype: plain
      dirname: room_jid
      outdir: "/var/www/muclogs"
      timezone: universal
      spam_prevention: true
  mod_muc_admin: {} 
```

create MUC Room
> ejabberdctl create_room sagar urn:xmpp:mucsub:nodes:messages xmpp_domain

room created successfully. 

**Subscribe MUC room**

> ejabberdctl subscribe_room usrname@xmpp_domain nickname_of user groupname@conferance.xmpp_domain xmpp_domain

getting error:
> **{error,"User's JID should have a resource"}**

**Please give me any suggestion for this.**
