### ISSUE TITLE
Issue Failed to establish outbound s2s connection domain -> user: DNS lookup failed: non-existing domain; bouncing for 174 seconds

### ISSUE THREAD

**Issue by bp91** [processone/ejabberd#2717]
Ejabberd version:
`18.09`

ejabberd.yml:
```
websocket_ping_interval: 30

websocket_timeout: 90

loglevel: 4

log_rotate_size: 50485760
log_rotate_date: "$D0"
log_rotate_count: 10

log_rate_limit: 100

hosts:
  - "wcs.test.biz"

certfiles:
  - "/opt/ejabberd-18.09/conf/server.pem"

ca_file: "/opt/ejabberd-18.09/conf/cacert.pem"

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    access: s2s
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/http-bind/ws": ejabberd_http_ws
      "/http-bind": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    web_admin: false
    ## register: true
    captcha: false
  -
    port: 7070
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/http-bind/ws": ejabberd_http_ws
      "/http-bind": mod_bosh
    web_admin: false
    captcha: false
    
  -
    port: 9090
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
    web_admin: true
    http_bind: true
    captcha: false
 
s2s_use_starttls: optional

auth_method: internal
resource_conflict: closeold

shaper:
  normal: 4000000
  fast: 8000000

max_fsm_queue: 10000

acl:
  admin:
    user:
      - "admin": "wcs.test.biz"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast

access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  s2s:
    - deny: blocked
    - allow: all
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - admin
      - users
    what:
      - "*"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"

language: "en"

acme:

   contact: "mailto:admin@localhost"

   ca_url: "https://acme-v01.api.letsencrypt.org"

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_configure: {} # requires mod_adhoc
  mod_bosh: 
    max_inactivity: 20
  mod_last: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      allow_subscription: true
  mod_muc_admin: {}
  ## mod_muc_log: {}
  ## mod_multicast: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: 
    send_pings: true
    ping_interval: 20
    ping_ack_timeout: 4
    timeout_action: kill
  mod_privacy: {}
  mod_private: {}
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    ip_access: trusted_network
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  ## mod_stats: {}
  ## mod_time: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  ## mod_avatar: {}
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
  mod_http_api: {}
  mod_fail2ban: {}

allow_contrib_modules: true
```

Hi, I have the following problem. I have two clustered ejabberd server running on two different machine.
The case is this:
I have the user **U** logged in with a resource in the ejabberd server **A**.

I send the following message from machine B and received from the ejabberd server **B**:

```
2018-12-11 17:40:34.137 [info] <0.816.0>@mod_http_api:log:543 API call send_message [{<<"to">>,<<"agent1@wcs.test.biz/euphonia">>},{<<"body">>,<<"{\"message\":\"logout\",\"time\":\"instant\",\"minutes\":\"null\",\"reason\":\"logout\",\"subject\":\"logout e\",\"command\":\"system_message\"}">>},{<<"subject">>,<<"logout">>},{<<"from">>,<<"admin">>},{<<"type">>,<<"normal">>}] from ::ffff:XXX.XXX.X.X:45430```

In order to logout the user **U** from ejabberd server **A**. 
On the ejabberd server **A** I receive the following log message:

```
2018-12-11 17:36:11.564 [warning] <0.650.0>@ejabberd_s2s_out:process_closed:160 Failed to establish outbound s2s connection wcs.test.biz -> admin: DNS lookup failed: non-existing domain; bouncing for 82 seconds
```

But on the server **A** nothing work as expected. 
Seems that communication between the two machines doesn't work. Can you help me? Thank you
