### ISSUE TITLE
Message carbons not working after update to 18.12

### ISSUE THREAD

**Issue by mbirth** [processone/ejabberd#2719]
After updating from 18.09 to 18.12, message carbons don't seem to work properly anymore. Although Conversations shows XEP-0280 as "available" (=supported/enabled), whenever I type something in Conversations, it doesn't show up in Gajim on my desktop and vice versa.

The only settings I've changed after the update were:

```
  mod_pubsub:
    force_node_config:
      ## Change from "whitelist" to "open" to enable OMEMO support
      ## See https://github.com/processone/ejabberd/issues/2425
      "eu.siacs.conversations.axolotl.*":
        access_model: open
```
("eu.siacs..." was commented out before.)

and

```
  mod_proxy65:
    access: local
    max_connections: 5
```

(Added that as I didn't have it configured before.)

Both shouldn't have any effect on message carbons, I believe.
