### ISSUE TITLE
Database failure for Compliance Suite Test XEP-0384

### ISSUE THREAD

**Issue by arendtio** [processone/ejabberd#2726]
While trying to get my server to pass the [XMPP compliance suite](https://compliance.conversations.im/) I have come to a point where I am not sure anymore where the problem originates from (a bug in ejabberd, a bug in the compliance suite or a misconfiguration on my side). Therefore, I am posting this bug report, without being 100% sure it is a bug within this project. If you think this is the wrong place for such an issue please say so.

Let's start with the setup:

- ejabberd 18.12 via Arch Linux x86_64 (installed via pacman)
- Mnesia database (~ 1.8GB, yes, I might want to migrate that to SQL pretty soon)

I tried running the compliance suite via the web service as well as via the command line, with a fresh user I created for that purpose. In both cases, the test for 'XEP-0384 OMEMO Encryption' fails (most other tests pass).

AFAIK, the relevant configuration part looks just fine:

```
  mod_caps: {}
...
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: false
    last_item_cache: false
    max_items_node: 1000
    default_node_config:
      max_items: 1000
    plugins:
      - "pep"
      - "flat"
    force_node_config:
      ## Change from "whitelist" to "open" to enable OMEMO support
      ## See https://github.com/processone/ejabberd/issues/2425
      "eu.siacs.conversations.axolotl.*":
        access_model: open
      ## Avoid buggy clients to make their bookmarks public
      "storage:bookmarks":
        access_model: whitelist
```

In order to dig a little deeper into the problem, removed all other tests from the compliance suite and saved the ejabberd.log that was generated while I ran the test. From my perspective, it looks like the relevant error message is this:

```
2018-12-15 12:08:39.934 [error] <0.598.0>@mod_pubsub:do_transaction:3643 transaction return internal error: {aborted,badarg}
```

The compliance suite on the other end seems to throw an exception when executing the following [node.delete()](https://github.com/iNPUTmice/caas/blob/9042c8f7e4ee05218f38183f3b4c58a32b253f16/caas-app/src/main/java/im/conversations/compliance/xmpp/tests/OMEMO.java#L73) line of the test:

```
java.util.concurrent.ExecutionException: rocks.xmpp.core.stanza.model.StanzaErrorException: internal-server-error  -  (type 'wait': retry after waiting (the error is temporary))
        Database failure
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at rocks.xmpp.util.concurrent.AsyncResult.get(AsyncResult.java:286)
        at im.conversations.compliance.xmpp.tests.OMEMO.run(OMEMO.java:83)
        at im.conversations.compliance.xmpp.TestExecutor.executeTestsFor(TestExecutor.java:52)
        at im.conversations.compliance.CommandLineLauncher.main(CommandLineLauncher.java:73)
```

(The line number of OMEMO.java doesn't match because I added some `system.out.println` for debugging purposes)

While looking for a solution I found #1531 which describes a similar issue but seems to be related to pqsql which is not present in this setup.

Does someone know what might cause those database failures?

-----

Server configuration and the server.log (log-level 5):

[ejabberd.log](https://github.com/processone/ejabberd/files/2682920/ejabberd.log)
[ejabberd.yml](https://github.com/processone/ejabberd/files/2682921/ejabberd.txt)
