### ISSUE TITLE
Incorrect loading of certs with restart | mod_http_upload

### ISSUE THREAD

**Issue by tyler71** [processone/ejabberd#2739]
Version 18.12.1
Config:

``` 
hosts:
  - "domain.tld"
  - "domain2.tld"
certfiles:
  - "/etc/ejabberd/certs/domain.tld.cert"
  - "/etc/ejabberd/certs/domain.tld.key"
  - "/etc/ejabberd/certs/domain2.tld.cert"
  - "/etc/ejabberd/certs/domain2.tld.key"
```
Doing `ejabberdctl restart` will cause domain.tld to load domain2.tld SSL certificate when attempting to download a file with Conversations. Conversations alerts the user to a "mismatch certificate" and lists domain2's domains
`ejabberdctl reload_config` appears to fix this

If relevant:
```
  mod_http_upload:
    host: "upload-xmpp.@HOST@"
    put_url: "https://@HOST@:5443/upload"
    docroot: "/foo/bar/storage"
```
