### ISSUE TITLE
Syntax Error on Erlang expressions inside yaml file

### ISSUE THREAD

**Issue by volga629** [processone/ejabberd#274]
Hello Everyone,
I am getting sysntax error and does in matter what change it still complain the same line
Any help thank you.

```
22:39:11.180 [error] Cannot load /opt/ejabberd/conf/ejabberd.yml: Syntax error on line 674 at position 46: did not find expected key
```

```

    ldap_vcard_map:
        "NICKNAME": {"%u": []}
        "GIVEN": {"%s": ["givenName"]}
        "FAMILY": {"%s": ["sn"]}
        "FN": {"%s, %s": ["sn", "givenName"]},
        "EMAIL": {"%s": ["mail"]}
        "BDAY": {"%s": ["birthDay"]}]}
    ## Search form
    ldap_search_fields:
      "User": "%u"
      "Name": "givenName"
      "Family Name": "sn"
      "Email": "mail"
      "Birthday": "birthDay"
    ## vCard fields to be reported
    ## Note that JID is always returned with search results
    ldap_search_reported:
      "Full Name": "FN"
      "Nickname": "NICKNAME"
      "Birthday": "BDAY"

```

**Comment by sandinak** [comment]
This response isn't useful  The issue ihere is that ldap_vcard_map has triple entries in the configuration that the user noted above: 
{modules,
  ..,
   {mod_vcard_ldap,
   [
    {ldap_vcard_map,
     [{"NICKNAME", "%u", []}, % just use user's part of JID as his nickname
      {"FIRST", "%s", ["givenName"]},
      {"LAST", "%s", ["sn"]},

I havn't found a good way to represent ... nor any single example that translates that to YAML
mod_vcard_map: 
   ldap_vcard_map: 
      "FIRST": "%s"
          - givenName 

Fails all day.  It's the only module that was NOT re-represented in the documentation as YAML .. please fix.

**Comment by Scort210** [comment]
zinid:  **Obviously** there are syntax errors in the documentation.  **Please read something about YAML** and update the documentation to be valid, rather than making snippy comments about something that's not the end user's fault.  They are following the manual.  Why this is "closed" without the docs having been fixed is beyond me.

**Comment by cromain** [comment]
we'll check the documentation for this particular case

**Comment by cromain** [comment]
recent commit 87d2eb by badlop will help for this this case. it allows to write erlang expressions as part of the YAML file. example:

**Comment by zinid** [comment]
@cromain there is no needs for such hacks, mod_vcard_ldap supports native yaml configuration, it's just not documented.

**Comment by sandinak** [comment]
zinid: I don't see that in the code... can you give an example?

**Comment by mute---** [comment]
Working config for AD
```
  mod_vcard_ldap:
    ldap_uids:
      "sAMAccountName": "%u"
    ldap_vcard_map: 
      "NICKNAME": {"%u": []} 
      "GIVEN": {"%s": ["givenName"]}
      "MIDDLE": {"%s": ["initials"]}
      "FAMILY": {"%s": ["sn"]}
      "FN": {"%s": ["displayName"]}
      "EMAIL": {"%s": ["mail"]}
      "ORGNAME": {"%s": ["company"]}
      "ORGUNIT": {"%s": ["department"]}
      "CTRY": {"%s": ["c"]}
      "LOCALITY": {"%s": ["l"]}
      "STREET": {"%s": ["streetAddress"]}
      "REGION": {"%s": ["st"]}
      "PCODE": {"%s": ["postalCode"]}
      "TITLE": {"%s": ["title"]}
      "URL": {"%s": ["wWWHomePage"]}
      "DESC": {"%s": ["description"]}
      "TEL": {"%s": ["telephoneNumber"]}
      "PHOTO": {"%s": ["thumbnailPhoto"]}
    ldap_search_fields: 
      "User": "%u"
      "Name": "givenName"
      "Family Name": "sn"
      "Email": "mail"
      "Company": "company"
      "Department": "department"
      "Role": "title"
      "Description": "description"
      "Phone": "telephoneNumber"
    ldap_search_reported: 
      "Full Name": "FN"
      "Nickname": "NICKNAME"
      "Email": "EMAIL"
```
