### ISSUE TITLE
Problem Missing Message

### ISSUE THREAD

**Issue by gylraj** [processone/ejabberd#2757]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 9.2`
- OS: Linux (Ubuntu)
- Installed from:  official deb/rpm

Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml
---------------------------------------------------------------------------
```yaml
loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "chat.cs.com"
certfiles:
  - "/opt/ejabberd-18.09/conf/server.pem"
ca_file: "/opt/ejabberd-18.09/conf/cacert.pem"
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    max_stanza_size: 131072
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    web_admin: true
    captcha: false
  -
    port: 5282
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    web_admin: true
    tls: true
    captcha: false
    http_bind: true
s2s_use_starttls: optional
auth_method: sql
sql_type: mysql
sql_server: "111.11.11.11"
sql_database: "ejabberd"
sql_username: "root"
sql_password: "pass"
new_sql_schema: true
shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 1000
acl:
  admin:
    user:
      - "admin@chat.cs.com"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - infinity
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who: all
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
    what:
      - "*"
      - "!stop"
      - "!start"
registration_timeout: infinity
  
language: "en"
acme:
   contact: "mailto:admin@ip-111-111-111-111.eu-west-3.compute.internal"
   ca_url: "https://acme-v01.api.letsencrypt.org"
modules:
  mod_offline_post:
    auth_token: "secret"
    post_url: "http://api.cs.com/users/push"
    post_url_json: "http://api.cs.com/users/pushjson"
    post_url_read: "http://api.cs.com/users/setmessagestatusxmpp"
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
    db_type: sql
  mod_blocking: {} # requires mod_privacy
  mod_caps: 
    db_type: sql
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_bosh: {}
  mod_last:
    db_type: sql
  mod_mam:
    db_type: sql
    use_cache: true
    default: always
    request_activates_archiving: false
    assume_mam_usage: false
  mod_muc:
    db_type: sql
    host: "room.@HOST@"
    access:
      - allow: all
    access_admin: ## all
      - allow: admin
    access_create: all
    access_persistent: all
    max_user_conferences: 3000000
    max_users: 10000
    max_users_admin_threshold: 1000
    default_room_options:
      persistent: true
      allow_subscription: true
      allow_query_users: true
      allow_private_messages: true
      allow_user_invites: true
      allow_visitor_nickchange: true
      anonymous: false
      captcha_protected: false
      mam: true
      members_by_default: true
      members_only: false
      public: true
      public_list: true
  mod_muc_admin: {}
  mod_offline:
    db_type: sql
    access_max_user_messages: max_user_offline_messages
    store_empty_body: unless_chat_state
  mod_ping:
    send_pings: true
    ping_interval: 32
    ping_ack_timeout: 5
    timeout_action: kill
  mod_privacy:
    db_type: sql
  mod_private:
    db_type: sql
  mod_pubsub:
    db_type: sql
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    max_items_node: 25
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      "storage:bookmarks":
        access_model: whitelist
        max_items: 25
      "urn:xmpp:bookmarks:0":
        access_model: whitelist
        max_items: 25
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    ip_access: trusted_network
    access: register
  mod_roster:
    versioning: true
    store_current_id: true
    db_type: sql
  mod_shared_roster: {}
  mod_time: {}
  mod_vcard:
    db_type: sql
    search: true 
  mod_vcard_xupdate: {}
  mod_avatar: {}
  mod_version: {}
  mod_stream_mgmt:
    max_ack_queue: infinity
    resume_timeout: 120
    resend_on_timeout: true
    max_resume_timeout: 120
  mod_s2s_dialback: {}
  mod_http_api: {}
allow_contrib_modules: true
```
------------------------------
Problem: 
sometimes some users have experienced missing messages
see id 143560
sender has message "okay" in archive  but receiver

MYSQL
archive table

```xml

<?xml version="1.0"?>

<resultset statement="SELECT * FROM archive WHERE (username='user1' or username='user2') and (bare_peer = 'user2@chat.cs.com' or bare_peer = 'user1@chat.cs.com')" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <row>
    <field name="username">user1</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1546999924303162</field>
    <field name="peer">user2@chat.cs.com</field>
    <field name="bare_peer">user2@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user2@chat.cs.com' from='user1@chat.cs.com/user1' type='chat' id='5c35586a27c7d1023b166fe6' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;type&gt;text&lt;/type&gt;&lt;date_sent&gt;1546999914386&lt;/date_sent&gt;&lt;sender_name&gt;Orly&lt;/sender_name&gt;&lt;/extraParams&gt;&lt;active xmlns='http://jabber.org/protocol/chatstates'/&gt;&lt;body&gt;okay&lt;/body&gt;&lt;thread&gt;user2@chat.cs.com&lt;/thread&gt;&lt;/message&gt;</field>
    <field name="txt">okay</field>
    <field name="id">143560</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:12:04</field>
  </row>

  <row>
    <field name="username">user2</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1546999959685488</field>
    <field name="peer">user1@chat.cs.com</field>
    <field name="bare_peer">user1@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user1@chat.cs.com' from='user2@chat.cs.com/c831979cafbfc8c0' type='chat' id='5c3558a59318cbbc95ca1bfc' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;date_sent&gt;1546999973888&lt;/date_sent&gt;&lt;sender_name&gt;Edison Canlas 👨‍💻&lt;/sender_name&gt;&lt;type&gt;thumbsup&lt;/type&gt;&lt;/extraParams&gt;&lt;body&gt;👍&lt;/body&gt;&lt;/message&gt;</field>
    <field name="txt">👍</field>
    <field name="id">143563</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:12:39</field>
  </row>

  <row>
    <field name="username">user1</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1546999959688791</field>
    <field name="peer">user2@chat.cs.com/c831979cafbfc8c0</field>
    <field name="bare_peer">user2@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user1@chat.cs.com' from='user2@chat.cs.com/c831979cafbfc8c0' type='chat' id='5c3558a59318cbbc95ca1bfc' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;date_sent&gt;1546999973888&lt;/date_sent&gt;&lt;sender_name&gt;Edison Canlas 👨‍💻&lt;/sender_name&gt;&lt;type&gt;thumbsup&lt;/type&gt;&lt;/extraParams&gt;&lt;body&gt;👍&lt;/body&gt;&lt;/message&gt;</field>
    <field name="txt">👍</field>
    <field name="id">143564</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:12:39</field>
  </row>

  <row>
    <field name="username">user2</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1546999979469703</field>
    <field name="peer">user1@chat.cs.com</field>
    <field name="bare_peer">user1@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user1@chat.cs.com' from='user2@chat.cs.com/c831979cafbfc8c0' type='chat' id='5c3558b99318cbbc95ca1bff' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;date_sent&gt;1546999993022&lt;/date_sent&gt;&lt;sender_name&gt;Edison Canlas 👨‍💻&lt;/sender_name&gt;&lt;type&gt;text&lt;/type&gt;&lt;/extraParams&gt;&lt;body&gt;Test&lt;/body&gt;&lt;/message&gt;</field>
    <field name="txt">Test</field>
    <field name="id">143565</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:12:59</field>
  </row>

  <row>
    <field name="username">user1</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1546999979473128</field>
    <field name="peer">user2@chat.cs.com/c831979cafbfc8c0</field>
    <field name="bare_peer">user2@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user1@chat.cs.com' from='user2@chat.cs.com/c831979cafbfc8c0' type='chat' id='5c3558b99318cbbc95ca1bff' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;date_sent&gt;1546999993022&lt;/date_sent&gt;&lt;sender_name&gt;Edison Canlas 👨‍💻&lt;/sender_name&gt;&lt;type&gt;text&lt;/type&gt;&lt;/extraParams&gt;&lt;body&gt;Test&lt;/body&gt;&lt;/message&gt;</field>
    <field name="txt">Test</field>
    <field name="id">143566</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:12:59</field>
  </row>

  <row>
    <field name="username">user1</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1546999982673828</field>
    <field name="peer">user2@chat.cs.com</field>
    <field name="bare_peer">user2@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user2@chat.cs.com' from='user1@chat.cs.com/user1' type='chat' id='5c3558ac2ea111023ba820dc' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;type&gt;text&lt;/type&gt;&lt;date_sent&gt;1546999980676&lt;/date_sent&gt;&lt;sender_name&gt;Orly&lt;/sender_name&gt;&lt;/extraParams&gt;&lt;active xmlns='http://jabber.org/protocol/chatstates'/&gt;&lt;body&gt;g hi&lt;/body&gt;&lt;thread&gt;user2@chat.cs.com&lt;/thread&gt;&lt;/message&gt;</field>
    <field name="txt">g hi</field>
    <field name="id">143567</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:13:02</field>
  </row>

  <row>
    <field name="username">user2</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1546999982677089</field>
    <field name="peer">user1@chat.cs.com/user1</field>
    <field name="bare_peer">user1@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user2@chat.cs.com' from='user1@chat.cs.com/user1' type='chat' id='5c3558ac2ea111023ba820dc' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;type&gt;text&lt;/type&gt;&lt;date_sent&gt;1546999980676&lt;/date_sent&gt;&lt;sender_name&gt;Orly&lt;/sender_name&gt;&lt;/extraParams&gt;&lt;active xmlns='http://jabber.org/protocol/chatstates'/&gt;&lt;body&gt;g hi&lt;/body&gt;&lt;thread&gt;user2@chat.cs.com&lt;/thread&gt;&lt;/message&gt;</field>
    <field name="txt">g hi</field>
    <field name="id">143568</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:13:02</field>
  </row>

  <row>
    <field name="username">user2</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1546999987697253</field>
    <field name="peer">user1@chat.cs.com/user1</field>
    <field name="bare_peer">user1@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user1@chat.cs.com/user1' from='user2@chat.cs.com/c831979cafbfc8c0' type='chat' id='5c3558c19318cbbc95ca1c06' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;date_sent&gt;1547000001306&lt;/date_sent&gt;&lt;sender_name&gt;Edison Canlas 👨‍💻&lt;/sender_name&gt;&lt;type&gt;text&lt;/type&gt;&lt;/extraParams&gt;&lt;body&gt;Testt&lt;/body&gt;&lt;/message&gt;</field>
    <field name="txt">Testt</field>
    <field name="id">143569</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:13:07</field>
  </row>

  <row>
    <field name="username">user1</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1546999987700504</field>
    <field name="peer">user2@chat.cs.com/c831979cafbfc8c0</field>
    <field name="bare_peer">user2@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user1@chat.cs.com/user1' from='user2@chat.cs.com/c831979cafbfc8c0' type='chat' id='5c3558c19318cbbc95ca1c06' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;date_sent&gt;1547000001306&lt;/date_sent&gt;&lt;sender_name&gt;Edison Canlas 👨‍💻&lt;/sender_name&gt;&lt;type&gt;text&lt;/type&gt;&lt;/extraParams&gt;&lt;body&gt;Testt&lt;/body&gt;&lt;/message&gt;</field>
    <field name="txt">Testt</field>
    <field name="id">143570</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:13:07</field>
  </row>

  <row>
    <field name="username">user1</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1547000008005957</field>
    <field name="peer">user2@chat.cs.com</field>
    <field name="bare_peer">user2@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user2@chat.cs.com' from='user1@chat.cs.com/user1' type='chat' id='5c3558c733a091023b764ecc' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;type&gt;text&lt;/type&gt;&lt;date_sent&gt;1547000007598&lt;/date_sent&gt;&lt;sender_name&gt;Orly&lt;/sender_name&gt;&lt;/extraParams&gt;&lt;active xmlns='http://jabber.org/protocol/chatstates'/&gt;&lt;body&gt;hbj&lt;/body&gt;&lt;thread&gt;user2@chat.cs.com&lt;/thread&gt;&lt;/message&gt;</field>
    <field name="txt">hbj</field>
    <field name="id">143571</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:13:28</field>
  </row>

  <row>
    <field name="username">user2</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1547000008009087</field>
    <field name="peer">user1@chat.cs.com/user1</field>
    <field name="bare_peer">user1@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user2@chat.cs.com' from='user1@chat.cs.com/user1' type='chat' id='5c3558c733a091023b764ecc' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;type&gt;text&lt;/type&gt;&lt;date_sent&gt;1547000007598&lt;/date_sent&gt;&lt;sender_name&gt;Orly&lt;/sender_name&gt;&lt;/extraParams&gt;&lt;active xmlns='http://jabber.org/protocol/chatstates'/&gt;&lt;body&gt;hbj&lt;/body&gt;&lt;thread&gt;user2@chat.cs.com&lt;/thread&gt;&lt;/message&gt;</field>
    <field name="txt">hbj</field>
    <field name="id">143572</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:13:28</field>
  </row>

  <row>
    <field name="username">user2</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1547000015072540</field>
    <field name="peer">user1@chat.cs.com/user1</field>
    <field name="bare_peer">user1@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user1@chat.cs.com/user1' from='user2@chat.cs.com/c831979cafbfc8c0' type='chat' id='5c3558dc9318cbbc95ca1c0d' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;date_sent&gt;1547000028801&lt;/date_sent&gt;&lt;sender_name&gt;Edison Canlas 👨‍💻&lt;/sender_name&gt;&lt;type&gt;text&lt;/type&gt;&lt;/extraParams&gt;&lt;body&gt;Hahaha&lt;/body&gt;&lt;/message&gt;</field>
    <field name="txt">Hahaha</field>
    <field name="id">143573</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:13:35</field>
  </row>

  <row>
    <field name="username">user1</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1547000015075728</field>
    <field name="peer">user2@chat.cs.com/c831979cafbfc8c0</field>
    <field name="bare_peer">user2@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user1@chat.cs.com/user1' from='user2@chat.cs.com/c831979cafbfc8c0' type='chat' id='5c3558dc9318cbbc95ca1c0d' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;date_sent&gt;1547000028801&lt;/date_sent&gt;&lt;sender_name&gt;Edison Canlas 👨‍💻&lt;/sender_name&gt;&lt;type&gt;text&lt;/type&gt;&lt;/extraParams&gt;&lt;body&gt;Hahaha&lt;/body&gt;&lt;/message&gt;</field>
    <field name="txt">Hahaha</field>
    <field name="id">143574</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:13:35</field>
  </row>

  <row>
    <field name="username">user1</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1547000086883694</field>
    <field name="peer">user2@chat.cs.com</field>
    <field name="bare_peer">user2@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user2@chat.cs.com' from='user1@chat.cs.com/user1' type='chat' id='5c355916015991023b80975a' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;Contactjid&gt;user3@chat.cs.com&lt;/Contactjid&gt;&lt;sender_name&gt;Orly&lt;/sender_name&gt;&lt;date_sent&gt;1547000086379&lt;/date_sent&gt;&lt;fullName&gt;Saucey&lt;/fullName&gt;&lt;type&gt;contact&lt;/type&gt;&lt;phoneNumber&gt;user3&lt;/phoneNumber&gt;&lt;/extraParams&gt;&lt;active xmlns='http://jabber.org/protocol/chatstates'/&gt;&lt;body&gt;Send a Contact&lt;/body&gt;&lt;thread&gt;user2@chat.cs.com&lt;/thread&gt;&lt;/message&gt;</field>
    <field name="txt">Send a Contact</field>
    <field name="id">143577</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:14:46</field>
  </row>

  <row>
    <field name="username">user2</field>
    <field name="server_host">chat.cs.com</field>
    <field name="timestamp">1547000086887337</field>
    <field name="peer">user1@chat.cs.com/user1</field>
    <field name="bare_peer">user1@chat.cs.com</field>
    <field name="xml">&lt;message xml:lang='en' to='user2@chat.cs.com' from='user1@chat.cs.com/user1' type='chat' id='5c355916015991023b80975a' xmlns='jabber:client'&gt;&lt;markable xmlns='urn:xmpp:chat-markers:0'/&gt;&lt;extraParams&gt;&lt;Contactjid&gt;user3@chat.cs.com&lt;/Contactjid&gt;&lt;sender_name&gt;Orly&lt;/sender_name&gt;&lt;date_sent&gt;1547000086379&lt;/date_sent&gt;&lt;fullName&gt;Saucey&lt;/fullName&gt;&lt;type&gt;contact&lt;/type&gt;&lt;phoneNumber&gt;user3&lt;/phoneNumber&gt;&lt;/extraParams&gt;&lt;active xmlns='http://jabber.org/protocol/chatstates'/&gt;&lt;body&gt;Send a Contact&lt;/body&gt;&lt;thread&gt;user2@chat.cs.com&lt;/thread&gt;&lt;/message&gt;</field>
    <field name="txt">Send a Contact</field>
    <field name="id">143578</field>
    <field name="kind">chat</field>
    <field name="nick"></field>
    <field name="created_at">2019-01-09 02:14:46</field>
  </row>

</resultset>


```

Plz Help 👍 

If there's error in my config, please tell me. thanks in advance
