### ISSUE TITLE
Being able to name Pubsub services

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#2766]
Id like to be able to set names on Pubsub services (like it's done on Metronome or Prosody https://github.com/jappix/jappix-tools/blob/master/metronome/configs/config_metronome.cfg.lua#L243) to be able to customize the default "Publish-Subscribe" string.

Something like
```
mod_pubsub:
    hosts:
      "blabla.@HOST@":
        name: "Blabla"
      "pictures.@HOST@"
        name: "Share and publish pictures"
```

**Comment by edhelas** [comment]
This issue is related to https://github.com/movim/movim/issues/564 on Movim.

**Comment by cromain** [comment]
This option is supported already.
see mod_pubsub:iq_disco_info:L984, here we get service name, which default value is "Publish-Subscribe".

**Comment by edhelas** [comment]
```
mod_pubsub:
    hosts:
      "blabla.@HOST@":
        name: "Blabla"
      "pictures.@HOST@"
        name: "Share and publish pictures"
```

The following syntax doesn't seems to work for me.
The documentation doesn't mention anything regarding a custom name https://docs.ejabberd.im/admin/configuration/#mod-pubsub
