### ISSUE TITLE
max_users in mod_muc needs two definitions

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#2770]
Neither
```
mod_muc:
  max_users: 1000
```
nor
```
mod_muc:
  default_room_options:
    max_users: 1000
```
...actually raise the number of allowed users.

The only way to have it changed from the default 200 is to define it in both places:
```
mod_muc:
  max_users: 1000
  default_room_options:
    max_users: 1000
```
