### ISSUE TITLE
Out of memory - Worst Memory User

### ISSUE THREAD

**Issue by gylraj** [processone/ejabberd#2776]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 9.2`
- OS: Linux (Ubuntu)
- Installed from:  official deb/rpm

Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml
---------------------------------------------------------------------------
```yaml
loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "chat.cs.com"
certfiles:
  - "/opt/ejabberd-18.09/conf/server.pem"
ca_file: "/opt/ejabberd-18.09/conf/cacert.pem"
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    max_stanza_size: 131072
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    web_admin: true
    captcha: false
  -
    port: 5282
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    web_admin: true
    tls: true
    captcha: false
    http_bind: true
s2s_use_starttls: optional
auth_method: sql
sql_type: mysql
sql_server: "111.11.11.11"
sql_database: "ejabberd"
sql_username: "root"
sql_password: "pass"
new_sql_schema: true
shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 1000
acl:
  admin:
    user:
      - "admin@chat.cs.com"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - infinity
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who: all
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
    what:
      - "*"
      - "!stop"
      - "!start"
registration_timeout: infinity
  
language: "en"
acme:
   contact: "mailto:admin@ip-111-111-111-111.eu-west-3.compute.internal"
   ca_url: "https://acme-v01.api.letsencrypt.org"
modules:
  mod_offline_post:
    auth_token: "secret"
    post_url: "http://api.cs.com/users/push"
    post_url_json: "http://api.cs.com/users/pushjson"
    post_url_read: "http://api.cs.com/users/setmessagestatusxmpp"
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
    db_type: sql
  mod_blocking: {} # requires mod_privacy
  mod_caps: 
    db_type: sql
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_bosh: {}
  mod_last:
    db_type: sql
  mod_mam:
    db_type: sql
    use_cache: true
    default: always
    request_activates_archiving: false
    assume_mam_usage: false
  mod_muc:
    db_type: sql
    host: "room.@HOST@"
    access:
      - allow: all
    access_admin: ## all
      - allow: admin
    access_create: all
    access_persistent: all
    max_user_conferences: 3000000
    max_users: 10000
    max_users_admin_threshold: 1000
    default_room_options:
      persistent: true
      allow_subscription: true
      allow_query_users: true
      allow_private_messages: true
      allow_user_invites: true
      allow_visitor_nickchange: true
      anonymous: false
      captcha_protected: false
      mam: true
      members_by_default: true
      members_only: false
      public: true
      public_list: true
  mod_muc_admin: {}
  mod_offline:
    db_type: sql
    access_max_user_messages: max_user_offline_messages
    store_empty_body: unless_chat_state
  mod_ping:
    send_pings: true
    ping_interval: 32
    ping_ack_timeout: 5
    timeout_action: kill
  mod_privacy:
    db_type: sql
  mod_private:
    db_type: sql
  mod_pubsub:
    db_type: sql
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    max_items_node: 25
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      "storage:bookmarks":
        access_model: whitelist
        max_items: 25
      "urn:xmpp:bookmarks:0":
        access_model: whitelist
        max_items: 25
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    ip_access: trusted_network
    access: register
  mod_roster:
    versioning: true
    store_current_id: true
    db_type: sql
  mod_shared_roster: {}
  mod_time: {}
  mod_vcard:
    db_type: sql
    search: true 
  mod_vcard_xupdate: {}
  mod_avatar: {}
  mod_version: {}
  mod_stream_mgmt:
    max_ack_queue: infinity
    resume_timeout: 120
    resend_on_timeout: true
    max_resume_timeout: 120
  mod_s2s_dialback: {}
  mod_http_api: {}
allow_contrib_modules: true
```
------------------------------
Plz Help 👍 

If there's error in my config, please tell me. thanks in advance

Problem: 
I think memory problem

```
2019-01-22 19:58:46 =ERROR REPORT====
** Generic server memsup terminating 
** Last message in was {'EXIT',<0.3538.0>,{port_died,normal}}
** When Server state == [{data,[{"Timeout",60000}]},{items,{"Memory Usage",[{"Allocated",1564233728},{"Total",16333664256}]}},{items,{"Worst Memory User",[{"Pid",<0.19132.0>},{"Memory",13089988}]}}]
```

see error.log and crash.log
https://gist.github.com/gylraj/ec7b8f433dd6e9041d18a584a28c57f0
