### ISSUE TITLE
ReST API - command "status" gives error in logs

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#2783]
Command "status" executed via ReST API always gives error in logs:
```
2019-01-30 09:14:03.602 [error] <0.17438.10>@mod_http_api:handle:305
 REST API Error: exit:
 {attribute_not_found,status,[]} [
  {mod_http_api,get_elem_delete,3,[{file,"src/mod_http_api.erl"},{line,338}]},
  {mod_http_api,'-format_args/2-fun-0-',2,[{file,"src/mod_http_api.erl"},{line,347}]},
  {lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
  {mod_http_api,format_args,2,[{file,"src/mod_http_api.erl"},{line,343}]},
  {mod_http_api,handle2,4,[{file,"src/mod_http_api.erl"},{line,318}]},
  {mod_http_api,handle,4,[{file,"src/mod_http_api.erl"},{line,277}]},
  {mod_http_api,perform_call,4,[{file,"src/mod_http_api.erl"},{line,234}]},
  {mod_http_api,process,2,[{file,"src/mod_http_api.erl"},{line,188}]}]
```
Command response is okay, just gives unnecessary error entry in logs.

**Comment by badlop** [comment]
> Command "status" executed via ReST API always gives error in logs:

**Executed** with what call?

It works correctly for me with this client:
```
<?php
$url='localhost:5282/api/status/';
$login="key";
$password='secret';
$request=null;
$info=array(
           );
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($info));
$output=curl_exec($ch);
curl_close($ch);
print_r($output);
?>
```

**Comment by beherit** [comment]
Something like that :) Call is executing correctly and I have correctly response but in logs I see errors.

**Comment by badlop** [comment]
I can't reproduce the problem. If you don't provide more details, it can't be solved. ejabberd version, how you installed, configuration file, and how to reproduce the problem (example client).

**Comment by beherit** [comment]
I have ejabberd 12.18 installed from jabber.at repository. ReST API configuration:
```
commands_admin_access: rest_api
commands:
  - add_commands:
    - change_password
    - check_account
    - check_password
    - get_presence
    - get_vcard
    - get_vcard2
    - incoming_s2s_number
    - kick_user
    - outgoing_s2s_number
    - private_get
    - private_set
    - register
    - send_message
    - set_last
    - stats
    - status
    - unban_ip
    - unregister

listen:
  - ip: "127.0.0.1"
    port: 5443
    module: ejabberd_http
    captcha: true
    web_admin: true
    request_handlers:
      "api": mod_http_api
      "bosh": mod_bosh
      "upload": mod_http_upload
      "ws": ejabberd_http_ws
```
Port 5443 is hidden behind nginx reverse proxy.

Example code in PHP where I execute "status" command:
```
function get_restapi_data($command, $arguments = array()) {
	$args = array(
		'headers' => array(
			'Authorization' => 'Basic '.base64_encode(get_option('xmpp_stats_login').':'.get_option('xmpp_stats_password')),
			'X-Admin' => 'true'
		),
		'body' => json_encode($arguments),
		'timeout' => get_option('xmpp_stats_rest_timeout', 5),
		'redirection' => 0,
		'httpversion' => '1.1',
		'sslverify' => apply_filters('xmpp_stats_sslverify', true)
	);
	$rest_url = get_option('xmpp_stats_rest_url');
	$response = wp_remote_post($rest_url.'/'.$command, $args);
	if(is_wp_error($response)) {
		return;
	}
	else if($response['response']['code'] == 200) {
		return $response['body'];
	}
	//Unexpected error
	return;
}
echo get_restapi_data('status');
```
