### ISSUE TITLE
Error: conflict (external authentication method)

### ISSUE THREAD

**Issue by codekidX** [processone/ejabberd#2785]
**Erlang version:**

`Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]`

**Ejabberd version**

`18.12.1`

I am running **ejabberd from docker** with `ejabberd/ecs` image.

To change the `ejabberd.yml` with my custom config I have used as shown below:

```yaml
hosts:
  - "**mydomain.com**"

#Logging
# loglevel: 0 to 5
loglevel: 5
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 2
log_rate_limit: 100

#authentication
auth_method: external
extauth_program: "/home/ejabberd/ejbauth"
extauth_instances: 3

#database
new_sql_schema: true
sql_type: mysql
sql_server: "**host_ip**"
sql_port: 3306
sql_database: "db"
sql_username: "db"
sql_password: "passw0rd"
```
The rest of the config is same as default `ejabberd.yml` except the path to ssl/tls certs.

> **EDIT**: docker-compose file is as shown below:

```yaml
version: "3" #this is the docker compose version and not the file version
services:
  ejabberd-ext-test:
    container_name: ejabberd-ext-test
    image: "ejabberd/ecs"
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml
      - ./ejbauth:/home/ejabberd/ejbauth
      - ./extauth.log:/home/ejabberd/extauth.log
    ports:
      - "6222:6222"
      - "6269:6269"
      - "6443:6433"
      - "6280:6280"
    tty: true
    stdin_open: true
```

The `/home/ejabberd/ejbauth` is linux executable binary from a dummy (just for test) go script as shown below:

```go
package main

import (
	"bufio"
	"encoding/binary"
	"os"
)

func main() {
	bioIn := bufio.NewReader(os.Stdin)
	bioOut := bufio.NewWriter(os.Stdout)

	// success := true
	var length uint16
	// var result uint16

	for {
		_ = binary.Read(bioIn, binary.BigEndian, &length)
		// buf := make([]byte, length)
		// r, err := bioIn.Read(buf)

		length = 2
		binary.Write(bioOut, binary.BigEndian, &length)
		result := 1
		

		binary.Write(bioOut, binary.BigEndian, &result)
		bioOut.Flush()
	}
}
```
on executing:

`ejabberdctl register ashhadmin mydomain.com passw0rd`

I get error:

`Error: conflict`

and on ejabberd.log:

```log
ejabberd-ext-test    | 09:30:49.346 [debug] Command 'register' execution allowed by rule 'console commands' (CallerInfo=#{caller_module => ejabberd_ctl})
ejabberd-ext-test    | 09:30:49.346 [debug] Executing command ejabberd_admin:register with Args=[<<"ashhadmin">>,<<"mydomain.com">>,<<"passw0rd">>]
ejabberd-ext-test    | 09:30:49.348 [debug] Received response from external authentication program: [0,1]
ejabberd-ext-test    | 09:30:49.348 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.348 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.348 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.348 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.348 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.348 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.349 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.349 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.349 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.349 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.349 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.349 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.349 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.349 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.352 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.352 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.352 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
ejabberd-ext-test    | 09:30:49.352 [warning] Unexpected info: {#Port<0.25>,{data,[0,1]}}
```

It would be really helpful if anyone can point me in the right direction and guide me with this issue. Thanks.
