### ISSUE TITLE
Bosh: Session restart has no effect - protocol violated with empty response

### ISSUE THREAD

**Issue by mercuriev** [processone/ejabberd#2791]
I can't establish a XMPP stream over BOSH session.

ejabberd 18.12.1 with config:

```yml
listen:
  -
    port: 5222
    module: ejabberd_c2s
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5280
    module: ejabberd_http
    http_bind: true

modules:
  # ... defaults

hosts:
  - "localhost"
  - "sub.localhost"
  
append_host_config:
  "sub.localhost":
    modules:
      mod_bosh:
        # never log off bots
        max_inactivity: 3153600000
      mod_register: {}
```

Following XEP-0206 I send:

### Session Creation Request

```xml
<body xmlns="http://jabber.org/protocol/httpbind" to="sub.localhost" wait="2" hold="1" rid="15835999"/>
```
```xml
<body authid='8641417727693459555' xmlns='http://jabber.org/protocol/httpbind' sid='19736781e2943334033297fa41473d9e3ce6cc14' wait='2' ver='1.11'  inactivity='3153600000' hold='1' xmpp:restartlogic='true' requests='2' secure='true' maxpause='120' xmlns:xmpp='urn:xmpp:xbosh' xmlns:stream='http://etherx.jabber.org/streams' from='sub.localhost'/>
```
Note absense of `<stream:features/>`, it is not sent on any subsequent requests as well.

### Authentication

```xml
<body xmlns="http://jabber.org/protocol/httpbind" sid="19736781e2943334033297fa41473d9e3ce6cc14" rid="15836000"><auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">AHBocHVuaXQAcGhwdW5pdA==</auth></body>
```
```xml
<body xmlns='http://jabber.org/protocol/httpbind'><success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/></body>
```

### Stream restart (restart logic supported in first reply)

```xml
<body xmlns="http://jabber.org/protocol/httpbind" restart="true" xmpp="urm:xmpp:xbosh" to="sub.localhost" sid="19736781e2943334033297fa41473d9e3ce6cc14" rid="15836001"/>
```
```xml
<body xmlns='http://jabber.org/protocol/httpbind'/>
```

Now, **what does empty response mean here** ? `<stream:features/>` are not sent as well.

### Bind request = empty reply

```xml
<body xmlns="http://jabber.org/protocol/httpbind" sid="19736781e2943334033297fa41473d9e3ce6cc14" rid="15836003"><iq xmlns="jabber:client" id="1549698973" type="set"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>bot</resource></bind></iq></body>
```
```xml
<body authid='2014332781703433001' xmlns='http://jabber.org/protocol/httpbind'/>
```

_Why connection manager fails to open a stream?_
_Is it configuration issue or a bug?_
