### ISSUE TITLE
Deny server doesn't block groupchat messages

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#2808]
19.02 HEAD

Having issues with the Matrix.org bridging (Ref: https://github.com/siacs/Conversations/issues/3392 ) I've decided (before seeing the whole stanza) that the solution is to block the whole server.

So I've added:
```
acl:
  ...
  blocked_servers:
    server:
      - "bridge.xmpp.matrix.org"

access_rules:
  ...
  s2s:
    - deny: blocked_servers
    - allow
  s2s_access: s2s
```
...and thought I was done... But the messages kept coming.

The stanza logs look like this: https://gist.github.com/9d2601e0acefe836582aa73528f1d785

So based on that I've extended the blocking part:
```
acl:
  ...
  blocked_servers:
    server:
      - "bridge.xmpp.matrix.org"
  blocked:
    user:
      - "#matrix#matrix.org@bridge.xmpp.matrix.org"

access_rules:
  ...
  c2s:
    - deny: blocked
    - allow
  s2s:
    - deny: blocked_servers
    - allow
  s2s_access: s2s
```
...by specifying the whole user, and looks like that did it.

But, why didn't it block the whole server in my first try?

**Comment by zinid** [comment]
I think `s2s_access` is a top level option, no?

**Comment by licaon-kter** [comment]
Of course, plain user error, the docs had it right (not sure where I saw it wrong), didn't notice the level.

Thanks

**Comment by licaon-kter** [comment]
And still getting messages with:
```
acl:
  blocked:
    user:
      - "#matrix#matrix.org@bridge.xmpp.matrix.org"

access_rules:
  c2s:
    - deny: blocked
    - allow
```

**Comment by weiss** [comment]
Yes, this is s2s traffic which won't be affected by c2s rules.  Something like this works for me:

```yaml
s2s_access: s2s

acl:
  blocked:
    server:
      - "bridge.xmpp.matrix.org"

access_rules:
  s2s:
    - deny: blocked
    - allow
```
