### ISSUE TITLE
empty user list in web admin page when using AD

### ISSUE THREAD

**Issue by AlexGerasymenko** [processone/ejabberd#281]
Hi,

we have ejabberd 14.07 setuped with AD support. Users could login normally as expected via xmpp client though web admin page shows empty list. Logged in (online) users are shown in web admin page. Here is a sample of host_config part
```
host_config:
  "domain.com":
     auth_method: ldap
     ldap_servers:
       - "192.168.0.1"
     ldap_port: 389
     ldap_rootdn: "cn=********,ou=SE-ServiceAccount,dc=*******,dc=priv"
     ldap_password: "************"
     ldap_base: "dc=**********,dc=priv"
     ldap_uids:
       "sAMAccountName":
             - "%u"
     ldap_filter: "(&(userPrincipalName=%u@domain.com)(memberOf=CN=**************,OU=**********,OU=**********,DC=***********,DC=priv))"
```
Error.log message:
```
2014-08-19 10:45:55.256 [error] <0.14982.0> CRASH REPORT Process 'eldap_#Ref<0.0.3.57252>' with 2 neighbours exited with reason: no match of right hand value {error,{asn1,{function_clause,[{'ELDAPv3',enc_SubstringFilter_substrings_components,[{'SubstringFilter_substrings',[{final,<<"@domain.com">>}]},[],0],[{file,"src/ELDAPv3.erl"},{line,1768}]},{'ELDAPv3',enc_SubstringFilter_substrings,2,[{file,"src/ELDAPv3.erl"},{line,1765}]},{'ELDAPv3',enc_SubstringFilter,2,[{file,"src/ELDAPv3.erl"},{line,1753}]},{'ELDAPv3',enc_Filter,2,[{file,"src/ELDAPv3.erl"},{line,1604}]},{'ELDAPv3',enc_Filter_and_components,3,[{file,"src/ELDAPv3.erl"},{line,1636}]},...]}}} in eldap:send_command/3 line 831 in gen_fsm:terminate/7 line 622
2014-08-19 10:45:55.257 [error] <0.13524.0> Supervisor ejabberd_sup had child 'ejabberd_auth_ldap_domain.com' started with ejabberd_auth_ldap:start_link(<<"domain.com">>) at <0.14981.0> exit with reason no match of right hand value {error,{asn1,{function_clause,[{'ELDAPv3',enc_SubstringFilter_substrings_components,[{'SubstringFilter_substrings',[{final,<<"@domain.com">>}]},[],0],[{file,"src/ELDAPv3.erl"},{line,1768}]},{'ELDAPv3',enc_SubstringFilter_substrings,2,[{file,"src/ELDAPv3.erl"},{line,1765}]},{'ELDAPv3',enc_SubstringFilter,2,[{file,"src/ELDAPv3.erl"},{line,1753}]},{'ELDAPv3',enc_Filter,2,[{file,"src/ELDAPv3.erl"},{line,1604}]},{'ELDAPv3',enc_Filter_and_components,3,[{file,"src/ELDAPv3.erl"},{line,1636}]},...]}}} in eldap:send_command/3 line 831 in context child_terminated
```
