### ISSUE TITLE
error in mod_http_upload_quota leads to shutdown

### ISSUE THREAD

**Issue by joudinet** [processone/ejabberd#2810]
I've modified mod_http_upload{,_quota} configurations to delete uploaded files after 30 days instead of when users are unregistered. See the diff of my changes:
```
--- a/ejabberd.yml
+++ b/ejabberd.yml
@@ -164,6 +164,9 @@ modules:
     access: all
     docroot: 'UPLOAD_ROOT'
     put_url: 'PUT_URL'
+    rm_on_unregister: false
+  mod_http_upload_quota:
+    max_days: 30
   mod_last: {}
   mod_mam:
     ## Mnesia is limited to 2GB, better to use an SQL backend
```

After restarting ejabberd, everything seems to work perfectly but, few hours later, ejabberd stops with the following error:
```
# cat /var/log/ejabberd/error.log 
2019-03-01 15:32:42.527 [error] <0.2021.0>@mod_http_upload_quota:handle_info:214 Got unexpected info: {'EXIT',<0.581.0>,shutdown}
```

Any idea what happens?

I'm using ejabberd 18.09 but I see no changes to `mod_http_upload_quota.erl` on more recent versions.

**Comment by licaon-kter** [comment]
I have the same 30, no issues.

What else made you think that this is the issue?

**Comment by joudinet** [comment]
Do you also have the same error message on the log?

Have you also the `rm_on_unregister: false` option on `mod_http_upload`?

To be honest, I'm not sure it is the reason of the issue. I just know it is the last modification I've done.
As soon as someone told me she couldn't connect from her chat client, I log in on the server and find out ejabberd was not running anymore. The last line of `ejabberd.log` was this error message.

Since then, I've restarted ejabberd and it is still up after one hour. I'll tell you if ejabberd stops again.

**Comment by licaon-kter** [comment]
What does `error.log` say?

No, I don't have the other option though.

**Comment by joudinet** [comment]
The `error.log` content:
```
# cat /var/log/ejabberd/error.log 
2019-03-04 11:27:24.868 [error] <0.580.0>@mod_http_upload_quota:handle_info:214 Got unexpected info: {'EXIT',<0.581.0>,shutdown}
```

What do you mean by letting ejabberd handle http_upload?
I do have an nginx server that proxies the XEP-0363 requests to ejabberd. So, I would answer yes, I let ejabberd handle the http_upload service, even though I have an nginx proxy. Here the corresponding nginx configuration, in case it is relevant:
```
# Forward XEP-0363 requests to the XMPP server's HTTP listener.
location ^~ /upload {
        proxy_pass       https://127.0.0.1:5443/upload;
        proxy_set_header Host           $host;
        proxy_set_header X-Real-IP      $remote_addr;
        proxy_buffering  off;
        tcp_nodelay      on;
        client_max_body_size 0;
}
```

Let me rephrase my issue: without activating mod_http_upload_quota, the http upload service works well. As soon as I activate mod_http_upload_quota to delete files after 30 days, ejabberd works for a few hours then stops and the only error in the error.log is the one related to `mod_upload_quota:handle_info`

**Comment by licaon-kter** [comment]
External app, nginx but not proxy say via https://github.com/weiss/ngx_http_upload

**Comment by joudinet** [comment]
I see. So no, I'm not using an external app to handle http upload.
I'm using mod_http_upload configured as a request_handler of ejabberd_http module:
```
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
    web_admin: true
    captcha: true
    tls: true
```
Does mod_http_upload_quota requires to use an external app for http upload? When I read the documentation, I understand on the contrary, that mod_http_upload_quota extends mod_http_upload:
`This module adds quota support for mod_http_upload.`
