### ISSUE TITLE
Configuration problem: Option: db_type

### ISSUE THREAD

**Issue by rufa11** [processone/ejabberd#2819]
Hello,
I'm using ejabberd 18.12.1-2 version on Ubuntu 18.04 and trying to use vCards in LDAP  as mentioned id ehjaberd documentation, my config:
```
modules: 
  mod_adhoc: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  ## mod_echo: {}
  mod_irc: {}
  mod_http_bind: {}
  ## mod_http_fileserver:
  ##   docroot: "/var/www"
  ##   accesslog: "/var/log/ejabberd/access.log"
  mod_last: {}
  mod_muc: 
    ## host: "conference.@HOST@"
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
  mod_muc_log: {}
  mod_offline: 
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  ## mod_pres_counter:
  ##   count: 5
  ##   interval: 60
  mod_privacy: {}
  mod_private: {}
  ## mod_proxy65: {}
  mod_pubsub: 
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    plugins: 
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
  mod_register: 
    ##
    ## Protect In-Band account registrations with CAPTCHA.
    ##
    ## captcha_protected: true

    ##
    ## Set the minimum informational entropy for passwords.
    ##
    ## password_strength: 32

    ##
    ## After successful registration, the user receives
    ## a message with this subject and body.
    ##
    welcome_message: 
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.

    ##
    ## When a user registers, send a notification to
    ## these XMPP accounts.
    ##
    ## registration_watchers:
    ##   - "admin1@example.org"

    ##
    ## Only clients in the server machine can register accounts
    ##
    ip_access: trusted_network

    ##
    ## Local c2s or remote s2s users cannot register accounts
    ##
    ## access_from: deny

    access: register
  mod_roster: {}
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard:
    db_type: ldap 
  ldap_vcard_map:
     "NICKNAME": {"%u": ["cn"]}
     "GIVEN": {"%s": ["givenName"]}
     "MIDDLE": {"%s": ["initials"]}
     "FAMILY": {"%s": ["sn"]}
     "FN": {"%s": ["cn"]}
     "EMAIL": {"%s": ["mail"]}
     "ORGNAME": {"%s": ["company"]}
     "ORGUNIT": {"%s": ["department"]}
     "CTRY": {"%s": ["c"]}
     "LOCALITY": {"%s": ["l"]}
     "STREET": {"%s": ["streetAddress"]}
     "REGION": {"%s": ["st"]}
     "PCODE": {"%s": ["postalCode"]}
     "TITLE": {"%s": ["title"]}
     "URL": {"%s": ["wWWHomePage"]}
     "DESC": {"%s": ["description"]}
     "PHOTO": {"%s": ["jpegPhoto"]}
  ldap_search_fields:
     "User": "%u"
     "Name": "givenName"
     "Family Name": "sn"
     "Email": "mail"
     "Company": "company"
     "Department": "department"
     "Role": "title"
     "Description": "description"
     "Phone": "telephoneNumber"
  ldap_search_reported:
     "Full Name": "FN"
     "Nickname": "NICKNAME"
     "Email": "EMAIL"
  mod_version: {}



```

But i'm getting this error:
```
Application mnesia started on node ejabberd@localhost
12:51:31.116 [info] Configuration problem:
** Option: db_type
** Invalid value: ldap
** Using as fallback: mnesia
12:51:31.127 [info] LDAP connection on freeipa.example.com:389
12:51:31.127 [info] LDAP connection on freeipa.example.com:389
12:51:31.141 [info] FQDN used to check DIGEST-MD5 SASL authentication: ejabberd
12:51:31.149 [info] Application p1_iconv started on node ejabberd@localhost
12:51:31.165 [info] Configuration problem:
** Option: db_type
** Invalid value: ldap
** Using as fallback: mnesia
12:51:31.172 [critical] Problem starting the module ldap_vcard_map for host <<"example.com">> 
 options: [{<<"NICKNAME">>,[{<<"%u">>,[<<"cn">>]}]},
           {<<"GIVEN">>,[{<<"%s">>,[<<"givenName">>]}]},
           {<<"MIDDLE">>,[{<<"%s">>,[<<"initials">>]}]},
           {<<"FAMILY">>,[{<<"%s">>,[<<"sn">>]}]},
           {<<"FN">>,[{<<"%s">>,[<<"cn">>]}]},
           {<<"EMAIL">>,[{<<"%s">>,[<<"mail">>]}]},
           {<<"ORGNAME">>,[{<<"%s">>,[<<"company">>]}]},
           {<<"ORGUNIT">>,[{<<"%s">>,[<<"department">>]}]},
           {<<"CTRY">>,[{<<"%s">>,[<<"c">>]}]},
           {<<"LOCALITY">>,[{<<"%s">>,[<<"l">>]}]},
           {<<"STREET">>,[{<<"%s">>,[<<"streetAddress">>]}]},
           {<<"REGION">>,[{<<"%s">>,[<<"st">>]}]},
           {<<"PCODE">>,[{<<"%s">>,[<<"postalCode">>]}]},
           {<<"TITLE">>,[{<<"%s">>,[<<"title">>]}]},
           {<<"URL">>,[{<<"%s">>,[<<"wWWHomePage">>]}]},
           {<<"DESC">>,[{<<"%s">>,[<<"description">>]}]},
           {<<"PHOTO">>,[{<<"%s">>,[<<"jpegPhoto">>]}]}]
 error: undef
[{ldap_vcard_map,start,
                 [<<"server.mila.quebec">>,
                  [{<<"NICKNAME">>,[{<<"%u">>,[<<"cn">>]}]},
                   {<<"GIVEN">>,[{<<"%s">>,[<<"givenName">>]}]},
                   {<<"MIDDLE">>,[{<<"%s">>,[<<"initials">>]}]},
                   {<<"FAMILY">>,[{<<"%s">>,[<<"sn">>]}]},
                   {<<"FN">>,[{<<"%s">>,[<<"cn">>]}]},
                   {<<"EMAIL">>,[{<<"%s">>,[<<"mail">>]}]},
                   {<<"ORGNAME">>,[{<<"%s">>,[<<"company">>]}]},
                   {<<"ORGUNIT">>,[{<<"%s">>,[<<"department">>]}]},
                   {<<"CTRY">>,[{<<"%s">>,[<<"c">>]}]},
                   {<<"LOCALITY">>,[{<<"%s">>,[<<"l">>]}]},
                   {<<"STREET">>,[{<<"%s">>,[<<"streetAddress">>]}]},
                   {<<"REGION">>,[{<<"%s">>,[<<"st">>]}]},
                   {<<"PCODE">>,[{<<"%s">>,[<<"postalCode">>]}]},
                   {<<"TITLE">>,[{<<"%s">>,[<<"title">>]}]},
                   {<<"URL">>,[{<<"%s">>,[<<"wWWHomePage">>]}]},
                   {<<"DESC">>,[{<<"%s">>,[<<"description">>]}]},
                   {<<"PHOTO">>,[{<<"%s">>,[<<"jpegPhoto">>]}]}]],
                 []},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,82}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1323}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,67}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,269}]}]
12:51:31.172 [critical] ejabberd initialization was aborted because a module start failed.

Crash dump was written to: /var/log/ejabberd/erl_crash_20190308-125128.dump
Problem starting the module ldap_vcard_map for host <<"server.mila.quebec">> 
 options: [{<<"NICKNAME">>,[{<<"%u">>,[<<"cn">>]}]},
           {<<"GIVEN">>,[{<<"%s">>,[<<"givenName">>]}]},
```
Can someone help please !
