### ISSUE TITLE
Importing picture from LDAP using ldap_vcard_map

### ISSUE THREAD

**Issue by rufa11** [processone/ejabberd#2823]
Hello,
I'm trying to import picture to Empathy user profile using ejabberd connected to LDAP but the picture is not imported, below the config:
```
mod_vcard:
     search: false
mod_vcard_ldap:
    search: true
    matches: 10
    ldap_uids: {"uid": "%u"}
##    db_type: ldap
    ldap_rootdn: "uid=ejabberd,cn=sysaccounts,cn=etc,dc=example,dc=com"
    ldap_password: "abc.123"
    ldap_base: "dc=example,dc=com"
##    ldap_uids:{"uid"}
    ldap_vcard_map:
      "NICKNAME": {"%u": ["cn"]}
      "GIVEN": {"%s": ["givenName"]}
      "MIDDLE": {"%s": ["initials"]}
      "FAMILY": {"%s": ["sn"]}
      "FN": {"%s": ["cn"]}
      "EMAIL": {"%s": ["mail"]}
      "ORGNAME": {"%s": ["company"]}
      "ORGUNIT": {"%s": ["department"]}
      "CTRY": {"%s": ["c"]}
      "LOCALITY": {"%s": ["l"]}
      "STREET": {"%s": ["streetAddress"]}
      "REGION": {"%s": ["st"]}
      "PCODE": {"%s": ["postalCode"]}
       "TITLE": {"%s": ["title"]}
      "URL": {"%s": ["wWWHomePage"]}
      "DESC": {"%s": ["description"]}
      "PHOTO": {"%s": ["jpegPhoto"]}
ldap_search_fields:
      "User": "%u"
      "Name": "givenName"
      "Family Name": "sn"
      "Email": "mail"
      "Company": "company"
      "Department": "department"
      "Role": "title"
      "Description": "description"
      "Phone": "telephoneNumber"
ldap_search_reported:
      "Full Name": "FN"
      "Nickname": "NICKNAME"
      "Email": "EMAIL"
```
Can someone help please!
