### ISSUE TITLE
Hook c2s_self_presence crashed when running mod_pubsub:on_self_presence

### ISSUE THREAD

**Issue by orlydonx** [processone/ejabberd#2824]
We have installed ejabberd 18.12.1. 
We are getting this always log in the error log.
We have implemented muc pub/sub in in our application using xmppframework for ios and smack for android.
We are clueless what seems to be wrong or what to at least consider in our ejabberd or mysql configurations.
Your kind reply is very much appreciated.
Many thanks!

**Here is the log info:**
```
2019-03-12 05:12:36.143 [error] <0.17423.0>@ejabberd_hooks:safe_apply:384 Hook c2s_self_presence crashed when running mod_pubsub:on_self_presence/1:
** Reason = 
{error,{badmatch,{error,implementation_faulty}},
       [{mod_pubsub,get_subscriptions_for_send_last,6,
                    [{file,"src/mod_pubsub.erl"},{line,2446}]},
        {mod_pubsub,'-send_last_items/1-fun-1-',6,
                    [{file,"src/mod_pubsub.erl"},{line,2956}]},
        {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
        {mod_pubsub,on_self_presence,1,
                    [{file,"src/mod_pubsub.erl"},{line,586}]},
        {ejabberd_hooks,safe_apply,4,
                        [{file,"src/ejabberd_hooks.erl"},{line,381}]},
        {ejabberd_hooks,run_fold1,4,
                        [{file,"src/ejabberd_hooks.erl"},{line,365}]},
        {ejabberd_c2s,process_self_presence,2,
                      [{file,"src/ejabberd_c2s.erl"},{line,724}]},
        {xmpp_stream_in,process_authenticated_packet,2,
                        [{file,"src/xmpp_stream_in.erl"},{line,656}]}]}
** Arguments = [{{presence,<<"H9CYz-31">>,available,<<"en">>,{jid,<<"96550407651">>,<<"chat.chatterx.com">>,<<"22BC06EEC5031F34_AND">>,<<"96550407651">>,<<"chat.chatterx.com">>,<<"22BC06EEC5031F34_AND">>},{jid,<<"96550407651">>,<<"chat.chatterx.com">>,<<>>,<<"96550407651">>,<<"chat.chatterx.com">>,<<>>},undefined,[],undefined,[{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"hash">>,<<"sha-1">>},{<<"node">>,<<"http://www.igniterealtime.org/projects/smack">>},{<<"ver">>,<<"NBoGUcJ1ljgBE8BFGCMFmGIhHq4=">>}],[]}],#{ip => {0,0,0,0,0,65535,44063,10867}}},#{tls_required => false,sid => {{1552,367484,203748},<0.17423.0>},tls_options => [compression_none],stream_restarted => true,stream_header_sent => true,mgmt_stanzas_out => 10,ip => {{0,0,0,0,0,65535,44063,10867},40708},mgmt_ack_timer => #Ref<0.2279749327.1212153857.157757>,stream_state => established,conn => c2s,csi_state => active,mgmt_max_queue => infinity,resource => <<"22BC06EEC5031F34_AND">>,stream_timeout => infinity,mgmt_xmlns => <<"urn:xmpp:sm:3">>,socket => {socket_state,gen_tcp,#Port<0.7301>,262144,#Ref<0.2279749327.1212284929.145142>,{state,50000,50000,50000,1552367499868111},none},mod => ejabberd_c2s,lserver => <<"chat.chatterx.com">>,mgmt_timeout => 30,stream_compressed => false,tls_enabled => false,tls_verify => false,stream_version => {1,0},mgmt_stanzas_in => 13,mgmt_state => active,server => <<"chat.chatterx.com">>,xmlns => <<"jabber:client">>,stream_id => <<"5522866912661709167">>,mgmt_stanzas_req => 10,mgmt_resend => true,access => c2s,mgmt_ack_timeout => 60000,auth_module => ejabberd_auth_sql,stream_authenticated => true,stream_encrypted => false,owner => <0.17423.0>,shaper => c2s_shaper,mgmt_queue_type => ram,mgmt_queue => {{[],[{10,{1552,367499,652395},{iq,<<"H9CYz-28">>,result,<<"en">>,{jid,<<>>,<<"upload.chat.chatterx.com">>,<<>>,<<>>,<<"upload.chat.chatterx.com">>,<<>>},{jid,<<"96550407651">>,<<"chat.chatterx.com">>,<<"22BC06EEC5031F34_AND">>,<<"96550407651">>,<<"chat.chatterx.com">>,<<"22BC06EEC5031F34_AND">>},[{disco_info,<<>>,[{identity,<<"store">>,<<"file">>,<<>>,<<"HTTP File Upload">>}],[<<"urn:xmpp:http:upload">>,<<"urn:xmpp:http:upload:0">>,<<"eu:siacs:conversations:http:upload">>,<<"http://jabber.org/protocol/disco#info">>,<<"http://jabber.org/protocol/disco#items">>],[{xdata,result,[],undefined,undefined,[],[{xdata_field,<<>>,hidden,<<"FORM_TYPE">>,false,<<>>,[<<"urn:xmpp:http:upload">>],[],[]},{xdata_field,<<"Maximum file size">>,'text-single',<<"max-file-size">>,false,<<>>,[<<"104857600">>],[],[]}]},{xdata,result,[],undefined,undefined,[],[{xdata_field,<<>>,hidden,<<"FORM_TYPE">>,false,<<>>,[<<"urn:xmpp:http:upload:0">>],[],[]},{xdata_field,<<"Maximum file size">>,'text-single',<<"max-file-size">>,false,<<>>,[<<"104857600">>],[],[]}]},{xdata,result,[],undefined,undefined,[],[{xdata_field,<<>>,hidden,<<"FORM_TYPE">>,false,<<>>,[<<"http://jabber.org/network/serverinfo">>],[],[]}]}]}],#{ip => {0,0,0,0,0,65535,44063,10867}}}}]},1,unlimited},csi_queue => {0,#{}},socket_monitor => #Ref<0.2279749327.1212153857.145143>,zlib => false,pres_a => {1,{{<<"5c46ca6c3aa8d104610acc2e">>,<<"room.chat.chatterx.com">>,<<"96550407651">>},nil,nil}},user => <<"96550407651">>,stream_direction => in,codec_options => [ignore_els],...}}]
```

**Here is our configuration:**
```yaml
language: "en"
hosts:
  - "chat.chatterx.com"
  - "saucey.chatterx.com"
  - "testcluster.chatterx.com"

loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

certfiles:
  - "/opt/ejabberd-18.12.1/conf/server.pem"
##  - "/etc/letsencrypt/live/localhost/fullchain.pem"
##  - "/etc/letsencrypt/live/localhost/privkey.pem"

ca_file: "/opt/ejabberd-18.12.1/conf/cacert.pem"

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: false
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    web_admin: true
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    http_bind: true    
    captcha: false
  -
    port: 5282
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    web_admin: true
    tls: true
    captcha: false
    http_bind: true
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
    web_admin: true
    captcha: false
    tls: true

s2s_use_starttls: optional



auth_method: sql

# sm_db_type: sql

# default_db: sql

sql_type: mysql
sql_server: "172.31.32.89"
sql_database: "ejabberd"
sql_username: "root"
sql_password: "hive1234"

sql_pool_size: 10
sql_keepalive_interval: 28800

new_sql_schema: true

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
  admin:
    user:
      - "admin@chat.chatterx.com"
      - "admin@testcluster.chatterx.com"
      - "saucey@testcluster.chatterx.com"

access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who: all
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
    what:
      - "*"
      - "!stop"
      - "!start"

shaper:
  normal: 50000
  fast: 50000

# shaper:
#   normal: 1000
#   fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - infinity
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast

max_fsm_queue: 10000

use_cache: true
cache_size: 20000
cache_life_time: 3600

acme:
   contact: "mailto:admin@chat.chatterx.com"
   ca_url: "https://acme-v01.api.letsencrypt.org"

modules:
  mod_offline_post: {}
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
    db_type: sql
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: 
    db_type: sql
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  # mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: "https://@HOST@:5443/upload"
  mod_last:
    db_type: sql
  mod_mam:
    db_type: sql
    use_cache: true
    default: always
    request_activates_archiving: false
    assume_mam_usage: false
  mod_muc:
    db_type: sql
    host: "room.@HOST@"
    access:
      - allow: all
    access_admin: ## all
      - allow: admin
    access_create: all
         ## - allow ## muc_create
    access_persistent: all
         ## - allow 
    max_user_conferences: 3000000
    max_users: 10000
    max_users_admin_threshold: 1000
    default_room_options:
      persistent: true
      allow_subscription: true
      allow_query_users: true
      allow_private_messages: true
      allow_user_invites: true
      allow_visitor_nickchange: true
      anonymous: false
      captcha_protected: false
      mam: true
      members_by_default: true
      members_only: false
      public: true
      public_list: true
  mod_muc_admin: {}
  mod_offline:
    db_type: sql
    access_max_user_messages: max_user_offline_messages
  mod_ping:
    send_pings: true
    ping_interval: 5
    ping_ack_timeout: 5
    timeout_action: kill
  mod_privacy:
    db_type: sql
    use_cache: true
    cache_size: 20000
  mod_private:
    db_type: sql
    use_cache: true
    cache_size: 20000
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    db_type: sql
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    max_items_node: 100
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
    force_node_config:
      ## Avoid using OMEMO by default because it
      ## introduces a lot of hard-to-track problems
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      ## Avoid buggy clients to make their bookmarks public
      "storage:bookmarks":
        access_model: whitelist
        max_items: 100
      "urn:xmpp:bookmarks:0":
        access_model: whitelist
        max_items: 100
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    # ip_access: trusted_network
    access: register
  mod_roster:
    versioning: true
    use_cache: true
    cache_size: 20000
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    max_ack_queue: infinity
    resume_timeout: 30
    resend_on_timeout: true
    max_resume_timeout: 30
  mod_time: {}
  mod_vcard:
    db_type: sql
    search: true 
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8
```
