### ISSUE TITLE
REST API not respecting mod_register access rules

### ISSUE THREAD

**Issue by mightyBroccoli** [processone/ejabberd#2837]
Defined access rules within mod_register are not respected when registration is done through REST api, thus it is possible to register blocked usernames.

OS: Debian 9.8
Ejabberd: Debian Backports 18.12.1-2~bpo9+1

##### module config excerpt
```yaml
  mod_register:
    access: access_register
```
##### access rules excerpt
```yaml
   access_register:
     - deny: blocked
     - allow
```
##### acl excerpt
```yaml
  blocked:
    user:
      - "hostmaster"
      - "ejabberd"
```
