### ISSUE TITLE
BOSH module error: not started for external host

### ISSUE THREAD

**Issue by francoisjacquet** [processone/ejabberd#2851]
I can login to local accounts, but **cannot** login to an external account using a BOSH JS client and an ejabberd server.

An ejabberd version **18.12.1** server is up and running on Ubuntu 16.04.

ejabberd is properly configured to respond to BOSH requests over `https`. The `/http-bind/` URL is proxied by Apache to `:5280/bosh`:
```
listen:
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
       "/bosh": mod_bosh
    web_admin: true
    http_bind: true
    tls: true
```

When I want to login using an external Jabber domain account (say, `me@externaljabber.com`) using a BOSH client like [ConverseJS](http://conversejs.org/), the following error shows up in the `error.log`:

```
[error] <0.522.0>@ejabberd_bosh:check_bosh_module:972 You are trying to use BOSH (HTTP Bind) in host <<"externaljabber.com">>, but the module mod_bosh is not started in that host. Configure your BOSH client to connect to the correct host, or add your desired host to the configuration, or check your 'modules' section in your ejabberd configuration file.
```

The same steps _do work_ using the client at https://conversejs.org.
