### ISSUE TITLE
not able to fetch mam messages

### ISSUE THREAD

**Issue by sandeepjangir** [processone/ejabberd#2853]
Hi all,

Ejabberd version: 19
installed from: source code

I am trying to get the muc group chat mam messages but I always get no messages from iq type result;

but I can see the messages in my mysql database archive table;

this is my ejabberd configuration:

```
  mod_mam:
    db_type: sql
    default: always
  mod_muc:
    access:
    - allow
    access_admin:
    - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
    - allow
    host: "conference.@HOST@"
    history_size: 0
    default_room_options:
      mam: true
      allow_user_invites: true
      allow_change_subj: true
      allow_query_users: true
      allow_visitor_status: true
      presence_broadcast: [participant, moderator]
      max_users: 500
      members_by_default: true
      persistent: true
      allow_subscription: true
```

this is my disco info iq result log:

```
<iq to="me@mydomain.com" id="aaffa" type="result" from="helloworld@conference.mydomain.com/me" xml:lang="en">
<query xmlns="http://jabber.org/protocol/disco#info" node="">
<identity category="client" type="pc" name="Psi"/>
<feature var="http://jabber.org/protocol/ibb"/>
<feature var="http://jabber.org/protocol/activity"/>
<feature var="http://jabber.org/protocol/tune"/>
<feature var="urn:xmpp:avatar:data"/>
<feature var="http://jabber.org/protocol/xhtml-im"/>
<feature var="urn:xmpp:jingle:apps:rtp:audio"/>
<feature var="http://jabber.org/protocol/mood+notify"/>
<feature var="http://jabber.org/protocol/disco#info"/>
<feature var="http://jabber.org/protocol/sxe"/>
<feature var="urn:xmpp:avatar:metadata"/>
<feature var="http://jabber.org/protocol/commands"/>
<feature var="urn:xmpp:jingle:1"/>
<feature var="http://jabber.org/protocol/si/profile/file-transfer"/>
<feature var="jabber:x:data"/>
<feature var="urn:xmpp:bob"/>
<feature var="http://jabber.org/protocol/geoloc+notify"/>
<feature var="http://jabber.org/protocol/geoloc"/>
<feature var="urn:xmpp:receipts"/>
<feature var="http://jabber.org/protocol/chatstates"/>
<feature var="http://jabber.org/protocol/bytestreams"/>
<feature var="http://jabber.org/protocol/si"/>
<feature var="urn:xmpp:time"/>
<feature var="urn:xmpp:jingle:transports:ice-udp:1"/>
<feature var="jabber:iq:last"/>
<feature var="urn:xmpp:jingle:apps:rtp:1"/>
<feature var="http://jabber.org/protocol/tune+notify"/>
<feature var="urn:xmpp:avatar:metadata+notify"/>
<feature var="urn:xmpp:message-correct:0"/>
<feature var="http://jabber.org/protocol/muc"/>
<feature var="http://jabber.org/protocol/activity+notify"/>
<feature var="http://jabber.org/protocol/mood"/>
<feature var="http://jabber.org/protocol/rosterx"/>
<feature var="urn:xmpp:ping"/>
<feature var="http://www.w3.org/2000/svg"/>
<x xmlns="jabber:x:data" type="result">
<field var="FORM_TYPE" type="hidden">
<value>urn:xmpp:dataforms:softwareinfo</value>
</field>
<field var="software" type="text-single">
<value>Psi</value>
</field>
<field var="software_version" type="text-single">
<value>1.3-webkit</value>
</field>
<field var="os" type="text-single">
<value>macOS</value>
</field>
<field var="os_version" type="text-single">
<value/>
</field>
</x>
</query>
</iq>
```

I am trying to get the mam messages by this query iq:

```
<iq type='set' id='juliet1'>
  <query xmlns='urn:xmpp:mam:2' queryid='f27' />
</iq>
```

But this always returns zero messages but I can see the messages in the database table;

Let me know what I am missing here;

Thanks
