### ISSUE TITLE
Thumbnail is not created mod_http_upload

### ISSUE THREAD

**Issue by relbraun** [processone/ejabberd#2859]
I have a server Ubuntu 18.04
The latest version of ejabberd (I have installed it from the source code).
the ejabberd.yml of mod_http_upload:
```
mod_http_upload:
    put_url: "http://10.0.2.220:5443/upload"
   access: all
   thumbnail: true
   docroot: "/usr/local/etc/ejabberd/uploads"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
      "Access-Control-Allow-Headers": "content-type, Authorization"
```
When I try to upload a picture the file is being uploaded successfully but the thumbnail is not being created.  The erlang.log file writes this:
`
2019-04-14 11:26:39.029 [debug] <0.32669.0>@mod_http_upload:identify:906 Cannot identify type of /usr/local/etc/ejabberd/uploads/5a7ae6f858ee3cdc0f3ac00a579916a0eaa9172b/dqH1dqG6hyuOlVvR11mP0fZh9Ue9d6Yop1V0qxLS/WhatsApp_Image_2019-03-04_at_12.18.49.jpeg: Decoding error
`
The jpeg format is in the suppoterd_format() list.

any idea?
