### ISSUE TITLE
mod_muc:handle_info:340 unexpected info: {#Ref<0.2354930856.1946419201.58898>,false}

### ISSUE THREAD

**Issue by lemon2015** [processone/ejabberd#2880]
> > What version of ejabberd are you using?
> 
> 18.01
> 
> > What operating system (version) are you using?
> 
> Centos 7.3
> 
> > How did you install ejabberd (source, package, distribution)?
>
>  package
> 
> > What did not work as expected? Are there error messages in the log? What
> 
```
2019-05-05 15:36:17.287 [error] <0.720.0>@mod_muc:handle_info:340 unexpected info: {#Ref<0.2354930856.1946419201.51287>,false}
2019-05-05 15:36:17.288 [error] <0.720.0>@mod_muc:handle_info:340 unexpected info: {#Ref<0.2354930855.70778882.229404>,false}
```
> 
> > was the unexpected behavior? What was the expected result?

At that time, all of the users of online group chat could not send messages normally. It lasts about 1-3 minutes. I didn't see the scene client. so , can you give me some advise for it ?  I will go to the scene tomorrow. 
thanks.

>> this is  a part of my ejabberd.yml about mod_muc

```yaml
 mod_mam:
    iqdisc: one_queue
    db_type: sql
    default: always
    request_activates_archiving: false
    assume_mam_usage: false
    cache_size: 1000
    cache_life_time: 3600
  mod_muc:
    db_type: sql
    host: "conference.@HOST@"
    max_user_conferences: 50
    history_size: 20
    default_room_options:
      mam: true
      logging: true
      persistent: false
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
  mod_muc_admin: {}
  ## mod_muc_log: {}
```
