### ISSUE TITLE
HTTP Upload Module: "Non-unicode filename" warning

### ISSUE THREAD

**Issue by alexara** [processone/ejabberd#2897]
### Summary

If there's an umlaut like `ä,ü` in the uploaded file's name, ejabberd throws an error.

### General Information 
* Ejabberd 19.05
* Nginx
* Nginx HTTP Upload Perl Module

### Config
```
    module: ejabberd_http
    request_handlers:
      "/upload": mod_http_upload
    tls: false

  mod_http_upload:
    access: acsupload
    put_url: "https://@HOST@/upload"
    docroot: "/path/upload"
    external_secret: ""
```

### Warning in ejabberd log:
```
> 2019-05-30 14:57:29.523 [warning] <0.50.0> Non-unicode filename <<"KÃ_che.jpg">> ignored
```
