### ISSUE TITLE
Namespace delegation does not forward the IQ to the external component

### ISSUE THREAD

**Issue by AlexSoloviov** [processone/ejabberd#2904]
I try to configure the namespace delegation to the external component. Means that if I send the IQ with specific namespace I expect that this IQ will route to the external component.

I have configured Ejabberd server as described in the documentation 
In logs, I see that Ejabberd listens that namespace. 
Also, my external component successfully connected to the Ejabberd server
But when I send the IQ, I get the error like "No module is handling this query"
Could you please give me an example of the IQ which I should use or some extra recommendations.

**Configuration:**
```
mod_delegation:
    namespaces:
      "jabber:iq:jcp":
         filtering: []
         access: external_jcp

external_jcp:
    external_component: allow

external_component:
    server:
      - "jcp.example.com"

```
**Logs:**
```
[debug] Supervisor ejabberd_gen_mod_sup started gen_server:start_link({local,'mod_delegation_connect.example.com'}, mod_delegation, [<<"connect.example.com">>,[{namespaces,[{<<"jabber:iq:jcp">>,[],external_jcp}]}]], []) at pid <0.448.0>


[info] (tls|<0.2534.0>) Received XML on stream = <<"<iq from='222@alex-s.testhost.com/222-6636-2711-5611' to='connect.example.com' type='get' id='test_1558520861411'><query xmlns='jabber:iq:jcp'/></iq>">>


sub_els =
        [#xmlel{
             name = <<"query">>,
             attrs = [{<<"xmlns">>,<<"jabber:iq:jcp">>}],
             children = []},
         #stanza_error{
             type = cancel,code = 503,by = <<>>,
             reason = 'service-unavailable',
             text =
                 [#text{
                      lang = <<"en">>,
                      data = <<"No module is handling this query">>}],
             sub_els = []}],

```

**Comment by jsautret** [comment]
Do you confirm that your component is conform to the admin mode protocol described in XEP-0355: Namespace Delegation, specifically the chapter 7. Discovering Support? The component must respond to the specific disco iq in order to be recognized by the server.

**Comment by jsautret** [comment]
Also, if you are using the new access rule syntax (which is in access_rules: section instead of access:), then the syntax should be :
```
access_rules:
...
  external_jcp:
    - allow: external_component
```
