### ISSUE TITLE
ejabberd_xmlrpc broken since new configuration validator  

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#2915]
ejabberd_xmlrpc got broken in  https://github.com/processone/ejabberd/commit/a02cff0e780bb735531594c4ece81e8628f79782

---

The problem is easy to reproduce, no need for a XMLRPC client in fact. Set basic configuration:
```yaml
listen:
  -
    port: 4560
    module: ejabberd_xmlrpc
    access_commands: {}
```
Then visit http://127.0.0.1:4560/
Result: 404 Not Found
Expected: 400 Bad Request

---

One solution is to revert back a few lines that got removed without any replacement in:
https://github.com/processone/ejabberd/commit/a02cff0e780bb735531594c4ece81e8628f79782#diff-8ff682b2555f0ee460dbe3e0eab6504fL143

For example, this gets ejabberd_xmlrpc working again perfectly:
```diff
--- a/src/ejabberd_http.erl
+++ b/src/ejabberd_http.erl
@@ -124,7 +124,11 @@ init(SockMod, Socket, Opts) ->
 			     true -> {SockMod, Socket}
 			  end,
     SockPeer =  proplists:get_value(sock_peer_name, Opts, none),
-    RequestHandlers = proplists:get_value(request_handlers, Opts, []),
+    XMLRPC = case proplists:get_bool(xmlrpc, Opts) of
+		 true -> [{[], ejabberd_xmlrpc}];
+		 false -> []
+	     end,
+    RequestHandlers = proplists:get_value(request_handlers, Opts, []) ++ XMLRPC,
     ?DEBUG("S: ~p~n", [RequestHandlers]),
 
     DefaultHost = proplists:get_value(default_host, Opts),
```

**Comment by zinid** [comment]
I do not understand why ejabberd_xmlrpc can be configured both as a listening module and an http handler. This brings inconsistency to the configuration.

**Comment by mremond** [comment]
What can we do to make this consistent.

**Comment by zinid** [comment]
@mremond I just fixed the issue to keep backward compatibility with older configs.

**Comment by paradisaeidae** [comment]
Has been re-applied to block ejabberd_xmlrpc being used as a http handler?
I would like to use it on a port already in use for regular messages.

**Comment by badlop** [comment]
> Has been re-applied to block ejabberd_xmlrpc being used as a http handler?

I don't understand your question. I've just checked in ejabberd 19.09.1 that ejabberd_xmlrpc works perfectly regardless of how you configure it. Both ways work, in fact both can be enabled at the same time:

```yaml
listen:
  -
    port: 4560
    module: ejabberd_xmlrpc
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/ee-xmlrpc": ejabberd_xmlrpc
```
