### ISSUE TITLE
Duplicated option: host_config with new configuration validator

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#2916]
Before, this was ok:
```
host_config:
  "convorb.im":
    auth_method: sql
    auth_password_format: scram

host_config:
  "sip.convorb.im":
    auth_method: sql
    auth_password_format: plain
```
...now (c318b5f8a235d5c5d26146f2ec28a1bf0aba7b82) says `[critical] <0.105.0>@ejabberd_app:start:71 Failed to start ejabberd application: Configuration error: duplicated option: host_config`

Removing the second `host_config` fixed it
