### ISSUE TITLE
Invalid IPv4 address: `::` with new configuration validator

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#2917]
Before, this was ok:
```
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    starttls_required: true
    zlib: true
    max_stanza_size: 262144
    access: c2s
```
... now (https://github.com/processone/ejabberd/commit/c318b5f8a235d5c5d26146f2ec28a1bf0aba7b82) this yields: `[critical] <0.105.0>@ejabberd_app:start:71 Failed to start ejabberd application: Invalid value of option listen->ip: invalid IPv4 address: ::`

Removing `ip: "::"` fixes it.

**Comment by zinid** [comment]
The following config works for me:
```yaml
hosts:
  - localhost

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    starttls_required: true
    zlib: true
    max_stanza_size: 262144
    access: c2s
```
