### ISSUE TITLE
mod_mam is not storing messages -  built from sources

### ISSUE THREAD

**Issue by andrisole92** [processone/ejabberd#2922]
Hi there,

I have just built eJabberd from source and enabled MySQL. Everything is working fine, connected to the MySQL, but the messages are not stored.

Here is my config:
```
default_db: sql
...
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    #db_type: sql
    assume_mam_usage: true
    default: always
    compress_xml: true
```

And here are screenshots from the database ( you can see that archive_prefs are stored, but not messages)

<img width="537" alt="archive_prefs" src="https://user-images.githubusercontent.com/17086705/59979681-aec24880-95b8-11e9-9cb4-d65a81c9f48f.png">
<img width="366" alt="archive" src="https://user-images.githubusercontent.com/17086705/59979682-aec24880-95b8-11e9-90b8-ebe66cad501b.png">

In addition to that admin panel also not showing correct data:

<img width="521" alt="Screenshot 2019-06-23 at 13 13 45" src="https://user-images.githubusercontent.com/17086705/59979689-cef20780-95b8-11e9-9457-9e63bcd3b466.png">

Looking forward to hearing back and thanks for your help.
