### ISSUE TITLE
Access-control-allow-origin on register using strophe .

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#2923]
Hi ,
I just started working with ejabbred.  I am using Strophe as client side library .

I am getting this error continuously when i am registring "new user" .

![image](https://user-images.githubusercontent.com/16096109/60338324-3e099a80-99c3-11e9-8f67-8c1b23664e9c.png)

There is no "connected" status . I have tried the changing my ejabberd.yml file like this. 
```yaml
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
      "http-bind": true
      "upload": mod_http_upload
       custom_headers:
         "Access-Control-Allow-Origin": "*"
         "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"
         "Access-Control-Allow-Headers": "Authorization"
         "Access-Control-Allow-Credentials": "true".
```
and the same thing i have done below the line 
```yaml
mod_http_upload:
    put_url: "https://@HOST@:5443/upload"
```
still i am getting the same error again and again with no change. 
Please help as i have spent a lot of time over this.
Thanks in advance .

**Comment by zinid** [comment]
Can you please check the indentation is correct? `custom_headers` must be at the same level as `request_handlers`. From this posted snipped it's unclear.

**Comment by zinid** [comment]
Here is the correct config:
```yaml
listen:
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
      "/http-bind": mod_bosh
      "/upload": mod_http_upload
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"
      "Access-Control-Allow-Headers": "Authorization"
      "Access-Control-Allow-Credentials": "true"
```
