### ISSUE TITLE
ejabberd_router:is_my_route return false when I try to access the web admin

### ISSUE THREAD

**Issue by relbraun** [processone/ejabberd#2925]
I am using the newest version of ejabberd, cloned form git.
 the ```ejabberd.yml``` listen config is:
```
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
    web_admin: true
    captcha: false
    ciphers: CIPHERS_INTERMEDIATE
    protocol_options: PROTOCOL_OPTIONS_INTERMEDIATE
    tls: false
  -
    ip: "::"
    port: 5280
    tls: false
    module: ejabberd_http
    web_admin: true
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000
```
The log file contains only these lines:
```
2019-07-02 18:06:39.078 [debug] <0.2875.0>@ejabberd_http:init:128 S: []
2019-07-02 18:06:39.078 [info] <0.2712.0>@ejabberd_listener:accept:251 (<0.2875.0>) Accepted connection 10.0.2.102:63264 -> 10.0.2.220:5280
2019-07-02 18:06:39.081 [debug] <0.2875.0>@ejabberd_http:process_header:283 (#Port<0.94507>) http query: 'GET' <<"/admin">>
```
I get 400 error response with the text: "Host not served".
I found this snippet in the source code that it means the ```ejabberd_router:is_my_route``` function return false.

Any idea? Thanks.
