### ISSUE TITLE
Transports / ejabberd_service broken?

### ISSUE THREAD

**Issue by thundergreen** [processone/ejabberd#2929]
Dear all.

I just upgraded Ejabberd to 19.05 but get errors in configuration with my transport which were configured like this:
```
  - port: 5347
    ip: "0.0.0.0"
    module: ejabberd_service
    access: all
    shaper: fast
    hosts:
      "discord.emevth.no-ip.biz":
        password: "discord"
```
But it throw error below:

```
22:55:12.389 [critical] Failed to start ejabberd application: Exception occured during configuration processing. This is most likely due to faulty/incompatible validator in third-party code. If you are not running any third-party code, please report the bug with ejabberd configuration file attached and the following stacktrace included:
** exception error: no function clause matching
                  ejabberd_service:'-listen_opt_type/1-fun-3-'([{<<"discord.emevth.no-ip.biz">>,
                                                                 [{password,
                                                                   <<"discord">>}]}]) (src/ejabberd_service.erl, line 272)
   in function  yconf:validate_option/3 (src/yconf.erl, line 1108)
   in call from yconf:validate_options/8 (src/yconf.erl, line 1085)
   in call from lists:map/2 (lists.erl, line 1239)
   in call from lists:map/2 (lists.erl, line 1239)
   in call from yconf:'-list/2-fun-0-'/3 (src/yconf.erl, line 518)
   in call from yconf:'-and_then/2-fun-0-'/3 (src/yconf.erl, line 590)
   in call from yconf:validate_option/3 (src/yconf.erl, line 1108)
xmpp@ejabberd:~/server/sbin$ ./ejabberdctl live
```
any ideea what I am doing wrong here?
