### ISSUE TITLE
Delete a persistant group .

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#2950]
Hi,
Thanks for the help so far . i have covered a lot of road.

I am working on MUC.  So i was wondering is there any way to delete a persistant room. 

Here are my configuration while creating testgroup.
```yaml
mod_muc:
     access:
       - allow
     access_admin:
       - allow: admin
     access_create: muc_create
     access_persistent: muc_create
     default_room_options:
       # persistent: true
       allow_subscription: true
       members_only: true
       mam: true
       ## mam: true
```
