### ISSUE TITLE
ERR_EMPTY_RESPONSE on mod_http_upload

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#2953]
Hi, 
I have configured the mod_http_upload.  Here re my configurations for the same:
```yaml
...
 -
      mod_http_upload:
          docroot: "/home/sagar-singh/Desktop/backups/chatting_server/APP_server/uploads"
          put_url: "http://@HOST@:5443/upload"
          max_size: 500000000 #500 MByte
          thumbnail: false
          custom_headers:
            "Access-Control-Allow-Origin": "*"
            "Access-Control-Allow-Methods": "PUT"
            "Access-Control-Allow-Headers": "content-type"
...

  access_rules:
...
   -
      soft_upload_quota:
          - all: 200000 # MiB
       hard_upload_quota:
          - all: 300000 # MiB
...
listen:
 ...
   -
     port: 5443
     ip: "::"
     module: ejabberd_http
     tls: true
     request_handlers:
        "/admin": ejabberd_web_admin
        "/api": mod_http_api
        "/bosh": mod_bosh
        "/captcha": ejabberd_captcha
        "/upload": mod_http_upload
        "/ws": ejabberd_http_ws
        "/oauth": ejabberd_oauth
```

I am using the XMLHttpRequest to send the file. Here is the sample code (if worthless, ignore):
```
xhr = new XMLHttpRequest();
xhr.onreadystatechange = function() {
        if (xhr.readyState === 4) {
        	success_callback(get);	console.log(get);
        }
};
xhr.open("PUT", put, true);
xhr.setRequestHeader('Content-Type', file.type);
xhr.send(file);
```

I am sending presence stanzas to the server and i am getting the GET and PUT urls. 
When I am uploading files to the server i am getting the ERR_EMPTY_RESPONSE. 

![image](https://user-images.githubusercontent.com/16096109/61609726-aa02ba00-ac74-11e9-80aa-0dd33fcec51f.png)

Also the files are not saving to the docroot folder.
What could go wrong . please help .

Thanks in advance.
