### ISSUE TITLE
Mix module not working for send message to mix channel in ejabberd 19.05

### ISSUE THREAD

**Issue by sujankumar4593** [processone/ejabberd#2958]
Hi I am using mix module with sql database I have created the channel and join with two users using following IQ
**IQ send to server  for creating channel**
```
<iq id='lx09df27'
    to='mix.dev.local.xmpp.com'
    type='set'>
  <create channel='group7' xmlns='urn:xmpp:mix:core:0'/>
</iq>
```
**IQ receiving from server for creating channel**
```
<iq to="sujan@dev.local.xmpp.com/Mobile-126351273127" type="result" from="mix.dev.local.xmpp.com" xml:lang="en" id="lx09df27">
<create xmlns="urn:xmpp:mix:core:0" channel="group7"/>
</iq>
```

**IQ sending to join to the channel**
```
<iq type='set'
    to='group7@mix.dev.local.xmpp.com'
    id='76CF-40C6-B91B-1EA08C332FC7' >
  <join xmlns='urn:xmpp:mix:core:0'>
    <subscribe node='urn:xmpp:mix:nodes:messages'/>
    <subscribe node='urn:xmpp:mix:nodes:presence'/>
    <subscribe node='urn:xmpp:mix:nodes:participants'/>
    <subscribe node='urn:xmpp:mix:nodes:info'/>
      <nick>Group007</nick>
  </join>
</iq>
```
**Receiving the Message and IQ respons**e 
```
<message to="sujan@dev.local.xmpp.com/Mobile-126351273127" from="group7@mix.dev.local.xmpp.com" id="7531656694332618160">
<event xmlns="http://jabber.org/protocol/pubsub#event">
<items node="urn:xmpp:mix:nodes:participants">
<item id="c5b2aa6130a4e05bc479">
<participant xmlns="urn:xmpp:mix:core:0" jid="sujan@dev.local.xmpp.com" nick="Group007"/>
</item>
</items>
</event>
</message>
```

```
<iq to="sujan@dev.local.xmpp.com/Mobile-126351273127" type="result" from="group7@mix.dev.local.xmpp.com" xml:lang="en" id="76CF-40C6-B91B-1EA08C332FC7">
<join xmlns="urn:xmpp:mix:core:0" id="c5b2aa6130a4e05bc479">
<nick>Group007</nick>
<subscribe node="urn:xmpp:mix:nodes:messages"/>
<subscribe node="urn:xmpp:mix:nodes:participants"/>
</join>
</iq>
```
Using the join iq I have join another user to the channel  and its sucessfully joined

When I send the following message to the channel with both users online i am not receiving the message from another user 

```
<message
         to='group7@mix.dev.local.xmpp.com'
         id='92vax143g'
         type='groupchat'>
  <body> Test Message </body>
</message>
```
I have checked the log with debugger mode the packet is dropped

```
2019-07-23 21:51:14.184 [debug] <0.514.0>@ejabberd_router:do_route:353 route:
#message{id = <<"1563898873564953">>,type = groupchat,lang = <<"en">>,
         from = #jid{user = <<"group5">>,
                     server = <<"mix.dev.local.xmpp.com">>,
                     resource = <<"1e5833a24199a0b782c2">>,
                     luser = <<"group5">>,
                     lserver = <<"mix.dev.local.xmpp.com">>,
                     lresource = <<"1e5833a24199a0b782c2">>},
         to = #jid{user = <<"sujan">>,server = <<"dev.local.xmpp.com">>,
                   resource = <<>>,luser = <<"sujan">>,
                   lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
         subject = [],
         body = [#text{lang = <<>>,data = <<"hi">>}],
         thread = undefined,
         sub_els = [#mix{submission_id = <<"2343242343j4kl243">>,
                         jid = #jid{user = <<"sujan">>,
                                    server = <<"dev.local.xmpp.com">>,
                                    resource = <<>>,luser = <<"sujan">>,
                                    lserver = <<"dev.local.xmpp.com">>,
                                    lresource = <<>>},
                         nick = <<>>}],
         meta = #{ip => {0,0,0,0,0,65535,32512,1}}}
2019-07-23 21:51:14.185 [debug] <0.514.0>@ejabberd_local:do_route:142 local route:
#message{id = <<"1563898873564953">>,type = groupchat,lang = <<"en">>,
         from = #jid{user = <<"group5">>,
                     server = <<"mix.dev.local.xmpp.com">>,
                     resource = <<"1e5833a24199a0b782c2">>,
                     luser = <<"group5">>,
                     lserver = <<"mix.dev.local.xmpp.com">>,
                     lresource = <<"1e5833a24199a0b782c2">>},
         to = #jid{user = <<"sujan">>,server = <<"dev.local.xmpp.com">>,
                   resource = <<>>,luser = <<"sujan">>,
                   lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
         subject = [],
         body = [#text{lang = <<>>,data = <<"hi">>}],
         thread = undefined,
         sub_els = [#mix{submission_id = <<"2343242343j4kl243">>,
                         jid = #jid{user = <<"sujan">>,
                                    server = <<"dev.local.xmpp.com">>,
                                    resource = <<>>,luser = <<"sujan">>,
                                    lserver = <<"dev.local.xmpp.com">>,
                                    lresource = <<>>},
                         nick = <<>>}],
         meta = #{ip => {0,0,0,0,0,65535,32512,1}}}
2019-07-23 21:51:14.186 [debug] <0.514.0>@ejabberd_sm:do_route:684 processing message to bare JID:
#message{id = <<"1563898873564953">>,type = groupchat,lang = <<"en">>,
         from = #jid{user = <<"group5">>,
                     server = <<"mix.dev.local.xmpp.com">>,
                     resource = <<"1e5833a24199a0b782c2">>,
                     luser = <<"group5">>,
                     lserver = <<"mix.dev.local.xmpp.com">>,
                     lresource = <<"1e5833a24199a0b782c2">>},
         to = #jid{user = <<"sujan">>,server = <<"dev.local.xmpp.com">>,
                   resource = <<>>,luser = <<"sujan">>,
                   lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
         subject = [],
         body = [#text{lang = <<>>,data = <<"hi">>}],
         thread = undefined,
         sub_els = [#mix{submission_id = <<"2343242343j4kl243">>,
                         jid = #jid{user = <<"sujan">>,
                                    server = <<"dev.local.xmpp.com">>,
                                    resource = <<>>,luser = <<"sujan">>,
                                    lserver = <<"dev.local.xmpp.com">>,
                                    lresource = <<>>},
                         nick = <<>>}],
         meta = #{ip => {0,0,0,0,0,65535,32512,1},
                  stanza_id => 1563898874185378}}
2019-07-23 21:51:14.187 [debug] <0.514.0>@ejabberd_router:do_route:353 route:
#message{
    id = <<"1563898873564953">>,type = error,lang = <<"en">>,
    from =
        #jid{
            user = <<"sujan">>,server = <<"dev.local.xmpp.com">>,
            resource = <<>>,luser = <<"sujan">>,
            lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
    to =
        #jid{
            user = <<"group5">>,server = <<"mix.dev.local.xmpp.com">>,
            resource = <<"1e5833a24199a0b782c2">>,luser = <<"group5">>,
            lserver = <<"mix.dev.local.xmpp.com">>,
            lresource = <<"1e5833a24199a0b782c2">>},
    subject = [],
    body = [#text{lang = <<>>,data = <<"hi">>}],
    thread = undefined,
    sub_els =
        [#mix{
             submission_id = <<"2343242343j4kl243">>,
             jid =
                 #jid{
                     user = <<"sujan">>,server = <<"dev.local.xmpp.com">>,
                     resource = <<>>,luser = <<"sujan">>,
                     lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
             nick = <<>>},
         #stanza_error{
             type = cancel,code = 503,by = undefined,
             reason = 'service-unavailable',
             text =
                 [#text{lang = <<"en">>,data = <<"User session not found">>}],
             sub_els = []}],
    meta = #{ip => {0,0,0,0,0,65535,32512,1},stanza_id => 1563898874185378}}
2019-07-23 21:51:14.188 [debug] <0.514.0>@mod_mix:route:107 Dropping packet:
#message{
    id = <<"1563898873564953">>,type = error,lang = <<"en">>,
    from =
        #jid{
            user = <<"sujan">>,server = <<"dev.local.xmpp.com">>,
            resource = <<>>,luser = <<"sujan">>,
            lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
    to =
        #jid{
            user = <<"group5">>,server = <<"mix.dev.local.xmpp.com">>,
            resource = <<"1e5833a24199a0b782c2">>,luser = <<"group5">>,
            lserver = <<"mix.dev.local.xmpp.com">>,
            lresource = <<"1e5833a24199a0b782c2">>},
    subject = [],
    body = [#text{lang = <<>>,data = <<"hi">>}],
    thread = undefined,
    sub_els =
        [#mix{
             submission_id = <<"2343242343j4kl243">>,
             jid =
                 #jid{
                     user = <<"sujan">>,server = <<"dev.local.xmpp.com">>,
                     resource = <<>>,luser = <<"sujan">>,
                     lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
             nick = <<>>},
         #stanza_error{
             type = cancel,code = 503,by = undefined,
             reason = 'service-unavailable',
             text =
                 [#text{lang = <<"en">>,data = <<"User session not found">>}],
             sub_els = []}],
    meta = #{ip => {0,0,0,0,0,65535,32512,1},stanza_id => 1563898874185378}}
2019-07-23 21:51:14.189 [debug] <0.514.0>@ejabberd_router:do_route:353 route:
#message{id = <<"1563898873564953">>,type = groupchat,lang = <<"en">>,
         from = #jid{user = <<"group5">>,
                     server = <<"mix.dev.local.xmpp.com">>,
                     resource = <<"1e5833a24199a0b782c2">>,
                     luser = <<"group5">>,
                     lserver = <<"mix.dev.local.xmpp.com">>,
                     lresource = <<"1e5833a24199a0b782c2">>},
         to = #jid{user = <<"mani">>,server = <<"dev.local.xmpp.com">>,
                   resource = <<>>,luser = <<"mani">>,
                   lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
         subject = [],
         body = [#text{lang = <<>>,data = <<"hi">>}],
         thread = undefined,
         sub_els = [#mix{submission_id = <<>>,
                         jid = #jid{user = <<"sujan">>,
                                    server = <<"dev.local.xmpp.com">>,
                                    resource = <<>>,luser = <<"sujan">>,
                                    lserver = <<"dev.local.xmpp.com">>,
                                    lresource = <<>>},
                         nick = <<>>}],
         meta = #{ip => {0,0,0,0,0,65535,32512,1}}}
2019-07-23 21:51:14.190 [debug] <0.514.0>@ejabberd_local:do_route:142 local route:
#message{id = <<"1563898873564953">>,type = groupchat,lang = <<"en">>,
         from = #jid{user = <<"group5">>,
                     server = <<"mix.dev.local.xmpp.com">>,
                     resource = <<"1e5833a24199a0b782c2">>,
                     luser = <<"group5">>,
                     lserver = <<"mix.dev.local.xmpp.com">>,
                     lresource = <<"1e5833a24199a0b782c2">>},
         to = #jid{user = <<"mani">>,server = <<"dev.local.xmpp.com">>,
                   resource = <<>>,luser = <<"mani">>,
                   lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
         subject = [],
         body = [#text{lang = <<>>,data = <<"hi">>}],
         thread = undefined,
         sub_els = [#mix{submission_id = <<>>,
                         jid = #jid{user = <<"sujan">>,
                                    server = <<"dev.local.xmpp.com">>,
                                    resource = <<>>,luser = <<"sujan">>,
                                    lserver = <<"dev.local.xmpp.com">>,
                                    lresource = <<>>},
                         nick = <<>>}],
         meta = #{ip => {0,0,0,0,0,65535,32512,1}}}
2019-07-23 21:51:14.191 [debug] <0.514.0>@ejabberd_sm:do_route:684 processing message to bare JID:
#message{id = <<"1563898873564953">>,type = groupchat,lang = <<"en">>,
         from = #jid{user = <<"group5">>,
                     server = <<"mix.dev.local.xmpp.com">>,
                     resource = <<"1e5833a24199a0b782c2">>,
                     luser = <<"group5">>,
                     lserver = <<"mix.dev.local.xmpp.com">>,
                     lresource = <<"1e5833a24199a0b782c2">>},
         to = #jid{user = <<"mani">>,server = <<"dev.local.xmpp.com">>,
                   resource = <<>>,luser = <<"mani">>,
                   lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
         subject = [],
         body = [#text{lang = <<>>,data = <<"hi">>}],
         thread = undefined,
         sub_els = [#mix{submission_id = <<>>,
                         jid = #jid{user = <<"sujan">>,
                                    server = <<"dev.local.xmpp.com">>,
                                    resource = <<>>,luser = <<"sujan">>,
                                    lserver = <<"dev.local.xmpp.com">>,
                                    lresource = <<>>},
                         nick = <<>>}],
         meta = #{ip => {0,0,0,0,0,65535,32512,1},
                  stanza_id => 1563898874190701}}
2019-07-23 21:51:14.192 [debug] <0.514.0>@ejabberd_router:do_route:353 route:
#message{
    id = <<"1563898873564953">>,type = error,lang = <<"en">>,
    from =
        #jid{
            user = <<"mani">>,server = <<"dev.local.xmpp.com">>,
            resource = <<>>,luser = <<"mani">>,
            lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
    to =
        #jid{
            user = <<"group5">>,server = <<"mix.dev.local.xmpp.com">>,
            resource = <<"1e5833a24199a0b782c2">>,luser = <<"group5">>,
            lserver = <<"mix.dev.local.xmpp.com">>,
            lresource = <<"1e5833a24199a0b782c2">>},
    subject = [],
    body = [#text{lang = <<>>,data = <<"hi">>}],
    thread = undefined,
    sub_els =
        [#mix{
             submission_id = <<>>,
             jid =
                 #jid{
                     user = <<"sujan">>,server = <<"dev.local.xmpp.com">>,
                     resource = <<>>,luser = <<"sujan">>,
                     lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
             nick = <<>>},
         #stanza_error{
             type = cancel,code = 503,by = undefined,
             reason = 'service-unavailable',
             text =
                 [#text{lang = <<"en">>,data = <<"User session not found">>}],
             sub_els = []}],
    meta = #{ip => {0,0,0,0,0,65535,32512,1},stanza_id => 1563898874190701}}
2019-07-23 21:51:14.193 [debug] <0.514.0>@mod_mix:route:107 Dropping packet:
#message{
    id = <<"1563898873564953">>,type = error,lang = <<"en">>,
    from =
        #jid{
            user = <<"mani">>,server = <<"dev.local.xmpp.com">>,
            resource = <<>>,luser = <<"mani">>,
            lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
    to =
        #jid{
            user = <<"group5">>,server = <<"mix.dev.local.xmpp.com">>,
            resource = <<"1e5833a24199a0b782c2">>,luser = <<"group5">>,
            lserver = <<"mix.dev.local.xmpp.com">>,
            lresource = <<"1e5833a24199a0b782c2">>},
    subject = [],
    body = [#text{lang = <<>>,data = <<"hi">>}],
    thread = undefined,
    sub_els =
        [#mix{
             submission_id = <<>>,
             jid =
                 #jid{
                     user = <<"sujan">>,server = <<"dev.local.xmpp.com">>,
                     resource = <<>>,luser = <<"sujan">>,
                     lserver = <<"dev.local.xmpp.com">>,lresource = <<>>},
             nick = <<>>},
         #stanza_error{
             type = cancel,code = 503,by = undefined,
             reason = 'service-unavailable',
             text =
                 [#text{lang = <<"en">>,data = <<"User session not found">>}],
             sub_els = []}],
    meta = #{ip => {0,0,0,0,0,65535,32512,1},stanza_id => 1563898874190701}}
```

**Comment by zinid** [comment]
Do you have `mod_mix_pam` in `modules` section of ejabberd.yml?

**Comment by sujankumar4593** [comment]
I am enabled the  mod_mix_pam in ejabberd.yml but still not working

This is my module section 
```
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
    #mod_avatar: {}
  mod_blocking: {}
  #mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  # mod_http_api: {}
  # mod_http_upload:
  #  put_url: "https://@HOST@:5443/upload"
  mod_last: 
    db_type: sql
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    db_type: sql
    assume_mam_usage: true
    default: always
  # mod_mqtt: {}
  # mod_muc:
  #  access:
  #    - allow
  #  access_admin:
  #    - allow: admin
  #  access_create: muc_create
  #  access_persistent: muc_create
  #  access_mam:
  #    - allow
  #  default_room_options:
  #    mam: true
  # mod_muc_admin: {}
  mod_offline:
    db_type: sql
    access_max_user_messages: max_user_offline_messages
  mod_ping:
    send_pings: true
    ping_interval: 60
    ping_ack_timeout: 30
    timeout_action: kill    
  mod_privacy:
    db_type: sql      
  mod_private: {}
  # mod_proxy65:
  #  access: local
  #  max_connections: 5
  **mod_mix: 
    db_type: sql
  mod_mix_pam:   
    db_type: sql**
  mod_pubsub:
    db_type: sql
    ignore_pep_from_offline: true
    access_createnode: pubsub_createnode
    plugins:
      - "flat"
      - "hometree"  
      - "pep"
    force_node_config:
      ## Change from "whitelist" to "open" to enable OMEMO support
      ## See https://github.com/processone/ejabberd/issues/2425
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      ## Avoid buggy clients to make their bookmarks public
      "storage:bookmarks":
        access_model: whitelist
 ## mod_push: {}
 ## mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network
  mod_roster:
    db_type: sql
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster:
    db_type: sql      
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard:
    db_type: sql
    search: false    
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

```
