### ISSUE TITLE
Enable BOSH with HTTPS

### ISSUE THREAD

**Issue by BoopathyRaja** [processone/ejabberd#2966]
**I want to enable HTTPS for BOSH Connection**
https://amchart.consilx.com:5281/http-bind

**Response**
```
This page isn’t working amchart.consilx.com didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Config Detail**
![Screenshot from 2019-07-26 17-00-08](https://user-images.githubusercontent.com/4328610/61949023-2247e300-afc7-11e9-8e90-c5307261af66.png)

**ejabberd.log**
```
[debug] <0.1809.0>@ejabberd_http:init:151 S: [{[<<"admin">>],ejabberd_web_admin},{[<<"http-bind">>],mod_bosh}]
[info] <0.361.0>@ejabberd_listener:accept:238 (<0.1809.0>) Accepted connection 14.142.204.195:59094 -> 172.31.45.128:5281
[info] <0.361.0>@ejabberd_listener:accept:238 (<0.1809.0>) Accepted connection 14.142.204.195:59094 -> 172.31.45.128:5281
[info] <0.361.0>@ejabberd_listener:accept:238 (<0.1810.0>) Accepted connection 14.142.204.195:59096 -> 172.31.45.128:5281
```

**This work properly when**
```yaml
   port: 5281
   ip: "0.0.0.0"
   module: ejabberd_http
   web_admin: true
   http_bind: true
   # tls: true
```

When I enable _tls:true_ all issue starts
```
The node ejabberd@localhost is started with status: started
ejabberd 18.12.97 is running in that node
```
**Can anyone help me out. 
Thank in advance**

**Comment by badlop** [comment]
So, visiting the BOSH page when tls:true fails.

I've installed exactly your ejabberd version, configured like this:
```yaml
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    tls: false
    request_handlers:
      "/admin": ejabberd_web_admin
      "/bosh": mod_bosh
  -
    port: 5281
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/bosh": mod_bosh
```

Then I can visit with a web browser those pages:

> http://localhost:5280/bosh/
> https://localhost:5281/bosh/

they show an informative text, and BOSH works with Tkabber and Gajim using both URLs. I can also visit the webadmin pages:

> http://localhost:5280/admin/
> https://localhost:5281/admin/

Configure the 5280 and 5281 listeners like I do, then visit the corresponding BOSH pages, and also the webadmin pages.  Are you able to visit the webadmin pages when tls:true , or does it also fail like with BOSH? If that's the case, then the problem is not in BOSH, the problem is in encryption.

You can also try installing ejabberd from a binary installer, which includes the required libraries, just to check if that works.
