### ISSUE TITLE
WebSocket broken in 19.08

### ISSUE THREAD

**Issue by mickeprag** [processone/ejabberd#2989]
In the config I have this configured:
```yaml
hosts:
  - "example.net"
```
The domain to point to the server is `xmpp.example.net`
This is the section for setting up WebSocket:
```yaml
listen:
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/ws": ejabberd_http_ws
```

This is the url used to access the server:
`wss://xmpp.example.net:5443/ws`

This works fine in version 19.05 but the same config does not work in 19.08 and returnes a 400 response.
Accessing the url (https://xmpp.example.net:5443/ws) from a browser returns (in version 19.08):
> Host not served

In version 19.05:

> ejabberd ejabberd_http_ws
> An implementation of WebSocket protocol
>
> This web page is only informative. To use WebSocket connection you need a Jabber/XMPP client that supports it.
