### ISSUE TITLE
"Option 'sm_db_type' is not defined for virtual host" error

### ISSUE THREAD

**Issue by di72nn** [processone/ejabberd#2994]
Hey!

After updating from 19.05 to 19.08 I started getting this warning (repeats multiple times):
```
2019-08-17 19:06:50.761 [warning] <0.572.0>@ejabberd_config:get_option:161 Option 'sm_db_type' is not defined for virtual host 'vk.mydomain.com'. This is a bug, please report it with the following stacktrace included:
** exception error: bad argument
   in function  ets:lookup_element/3
      called as ets:lookup_element(ejabberd_options,
                                   {sm_db_type,<<"vk.mydomain.com">>},
                                   2)
   in call from ejabberd_config:get_option/1 (src/ejabberd_config.erl, line 157)
   in call from ejabberd_sm:get_sm_backend/1 (src/ejabberd_sm.erl, line 903)
   in call from ejabberd_sm:get_user_resources/2 (src/ejabberd_sm.erl, line 219)
   in call from mod_pubsub:send_stanza/4 (src/mod_pubsub.erl, line 3087)
   in call from lists:foreach/2 (lists.erl, line 1338)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 236)
   in call from ejabberd_hooks:run1/3 (src/ejabberd_hooks.erl, line 203)
```
Which looks very similar to #2930.

I use [vk4xmpp transport](https://github.com/mrDoctorWho/vk4xmpp) using the following configuration:
```YAML
hosts:
  - "mydomain.com"
  - "someotherdomain.com"

listen:
  -
    port: 5557
    module: ejabberd_service
    access: local
    shaper: fast
    ip: "127.0.0.1"
    hosts:
      "vk.mydomain.com":
        password: "password"

default_db: sql

sql_type: mysql
```
I don't have `sm_db_type` defined at all.

I've been using that config for a while now, nothing like that had happened before the update.
