### ISSUE TITLE
Error connecting to ejabberd on AWS

### ISSUE THREAD

**Issue by shaggi7** [processone/ejabberd#3005]
Hi All,
I am able to set up ejabberd on my local machine and do perform all desired action using my client.
But now i installed ejabberd server on my AWS instance . 

- I have configured all the CORS policy on AWS . I am getting this error .

> Access to XMLHttpRequest at 'http://ec2-XX-XXX-XXX-XX.ap-south-1.compute.amazonaws.com:5280/http-bind' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

```
listen:
-
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"
      "Access-Control-Allow-Headers": "Authorization, Content-Type"
      "Access-Control-Allow-Credentials": "true"
```
