### ISSUE TITLE
New configuration validator vs. additional-configuration-files

### ISSUE THREAD

**Issue by stefansieg** [processone/ejabberd#3018]
Hi,

with the new configuration validator the ACL example at: https://docs.ejabberd.im/admin/configuration/#include-additional-configuration-files
will result in the following error message:

"Failed to start ejabberd application: Configuration error: duplicated option: acl"

So, either the config checker, the documentation, or I'm wrong :)

**Comment by zinid** [comment]
Yeah, the new version only allows `append_host_config` and `host_config` options to be duplicated.

**Comment by badlop** [comment]
This updated paragraph is correct for the Doc, @zinid ?

---

Please notice that options already defined in the main configuration file cannot be redefined in the included configuration files. But you can use `host_config` and `append_host_config` as usual (see https://docs.ejabberd.im/admin/configuration/#virtual-hosting).

In this example, `ejabberd.yml` defines some ACL for the whole ejabberd server, and later includes another file:

```
acl:
  admin:
    user:
      - "admin": "localhost"
include_config_file:
  "/etc/ejabberd/acl.yml":
```

The file `acl.yml` can add additional administrators to one of the virtual hosts:

```
append_host_config:
  "localhost":
    acl:
      admin:
        user:
          - "bob": "localhost"
          - "jan": "localhost"
```

**Comment by zinid** [comment]
@badlop no :)
ejabberd will complain on duplicated `admin` option. It's better to rename the option to something like `friends`.

**Comment by zinid** [comment]
Also, the updated syntax is:
```
append_host_config:
  localhost:
    acl:
      admin:
        user:
          - bob@localhost
          - jan@localhost
```

**Comment by badlop** [comment]
Great the new syntax!

> ejabberd will complain on duplicated admin option.

Uhmm, it gets accepted, and works correctly: all the accounts have admin rights.

In fact, this is also accepted and works:
ejabberd.yml:
```
host_config:
  localhost:
    acl:
      admin:
        user:
          - user1@localhost
          - "user1@example1.org"
          - "user1@shakespeare.example"
include_config_file: "/etc/ejabberd/acl.yml"
```
acl.yml:
```
append_host_config:
  localhost:
    acl:
      admin:
        user:
          - user2@localhost
```
I would consider the behaviour that I see a feature. Is it desired and ready for documenting, or a bug in the configuration checker?
