### ISSUE TITLE
Webadmin 404 error in 19.09

### ISSUE THREAD

**Issue by vampik** [processone/ejabberd#3050]
## Environment

- ejabberd version: 19.09
- Erlang version: `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.4.4`
- OS: Linux (Gentoo)
- Installed from: other

## Configuration

```yaml
hosts:
  - "example.net"
listen:
...
  -
    request_handlers:
      "/admin": ejabberd_web_admin
    port: 5281
    ip: "::"
    module: ejabberd_http
    tls: true
    protocol_options:
      - "no_sslv3"
      - "no_tlsv1"
      - "cipher_server_preference"
      - "no_compression"
    dhfile: "/etc/ssl/ejabberd/dhparams.pem"
    ciphers: "ECDH:DH:!3DES:!aNULL:!eNULL:!MEDIUM@STRENGTH"
...
```
 
## Errors from error.log/crash.log

No errors

## Bug description

This seems to be related to #2989, but the conversation is closed there, so I open a new issue.

Since 19.08 accessing https://jabber.example.net:5281/admin gave me "Host not served" error. The host I serve is example.net, but the fqdn of the ejabberd server itself is jabber.example.net.

I've read that it should be fixed in 19.09, but it is not.

Now accessing https://jabber.example.net:5281/admin gives me "404 Not Found" error instead.
