### ISSUE TITLE
Rest API "AccessRules: Account does not have the right to perform the operation" on /register

### ISSUE THREAD

**Issue by thiras** [processone/ejabberd#3054]
## Environment

- ejabberd version: 19.09
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.4
- OS: Linux (Ubuntu)
- Installed from: official deb/rpm

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
hosts:
  - "chat.example.com"
  - "chat.example.net"

host_config:
  "chat.example.com":
    auth_method: [sql]

host_config:
  "chat.example.net":
    auth_method: [sql]

default_db: sql
new_sql_schema: true

sql_type: mysql
sql_server: "localhost"
sql_database: "ejab_db"
sql_username: "ejab_usr"
sql_password: "password"

loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

certfiles:
  - "/opt/ejabberd/conf/fullchain.pem"
  - "/opt/ejabberd/conf/privkey.pem"

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    protocol_options:
      - "no_sslv2"
      - "no_sslv3"
      - "no_tlsv1"
      - "no_tlsv1_1"
    ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
    dhfile: "/opt/ejabberd/conf/new_dhparams.pem"
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000

s2s_use_starttls: optional

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "admin@chat.example.com"
      - "admin@chat.example.net"

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number

commands_admin_access:
  - allow:
    - user: "admin@chat.example.net"
commands:
  - add_commands: [user, admin, open]
# Tokens are valid for a year as default:
oauth_expire: 31536000
oauth_access: all

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

max_fsm_queue: 10000

acme:
   contact: "mailto:admin@chat"
   ca_url: "https://acme-v01.api.letsencrypt.org"

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    db_type: sql
    assume_mam_usage: true
    default: always
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
```

## Errors from error.log/crash.log

No errors

## Bug description

I've created token with ejabberd:admin scope through command line interface. Here is my request;

```
POST /api/register HTTP/1.1
Host: chat.example.net:5443
Content-Type: application/json
X-Admin: true
Authorization: Bearer TOKEN
cache-control: no-cache
Postman-Token: e5cf2666-dcca-4391-8f2c-1a6a9d6478d8
{
    "user": "apiusertest",
    "host": "chat.example.net",
    "password": "789123"
}
```

With this request I get;

```
{"status":"error","code":32,"message":"AccessRules: Account does not have the right to perform the operation."}
```

**Comment by prefiks** [comment]
Was that token created for "admin@chat.example.com" or "admin@chat.example.net"? Only those two could match "admin access" rule, and thats only rule that allows oauth access.

**Comment by thiras** [comment]
@prefiks I've tried for both. And both generated with ejabberd:admin scope.

**Comment by prefiks** [comment]
Could you try set loglevel in config to 5 and try to execute command, this should log information about auth that was used, maybe this will show what's going on

**Comment by thiras** [comment]
@prefiks Here is level 5 log after hitting /register

```
2019-10-07 13:18:17.831 [info] <0.378.0>@ejabberd_listener:accept:256 (<0.596.0>) Accepted connection [::ffff:195.174.215.70]:58068 -> [::ffff:45.79.150.252]:5443
2019-10-07 13:18:17.832 [debug] <0.596.0>@ejabberd_http:init:128 S: [{[<<"admin">>],ejabberd_web_admin},{[<<"api">>],mod_http_api},{[<<"bosh">>],mod_bosh},{[<<"captcha">>],ejabberd_captcha},{[<<"upload">>],mod_http_upload},{[<<"ws">>],ejabberd_http_ws},{[<<"oauth">>],ejabberd_oauth}]
2019-10-07 13:18:18.157 [debug] <0.596.0>@ejabberd_http:process_header:283 ({tlssock,#Port<0.64>,#Ref<0.397140347.1498021889.54075>}) http query: 'POST' <<"/api/register">>
2019-10-07 13:18:18.157 [debug] <0.596.0>@ejabberd_http:process:355 [<<"api">>,<<"register">>] matches [<<"api">>]
2019-10-07 13:18:18.168 [info] <0.596.0>@mod_http_api:log:509 API call register [{<<"user">>,<<"apiusertest">>},{<<"host">>,<<"chat.example.net">>},{<<"password">>,<<"789123">>}] from ::ffff:195.174.215.70:58068
2019-10-07 13:18:18.169 [debug] <0.444.0>@ejabberd_sql:sql_query_internal:632 SQL: "select jid, scope, expire from oauth_token where token='trZesDYu3UtAxx1AsvlyzQJoEnkvdEYQ'"
2019-10-07 13:18:18.177 [debug] <0.362.0>@ejabberd_access_permissions:handle_call:120 Command 'register' execution denied (CallerInfo=#{caller_module => mod_http_api,caller_server => <<"chat.example.net">>,ip => {0,0,0,0,0,65535,50094,55110},oauth_scope => [<<"ejabberd:admin">>],tag => <<>>,usr => {<<"admin">>,<<"chat.example.net">>,<<>>}})
```

**Comment by prefiks** [comment]
Could you change "admin access" rule to this and see if this helps:
```
  "admin access":
    who:
      access:
        allow:
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: admin
```

iirc rule that you here requires both admin user and access from 127.0.0.1, if you remove acl: loopback just using admin matching token should work

**Comment by thiras** [comment]
Thank you very much. It solved. It might be good idea to add to the docs that.

**Comment by badlop** [comment]
>  It might be good idea to add to the docs that.

That is already explained in this paragaph:

> who section will allow command to be executed if at least one rule included inside it will be successfully matched, if you need to have ensure that multiple rules must be matched at this same time, you need to use - access rule for that.

https://docs.ejabberd.im/developer/ejabberd-api/permissions/#rules-inside-who-section

After this paragraph there are two examples, one of each case. Anyway, I've made more verbose the explanation of those two examples.

**Comment by shouhuori** [comment]
@prefiks  I wrote config file like you, still get this error.
request json:
```json
   {
      "user": "bob",
      "host": "chat.100100.li",
      "password": "SomEPass44"
    }
```
error message:
```json
{
    "status": "error",
    "code": 32,
    "message": "AccessRules: Account does not have the right to perform the operation."
}
```
ejabberd.yml:
```yml
###
###'           ejabberd configuration file
###
### The parameters used in this configuration file are explained at
###
###       https://docs.ejabberd.im/admin/configuration
###
### The configuration file is written in YAML.
### *******************************************************
### *******           !!! WARNING !!!               *******
### *******     YAML IS INDENTATION SENSITIVE       *******
### ******* MAKE SURE YOU INDENT SECTIONS CORRECTLY *******
### *******************************************************
### Refer to http://en.wikipedia.org/wiki/YAML for the brief description.
###

hosts:
  - chat.100100.li 

loglevel: 5

certfiles:
        - "/etc/nginx/ssl/ssl-bundle.crt"
        - "/etc/nginx/ssl/ssl.key"

ca_file: "/opt/ejabberd/conf/cacert.pem"

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
      "/oauth": ejabberd_oauth
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000

s2s_use_starttls: optional

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - 101.91.184.117
      - ::FFFF:49.7.235.83/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - admin@chat.100100.li
    ip:
      - ::FFFF:49.7.235.83/128
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
            acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
           allow:
             acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
    what:
      - status
      - register 
      - connected_users_number
  "admin commands":
    who: 
      - acl: loopack
    what:
      - register 
      - status
      - connected_users_number

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

max_fsm_queue: 10000

acme:
   contact: "mailto:admin@bwyubloqhgyb29bm-0416860"
   ca_url: "https://acme-v02.api.letsencrypt.org"

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    ## db_type: sql
    assume_mam_usage: true
    default: never
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

oauth_expire: 31536000
oauth_access: all
### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8

```
