### ISSUE TITLE
HTTP upload broken on 19.08

### ISSUE THREAD

**Issue by mbirth** [processone/ejabberd#3058]
## Environment

- ejabberd version: 19.08
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.3.4`
- OS: Linux (Ubuntu 19.10 on arm64 on a Raspberry Pi 4)
- Installed from: official binary installer

## Errors from error.log/crash.log

No errors or crash in log.

## Bug description

Gajim gives: `[Errno 104] Connection reset by peer` when trying to use HTTP upload.

The exact same ejabberd.yml with ejabberd 19.05 makes HTTP uploads work again.

(On a sidenote, 19.05 and 19.08 arm64 seem to be compiled without thumbnail-support.)

**Comment by licaon-kter** [comment]
Gist of the config?

**Comment by mbirth** [comment]
Nothing fancy:

```yaml
  mod_http_upload:
    access: local
    docroot: "/var/www/html/chat/upload"
    put_url: "https://xmpp.@HOST@:5443/upload"
    get_url: "https://xmpp.@HOST@/upload"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type, Origin, X-Requested-With"
```
