### ISSUE TITLE
Invalid value of option ldap_uids: expected map, got list instead

### ISSUE THREAD

**Issue by Bundesferkel** [processone/ejabberd#3065]
## Environment

- ejabberd version: 19.08, 19.09, 19.09.1
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 8.2.1
- OS: Linux (Debian)
- Installed from: official deb/rpm

## Configuration (only if needed):
```yaml
auth_method: ldap
ldap_servers:
  - "***1.***.*******-******.***"
  - "***2.***.*******-******.***"
ldap_encrypt: none
ldap_port: 389
ldap_rootdn: "CN=****-**,OU=********,OU=********,DC=***,DC=*******-******,DC=***"
ldap_password: "****************"
ldap_base: "OU=********,DC=***,DC=*******-******,DC=***"
ldap_uids:
  - "sAMAccountName": "%u"
ldap_filter: "(objectClass=organizationalPerson)"
```
## Errors from error.log/crash.log
2019-10-14 18:21:36.470 [critical] <0.107.0>@ejabberd_app:start:71 Failed to start ejabberd application: Invalid value of option ldap_uids: expected map, got list instead

## Bug description

Until (including) ejabberd 19.05 the usage of the server works like a charm. Only possibility to login is via Active Directory (Windows Server 2012 r2).
Starting with ejabberd 19.08 ejabberd isn't able to start anymore. I don't understand, what the problem could be. There's nothing changed in the LDAP credentials.
Are there any variables belonging to ldap changed, which are not documented in the empty config-master or faq/manual or is it just a bug?
