### ISSUE TITLE
Crash exception "key_exists"

### ISSUE THREAD

**Issue by ruifil** [processone/ejabberd#3068]
## Environment

- ejabberd version: 19.05
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.4
- OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
- Installed from: official rpm (https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/19.05/ejabberd-19.05-0.x86_64.rpm)

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
hosts:
  - "livechat.contact.private.com"
listen:
  -
    port: 5222
    module: ejabberd_c2s
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/http-bind": mod_bosh
      "/api": mod_http_api
      "/admin": ejabberd_web_admin
    captcha: false
auth_method: odbc
auth_use_cache: false
host_config:
  "livechat.contact.private.com":
    auth_method:
      - odbc
      - anonymous
    allow_multiple_connections: false
    anonymous_protocol: sasl_anon
sql_type: mysql
sql_server: "xxx.private.com"
sql_database: "xxx"
sql_password: "xxx"
sql_username: "livechat"
sql_port: 3306
sql_keepalive_interval: 120
sql_pool_size: 10
shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 1000
acl:
  admin:
    user:
      - "virtua": "livechat.contact.private.com"
  local:
    user_regexp: ""
  operators:
    user_regexp:
      - "^op_"
access_rules:
  max_user_sessions:
    - 10: all
  max_user_offline_messages:
    - 5000: admin
    - 100: all
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow: all
  c2s_shaper:
    - allow: all
  s2s_shaper:
    - allow: fast
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_admin:
    - allow: admin
    - allow: operators
  muc:
    - allow: all
  pubsub_createnode:
    - allow: local
  register:
    - allow: all
commands_admin_access: configure
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
              - acl: loopback
              - acl: admin
      - oauth:
          - scope: "ejabberd:admin"
          - access:
              - allow:
                  - acl: loopback
                  - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
    what:
      - "status"
      - "connected_users_number"
      - "get_room_occupants"
      - "get_room_occupants_number"
language: "en"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_http_api: {}
  mod_bosh:
    max_inactivity: 360
  mod_last: {}
  mod_muc:
    host: "conference.@HOST@"
    access: muc
    access_create: muc_admin
    access_persistent: muc_admin
    access_admin: muc_admin
    max_user_conferences: 100
    default_room_options:
      persistent: true
      max_users: 5000
      anonymous: true
      members_by_default: false
      moderated: true
      public: false
      public_list: false
      allow_change_subj: false
      allow_query_users: false
      allow_user_invites: false
      allow_visitor_nickchange: false
      allow_private_messages: false
      allow_visitor_status: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private:
    db_type: odbc
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard:
    db_type: odbc
    search: false
  mod_version: {}
  mod_mam:
    db_type: odbc
    default: always
    cache_size: 10000
    cache_life_time: 28800
allow_contrib_modules: true
disable_sasl_mechanisms: ["X-OAUTH2"]
```

## Errors from error.log/crash.log
```
2019-10-23 15:09:30 =ERROR REPORT====
** State machine <0.28701.150> terminating 
** Last message in was {'$gen_sync_event',{<0.29285.151>,#Ref<0.248162263.1031536644.259362>},{body,<<>>,[{sid,<<"b384e5a1f3b6927fe837921e5facdad53439af5d">>},{rid,141371452}],[{xmlstreamelement,{xmlel,<<"presence">>,[{<<"xmlns">>,<<"jabber:client">>},{<<"to">>,<<"op_1002275@livechat.contact.private.com">>},{<<"id">>,<<"8fad1c7b-8420-4330-93d6-83a4b5d46ad1:sendPresence">>}],[{xmlel,<<"datalayer">>,[],[{xmlcdata,<<"{\"private data....."]}]}}">>}]},{xmlel,<<"rqpriority">>,[],[]},{xmlel,<<"rqdelay">>,[],[{xmlcdata,<<"7">>}]}]}}],5368}}
** When State == active
**      Data  == {state,<<"livechat.contact.private.com">>,<<"b384e5a1f3b6927fe837921e5facdad53439af5d">>,{{[],[]},0,unlimited},{{[],[]},0,unlimited},none,<0.27691.150>,<<"1.0">>,#Ref<0.248162263.1035468802.82124>,undefined,20,360,141371450,<<>>,undefined,unlimited,{2,{141371449,{body,<<>>,[],[],0},nil,{141371450,{body,<<>>,[],[],0},nil,nil}}},{1,{141371452,{{<0.27275.151>,#Ref<0.248162263.1035468802.79519>},{body,<<>>,[{sid,<<"b384e5a1f3b6927fe837921e5facdad53439af5d">>},{rid,141371452}],[{xmlstreamelement,{xmlel,<<"presence">>,[{<<"xmlns">>,<<"jabber:client">>},{<<"to">>,<<"op_1002275@livechat.contact.private.com">>},{<<"id">>,<<"8fad1c7b-8420-4330-93d6-83a4b5d46ad1:sendPresence">>}],[{xmlel,<<"datalayer">>,[],[{xmlcdata,<<"{private data......}">>}]},{xmlel,<<"rqpriority">>,[],[]},{xmlel,<<"rqdelay">>,[],[{xmlcdata,<<"7">>}]}]}}],5368}},nil,nil}},{{[],[]},0,1000},{{10,56,32,221},56412},2}
** Reason for termination = 
** {{key_exists,141371452},[{gb_trees,insert_1,4,[{file,"gb_trees.erl"},{line,319}]},{gb_trees,insert,3,[{file,"gb_trees.erl"},{line,278}]},{ejabberd_bosh,active1,3,[{file,"src/ejabberd_bosh.erl"},{line,431}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-10-23 15:09:30 =CRASH REPORT====
  crasher:
    initial call: ejabberd_bosh:init/1
    pid: <0.28701.150>
    registered_name: []
    exception exit: {{{key_exists,141371452},[{gb_trees,insert_1,4,[{file,"gb_trees.erl"},{line,319}]},{gb_trees,insert,3,[{file,"gb_trees.erl"},{line,278}]},{ejabberd_bosh,active1,3,[{file,"src/ejabberd_bosh.erl"},{line,431}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: ['mod_bosh_livechat.contact.private.com',ejabberd_gen_mod_sup,ejabberd_sup,<0.107.0>]
    message_queue_len: 0
    messages: []
    links: [<0.515.0>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 9475
  neighbours:
2019-10-23 15:09:30 =SUPERVISOR REPORT====
     Supervisor: {local,'mod_bosh_livechat.contact.private.com'}
     Context:    child_terminated
     Reason:     {{key_exists,141371452},[{gb_trees,insert_1,4,[{file,"gb_trees.erl"},{line,319}]},{gb_trees,insert,3,[{file,"gb_trees.erl"},{line,278}]},{ejabberd_bosh,active1,3,[{file,"src/ejabberd_bosh.erl"},{line,431}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
     Offender:   [{pid,<0.28701.150>},{id,undefined},{mfargs,{ejabberd_bosh,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]

2019-10-23 15:32:28 =ERROR REPORT====
** State machine <0.1824.155> terminating 
** Last message in was {'$gen_sync_event',{<0.15658.155>,#Ref<0.248162263.1035730946.195232>},{body,<<>>,[{sid,<<"2eafd8986ba7e184b7977019df9bb77e08eb01d3">>},{rid,3141748610}],[{xmlstreamelement,{xmlel,<<"message">>,[{<<"xmlns">>,<<"jabber:client">>},{<<"type">>,<<"chat">>},{<<"to">>,<<"op_1003816@livechat.contact.private.com">>}],[{xmlel,<<"body">>,[],[{xmlcdata,<<"Hi there. I brought the sage Barista pro last december and recently the temperature has significantly dropeed">>}]},{xmlel,<<"requestId">>,[],[{xmlcdata,<<"17143959">>}]},{xmlel,<<"active">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}]}}],429}}
** When State == active
**      Data  == {state,<<"livechat.contact.private.com">>,<<"2eafd8986ba7e184b7977019df9bb77e08eb01d3">>,{{[],[]},0,unlimited},{{[],[]},0,unlimited},none,<0.4256.155>,<<"1.0">>,#Ref<0.248162263.1038352385.151295>,undefined,20,360,3141748609,<<>>,undefined,unlimited,{2,{3141748608,{body,<<>>,[],[],0},nil,{3141748609,{body,<<>>,[],[],0},nil,nil}}},{2,{3141748610,{{<0.14357.155>,#Ref<0.248162263.1035730946.189760>},{body,<<>>,[{sid,<<"2eafd8986ba7e184b7977019df9bb77e08eb01d3">>},{rid,3141748610}],[{xmlstreamelement,{xmlel,<<"message">>,[{<<"xmlns">>,<<"jabber:client">>},{<<"type">>,<<"chat">>},{<<"to">>,<<"op_1003816@livechat.contact.private.com">>}],[{xmlel,<<"body">>,[],[{xmlcdata,<<"Hi there. I brought ....">>}]},{xmlel,<<"requestId">>,[],[{xmlcdata,<<"17143959">>}]},{xmlel,<<"active">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}]}}],429}},nil,{3141748611,{{<0.15527.155>,#Ref<0.248162263.1032060932.135017>},{body,<<>>,[{sid,<<"2eafd8986ba7e184b7977019df9bb77e08eb01d3">>},{rid,3141748611}],[{xmlstreamelement,{xmlel,<<"message">>,[{<<"xmlns">>,<<"jabber:client">>},{<<"type">>,<<"chat">>},{<<"to">>,<<"op_1003816@livechat.contact.private.com">>}],[{xmlel,<<"requestId">>,[],[{xmlcdata,<<"17143959">>}]},{xmlel,<<"composing">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}]}},{xmlstreamelement,{xmlel,<<"message">>,[{<<"xmlns">>,<<"jabber:client">>},{<<"type">>,<<"chat">>},{<<"to">>,<<"op_1003816@livechat.contact.private.com">>}],[{xmlel,<<"body">>,[],[{xmlcdata,<<"i have tried...">>}]},{xmlel,<<"requestId">>,[],[{xmlcdata,<<"17143959">>}]},{xmlel,<<"active">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}]}}],589}},nil,nil}}},{{[],[]},0,1000},{{10,56,32,221},45062},2}
** Reason for termination = 
** {{key_exists,3141748610},[{gb_trees,insert_1,4,[{file,"gb_trees.erl"},{line,319}]},{gb_trees,insert,3,[{file,"gb_trees.erl"},{line,278}]},{ejabberd_bosh,active1,3,[{file,"src/ejabberd_bosh.erl"},{line,501}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-10-23 15:32:28 =CRASH REPORT====
  crasher:
    initial call: ejabberd_bosh:init/1
    pid: <0.1824.155>
    registered_name: []
    exception exit: {{{key_exists,3141748610},[{gb_trees,insert_1,4,[{file,"gb_trees.erl"},{line,319}]},{gb_trees,insert,3,[{file,"gb_trees.erl"},{line,278}]},{ejabberd_bosh,active1,3,[{file,"src/ejabberd_bosh.erl"},{line,501}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: ['mod_bosh_livechat.contact.private.com',ejabberd_gen_mod_sup,ejabberd_sup,<0.107.0>]
    message_queue_len: 0
    messages: []
    links: [<0.515.0>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 6568
  neighbours:
2019-10-23 15:32:28 =SUPERVISOR REPORT====
     Supervisor: {local,'mod_bosh_livechat.contact.private.com'}
     Context:    child_terminated
     Reason:     {{key_exists,3141748610},[{gb_trees,insert_1,4,[{file,"gb_trees.erl"},{line,319}]},{gb_trees,insert,3,[{file,"gb_trees.erl"},{line,278}]},{ejabberd_bosh,active1,3,[{file,"src/ejabberd_bosh.erl"},{line,501}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
     Offender:   [{pid,<0.1824.155>},{id,undefined},{mfargs,{ejabberd_bosh,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]
```

## Bug description

Some messages are lost and some chat connection sometimes breaks.

**Comment by ruifil** [comment]
The bug occurs for approximately 3% of chats (we are handling approximately 10000 chats/day, stable error ratio, linear with load).
We use for frontend the library http://strophe.im/strophejs/ in Bosh mode.
The errors occur on anonymous chats.

Can you please help, this issue is business critical. 
Do you have any possible Workaround to implement on client side or on ejabberd ?

Thank for your help.

**Comment by zinid** [comment]
The workaround is to use websockets. Does strophe support it nowadays?

**Comment by ruifil** [comment]
Thanks for the idea, websockets work, but not for session restore after webpage reload.
Our implementation we use SASL ANONYMOUS mechanism for customer connection. 
Stophejs don't support session restore with websockets.

And I think ejabberd don't support websockets session restore for anonymous connection. Can you confirm ?

**Comment by zinid** [comment]
This is not some ejabberd specifics. This is because XEP-0198 (for session resumption) doesn't support SASL ANONYMOUS.

**Comment by badlop** [comment]
Did you find some kind of solution in the end?

**Comment by amirphl** [comment]
We also have the same issue while using both instead of WebSocket:

```
2021-12-13 21:21:07.146816+03:30 [error] <0.564.0>@supervisor:do_restart/3:722 SUPERVISOR REPORT:
    supervisor: {local,'mod_bosh_g1.room.gharar.ir'}
    errorContext: child_terminated
    reason: {{key_exists,1391259609},
             [{gb_trees,insert_1,4,[{file,"gb_trees.erl"},{line,319}]},
              {gb_trees,insert,3,[{file,"gb_trees.erl"},{line,278}]},
              {ejabberd_bosh,active1,3,
                             [{file,"src/ejabberd_bosh.erl"},{line,502}]},
              {p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,226}]}]}
    offender: [{pid,<0.31350.7>},
               {id,undefined},
               {mfargs,{ejabberd_bosh,start_link,undefined}},
               {restart_type,temporary},
               {shutdown,5000},
               {child_type,worker}]
```
Is there any fix submitted?

**Comment by licaon-kter** [comment]
Which OS? ejabberd version? Gist of config?

**Comment by amirphl** [comment]
Thanks for the support.
Ejabberd is deployed from tag: 20.07 inside Docker environment.
Docker image: erlang:23.1.4
Host OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

**Comment by amirphl** [comment]
We are using Ejabberd in place of Prosody in the Jitsi environment.

Ejabberd configuration flags:
--enable-debug --enable-mysql --enable-odbc --enable-pam --enable-pgsql --enable-redis --enable-sip --enable-sqlite --enable-stun --enable-tools --enable-zlib

ejabberd.yml
```
hosts:
  - "${XMPP_DOMAIN}"
  - "auth.${XMPP_DOMAIN}"
  - "recorder.${XMPP_DOMAIN}"

host_config:
  ${XMPP_DOMAIN}:
    s2s_access: none
    disable_sasl_mechanisms: ["X-OAUTH2"]
    auth_method: jwt
    jwt_key: /home/ejabberd/jwk.key
    allow_multiple_connections: true
    modules:
      mod_bosh:
        max_inactivity: 60
      mod_disco: {}
      mod_roster:
        versioning: true
      mod_muc:
        hosts:
          - conference.${XMPP_DOMAIN}
        access: all
        access_create: all
        access_persistent: internal_muc
        access_admin: room_admin
        max_users: 10000
        max_rooms_discoitems: 1000
        max_user_conferences: 1000
        max_users_admin_threshold: 10
        default_room_options:
          max_users: 10000
      mod_mam: {}
      mod_muc_admin: {}
      mod_ping: {}
      mod_pubsub:
        access_createnode: local

  auth.${XMPP_DOMAIN}:
    ## Disable s2s to prevent spam
    s2s_access: none
    auth_method: internal
    auth_password_format: scram
    allow_multiple_connections: true
    modules:
      mod_adhoc: {}
      mod_admin_extra: {}
      mod_roster:
        versioning: true
      mod_muc:
        hosts:
          - internal.auth.${XMPP_DOMAIN}
        access: internal_muc
        access_create: internal_muc
        access_mam: internal_muc
        access_persistent: internal_muc
        access_admin: internal_muc
      mod_mam: {}
      mod_muc_admin: {}
      mod_ping: {}
      mod_pubsub:
        access_createnode: internal_muc

  recorder.${XMPP_DOMAIN}:
    ## Disable s2s to prevent spam
    s2s_access: none
    auth_method: internal
    auth_password_format: scram
    allow_multiple_connections: true
    modules:
      mod_adhoc: {}
      mod_admin_extra: {}
      mod_roster:
        versioning: true
      mod_ping: {}

loglevel: notice
log_rotate_size: 104857600
log_rotate_count: 1

#certfiles:
#  - "/home/ejabberd/fullchain1.pem"
#  - "/home/ejabberd/privkey1.pem"

listen:
  -
    port: 5222
    #ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    # starttls_required: true
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/http-bind": mod_bosh
      "/xmpp-websocket": ejabberd_http_ws

  -
    port: 5281
    ip: "127.0.0.1"
    module: ejabberd_http
    request_handlers:
      /api: mod_http_api

  - 
    port: 5347
    module: ejabberd_service
    hosts:
      focus.${XMPP_DOMAIN}:
        password: "${JICOFO_COMPONENT_SECRET}"

acl:
  api:
    user:
      - "apiuser@auth.${XMPP_DOMAIN}"
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "focus@auth.${XMPP_DOMAIN}"
      - "jvb@auth.${XMPP_DOMAIN}"
      - "jibri@auth.${XMPP_DOMAIN}"
      - "recorder@recorder.${XMPP_DOMAIN}"
      - "jigasi@auth.${XMPP_DOMAIN}"

api_permissions:
  "api access":
    from:
      - mod_http_api
    who:
      access:
        allow:
          acl: api
          acl: loopback # optional but recommended to restrict the api access to the local network
    what:
      - "*"
      - "!stop"
      - "!start"

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
  internal_muc:
    allow: admin

shaper:
  normal: 10000
  fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin # default: 500
    1000: all # default: 100
  c2s_shaper:
    none: admin
    normal: all

max_fsm_queue: 1000000 # default: 10000

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh:
    max_inactivity: 60
    prebind: true
    use_cache: true 
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    ## db_type: sql
    assume_mam_usage: true
    default: never
  mod_mqtt: {}
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

jwt_key: /home/ejabberd/jwk.key
```
