### ISSUE TITLE
MySQL over SSL

### ISSUE THREAD

**Issue by pacija** [processone/ejabberd#3070]
Hi,

any chance to get the possibility to connect ejabberd with MySQL over SSL?

I guess ejabberd config should get something like:

```
sql_type: mysql
sql_server: "mysql.example.org"

host_config:
  "example.org":
    sql_database: "ejabberd"
    sql_username: "ejabberd"
    sql_password: "BlaBla"
    sql_ssl: "True"
    sql_ssl_key: "/path/to/client-privkey.pem"
    sql_ssl_cert: "/path/to/client-cert.pem"
    sql_ssl_ca: "/path/to/mysql-ca.pem"
```
