### ISSUE TITLE
Failed to start ejabberd after adding append_host_config

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#3098]
## Environment

- ejabberd version: 19.09
- Erlang version: 10.2.4
- OS: Debian 10
- Installed from: official deb backports

## Configuration (only if needed):

```
append_host_config:
  domain.tld:
    modules:
      mod_muc:
        host: "muc.@HOST@"
        access: all
        access_create: all
        access_persistent: muc_admin
        access_admin: muc_admin
        history_size: 20
        max_users: 50
        max_room_id: 20
        max_room_name: 40
        max_room_desc: 300
        min_message_interval: 1
        min_presence_interval: 5
        default_room_options:
          allow_change_subj: false
          allow_user_invites: true
          moderated: false
          persistent: false
      mod_muc_admin: {}

append_host_config:
  domain2.tld:
    modules:
      mod_muc:
        host: "conference.@HOST@"
        access: all
        access_create: all
        access_persistent: muc_admin
        access_admin: muc_admin
        history_size: 20
        max_users: 50
        max_room_id: 20
        max_room_name: 40
        max_room_desc: 300
        min_message_interval: 1
        min_presence_interval: 5
        default_room_options:
          allow_change_subj: false
          allow_user_invites: true
          moderated: false
          persistent: false
      mod_muc_admin: {}
```

## Errors from error.log/crash.log

2019-11-26 21:44:15.562 [critical] <0.105.0>@ejabberd_app:start:71 Failed to start ejabberd application: Invalid value of option append_host_config: duplicated key: domain2.tld

## Bug description

After upgrade from ejabberd 18.12 to 19.09 I have problem with append_host_config option - only when I remove append_host_config for host domain2.tld ejabberd starts normaly. I don't see any duplicate keys, what does this error mean?

**Comment by licaon-kter** [comment]
The parser changed at some point, see the changelog. Iirc use host_config instead

**Comment by zinid** [comment]
Already fixed in `master`.

**Comment by beherit** [comment]
@licaon-kter host_config instead of append_host_config gives this same error. Is any solution for it or only rebuilding ejabberd from master?

**Comment by zinid** [comment]
> Is any solution for it?

Yes. Specify all virtual hosts under a single `append_host_config` section, e.g.
```yaml
append_host_config:
  domain.tld:
    modules:
      mod_muc:
        host: "muc.@HOST@"
        access: all
        access_create: all
        access_persistent: muc_admin
        access_admin: muc_admin
        history_size: 20
        max_users: 50
        max_room_id: 20
        max_room_name: 40
        max_room_desc: 300
        min_message_interval: 1
        min_presence_interval: 5
        default_room_options:
          allow_change_subj: false
          allow_user_invites: true
          moderated: false
          persistent: false
      mod_muc_admin: {}
  domain2.tld:
    modules:
      mod_muc:
        host: "conference.@HOST@"
        access: all
        access_create: all
        access_persistent: muc_admin
        access_admin: muc_admin
        history_size: 20
        max_users: 50
        max_room_id: 20
        max_room_name: 40
        max_room_desc: 300
        min_message_interval: 1
        min_presence_interval: 5
        default_room_options:
          allow_change_subj: false
          allow_user_invites: true
          moderated: false
          persistent: false
      mod_muc_admin: {}
```
