### ISSUE TITLE
eJabberd Federation - Stream closed by local host: Idle connection (connection-timeout)

### ISSUE THREAD

**Issue by logicwonder** [processone/ejabberd#3105]
## Environment

- ejabberd version: 19.02
- Erlang version: `9.2`
- OS: Ubuntu Server 16.04 LTS
- Installed from: source 
- Federated 2 servers with single test user in each server.
  - user01@abc.xyx.com  in node-1
  - user02@pqr.xyz.com in node-2

## Configuration:
```
loglevel: 5
log_rotate_size: 0
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "abc.xyz.com"
route_subdomains: s2s
certfiles:
  
  - "/etc/letsencrypt/live/localhost/fullchain.pem"
  - "/etc/letsencrypt/live/localhost/privkey.pem"
s2s_cafile: "/etc/ssl/certs/ca-certificates.crt"
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    protocol_options:
     - "no_sslv2"
     - "no_sslv3"
     - "no_tlsv1"
     - "no_tlsv1_1"
    ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POL
Y1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDH
E-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/api": mod_http_api
    web_admin: true
    captcha: true
  
    
s2s_use_starttls: false
auth_method: sql
auth_password_format: scram
sql_type: pgsql
sql_server: "xxx.xxx.xxx.xxx"
sql_database: "xxxxx"
sql_username: "xxxxx"
sql_password: "xxxxxx"
sql_port: 5432
default_db: sql
shaper:
  normal: 1000
  fast: 100000
max_fsm_queue: 10000
acl:
  admin: 
    user: 
       - "admin@abc.xyz.com" 
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 1500
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: admin
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - ip: "xxx.xxx.xxx.xxx/32"
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "xxx.xxx.xxx.xxx/32"
    what:
      - "status"
      - "connected_users_number"
  "API used from localhost allows all calls":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "*"
      - "!stop"
      - "!start"
  
language: "en"
acme:
   contact: "mailto:example-admin@example.com"
   ca_url: "https://acme-v01.api.letsencrypt.org"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_echo: {}
  mod_bosh: {}
  mod_last: {}
  mod_mam:
    default: always
    db_type: sql
  mod_muc:
    max_user_conferences: 100
    host: "conference.@HOST@"
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      allow_subscription: true
      mam: true
      persistent: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      "storage:bookmarks":
        access_model: whitelist
  mod_push: 
    include_sender: true
  mod_push_keepalive: {}
  mod_roster:
    use_cache: true
    cache_size: 10000
    cache_life_time: 3600
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_avatar: {}
  mod_version: {}
  mod_stream_mgmt: 
    max_ack_queue: 1000
    resume_timeout: 300     
    max_resume_timeout: 300
    resend_on_timeout: true  
    ack_timeout: 60
  mod_s2s_dialback: {}
  mod_http_api: {}
  mod_fail2ban: {}
allow_contrib_modules: true
```

## Errors from error.log/crash.log

20:22:57.638 [debug] route:
#message{
    id = <<"Pe0bb0390-cc1d-4be7-b21a-b345dee1f00c">>,type = error,
    lang = <<"en">>,
    from =
        #jid{
            user = <<"user02">>,server = <<"pqr.xyz.com">>,
            resource = <<>>,luser = <<"user02">>,
            lserver = <<"pqr.xyz.com">>,lresource = <<>>},
    to =
        #jid{
            user = <<"user01">>,server = <<"abc.xyz.com">>,
            resource = <<"TestClient">>,luser = <<"user01">>,
            lserver = <<"abc.xyz.com">>,lresource = <<"TestClient">>},
    subject = [],
    body =
        [#text{
             lang = <<>>,
             data =
                 <<"Sample test message">>}],
    thread = undefined,
    sub_els =
        [#xmlel{
             name = <<"request">>,
             attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>}],
             children = []},
         #xmlel{
             name = <<"request">>,
             attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>}],
             children = []},
         #stanza_error{
             type = wait,code = 504,by = undefined,
             reason = 'remote-server-timeout',
             text =
                 [#text{
                      lang = <<"en">>,
                      data =
                          <<"Stream closed by local host: Idle connection (connection-timeout)">>}],
             sub_els = []}],
    meta = #{ip => {0,0,0,0,0,65535,2722,1360},mam_archived => true}}

## Bug description

We have configured eJabberd Federation with two eJabberd server instances:

- abc.xyz.com
- pqr.xyz.com

We are using Smack 4.3 for the test client. **We are able to send and received one to one and group messages across the federated instances.**

However **intermittently** we come across the  "**remote-server-timeout    Stream closed by local host: Idle connection (connection-timeout)**" error in the sender node-1 (abc.xyz.com) and messages are not delivered at receiver node-2 (pqr.xyz.com). During this time user02 is able to send messages to user01. This issue is also observed the other way around.
