### ISSUE TITLE
mod_push warning: feature-not-implemented (cancel) disabling the push

### ISSUE THREAD

**Issue by logicwonder** [processone/ejabberd#3121]
## Environment

- ejabberd version: 19.09.1
- Erlang version: 10.6.1
- OS: Linux (Debian)
- Installed from: source 

## Configuration:
```
loglevel: 4
log_rotate_size: 10485760
log_rotate_date: "$D0"
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "testserver.com"
certfiles:

  - "/etc/ssl/ejabberd/testserver.pem"
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    protocol_options:
     - "no_sslv2"
     - "no_sslv3"
     - "no_tlsv1"
     - "no_tlsv1_1"
    ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POL
Y1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDH
E-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
    starttls: true
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/api": mod_http_api
      "/admin": ejabberd_web_admin
      "/captcha": ejabberd_captcha
  -
    port: 8888
    module: ejabberd_service
    access: all
    check_from: false
    shaper: fast
    ip: "xxx.xxx.xxx.xxx"
    hosts:
       "push.testserver.com":
         password: "********"

auth_method: sql
auth_password_format: scram
sql_type: pgsql
sql_server: "xxx.xxx.xxx.xxx"
sql_database: "****"
sql_username: "****"
sql_password: "*********"
sql_port: 5432
default_db: sql
shaper:
  normal: 1000
  fast: 100000
max_fsm_queue: 10000
acl:
  admin:
    user:
       - "admin@testserver.com"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 1500
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: admin
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - ip: "xxx.xxx.xxx.xxx/32"
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "xxx.xxx.xxx.xxx/32"
    what:
      - "status"
      - "connected_users_number"
  "API used from localhost allows all calls":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "*"
      - "!stop"
      - "!start"

language: "en"
acme:
   contact: "mailto:example-admin@example.com"
   ca_url: "https://acme-v01.api.letsencrypt.org"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_bosh: {}
   mod_last: {}
  mod_mam:
    default: always
    db_type: sql
  mod_muc:
    max_user_conferences: 100
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      allow_subscription: true
      mam: true
      persistent: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      "storage:bookmarks":
        access_model: whitelist
  mod_push:
    include_sender: true
  mod_push_keepalive: {}
  mod_roster:
    use_cache: true
    cache_size: 10000
    cache_life_time: 3600
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_avatar: {}
  mod_version: {}
  mod_stream_mgmt:
    max_ack_queue: 1000
    resume_timeout: 300   
    max_resume_timeout: 300
    resend_on_timeout: true 
    ack_timeout: 60
  mod_s2s_dialback: {}
  mod_http_api: {}
  mod_fail2ban: {}
allow_contrib_modules: true

```

## Errors from error.log
`2019-12-20 21:09:15.833 [info] <0.2250.0>@mod_stream_mgmt:transition_to_pending:451 (tls|<0.2250.0>) Closing c2s connection for sam@testserver.com/cli: Connection failed: connection closed; waiting 300 seconds for stream resumption
2019-12-20 21:09:17.694 [warning] <0.439.0>@mod_push:notify:461 push.testserver.com rejected notification for sam@testserver.com (sam@testserver.com), **disabling push: feature-not-implemented (cancel)**`

## Bug description
We are trying to configure ejabberd to push notifications to FCM by implementing a app server (XEP-0357). When the user goes offline, the record in push_session is deleted and the following IQ is received in the app server log:

`<iq to="push.testserver.com" from="testserver.com" type="set" id="rr-1576856571071-18403269807138247376-tvZYPvSQzFO2ti5dd8ZiIFtUySY=-55238004"><pubsub xmlns="http://jabber.org/protocol/pubsub"><publish node="sam@testserver"><item><notification xmlns="urn:xmpp:push:0"/></item></publish><publish-options><x xmlns="jabber:x:data" type="submit"><field var="FORM_TYPE"><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var="secret"><value>ctN-MXfg3zQ:APA91bGuDRhHMTT_PsjgNETh0IMht6iyzRlngE9FmmcnmRJbHAqxXdaplAyliDAoWd1qpCMIaAmBQXaE5fSNgDg_r8VZqxydDUgMyDA5guSAffh9elZ6Qt_Q8Un3gf1LKEnFJ_ufVwtb</value></field></x></publish-options></pubsub></iq>  `

Why do I get the error feature-not-implemented (cancel) disabling the push?
Currently I am not acknowledging/replying to any IQ received at the external service. Could that be a problem?
