### ISSUE TITLE
oauth_issue_token - case clause issue

### ISSUE THREAD

**Issue by Shruthi-Bharadwaj** [processone/ejabberd#3122]
## Environment

- ejabberd version: 19.09.57
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.5.6
- OS: Centos
- Installed from: source

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

Please, give us a precise description (what does not work, what is expected, etc.)

I have deployed ejabberd on a aws server with a certain IP and hostname as `ejabberd.myname.test`

From my NodeJS server I am trying to hit the ejabberd API to issue token for a certain jid:
```
return` rp({
      uri: `${EJABBERD_URL}/api/oauth_issue_token`,
      method: 'POST',
      headers: {
        'X-Admin': true,
        'Authorization': this.adminAuth,
      },
      body: {
        jid,
        ttl: 3600,
        scopes: "sasl_auth"
      },
      json: true,
    })

```

> where: 
> EJABBERD_URL : ejabberd.myname.test:5280
> this.adminAuth:  "Basic " + new Buffer(EJABBERD_ADMIN_USERNAME + ":" + EJABBERD_ADMIN_PASSWORD).toString("base64");

There is a case_clause error thrown upon hitting this API:

```
 [info] (<0.558.0>) Accepted connection [::ffff:192.168.0.100]:54170 -> [::ffff:192.168.0.200]:5280
2019-12-23 12:28:52.060635+05:30 [info] API call oauth_issue_token [{<<"jid">>,<<"anish@ejabberd.quezx.test">>},
                            {<<"ttl">>,3600},
                            {<<"scopes">>,<<"sasl_auth">>}] from ::ffff:192.168.0.100:54170
2019-12-23 12:28:52.061433+05:30 [error] REST API Error: oauth_issue_token([{<<"jid">>,<<"anish@ejabberd.myname.test">>},
                                   {<<"ttl">>,3600},
                                   {<<"scopes">>,<<"sasl_auth">>}]) -> error:{case_clause,
                                                                              admin_generated} [{ejabberd_oauth,
                                                                                                 authenticate_user,
                                                                                                 2,
                                                                                                 [{file,
                                                                                                   "src/ejabberd_oauth.erl"},
                                                                                                  {line,
                                                                                                   263}]},
                                                                                                {oauth2,
                                                                                                 auth_user,
                                                                                                 3,
                                                                                                 [{file,
                                                                                                   "src/oauth2.erl"},
                                                                                                  {line,
                                                                                                   351}]},
                                                                                                {ejabberd_oauth,
                                                                                                 oauth_issue_token,
                                                                                                 3,
                                                                                                 [{file,
                                                                                                   "src/ejabberd_oauth.erl"},
                                                                                                  {line,
                                                                                                   140}]},
                                                                                                {mod_http_api,
                                                                                                 handle2,
                                                                                                 4,
                                                                                                 [{file,
                                                                                                   "src/mod_http_api.erl"},
                                                                                                  {line,
                                                                                                   267}]},
                                                                                                {mod_http_api,
                                                                                                 handle,
                                                                                                 4,
                                                                                                 [{file,
                                                                                                   "src/mod_http_api.erl"},
                                                                                                  {line,
                                                                                                   228}]},
                                                                                                {mod_http_api,
                                                                                                 perform_call,
                                                                                                 4,
                                                                                                 [{file,
                                                                                                   "src/mod_http_api.erl"},
                                                                                                  {line,
                                                                                                   188}]},
                                                                                                {mod_http_api,
                                                                                                 process,
                                                                                                 2,
                                                                                                 [{file,
                                                                                                   "src/mod_http_api.erl"},
                                                                                                  {line,
                                                                                                   141}]},
                                                                                                {ejabberd_http,
                                                                                                 process,
                                                                                                 2,
                                                                                                 [{file,
                                                                                                   "src/ejabberd_http.erl"},
                                                                                                  {line,
                                                                                                   366}]}]


```

Here is my ejabberd.yml file

```
###
###              ejabberd configuration file
###
### The parameters used in this configuration file are explained at
###
###       https://docs.ejabberd.im/admin/configuration
###
### The configuration file is written in YAML.
### *******************************************************
### *******           !!! WARNING !!!               *******
### *******     YAML IS INDENTATION SENSITIVE       *******
### ******* MAKE SURE YOU INDENT SECTIONS CORRECTLY *******
### *******************************************************
### Refer to http://en.wikipedia.org/wiki/YAML for the brief description.
###

hosts:
  - ejabberd.myname.test

loglevel: info

## If you already have certificates, list them here
#  certfiles:
#  - /etc/letsencrypt/live/domain.tld/fullchain.pem
#  - /etc/letsencrypt/live/domain.tld/privkey.pem

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      /admin: ejabberd_web_admin
      /api: mod_http_api
      /bosh: mod_bosh
      /captcha: ejabberd_captcha
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    http_bind: true
    register: true
    web_admin: true
    request_handlers:
      /admin: ejabberd_web_admin
      /oauth: ejabberd_oauth
      /api: mod_http_api
      /bosh: mod_bosh
      /.well-known/acme-challenge: ejabberd_acme
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000

s2s_use_starttls: optional

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::ffff:192.168.0.100/128

  admin:
    user:
      - "gloryque@ejabberd.myname.test"

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: all

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: admin
          #acl: loopback
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: admin
            #acl: loopback
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - check_account
      - register
      - status
      - connected_users_number
      - oauth_issue_token
  "API used from localhost allows all calls":
    who:
      ip: "0.0.0.0/8"
    what:
      - "*"
      - "!stop"
      - "!start"

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    db_type: sql
    assume_mam_usage: true
    default: always
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      mam: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  #mod_http_bind: {} 
  mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: all
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false


auth_method: sql
default_db: sql
new_sql_schema: true
sql_type: mysql
sql_server: <server_IP_Address>
sql_port: 3306
sql_database: "<DB_Name>"
sql_username: "<BD_Username>"
sql_password: "<DB_Password>"
sql_pool_size: 5

oauth_access: all



### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8

```
