### ISSUE TITLE
Ejabberd 19.x does not support external HTTP auth

### ISSUE THREAD

**Issue by Adiii717** [processone/ejabberd#3124]
## Environment

- ejabberd version: 19.x
- Erlang version: `Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]`
- OS: Linux (Debian)
- Installed from: Offical Docker image

## Configuration 
```
auth_method: http
auth_opts:
  host: "http://localhost:12000"
  connection_pool_size: 10
  connection_opts: []
  basic_auth: ""
  path_prefix: "/"
...
```

## Errors from error.log/crash.log

```
06:30:30.437 [critical] Failed to start ejabberd application: Invalid value of option auth_method->1: unsupported database: http
```

## Bug description

The ejabberd external HTTP auth module stop working with 19.x and the config not allow me to use `auth_method:http`, it crashes with the mentioned error, previously we were able to authenticate users using this module.
https://github.com/processone/ejabberd-contrib/tree/master/ejabberd_auth_http
Thanks
