### ISSUE TITLE
Can't connect from ejabberd to any pushservers (no SASL)

### ISSUE THREAD

**Issue by centertivevier** [processone/ejabberd#3133]
## Environment

- ejabberd version: 19.01
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.2.4`
- OS: Linux (Debian 10)
- Installed from: source: deb http://deb.debian.org/debian buster-backports | distro package: ejabberd/buster-backports,now 19.09.1-1~bpo10+1 amd64

## Configuration:

```yaml

sql_type: mysql
loglevel: 3
hide_sensitive_log_data: true

log_rotate_size: 0
log_rotate_date: ""

###.  ================
###'  SERVED HOSTNAMES

hosts:
  - "myserver.com"

###.  ============
###'  Certificates

certfiles:
  - "/etc/ejabberd/certs/x.key"
  - "/etc/ejabberd/certs/x.crt"


###.  =================
###'  TLS configuration

define_macro:
  'TLS_CIPHERS': "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384"
  'TLS_OPTIONS':
    - "no_sslv3"
    - "no_tlsv1"
    - "no_tlsv1_1"
    - "cipher_server_preference"
    - "no_compression"
  'DH_FILE': "/etc/ejabberd/dh4096.pem"

c2s_ciphers: 'TLS_CIPHERS'
s2s_ciphers: 'TLS_CIPHERS'
c2s_protocol_options: 'TLS_OPTIONS'
s2s_protocol_options: 'TLS_OPTIONS'
c2s_dhfile: 'DH_FILE'
s2s_dhfile: 'DH_FILE'

###.  ===============
###'  LISTENING PORTS

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls_required: true
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s

    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288

disable_sasl_mechanisms:
  - "digest-md5"
  - "x-oauth2"

###.  ==================
###'  S2S GLOBAL OPTIONS

s2s_use_starttls: required

###.  ==============
###'  AUTHENTICATION

auth_method: sql
auth_password_format: scram

###.  ===============
###'  TRAFFIC SHAPERS

shaper:
  normal: 1000
  fast: 50000

max_fsm_queue: 10000

###.   ====================
###'   ACCESS CONTROL LISTS

acl:
  admin:
     user:
       - "ABX": "myserver.com"

  local:
    user_regexp: ""

  shortname:
    user_glob:
      - "?"
      - "??"

  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"

###.  ============
###'  SHAPER RULES

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 500
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast

###.  ============
###'  ACCESS RULES

access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - deny: shortname
    - allow: all
  trusted_network:
    - allow: local

## ===============
## API PERMISSIONS
## ===============

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
        - allow:
          - acl: loopback
          - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"
###.  =======
###'  CAPTCHA

captcha_cmd: "/usr/share/ejabberd/captcha.sh"
captcha_limit: 5

###.  =======
###'  MODULES

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_block_strangers: {}
  mod_blocking: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  ## mod_delegation: {}  
  mod_disco:
    server_info:
      -
        modules: all
        name: "abuse-addresses"
        urls:
          - "mailto:webmaster@myserver.com"
      -
        modules: all
        name: "support-addresses"
        urls:

          - "mailto:webmaster@myserver.com"
      -
         modules: all
         name: "admin-addresses"
         urls:
           - "mailto:webmaster@myserver.com"
  ## mod_echo: {}
  mod_bosh: {}
  ## mod_http_fileserver:
  mod_http_upload:
    host: "upload.@HOST@"
    docroot: "/opt/ejabberd/upload"
    put_url: "https://upload.myserver.com/"
    get_url: "https://upload.myserver.com/"
    secret_length: 40
    file_mode: "0640"
    dir_mode: "2750"
    max_size: 1048218029 # 1 GB
    access: local
    thumbnail: true
    custom_headers:
      "Access-Control-Allow-Origin": "https://upload.myserver.com/"
      "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type"
  mod_http_upload_quota:
    max_days: 7
  mod_last: {}
  mod_mam:
    db_type: sql
    assume_mam_usage: true
    default: always
    request_activates_archiving: true
  mod_muc:
    host: "konf.@HOST@"
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      mam: true
      persistent: true
      public: false
      public_list: false
  mod_muc_admin: {}
  ## mod_muc_log: {}
  ## mod_multicast: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_pres_counter:
    count: 16
    interval: 60
 mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    host: "proxy65.@HOST@"
    port: 55555
    ip: "127.0.0.1"
    max_connections: 5
  mod_pubsub:
    db_type: sql
    host: "pubsub.@HOST@"
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins:
      - "flat"
      - "pep"
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: open
      "storage:bookmarks":
        access_model: whitelist
  mod_push:
    include_sender: false
    include_body: "Hej da"
    db_type: sql
  mod_push_keepalive:
    wake_on_start: true
    wake_on_timeout: true
    resume_timeout: 1800
  mod_register:
    captcha_protected: true
    password_strength: 64
    ip_access: all
    access: register
  mod_roster:
    db_type: sql
    versioning: true
  mod_shared_roster: {}
  mod_sic: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_avatar: {}
  mod_version:
    show_os: false
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  ##mod_s2s_dialback: {}
  ## mod_http_api: {}
  mod_fail2ban: {}

allow_contrib_modules: true

```

## Errors from error.log/crash.log

```
2019-12-30 23:16:37.572 [warning] <0.510.0>@ejabberd_s2s_out:handle_auth_failure:219 (tls|<0.510.0>) Failed outbound s2s EXTERNAL authentication myserver.com -> push.tigase.im (hidden_by_ejabberd): Authentication failed: Peer provided no SASL mechanisms; most likely it doesn't accept our certificate
2019-12-30 23:16:37.572 [warning] <0.510.0>@ejabberd_s2s_out:process_auth_result:138 Failed to establish outbound s2s connection myserver.com -> push.tigase.im: authentication failed; bouncing for 274 seconds

The server send the on debugmode the following stanzas:

2019-12-29 23:21:34.720 [debug] <0.363.0>@ejabberd_s2s:route:347 Local route:
#iq{id =
        <<"rr-1577658126717-9710391111879476430-VNzivZ3vFHMI/7787JoFmMtd+bM=-55238004">>,
    type = set,lang = <<>>,
    from =
        #jid{
            user = <<>>,server = <<"myserver.com">>,resource = <<>>,
            luser = <<>>,lserver = <<"myserver.com">>,lresource = <<>>},
    to =
        #jid{
            user = <<>>,server = <<"push.tigase.im">>,resource = <<>>,
            luser = <<>>,lserver = <<"push.tigase.im">>,lresource = <<>>},
    sub_els =
        [#pubsub{
             subscriptions = undefined,subscription = undefined,
             affiliations = undefined,
             publish =
                 #ps_publish{
                     node =
                         <<"642A927D1670831FA0CA18F91BC5B28C18B93A483EABEF4CD41561EA75E13F7F">>,
                     items =
                         [#ps_item{
                              xmlns = <<>>,id = <<>>,
                              sub_els =
                                  [#push_notification{xdata = undefined}],
                              node = <<>>,publisher = <<>>}]},
             publish_options = undefined,subscribe = undefined,
             unsubscribe = undefined,options = undefined,items = undefined,
             retract = undefined,create = undefined,configure = undefined,
             default = undefined,delete = undefined,purge = undefined,
             rsm = undefined}],
    meta = #{}}
2019-12-29 23:21:34.720 [debug] <0.363.0>@ejabberd_s2s:start_connection:382 Finding connection for {<<"myserver.com">>,<<"push.tigase.im">>}
2019-12-29 23:21:34.720 [info] <0.511.0>@ejabberd_s2s_out:init:273 Outbound s2s connection started: myserver.com -> push.tigase.im
2019-12-29 23:21:34.720 [debug] <0.363.0>@ejabberd_s2s:choose_pid:432 Using ejabberd_s2s_out <0.511.0>
2019-12-29 23:21:34.720 [debug] <0.363.0>@ejabberd_s2s:route:352 Sending to process <0.511.0>
2019-12-29 23:21:34.722 [debug] <0.363.0>@ejabberd_router:do_route:384 Route:
#iq{id =
        <<"rr-1577658126720-17199199313451245463-7UBqV0fLYu+BkVm9gUT8hHmzUng=-55238004">>,
    type = set,lang = <<>>,
    from =
        #jid{
            user = <<>>,server = <<"myserver.com">>,resource = <<>>,
            luser = <<>>,lserver = <<"myserver.com">>,lresource = <<>>},
    to =
        #jid{
            user = <<>>,server = <<"push.pix-art.de">>,resource = <<>>,
            luser = <<>>,lserver = <<"push.pix-art.de">>,lresource = <<>>},
    sub_els =
        [#pubsub{
             subscriptions = undefined,subscription = undefined,
             affiliations = undefined,
             publish =
                 #ps_publish{
                     node = <<"snKfHCckWkB0">>,
                     items =
                         [#ps_item{
                              xmlns = <<>>,id = <<>>,
                              sub_els =
                                  [#push_notification{xdata = undefined}],
                              node = <<>>,publisher = <<>>}]},
             publish_options =
                 #xdata{
                     type = submit,instructions = [],title = undefined,
                     reported = undefined,items = [],
                     fields =
                         [#xdata_field{
                              label = <<>>,type = hidden,
                              var = <<"FORM_TYPE">>,required = false,
                              desc = <<>>,
                              values =
                                  [<<"http://jabber.org/protocol/pubsub#publish-options">>],
                              options = [],sub_els = []},
                          #xdata_field{
                              label = <<>>,type = undefined,
                              var = <<"secret">>,required = false,desc = <<>>,
                              values = [<<"BGd/zmQWYqB+AeDMQLP4JnCw">>],
                              options = [],sub_els = []}]},
             subscribe = undefined,unsubscribe = undefined,
             options = undefined,items = undefined,retract = undefined,
             create = undefined,configure = undefined,default = undefined,
             delete = undefined,purge = undefined,rsm = undefined}],
    meta = #{}}
```

## Bug description

i used a "Ejabberd 19.09.1" on my system and with Conversations from F-Droid is all fine. But used the clients a programm with a pushserver in example Monal, Siskin or PixArt-Messenger for GCM or Applepush, they
can't connected from ejabberd to the pushserver. I get the following error on all pushserver:

I set the starttls required to false, enable die md5-hash, used very smoove ciphersuite, on all the same problem. I think is a problem on my config, but with this bug you can used xmpp with Iphones, then push are not worked. Connecting to other server like user or muc works all fine!

Have any one a idea what the problem is?
