### ISSUE TITLE
API created muc_room , phone sdk can not fetch it's options

### ISSUE THREAD

**Issue by arpitvaishnav** [processone/ejabberd#3141]
I am creating muc_room from the admin API with all the required options of the team. 

```
{title,<<"1 X Team">>},
 {description,<<>>},
 {allow_change_subj,true},
 {allow_query_users,true},
 {allow_private_messages,true},
 {allow_private_messages_from_visitors,anyone},
 {allow_visitor_status,true},
 {allow_visitor_nickchange,true},
 {public,false},
 {public_list,true},
 {persistent,true},
 {moderated,true},
 {members_by_default,true},
 {members_only,true},
 {allow_user_invites,true},
 {password_protected,false},
 {captcha_protected,false},
 {password,<<>>},
 {anonymous,true},
 {logging,false},
 {max_users,200},
 {allow_voice_requests,true},
 {allow_subscription,true},
 {mam,true},
 {presence_broadcast,[moderator,participant,visitor]},
 {voice_request_min_interval,'1800'},
 {vcard,<<>>},
 {captcha_whitelist,[]},
 {affiliations,[{{<<"z">>,<<x.y.care">>,<<>>},{owner,<<>>}}]},
 {subject,[]},
 {subject_author,<<>>}]

```
mod_muc settings on the server 
```
  mod_muc:
    db_type: sql
    access_admin:
      allow: admin
    access_create: muc_create
    access_persistent: muc_create
    history_size: 30
    max_rooms_discoitems: 1000
    max_user_conferences: 105
    max_users_presence: 100
    min_presence_interval: 0
```

Now, the owner of the team is not able to access the options of team from mobile SDK 
which again is possible if with the same option created from SDK.

any reason? Any solution

**Comment by licaon-kter** [comment]
What SDK? Detail your setup exactly

**Comment by arpitvaishnav** [comment]
We have a live application IOS (ejabberd) and Android (Smack) and ROR backend. 
Till now the muc_room is created and updated from (IOS / Android) SDKs which is working fine.

As per the new requirement, we have started adding many teams together from API with exactly the same options + affiliations (API) used by mobile. 

- This also let us add teams on the ejabberd similar to mobile SDKs (done) 
- We can see teams from API on mobile (done)
- when we update  room which was created from API, we are not getting any error or any response, 
 and on refresh, we lose the room from disco items

**Comment by arpitvaishnav** [comment]
Here is a detailed configuration of ejabberd server
```
loglevel: 5
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "www.eeee.com"
certfiles:
  - "/home/ejabberd/conf/ssl/www.eeee.com.pem"
define_macro:
  'TLS_CIPHERS': "HIGH:!aNULL:!eNULL:!3DES:@STRENGTH"
  'TLS_OPTIONS':
    - "no_sslv3"
    - "cipher_server_preference"
    - "no_compression"
c2s_ciphers: 'TLS_CIPHERS'
s2s_ciphers: 'TLS_CIPHERS'
c2s_protocol_options: 'TLS_OPTIONS'
s2s_protocol_options: 'TLS_OPTIONS'
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    certfile: /home/ejabberd/conf/ssl/www.eeee.com.pem
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5223
    ip: "::"
    module: ejabberd_c2s
    access: c2s
    shaper: c2s_shaper
    tls: true
    max_stanza_size: 65536
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
  
    web_admin: true
    register: true
    captcha: false
    certfile: "/home/ejabberd/conf/ssl/www.eeee.com.pem"
  -
    port: 5281
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
  
    web_admin: true
    register: true
    captcha: false
    tls: true
    certfile: "/home/ejabberd/conf/ssl/www.eeee.com.pem"
disable_sasl_mechanisms: ["X-OAUTH2"]
s2s_use_starttls: optional
auth_method: sql
default_db: sql
sql_type: mysql
sql_database: "ejabberd"
sql_password: "xsss"
sql_server: "xxx"
sql_username: "xxx"
sql_pool_size: 15
sql_port: 3306
shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 10000
acl:
  admin:
    user:
      - "user@www.eeee.com"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
shaper_rules:
  max_user_sessions: 30
  max_user_offline_messages:
    - 5000: admin
    - 30
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin

  muc_create:
    - allow: all

  pubsub_createnode:
    - allow: local
  register:
    - allow: all
    - registration_timeout: infinity

  trusted_network:
    - allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - user: user@www.eeee.com
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - user: user@www.eeee.com
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"
registration_timeout: infinity
language: "en"
acme:
  contact: "mailto:admin@ip-172-31-82-229.ec2.internal"
  ca_url: "https://acme-v01.api.letsencrypt.org"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
    db_type: sql
  mod_blocking: {} # requires mod_privacy
  mod_caps:
    db_type: sql
  mod_carboncopy: {}
  mod_client_state:
    queue_chat_states: true
    queue_pep: false
    queue_presence: true
  mod_configure: {} # requires mod_adhoc

  mod_disco: {}

  mod_irc:
    db_type: sql
  mod_bosh: {}
  mod_last:
    db_type: sql
  mod_mam:
    default: always
    db_type: sql
    
  mod_muc:
    db_type: sql
    access_admin:
      allow: admin
    access_create: muc_create
    access_persistent: muc_create  
    history_size: 30
    max_rooms_discoitems: 1000
    max_user_conferences: 105
    max_users_presence: 100
    min_presence_interval: 0
  mod_muc_admin: {}

  mod_multicast:
    host: "xx.yyy.com"
    access: multicast
    limits:
      local:
        message: 50
        presence: infinite
      remote:
        message: 50
        presence: infinite
  mod_offline:
    db_type: sql
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy:
    db_type: sql
  mod_private:
    db_type: sql
  mod_pubsub:
    db_type: sql
    access_createnode: pubsub_createnode
  
    ignore_pep_from_offline: true
  
  
    last_item_cache: false
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
    ip_access: all
    access: register
  mod_roster:
    db_type: sql
  mod_shared_roster:
    db_type: sql
  mod_vcard:
    db_type: sql
    search: true
  mod_vcard_xupdate: {}
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
  mod_http_api: {}
allow_contrib_modules: true

  - allow:
    - user: "xxx@yyy.com"
commands:
  add_commands:
    - status
    - registered_users
    - register
    - unregister
    - get_roster
    - connected_users
    - send_stanza_c2s
    - send_stanza
    - join_cluster
    - send_direct_invitation
    - subscribe_room
    - get_user_rooms
    - get_presence 
oauth_expire: 3600
oauth_access: all

```

**Comment by badlop** [comment]
I don't understand why it fails. As you don't provide your ejabberd version, or your API calls, there may be some important detail in your setup to explain your problem.

I'll detail how I test it, so you can replicate my test, and hopefully find the divergence and source of the problem:

1. Install ejabberd 19.09.1
2. I configure with simple MUC options, almost equivalent to yours:
```
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
```
3. Start ejabberd
4. Register account user7@localhost
5. Create a new room, and make user7 an owner, so he has permission to get the room options:
```
$ ejabberdctl create_room room2api conference.localhost localhost
$ ejabberdctl set_room_affiliation room2api conference.localhost user7@localhost owner
```
6. Now user7 logins with a Jabber client and requests the room options:
```
<iq id='42:674539'
	xml:lang='es'
	type='get'
	to='room2api@conference.localhost'>
  <query xmlns='http://jabber.org/protocol/muc#owner'/>
</iq>

<iq xml:lang='es'
	to='user7@localhost/tka1'
	from='room2api@conference.localhost'
	type='result'
	id='42:674539'>
  <query xmlns='http://jabber.org/protocol/muc#owner'>
    <x type='form'
	xmlns='jabber:x:data'>
      <title>Configuration of room room2api@conference.localhost</title>
      <field var='FORM_TYPE'
	type='hidden'>
        <value>http://jabber.org/protocol/muc#roomconfig</value>
      </field>
      <field var='muc#roomconfig_roomname'
	type='text-single'
	label='Título de la sala'/>
      <field var='muc#roomconfig_roomdesc'
	type='text-single'
	label='Descripción de la sala'/>
      <field var='muc#roomconfig_lang'
	type='text-single'
	label='Natural Language for Room Discussions'>
        <value/>
      </field>
...
```
