### ISSUE TITLE
How to request API with basic auth?

### ISSUE THREAD

**Issue by xdnroot** [processone/ejabberd#3147]
Hi, I didn't see example request parameter that needed in order to exec api command with basic auth in ejabberd documentation, except: [https://docs.ejabberd.im/developer/ejabberd-api/admin-api/](https://docs.ejabberd.im/developer/ejabberd-api/admin-api/)

And my question is:

> what are the parameters needed to get data from API request with Basic Auth?

I tried to request to _https://mydomain.com/api/check_account_ like this, HTTP Header
`X-Admin: true`
`Authorization: Basic`
And with data json:
`{
	"user": "user",
	"host": "mydomain.com"
}`

This is the response frome that request:
`{"status":"error","code":10,"message":"You are not authorized to call this command."}`

In my config yml file, I just set default configuratiion to allow admin (user@mydomain.com is admin):

```
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
	allow:
          acl: globalip
          acl: admin
      oauth:
	scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
```
