### ISSUE TITLE
LDAPs not working on w12k?

### ISSUE THREAD

**Issue by Snowmanko** [processone/ejabberd#3151]
Hi,

we have recently upgraded our Windows Servers (Active Directory) from 2008 to 2012 and ejabberd suddenly stoped working. Can someone identify this issue?

`2020-01-25 13:26:54.093 [error] <0.483.0>@eldap:connect_bind:1073 LDAP connection to 10.1.2.3:636 failed: TLS connection is closed`

ejabberd configuration was not changed. I've searched for everything and I could not make it work.

`OS is Debian 9, ejabberd 18.09-2~bpo9+1, openssl 1.1.0l-1~deb9u1 `

```
host_config:
  "jabber.domain.com":
   auth_method: ldap
   language: "cs"
   ldap_base: "[redacted]"
   ldap_encrypt: tls
   ldap_filter: "[redacted]"
   ldap_uids: ["sAMAccountName"]
   ldap_password: "[redacted]"
   ldap_port: 636
   ldap_rootdn: "[redacted]"
   ldap_servers: 
    - "10.1.2.3"
```
