### ISSUE TITLE
Ejabberd 18.1.0 ignore accept_interval for C2S

### ISSUE THREAD

**Issue by Adiii717** [processone/ejabberd#3162]
## Environment

- ejabberd version: 18.1.0
- OS: Linux (Alpine)
- Installed from: docker image

## Configuration ejabberd.yml

```yaml
listen:
  - 
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    accept_interval: 100
...
```

## Bug description

Ejabberd does not crash but seems like its ignoring the `acept_interval` option.
```
00:06:28.546 [error] unknown listen option 'accept_interval' for 'ejabberd_c2s' will be likely ignored, available options are: access, shaper, certfile, ciphers, dhfile, cafile, protocol_options, tls, tls_compression, starttls, starttls_required, tls_verify, zlib, max_fsm_queue
```
