### ISSUE TITLE
ejabberdctl reload_config exits with code 1 for no apparent reason

### ISSUE THREAD

**Issue by vthriller** [processone/ejabberd#3170]
## Environment

- ejabberd version: 20.01
- Erlang version: `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.2.1`
- OS: Linux (Alpine 3.9.5)
- Installed from: official docker image (`ejabberd/ecs:20.01`)

## Configuration (only if needed):

Heavily trimmed (and a bit abbreviated) stock config:

```yaml
hosts: [localhost]

loglevel: 4
log_rotate_size: 10485760
log_rotate_count: 10

certfiles: []
acme:
  auto: false

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true

s2s_use_starttls: optional

acl:
  local: {user_regexp: ""}
  loopback: {ip: [127.0.0.0/8]}
  admin: {user: []}

access_rules:
  local: {allow: local}
  c2s: {allow: all}

api_permissions:
  "console commands":
    from: [ejabberd_ctl]
    who: all
    what: "*"

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  c2s_shaper:
    none: admin
    normal: all

max_fsm_queue: 10000

modules: {}
```

## Bug description

Start ejabberd:

```
# docker run --name ejabberd -v $(pwd)/ejabberd.yml:/home/ejabberd/conf/ejabberd.yml ejabberd/ecs:20.01
```

It seems to be ok with the config:

```
[info] Loading configuration from /home/ejabberd/conf/ejabberd.yml
[info] Configuration loaded successfully
[info] Loading modules for localhost
[info] Waiting for Mnesia synchronization to complete
[info] ejabberd 20.1.0 is started in the node ejabberd@32ed935e8f1a in 2.32s
[info] Start accepting TCP connections at [::]:5222 for ejabberd_c2s
```

But if we reload the same config, with or without any changes, `ejabberdctl` exits with 1 with no complaints otherwise.

```
# docker exec -it ejabberd sh
# bin/ejabberdctl set_loglevel debug; echo $?
0
# bin/ejabberdctl reload_config; echo $?
1
```

Maybe logs will say more? Nope, that's all I got:

```
[debug] Command 'reload_config' execution allowed by rule 'console commands' (CallerInfo=#{caller_module =>
                                                      ejabberd_ctl})
```
