### ISSUE TITLE
ejabberdctl reload_config does not reload ldap options in host_config

### ISSUE THREAD

**Issue by gregkare** [processone/ejabberd#3181]
## Environment

- ejabberd version: 20.02 (previous versions too)
- Erlang version: `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.4`
- OS: Linux (Ubuntu 18.04)
- Installed from: official deb

## Configuration (only if needed):

```yaml
include_config_file: "/opt/ejabberd/conf/example.yml"
```

## Errors from error.log/crash.log

No errors

## Bug description

When running `ejabberdctl reload_config`, I expect the content of the included config file to be reloaded if it has changed. However, any change to an included config file is not applied until the service is restarted.

Is this by design, or is this a bug? In the meantime we are moving our vhosts back into the `/opt/ejabberd/conf/ejabberd.yml` file

**Comment by prefiks** [comment]
Hello,

Usually this will work, are there particular options that don't work that way? Did this happens just for some modules?

**Comment by gregkare** [comment]
The one I have ran into is the ldap config for vhosts. Changing the filter in the included config file does not have any effect when reloading the config, but it works as it should in the `ejabberd.yml` file. Example:

```yml
host_config:
  "example.com":
    sql_type: pgsql
    sql_server: "localhost"
    sql_database: "db"
    sql_username: "user"
    sql_password: "password"
    auth_method: ldap
    ldap_servers: ["localhost"]
    ldap_rootdn: "root"
    ldap_password: "password"
    ldap_encrypt: none
    ldap_tls_verify: hard # when TLS is enabled, don't proceed if a cert is invalid
    ldap_base: "base"
    ldap_filter: "(objectClass=person)"
```
