### ISSUE TITLE
Unable to exchange OMEMO keys with users on the same server

### ISSUE THREAD

**Issue by nek0** [processone/ejabberd#3195]
## Environment

- ejabberd version: 20.01
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.5.5
- OS: NIxOS 20.09pre217377.ee9362f880e (Nightingale)
- Installed from: distro package

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
hosts:
  - <redacted>
loglevel: 4
log_rotate_size: 0
log_rotate_date: "$D0"
log_rotate_count: 1
log_rate_limit: 100
hide_sensitive_log_data: true
listen:
  -
    port: 5222
    module: ejabberd_c2s
    starttls: true
    starttls_required: true
    zlib: true
  -
    port: 5269
    module: ejabberd_s2s_in
    transport: tcp
  -
    module: ejabberd_http
    port: 5280
    request_handlers:
      /.well-known/acme-challenge: ejabberd_acme
  -
    module: ejabberd_xmlrpc
    port: 4560
    ip: "127.0.0.1"
    access_commands: {}
s2s_use_starttls: required
outgoing_s2s_families:
  - ipv4
  - ipv6
acme:
  auto: true
  contact:
    - mailto:<redacted>
  cert_type: ec
  ca_url: https://acme-v02.api.letsencrypt.org/directory
auth_method: internal
auth_password_format: scram
language: de
acl:
  admin:
    - user: nek0
access_rules:
  admin:
    allow: admin
shaper_rules:
  max_user_offline_messages:
    - 5000: admin
    - 100
modules:
  mod_adhoc: {}
  mod_announce:
    access: admin
  mod_avatar: {}
  mod_vcard_xupdate: {}
  mod_pubsub:
    ignore_pep_from_offline: false
    last_item_cache: false
    max_items_node: 1000000
    plugins: 
      - "flat"
      - "hometree"
      - "pep"
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      "storage:bookmarks":
        access_model: whitelist
  mod_client_state:
    queue_chat_states: true
    queue_pep: false
    queue_presence: true
  mod_disco:
    server_info:
      -
        modules: all
        name: abuse-addresses
        urls: [mailto:<redacted>]
  mod_fail2ban:
    access: admin
  mod_last: {}
  mod_mam: {}
  mod_muc:
    access: all
    access_create: admin
    access_admin: admin
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping:
    send_pings: true
    ping_interval: 240
    timeout_action: kill
  mod_pres_counter:
    count: 5
    interval: 60
  mod_privacy: {}
  mod_proxy65: {}
  mod_caps: {}
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    access: none
  mod_roster:
    versioning: true
    store_current_id: true
  mod_s2s_dialback: {}
  mod_vcard:
    search: true
    matches: infinity
    allow_return_all: false
  mod_version: {}
```

## Errors from error.log/crash.log

No errors

## Bug description

When trying to query OMEMO-Keys for users on my own server from my account which resides on the same server I get no valid responses. Key exchange with other users on other servers works flawlessly, though.
