### ISSUE TITLE
Server returned unsecure transport in mode_http_upload

### ISSUE THREAD

**Issue by sandeepjangir** [processone/ejabberd#3219]
## Environment

- ejabberd version: 20.03
- Erlang version: `10.3.4`
- OS: Linux (Debian)
- Installed from: official binary installer

```yaml
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
#    tls: true
    request_handlers:
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws


mod_http_upload:
    name: "HTTP File Uploading"
    put_url: "http://@HOST@:5443/upload"
    access: http_upload_acl
    thumbnail: false
    docroot: "/opt/ejabberd/uploads"
    max_size: infinity
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET, HEAD, POST, PUT, OPTIONS, DELETE"
      "Access-Control-Allow-Headers": "Content-Type, Origin, X-Requested-With"
  mod_http_upload_quota:
    max_days: 100
    access_soft_quota:
        - 1000: all # MiB
    access_hard_quota:
        - 1100: all # MiB
...
```

## Errors from error.log/crash.log
stuck here

`19:25:31.640 [info] (tls|<0.517.0>) Send XML on stream = <<"<iq xml:lang='en' to='sandeep@chat.mydomain.co/gajim.JUYZA0GI' from='upload.chat.mydomain.co' type='result' id='fffea140-e726-4873-8fe8-fa18c056e42d'><slot xmlns='urn:xmpp:http:upload:0'><get url='http://chat.mydomain.co:5443/upload/c9c7de3b46766fdc9636e737ad6273a5afdc76a2/7sZ4xCo8OMAXgoFUwSUq3kD1dNqvZZ7jPTgI8DZs/1583061678528.pdf'/><put url='http://chat.mydomain.co:5443/upload/c9c7de3b46766fdc9636e737ad6273a5afdc76a2/7sZ4xCo8OMAXgoFUwSUq3kD1dNqvZZ7jPTgI8DZs/1583061678528.pdf'/></slot></iq>">>
`

## Issue description

When I am trying to upload any media from client like Gajim the info log stucks at single point without throwing any error and I cannot upload the media and receives the following error:

Note: I have checked the file permission and the the document directory is existing in the exact location what is mentioned in the config;

<img width="568" alt="Screenshot 2020-04-11 at 12 36 19 AM" src="https://user-images.githubusercontent.com/14825242/79023516-22603100-7b9e-11ea-94e2-d7e0ae464758.png">

Thanks in advance
Sandeep Jangir

**Comment by licaon-kter** [comment]
Use `httpS://path` instead?!

**Comment by sandeepjangir** [comment]
@licaon-kter 
Why it is not possible without ssl ?

**Comment by weiss** [comment]
> Why it is not possible without ssl ?

The error message is generated by Gajim, not ejabberd, so this is the wrong issue tracker to ask this question.

**Comment by sandeepjangir** [comment]
@weiss 
I have tried this with other clients as well and there is no log on the server and file failed to upload;
Even tried with postman to upload file at http://@HOST@:5443/upload but no luck

**Comment by weiss** [comment]
> I have tried this with other clients as well and there is no log on the server and file failed to upload

You might have tried things with "other clients", and maybe you got error messages, who knows.  The only thing you've show us is Gajim's error message that tells you about Gajim not allowing HTTP URLs.  So this is the only thing we can comment on.

**Comment by sandeepjangir** [comment]
When I tried to upload the media from any client I am not getting any error on ejabberd and getting this response:

You can see the last line info message, it stuck here and nothing happens;

<img width="1397" alt="Screenshot 2020-04-10 at 9 07 58 PM" src="https://user-images.githubusercontent.com/14825242/79046890-09549000-7c31-11ea-9abe-f9a685e0a2ed.png">

**Comment by licaon-kter** [comment]
It's not stuck, there's no more info to show, ejabberd did what it had to do.

**Comment by weiss** [comment]
Those log lines show that the client requested and got the permission to upload a file.  This communication is done over the HTTP connection.  ejabberd is now waiting for the client to initiate the actual HTTP connection.  From your log snippet no attempt to open that HTTP connection is made.  This might be due to the client refusing to attempt the connection (either due to the same reason Gajim refuses it, or for another reason).  Or due to the HTTP address/port not being accessible for the client for some reason.  A good client would show an error message either way.

**Comment by SomwareHR** [comment]
Hi,

So, the question is actually: 
"How do I configure ejabberd to accept http uploads and not enforce httpS?"

**Comment by weiss** [comment]
> How do I configure ejabberd to accept http uploads and not enforce httpS?

```yaml
listen:
  -
    module: ejabberd_http
    port: 8080
    ip: "::"
    tls: false
    request_handlers:
      /share: mod_http_upload

modules:
  mod_http_upload:
    put_url: http://@HOST@:8080/share
```
