### ISSUE TITLE
MUC Service Crash and Make all members disconnected from Service

### ISSUE THREAD

**Issue by axcl** [processone/ejabberd#3249]
## Environment

- ejabberd version: 20.03
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from:  official deb/rpm

## Ejabberd Config
```
loglevel: 2
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "domain.com"
define_macro:
  'CERTFILE': "/opt/ejabberd-20.03/conf/server.pem"
  'TLSOPTS':
    - "no_sslv3"
listen:
  - 
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    certfile: 'CERTFILE'
    protocol_options: 'TLSOPTS'
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  - 
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  - 
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/api": mod_http_api
    web_admin: true
    http_bind: true
    register: true
    captcha: true
auth_method: sql
sql_type: mysql
sql_server: "localhost"
sql_database: "ejabberd"
sql_username: "ejabberd"
sql_password: "password"
sql_port: 3306
default_db: sql
shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 1000
acl:
  admin:
    user:
      - "admin@domain.com"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - deny
  trusted_network:
    - allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"
  
language: "en"
captcha_cmd: "/opt/ejabberd-17.09/lib/ejabberd-17.09/priv/bin/captcha.sh"
captcha_host: "domain.com:4000"
captcha_limit: 3
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_bosh: {}
  mod_last: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    max_users: 30
    history_size: 0
    max_room_id: 20
    max_room_name: 20
    max_room_desc: 200
    min_message_interval: 0.4
    min_presence_interval: 4
    default_room_options:
      allow_change_subj: false
      allow_query_users: false
      allow_private_messages: true
      members_by_default: false
      persistent: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_pres_counter:
    count: 5
    interval: 60
  mod_privacy: {}
  mod_private: {}
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    captcha_protected: true
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to domain.
    ip_access: trusted_network
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
  mod_http_api: {}
allow_contrib_modules: true
```

## Errors from error.log/crash.log
```
2020-05-03 17:29:34.732 [info] <0.7353.0>@ejabberd_c2s:bind:434 (tls|<0.7353.0>) Opened c2s session for slayer@domain.com/xabber-android-S6I7i4E6
2020-05-03 17:31:09.917 [info] <0.7342.0>@mod_muc_room:terminate:884 Stopping MUC room support@conference.domain.com
2020-05-03 17:31:09.920 [error] <0.7342.0>@mod_muc_room:normal_state:497 gen_fsm <0.7342.0> in state normal_state terminated with reason: no case clause matching 1588507068043950 in mod_muc_room:normal_state/2 line 497
2020-05-03 17:31:09.920 [error] <0.7342.0>@mod_muc_room:normal_state:497 CRASH REPORT Process <0.7342.0> with 0 neighbours exited with reason: no case clause matching 1588507068043950 in mod_muc_room:normal_state/2 line 497 in p1_fsm:terminate/8 line 760
2020-05-03 17:31:09.921 [error] <0.446.0>@mod_muc_room:normal_state:497 Supervisor 'mod_muc_room_sup_domain.com' had child undefined started with {mod_muc_room,start_link,undefined} at <0.7342.0> exit with reason no case clause matching 1588507068043950 in mod_muc_room:normal_state/2 line 497 in context child_terminated
```
## Bug description

 MUC Service Crash and Make all members disconnected from Service without sending any presence and members can not send any message after that until they left and renenter again.

Also this happens to specific rooms only other rooms are working as expected.

05:31:37 PM IST] ‎error while sending .. ( Only occupants are allowed to send messages to the conference )

**Comment by licaon-kter** [comment]
gist of the config?

**Comment by axcl** [comment]
@licaon-kter updated Config.

**Comment by licaon-kter** [comment]
```
    modules:
      mod_muc:
        access:
          - allow
        access_admin:
          - allow: admin
        access_create: muc_create
        access_persistent: muc_create
        default_room_options:
          mam: true
        history_size: 1000
      mod_muc_admin: {}
```
...can you setup rooms like this and test? You have a lot of restrictions in your setup.
