### ISSUE TITLE
Setting vcard photo via API does not seem to work

### ISSUE THREAD

**Issue by ganySA** [processone/ejabberd#3266]
Attempting to set the PHOTO value of a vcard does not seem to work in the API. The value is saved but does not display on clients?
```yaml
{
localhost:5443/api/set_vcard
       "user": "test",
      "host": "server1",
      "name": "PHOTO",
      "content": <Base64 value>
}
```

Am i process the command incorrectly or is this a bug?
