### ISSUE TITLE
ejabberd_stun accepts just a single certfile

### ISSUE THREAD

**Issue by f055** [processone/ejabberd#3276]
## Environment

- ejabberd version: 20.04
- OS: Linux (Debian Buster)
- Installed from: official deb/rpm

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
listen:
  -
    port: 5349
    tls: true
    module: ejabberd_stun
    certfile: /etc/ejabberd/server.pem
```

## Bug description

When `ejabberd_stun` is in TLS mode it requires a certificate. However, it seems the configuration at the moment only expect a single `certfile`, which means Let's Encrypt certificates are harder to use, as they generate two files, `fullchain.pem` and `privkey.pem`. The main `certfiles` setting allows a list of certificates. It would be nice to duplicate this approach in `ejabberd_stun`.
