### ISSUE TITLE
Update ejabberd.yml.example to include custom headers for mod_http_upload

### ISSUE THREAD

**Issue by f055** [processone/ejabberd#3288]
**Is your feature request related to a problem? Please describe.**
At the moment, a fresh install of latest ejabberd doesn't pass the HTTP File Upload test in the XMPP Compliance suite, meaning the default config for HTTP File Upload is not optimal.

**Describe the solution you'd like**
It could easily be passed by an out-of-the-box ejabberd if we update the default config file to include the necessary custom headers:

```yml
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
    custom_headers:
      "Access-Control-Allow-Origin": "https://@HOST@"
      "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type"
```
