### ISSUE TITLE
roster_groups_allowed in .yml file doesn't accept list

### ISSUE THREAD

**Issue by relbraun** [processone/ejabberd#3302]
```
mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    max_items_node: 1000
    plugins:
      - "flat"
      - "pep"
    force_node_config:
      ## Change from "whitelist" to "open" to enable OMEMO support
      ## See https://github.com/processone/ejabberd/issues/2425
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      ## Avoid buggy clients to make their bookmarks public
      "storage:bookmarks":
        access_model: whitelist
      "my:pep:x":
        access_model: roster
        notification_type: normal
        roster_groups_allowed: 
            - "group1"
            - "group2"

```
this config is not acceptable because  `roster_groups_allowed` parameter expect string and not list. Any idea?
