### ISSUE TITLE
(Simple) customization of mod_register_web

### ISSUE THREAD

**Issue by htgoebel** [processone/ejabberd#3309]
**Is your feature request related to a problem? Please describe.**
Using `mod_register_web` is great to get started with web-based registration. But this page is missing some important information, which are relevant even for hobbyists: terms of service and privacy statement. And even a hobbyist might want to style the pages a bit like her/his homepage.

**Describe the solution you'd like**
Add two option to allow customizing the pages:
```
mod_register_web:
   html_body_start >
       <style>@import url("mystyle.css")</style>
       <p>Hello Firiends!</p>
   html_body_end: >
       <p>Please see the <a href="terms.html">terms of service</a> and my
       <a href="privacy.html">privacy policy</a>.
       </p>
```
The content of this two options will be included into the generated pages verbatim, just after the `<body>` openin tag and jsut becode the `</body>` closing tag.

This allows for adding both content and style. (and when using tricky CSS, even changing content :-)

**Describe alternatives you've considered**
- An option to supply an additional style-sheet to be included after the standard one -> nice, but less flexible
- Options like `terms_of_service_url` and `privacy_policy_url` -> Pro: ejabberd could provide translations. Con: Less flexible.
- Option specifying a page template file (in `~/ejabberd`) -> I have no clue about available templating engines for erlang.
- Use custom from in Homepage, like the [Ejabberd Account Tools](https://wordpress.org/plugins/ejabberd-account-tools/) -> Pro: very good integration into homepage. Con: Rely on privacy distroying reCaptcha from google.

**Additional context**
Even a hobbyist want to tell her/his friends that this is a hobbyist's side and might not be available all to time :-) And she/he is also subject to privacy regulations, e.g. the the Europian GDPR.

**Comment by badlop** [comment]
You can try this implementation at: https://github.com/badlop/ejabberd/commit/cdcb2e1fd572e6f0454cf8f0b2390001026b80e3

Example configuration:
```yaml
modules:
  mod_register_web:
    html_body_start:
      - <style>@import url('mystyle.css')</style>
      - <p>Hello Firiends!</p>
    html_body_end:
      - <p>Please see the <a href="terms.html">terms of service</a> and my <a href="privacy.html">privacy policy</a>.</p>
```
