### ISSUE TITLE
AccessRules: Account does not have the right to perform the operation

### ISSUE THREAD

**Issue by Kalmuraee** [processone/ejabberd#3315]
## Environment

- ejabberd version: 20.04
- Erlang version: `erl +V`
- OS: Linux (Ubuntu Server)
- Installed from: Docker

## Issue description

I've been trying to trigger event from an API , I've generated a token and I'm using it with the event .

## Configuration 
```yaml
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
    what:
      - "*"
      - connected_users_number
  "web admin":
    who:
      - access:
          - allow:
              - acl: loopback
              - acl: admin
      - oauth:
          - scope: "sasl_auth"
          - access:
              - allow:
                  - acl: loopback
                  - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
```

## Log Details 
```
2020-06-25 18:52:09.790988+00:00 [debug] Command 'status_list' execution denied (CallerInfo=
#{caller_module =>mod_http_api,
  caller_server =><<"localhost">>, 
  ip => {0,0,0,0,0,65535, 13274,55614},
  oauth_scope => [],
  tag => <<>>,
  usr => {<<"admin">>, <<"localhost">>, <<>>}})
```

I'm still trying to figure out why do I receive this message

**Comment by prefiks** [comment]
Hello, do you have mod_admin_extra listed in your `modules` section?

**Comment by Kalmuraee** [comment]
Thanks @prefiks  
Yes `mod_admin_extra` is in the `modules` section.
```yaml
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    db_type: sql
    assume_mam_usage: true
    default: never
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_sip: {}
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

```

**Comment by badlop** [comment]
I configure like this:
```yaml
listen:
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /api: mod_http_api
      /oauth: ejabberd_oauth

api_permissions:
  "admin access":
    who:
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: admin
    what:
      - status_list

acl:
  admin:
    user:
      - user1@localhost
```

And register the admin account:
```
$ ejabberdctl register user1 localhost mypass11
```

Then I visit the OAuth page
```
http://localhost:5280/oauth/authorization_token?response_type=token&scope=ejabberd:admin
```

and provide the admin account credentials:
```
User: user1@localhost
Password: mypass11
```

it redirects me to this page, so I have the access token:
```
http://localhost:5280/oauth/authorization_token?access_token=RS8zbvostWEyUpx8cyVFV3cHILLWGYpQ&token_type=bearer&expires_in=31536000&scope=ejabberd:admin&state=
```

I create user3 account and login to it, and now I can finally query the API, that works correctly:
```
$ curl -v -H "Authorization: Bearer RS8zbvostWEyUpx8cyVFV3cHILLWGYpQ" http://localhost:5280/api/status_list -d '{"status": "away"}'
[{"user":"user3","host":"localhost","resource":"tka1","priority":8,"status":"Busysss"}]
```
