### ISSUE TITLE
mod_muc Too many users in this conference

### ISSUE THREAD

**Issue by Socketsj** [processone/ejabberd#3333]
## Environment

- ejabberd version: 20.04
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from: official binary installer

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
    max_users: 2000
    max_user_conferences: 2000
    max_users_presence: 2000
```

## Errors from error.log/crash.log

500 wait resource-constraint Too many users in this conference

## Bug description

I create the muc room with 500 members. when I join more than 200 members, has error
```
500 wait resource-constraint Too many users in this conference
```

But, I config it like [https://docs.ejabberd.im/admin/configuration/modules/#mod-muc](https://docs.ejabberd.im/admin/configuration/modules/#mod-muc), How can I have 500 mebers muc room
