### ISSUE TITLE
Failed c2s EXTERNAL authentication user xyz Failed to get peer certificate

### ISSUE THREAD

**Issue by onelab72** [processone/ejabberd#3339]
## Environment

- ejabberd version: 20.4.0
- Erlang version: `Erlang/OTP 22 [erts-10.5] [source] [64-bit]`
- OS: Linux (Alpine)
- Installed from: docker
## Configuration 

```yaml
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
    cafile: /home/ejabberd/conf/cafile
    tls_verify: true...

# HTTP auth setting

auth_method: http
auth_opts:
  host: "http://authserver
  connection_pool_size: 10
  connection_opts: []
  basic_auth: ""
  path_prefix: "/"
```

## Errors from error.log/crash.log

```
Failed c2s EXTERNAL authentication for abc@hosst from ::ffff:172.17.0.1: Failed to get peer certificate
```

## Bug description

I am trying to authenticate client against base on **SASL EXTERNAL with Certificates** [https://xmpp.org/extensions/xep-0178.html](url) but user try to connect  even with client certificate got the above warning.

Same error if no certificate provided and also client still able able to connect.

What I am expecting is

- If no certificate provided client should not able to connect while Ejabberd just bypass the `starttls_required` and `tls_verify` flag
- Is there a way to not **allow connection if certificate is not valid**?
- Can I use just only **client certificate authentication** or should I use certificate along with **http-auth**?

Relevant commit is  [https://github.com/processone/ejabberd/commit/8b29af62](url) but it does not help

**Comment by jsautret** [comment]
With your configuration, authentication is first tried with the client certificate. If it fails, it fallback to the http backend. If you want to use only client certificate authentication, your have to remove the HTTP auth setting.

**Comment by onelab72** [comment]
Thanks for the response @jsautret, here is my update setting

```
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
    cafile: /home/ejabberd/conf/cafile    
    tls_verify: true
```
I removed the `http` auth. but when I tried to connect client with client certificate I got below error.

```
2020-07-24 13:41:43.284703+00:00 [warning] (tls|<0.616.0>) Failed c2s EXTERNAL authentication for user@host from ::ffff:172.17.0.1: Failed to get peer certificate
```

![Screenshot from 2020-07-24 18-45-44](https://user-images.githubusercontent.com/68630419/88398002-2b3be200-cdde-11ea-8ec7-ba8b429154e0.png)

So then should I enable **anonymous authentication**? if yes I do not a client to connect with out certificate and I expected client  should not able to connect if certificate is not valid.

would be great if provide example config for Ejabberd that base on the following XEP [https://xmpp.org/extensions/xep-0178.html](url)

**Comment by jsautret** [comment]
According to the message, the client is not sending its certificate, so it's likely a client side issue.

**Comment by onelab72** [comment]
Okay let assume client not sending certificate then I am expecting Ejabberd should not allow connection but client can still able to create connection if not certificate provided?

**Comment by onelab72** [comment]
Also when I pass certificate properly from client side then it ask for password? If its certificate base authentication should client ask the password?

**Comment by mremond** [comment]
As @jsautret already explained:
- If you configure a second fallback authentication, the client certificate auth fails and then ejabberd uses as configured the password authentication.
- Your client certificate authentication does not seem to work. It may not be properly implemented in that client.

Again, from the comment you provide, there is no evidence that the server is not behaving properly. As such, your client is probably not doing the right thing.

**Comment by onelab72** [comment]
@mremond thanks for the explanation, just one final question as I did not find any thing in documentation 

So the Ejabberd will not allow user to login without client certificate with below config?

```
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
    cafile: /home/ejabberd/conf/cafile
    tls_verify: true
```

**Comment by mremond** [comment]
It won't, if you do not have fallback authentication defined.

**Comment by onelab72** [comment]
Thanks its really helpful @mremond 

So I am using https://apkgk.com/org.atalk.android as a client it has support for client certificate and I am no longer getting `Failed to get peer certificate` this error.
From client page
>* SSL Certificate authentication, DNSSEC and DANE Security implementation for enhanced secure Connection Establishment

But during connection it ask for password even certificate verified, do have any suggestion why the client still asking for password and if its expected where I should define these password in ACL?

Thanks

**Comment by mremond** [comment]
The password is not defined in the certificate itself. The certificate must have been signed be a trusted CA. If that CA is not defined in the default OS CA root, then you need to pass it through the `cafile` listener option.

See: https://docs.ejabberd.im/admin/configuration/listen-options/#cafile

**Comment by prefiks** [comment]
How did you generate those certificates used by client? Did you sign them with cert that you you use in ejabberd cacert/c2s_cacert options? You also need to make sure that certificate that user uses has that user jid present in subjectAltName of that certificate.

**Comment by onelab72** [comment]
@mremond yes I pass the CA and Ejabberd seems working, with out CA its throw Waring like below
```
[warning] Invalid certificate in /home/ejabberd/conf/server.pem: at line 37: certificate is signed by unknown CA
```

**Comment by onelab72** [comment]
@prefiks I generate in pkcs12 format as the client accept `pkcs12` formate, I use below command to generate the certificate for client

```
openssl pkcs12 -export -in my.bundle.pem -inkey mykey.com.key -out mydomain.p12  -name *.domain.com -passin pass:myPass -passout pass:myPass
```
The above command does not include `root CA`, should so this include root CA as well?

**Comment by prefiks** [comment]
Hello,

But why you are using this certificate on server, if you want to use it for client authentication, your client is supposed to send it to server when it's opening connection?

**Comment by onelab72** [comment]
Hi @prefiks  thanks for quick response.

>you are using this certificate on server
On server side we are using this for TLS, but I am trying to implment SASL EXTERNAL with Certificates https://xmpp.org/extensions/xep-0178.html this extension of xmpp.
>Your client is supposed to send it to server when it's opening connection
Yes, this is my understanding, might be I am wrong, which certificate client should sent then if I want to implement https://xmpp.org/extensions/xep-0178.html in Ejabberd?

**Comment by prefiks** [comment]
So server is supposed to send certificate that in subject has domain name used by it, ideally signed by known cert authority (using external auth with cert doesn't change anything here, you just follow step as usual for xmpp server to make it support tls).

But if you want to use xmpp certs for client authentication, then you must make client send cert that have xmppAddr for jid that account is uses in altSubj field of that cert, it also needs to be signed by root cert that you pass in cafile in ejabberd config.

**Comment by prefiks** [comment]
You can see how our test generate cert that is used for testing this feature: Cert must have this in altSubject https://github.com/processone/ejabberd/blob/master/test/ejabberd_SUITE_data/openssl.cnf#L224 you can also see how openssl is called in https://github.com/processone/ejabberd/blob/master/test/ejabberd_SUITE_data/gencerts.sh - it uses that .cnf file, cert.pem is what is then used by client

**Comment by onelab72** [comment]
>you just follow step as usual for xmpp server to make it support tls

Yes, I can verify TLS is configured on Ejabberd side and that seem working


> But if you want to use xmpp certs for client authentication, then you must make client send cert that have xmppAddr for jid that account is uses in altSubj field of that cert, it also needs to be signed by root cert that you pass in cafile in ejabberd config.

I see, I missed signed by root cert and altSubj field.


Let me check the link and try with, will update you back.
Thanks for the help.

**Comment by onelab72** [comment]
@prefiks Thanks for the help, it's really helpful. Generating client certificate with root CA I am able to make connection, but as I am not able to edit AltSubj field for existing certificate according to this [post](https://security.stackexchange.com/questions/192676/add-a-sansubject-alternative-name-to-already-existing-cert)


With out Altsubject Field I am getting this error

```
[warning] (tls|<0.685.0>) Failed c2s EXTERNAL authentication from ::ffff:x.x.6.79: Certificate JID mismatch

```

I am still confuse regarding client certs so asking few question for more clarification

some background "Server using certificate that issued by Alpha SSL and using CA from [here](https://www.alphassl.com/support/install-root-certificate.html)", so far so good and able to create client certificate using that key and pem file provided by Alpha SSL. so my questions are

- Do I need same Alpha key and PEM file to generate client certs?
- Or can I generate client certs by only using CA? or should I get new certs from Alpha?
- All client can use single certs? or every client will use own certs with subjectaltname like `user1@mydns.com, user2@mydns.com` for JID? 


FYI I use this command to generate clients certs

```
openssl pkcs12 -export -out mysslname.pfx -inkey mydomain.com.key -in mydomain.bundle.pem -certfile ca.pem

```

And use `mysslname.pfx` this on client side which throw error as subjectalt name is missing and not able to update that. Please suggest.

**Comment by prefiks** [comment]
You should create you own ca cert that you control, and use it, you probably won't be even able to use public CA, as i doubt you will make them sign cert with xmppAddr (and also would need to make them sign cert for each user). Using self signed cert in this case shouldn't be a problem anyway, those cert shouldn't be publicly visible, only your server and client will ever see them.

**Comment by onelab72** [comment]
@prefiks  thanks for the details. So you suggest sign certs for each user base on their JID.

I was able to configure and run with self signed certificate, now client able to make connection but Ejabberd throw below warning

```
[warning] (tls|<0.628.0>) Failed c2s EXTERNAL authentication from ::ffff:x.x.178.146: self signed certificate
```

Seems like I need to allow ejabberd to work with self signed certificate?

**Comment by prefiks** [comment]
Did you pass path to a cert that was used to sign that in cacert option?

**Comment by onelab72** [comment]
@prefiks yes. the config is same as with alpha SSL certs, I just change name of certs.

```
certfiles:                                                             
  - /home/ejabberd/conf/myserver.pem                                
                                                                       
ca_file: "/home/ejabberd/conf/rootca.pem"     
```

**Comment by prefiks** [comment]
Did you sign client cert with private key associated to rootca?

**Comment by onelab72** [comment]
@prefiks yes, I double check again, but seems like you doubt about client certs?

**Comment by prefiks** [comment]
So i just tested this on my local instalation, and having cafile in listener and using client cert that was signed by key associated with cert from cafile works without ok there, i am guessing your client cert isn't correctly signed.

I didn't also answer to your question about multiple jids in single cert, you can have single cert with multiple altSubject for moultiple jids, and as it should work in ejabberd, but in that case you must pass base64 encoded jid inside <auth/> element to tell server which user should be logged in (i verifed that it works with current version).

**Comment by onelab72** [comment]
I see, so I thought the issue is on my side but tried different approach and the error still exist. 

Here is my complete `ejabberd.yml` might be some other thing that create conflict

```
###
###              ejabberd configuration file
###
hosts:
  - "mydns.com"

loglevel: 4
log_rotate_size: 30485760
log_rotate_count: 10


certfiles:
  - /home/ejabberd/conf/server.pem 

ca_file: "/home/ejabberd/conf/ca.crt"

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
    tls_verify: true
    cafile: "/home/ejabberd/conf/ca.crt"

  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/ws": ejabberd_http_ws
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin

s2s_use_starttls: optional

acl:

  admin:
    user:
      - "admin@mydns.com"

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 50000: security_admin
    - 100
  2s_shaper:
    - fast

max_fsm_queue: 10000

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_http_api: {}
  mod_ping: {}
  mod_privacy: {}
  # mod_private: {}

  mod_roster:
    versioning: true
  mod_sip: {}
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt: {}
  mod_version: {}


```

and Here is the script to generate certs for server and client device
 
```
openssl genrsa -out ca.key 4096
openssl req -new -x509 -days 100 -key ca.key -out ca.crt     -subj "/C=US/ST=Acme State/L=Acme City/O=Acme Inc./CN=*.mydns.com"


openssl genrsa -out client.key 4096
openssl req -new -key client.key -out client.csr -subj "/C=US/ST=Acme State/L=Acme City/O=Acme Inc./CN=*.mydns.com" \
    -reqexts SAN \
    -config <(cat /etc/ssl/openssl.cnf <(printf "\n[SAN]\nsubjectAltName=DNS:test@test.mydns.com")) 

### client certs 

openssl x509 -req -days 365 -in client.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out client.crt



### Generate Server certs

openssl genrsa -out server_key.key 4096
openssl req -new \
    -key server_key.key \
    -out server.csr \
    -subj "/C=US/ST=Acme State/L=Acme City/O=Acme Inc./CN=*.mydns.com"


openssl x509 -req -days 1460 -in server.csr \
    -CA ca.crt -CAkey ca.key \
    -CAcreateserial -out server.pem
echo "adding bundle"
cat server_key.key >> server.pem

#### Generate for device

openssl pkcs12 -export -clcerts -in client.crt -inkey client.key -out client.p12

openssl pkcs12 -in client.p12 -out client.pem -clcerts
```

@prefiks  please look into this and let me know if there is any thing that I am missing.
thanks, appreciated.
