### ISSUE TITLE
Can't grant privilages to access webadmin for just one virtual host

### ISSUE THREAD

**Issue by JuniorJPDJ** [processone/ejabberd#3355]
## Environment

- ejabberd version: 20.07 tag
- Installed from: official docker image

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
acl:
  local:
    user_regexp: ""
  loopback:
    ip: 
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - juniorjpdj@juniorjpdj.pl
#      - marcin@marcin.co

append_host_config:
# same for host_config: but it breaks also other things
  "marcin.co":
    acl:
      admin:
        user:
          - marcin@marcin.co

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all 
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
```

## Bug description

I want to give my friend webadmin access for his virtualhost.
When I add him just for his virtualhost (like in config above) he has his vhost on list of vhosts but his webadmin is blank when he clicks on it and he lacks left menu.

His web panel:
![image](https://user-images.githubusercontent.com/7334549/89710018-eb4d3100-d97f-11ea-9c66-836c77b735be.png)
![image](https://user-images.githubusercontent.com/7334549/89710021-f011e500-d97f-11ea-828e-7acbf5db6e16.png)

My web panel:
![image](https://user-images.githubusercontent.com/7334549/89710032-0455e200-d980-11ea-84ac-6c05cb28711f.png)
![image](https://user-images.githubusercontent.com/7334549/89710036-0881ff80-d980-11ea-8482-768585fe6391.png)
