### ISSUE TITLE
RFE: Add specific domains support to Letsencrypt renewal configuration

### ISSUE THREAD

**Issue by adriangibanelbtactic** [processone/ejabberd#3361]
**Is your feature request related to a problem? Please describe.**
The problem is to make work LetsEncrypt default renewal with custom domains when they are not publicy exposed.

If we define in ejabberd.xml the following stanza:
```
hosts:
  - chat.example.net
  - example.com
```
then, ejabberd assumes the domains that are going to be associated in a public manner to the server are:
- chat.example.net
- pubsub.chat.example.net
- conference.chat.example.net
- example.com
- pubsub.example.com
- conference.example.com
.

Despite the former making sense or not in an ejabberd environment I'm not going to point example.com to the ejabberd server so that the Letsencrypt automatic renewal works even if I'm entering it with only chat.example.net url.
 

**Describe the solution you'd like**
I want the acme stanza from ejabberd.yml file to support custom domains so that they are the only ones to be renewed with the auto acme feature.
If no custom domains are set then do the default behaviour (try to renew everything).

Example:
```
acme:
  ca_url: https://acme-v02.api.letsencrypt.org/directory
  contact:
    - mailto:certificate@example.net
  domains:
    - chat.example.net
    - pubsub.chat.example.net
    - conference.chat.example.net
  auto: true
  cert_type: rsa
```

**Describe alternatives you've considered**
I think that this should be easier to fix if ejabberd would allow us to define virtual hosts associated to domains (what ejabberd names as hosts) as it happens in webservers.

Then, you know, ejabberd would only try to renew certificates associated to every defined virtual hosts.

**Additional context**
An old stanza example without domains support would be:
```
acme:
  ca_url: https://acme-v02.api.letsencrypt.org/directory
  contact:
    - mailto:certificate@example.net
  auto: true
  cert_type: rsa
```
