### ISSUE TITLE
mod_mam is not storing messages - RPM packages ejabberd-20.07-0.x86_64.rpm on centos8

### ISSUE THREAD

**Issue by wurstdog** [processone/ejabberd#3371]
Hi there,

i have just install ejabberd-20.07 as a cluster on Centos8 from package and enabled MySQL (mariadb, galeracluster). 
The user authentication with sql works well but i have a problem with offlinemessages
and with messages archiving.

#### Mariadb version
+---------------------+
| @@version.  |
+---------------------+
| 10.4.12-MariaDB-log |
+---------------------+

#### ejabberd packages

ejabberd-20.07-0.x86_64.rpm

#### ejabberd version

The node ejabberd@ejabberd01 is started with status: started
ejabberd 20.07 is running in that node

#### ejabberd cluster

ejabberd@ejabberd03
ejabberd@ejabberd02
ejabberd@ejabberd01

#### Galeracluster
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| wsrep_cluster_size | 3     |
+--------------------+-------+

```
MariaDB [ejabberd]> select * from archive;
Empty set (0.001 sec)

MariaDB [ejabberd]> select * from archive_prefs;
Empty set (0.000 sec)

```
snippset ejabberd.yml

```
default_db: sql
sql_type: mysql
```

```
mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    db_type: sql
    assume_mam_usage: true
    default: always
```

 
On my other server with ejabberd and mariadb everything works perfect for me.

#### ejabberd version
ejabberd 19.9.0

#### Mariadb version
+----------------------------------------+
| @@version                                                  |
+----------------------------------------+
| 10.4.11-MariaDB-1:10.4.11+maria~bionic |
+----------------------------------------+

Thx
