### ISSUE TITLE
MUC Room from Rest API

### ISSUE THREAD

**Issue by AtifShahzed** [processone/ejabberd#3376]
Hi,

I am facing following error when I try to create a MUC from rest api.
My post request is following along with error log.

```
POST /api/create_room
 {
      "name": "room1",
      "service": "muc.blabla.com",
      "host": "blabla.com"
    }
```
**Error log details are given below when I rung the above api.**

```2020-09-02 08:15:56.850 [error] <0.541.0>@mod_http_api:handle:258 REST API Error:
 create_room([{<<"name">>,<<"room1">>},{<<"service">>,<<"muc.blabla">>},{<<"host">>,<<"blabla">>}]) ->
 error:{unregistered_route,<<"muc.blabla">>}
 [{ejabberd_router,host_of_route,1,[{file,"src/ejabberd_router.erl"},{line,280}]},
  {mod_muc,find_online_room,2,[{file,"src/mod_muc.erl"},{line,325}]},
  {mod_muc_admin,create_room_with_opts,4,[{file,"src/mod_muc_admin.erl"},{line,661}]},
  {mod_http_api,handle2,4,[{file,"src/mod_http_api.erl"},{line,268}]},
  {mod_http_api,handle,4,[{file,"src/mod_http_api.erl"},{line,229}]},
  {mod_http_api,perform_call,4,[{file,"src/mod_http_api.erl"},{line,189}]},
  {mod_http_api,process,2,[{file,"src/mod_http_api.erl"},{line,142}]},
  {ejabberd_http,process,2,[{file,"src/ejabberd_http.erl"},{line,370}]}]
```

**MUC Configuration**

```
    mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
       persistent: true
       public: false
       members_only: true
  mod_muc_admin: {}
```

**Command line error** 
```

ejabberdctl create_room "DEMO" "muc.BLAH.com"  "BLAH.com"

Unhandled exception occurred executing the command:
** exception error: {unregistered_route,<<"muc.BLAH.com">>}
   in function  ejabberd_router:host_of_route/1 (src/ejabberd_router.erl, line 280)
   in call from mod_muc:find_online_room/2 (src/mod_muc.erl, line 325)
   in call from mod_muc_admin:create_room_with_opts/4 (src/mod_muc_admin.erl, line 661)
   in call from ejabberd_ctl:call_command/4 (src/ejabberd_ctl.erl, line 315)
   in call from ejabberd_ctl:try_call_command/4 (src/ejabberd_ctl.erl, line 280)
   in call from ejabberd_ctl:process2/4 (src/ejabberd_ctl.erl, line 233)
   in call from ejabberd_ctl:process/2 (src/ejabberd_ctl.erl, line 211)
   in call from rpc:'-handle_call_call/6-fun-0-'/5 (rpc.erl, line 197)
```
