### ISSUE TITLE
MUC with password does not work

### ISSUE THREAD

**Issue by AtifShahzed** [processone/ejabberd#3383]
Hi,

**Step 1)  I am creating MUC through Rest API.
https://abc.com:5443/api/create_room**

```
{
    "name": "room1",
    "service": "conference.abc.com",
    "host": "abc.com"
}
```

-_**--Room created successfully.**_

**Step 2) Add user as a affiliated member of the MUC room.
https://abc.com:5443/api/set_room_affiliation**

```
{
    "name": "room1",
    "service": "abc.com",
    "jid": "11111611@abc.com",
    "affiliation": "member"
}
```

**Step 3) Send Invitation
https://abc.com:5443/api/send_direct_invitation**

```
{
    "name": "room1",
    "service": "conference.abc.com",
    "password": "34234234234234",
    "reason": "Check this out!",
    "users": "11111611@abc.com"
}
```

For testing I am using Converse.js online hosted version.
When i send invitation Conerse.js receives an invitation and prompt Nick and then prompt password.
In room invitation I have set the password so when i enter that password  it does not work and throws an error.

**This groupchat requires a password
A password is required to enter this room**
 

I have following configuration for the Room.

```yaml
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_register: all
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      persistent: true
      allow_user_invites : true
      mam: true
      members_only: true
      password_protected: true
      public: false
      anonymous: false
```
