### ISSUE TITLE
Unable to send messages to a MUC room

### ISSUE THREAD

**Issue by karimhm** [processone/ejabberd#3394]
## Environment

- ejabberd version: **18.09**
- Erlang version: **Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.5**
- OS: **Linux (alpine:3.11)**
- Installed from: **Docker**

## Configuration:

```yaml
hosts:
  - chat.example.com
  - conference.chat.example.com
 
loglevel: 5
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
 
certfiles:
  - /etc/letsencrypt/live/chat.example.com/fullchain.pem
  - /etc/letsencrypt/live/chat.example.com/privkey.pem
 
ca_file: "/etc/letsencrypt/live/chat.example.com/fullchain.pem"
 
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000

s2s_use_starttls: optional

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "admin@chat.example.com"
 
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
 
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
 
shaper:
  normal: 1000
  fast: 50000
 
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    infinity: admin
    infinity: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast
 
max_fsm_queue: 10000
 
acme:
   contact: "mailto:example-admin@example.com"
   ca_url: "https://acme-v01.api.letsencrypt.org"
 
sql_type: pgsql
sql_server: "ejabberd_server"
sql_database: "ejabberd"
sql_username: "ejabberd"
sql_password: "{PASSWORD}"
 
auth_method: sql
auth_password_format: scram
default_db: sql
 
commands_admin_access: configure
commands:
  - add_commands:
    - user
oauth_expire: 3600
oauth_access: all
 
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    compress_xml: true
    db_type: sql
    assume_mam_usage: true
    clear_archive_on_room_destroy: false
    user_mucsub_from_muc_archive: true
    default: always
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true
      allow_private_messages: false
      allow_user_invites: true
      mam: true
      persistent: true
      public: false
      allow_private_messages_from_visitors: nobody
      anonymous: false
      members_by_default: false
      members_only: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
    store_groupchat: true
    store_empty_body: true
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push:
    include_body: true
    include_sender: truey
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_sip: {}
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
```

## Errors from error.log/crash.log

```
ejabberd    | 2020-09-17 11:33:57.896024+00:00 [notice] (tls|<0.712.0>) Received XML on stream = <<"<message id=\"B1668FC8-4AAD-4E8C-9386-EAF947B44770\" to=\"room@conference.chat.example.com\" type=\"groupchat\"><body>d</body><request xmlns=\"urn:xmpp:receipts\"/><origin-id xmlns=\"urn:xmpp:sid:0\" id=\"B1668FC8-4AAD-4E8C-9386-EAF947B44770\"/></message>">>
ejabberd    | 2020-09-17 11:33:57.896525+00:00 [debug] Running hook c2s_handle_recv: mod_stream_mgmt:c2s_handle_recv/3
ejabberd    | 2020-09-17 11:33:57.896679+00:00 [debug] Running hook c2s_authenticated_packet: mod_client_state:c2s_authenticated_packet/2
ejabberd    | 2020-09-17 11:33:57.897614+00:00 [debug] Running hook c2s_authenticated_packet: mod_stream_mgmt:c2s_authenticated_packet/2
ejabberd    | 2020-09-17 11:33:57.897800+00:00 [debug] Running hook user_send_packet: mod_privacy:user_send_packet/1
ejabberd    | 2020-09-17 11:33:57.897971+00:00 [debug] Running hook user_send_packet: mod_vcard_xupdate:user_send_packet/1
ejabberd    | 2020-09-17 11:33:57.898089+00:00 [debug] Running hook user_send_packet: mod_caps:user_send_packet/1
ejabberd    | 2020-09-17 11:33:57.898249+00:00 [debug] Running hook user_send_packet: mod_mam:user_send_packet/1
ejabberd    | 2020-09-17 11:33:57.898358+00:00 [debug] Running hook user_send_packet: mod_carboncopy:user_send_packet/1
ejabberd    | 2020-09-17 11:33:57.898502+00:00 [debug] Running hook user_send_packet: mod_mam:user_send_packet_strip_tag/1
ejabberd    | 2020-09-17 11:33:57.898608+00:00 [debug] Running hook privacy_check_packet: mod_last:privacy_check_packet/4
ejabberd    | 2020-09-17 11:33:57.898834+00:00 [debug] Running hook privacy_check_packet: mod_privacy:check_packet/4
ejabberd    | 2020-09-17 11:33:57.899462+00:00 [debug] Route:
ejabberd    | #message{id = <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>,type = groupchat,
ejabberd    |          lang = <<"en">>,
ejabberd    |          from = #jid{user = <<"karim">>,server = <<"chat.example.com">>,
ejabberd    |                      resource = <<"chatsecure2084">>,luser = <<"karim">>,
ejabberd    |                      lserver = <<"chat.example.com">>,
ejabberd    |                      lresource = <<"chatsecure2084">>},
ejabberd    |          to = #jid{user = <<"room">>,server = <<"conference.chat.example.com">>,
ejabberd    |                    resource = <<>>,luser = <<"room">>,
ejabberd    |                    lserver = <<"conference.chat.example.com">>,lresource = <<>>},
ejabberd    |          subject = [],
ejabberd    |          body = [#text{lang = <<>>,data = <<"d">>}],
ejabberd    |          thread = undefined,
ejabberd    |          sub_els = [#xmlel{name = <<"request">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>}],
ejabberd    |                            children = []},
ejabberd    |                     #xmlel{name = <<"origin-id">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:sid:0">>},
ejabberd    |                                     {<<"id">>,
ejabberd    |                                      <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>}],
ejabberd    |                            children = []}],
ejabberd    |          meta = #{ip => {0,0,0,0,0,65535,10605,62329}}}
ejabberd    | 2020-09-17 11:33:57.902018+00:00 [debug] Local route:
ejabberd    | #message{id = <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>,type = groupchat,
ejabberd    |          lang = <<"en">>,
ejabberd    |          from = #jid{user = <<"karim">>,server = <<"chat.example.com">>,
ejabberd    |                      resource = <<"chatsecure2084">>,luser = <<"karim">>,
ejabberd    |                      lserver = <<"chat.example.com">>,
ejabberd    |                      lresource = <<"chatsecure2084">>},
ejabberd    |          to = #jid{user = <<"room">>,server = <<"conference.chat.example.com">>,
ejabberd    |                    resource = <<>>,luser = <<"room">>,
ejabberd    |                    lserver = <<"conference.chat.example.com">>,lresource = <<>>},
ejabberd    |          subject = [],
ejabberd    |          body = [#text{lang = <<>>,data = <<"d">>}],
ejabberd    |          thread = undefined,
ejabberd    |          sub_els = [#xmlel{name = <<"request">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>}],
ejabberd    |                            children = []},
ejabberd    |                     #xmlel{name = <<"origin-id">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:sid:0">>},
ejabberd    |                                     {<<"id">>,
ejabberd    |                                      <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>}],
ejabberd    |                            children = []}],
ejabberd    |          meta = #{ip => {0,0,0,0,0,65535,10605,62329}}}
ejabberd    | 2020-09-17 11:33:57.902939+00:00 [debug] Running hook sm_receive_packet: mod_mam:sm_receive_packet/1
ejabberd    | 2020-09-17 11:33:57.903282+00:00 [debug] Processing message to bare JID:
ejabberd    | #message{id = <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>,type = groupchat,
ejabberd    |          lang = <<"en">>,
ejabberd    |          from = #jid{user = <<"karim">>,server = <<"chat.example.com">>,
ejabberd    |                      resource = <<"chatsecure2084">>,luser = <<"karim">>,
ejabberd    |                      lserver = <<"chat.example.com">>,
ejabberd    |                      lresource = <<"chatsecure2084">>},
ejabberd    |          to = #jid{user = <<"room">>,server = <<"conference.chat.example.com">>,
ejabberd    |                    resource = <<>>,luser = <<"room">>,
ejabberd    |                    lserver = <<"conference.chat.example.com">>,lresource = <<>>},
ejabberd    |          subject = [],
ejabberd    |          body = [#text{lang = <<>>,data = <<"d">>}],
ejabberd    |          thread = undefined,
ejabberd    |          sub_els = [#xmlel{name = <<"request">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>}],
ejabberd    |                            children = []},
ejabberd    |                     #xmlel{name = <<"origin-id">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:sid:0">>},
ejabberd    |                                     {<<"id">>,
ejabberd    |                                      <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>}],
ejabberd    |                            children = []}],
ejabberd    |          meta = #{ip => {0,0,0,0,0,65535,10605,62329},
ejabberd    |                   stanza_id => 1600342437903092}}
ejabberd    | 2020-09-17 11:33:57.904064+00:00 [debug] Running hook bounce_sm_packet: ejabberd_sm:bounce_sm_packet/1
ejabberd    | 2020-09-17 11:33:57.904494+00:00 [debug] Route:
ejabberd    | #message{
ejabberd    |     id = <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>,type = error,
ejabberd    |     lang = <<"en">>,
ejabberd    |     from =
ejabberd    |         #jid{
ejabberd    |             user = <<"room">>,server = <<"conference.chat.example.com">>,
ejabberd    |             resource = <<>>,luser = <<"room">>,
ejabberd    |             lserver = <<"conference.chat.example.com">>,lresource = <<>>},
ejabberd    |     to =
ejabberd    |         #jid{
ejabberd    |             user = <<"karim">>,server = <<"chat.example.com">>,
ejabberd    |             resource = <<"chatsecure2084">>,luser = <<"karim">>,
ejabberd    |             lserver = <<"chat.example.com">>,lresource = <<"chatsecure2084">>},
ejabberd    |     subject = [],
ejabberd    |     body = [#text{lang = <<>>,data = <<"d">>}],
ejabberd    |     thread = undefined,
ejabberd    |     sub_els =
ejabberd    |         [#xmlel{
ejabberd    |              name = <<"request">>,
ejabberd    |              attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>}],
ejabberd    |              children = []},
ejabberd    |          #xmlel{
ejabberd    |              name = <<"origin-id">>,
ejabberd    |              attrs =
ejabberd    |                  [{<<"xmlns">>,<<"urn:xmpp:sid:0">>},
ejabberd    |                   {<<"id">>,<<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>}],
ejabberd    |              children = []},
ejabberd    |          #stanza_error{
ejabberd    |              type = cancel,code = 503,by = undefined,
ejabberd    |              reason = 'service-unavailable',
ejabberd    |              text =
ejabberd    |                  [#text{lang = <<"en">>,data = <<"User session not found">>}],
ejabberd    |              sub_els = []}],
ejabberd    |     meta =
ejabberd    |         #{ip => {0,0,0,0,0,65535,10605,62329},stanza_id => 1600342437903092}}
ejabberd    | 2020-09-17 11:33:57.905453+00:00 [debug] Local route:
ejabberd    | #message{
ejabberd    |     id = <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>,type = error,
ejabberd    |     lang = <<"en">>,
ejabberd    |     from =
ejabberd    |         #jid{
ejabberd    |             user = <<"room">>,server = <<"conference.chat.example.com">>,
ejabberd    |             resource = <<>>,luser = <<"room">>,
ejabberd    |             lserver = <<"conference.chat.example.com">>,lresource = <<>>},
ejabberd    |     to =
ejabberd    |         #jid{
ejabberd    |             user = <<"karim">>,server = <<"chat.example.com">>,
ejabberd    |             resource = <<"chatsecure2084">>,luser = <<"karim">>,
ejabberd    |             lserver = <<"chat.example.com">>,lresource = <<"chatsecure2084">>},
ejabberd    |     subject = [],
ejabberd    |     body = [#text{lang = <<>>,data = <<"d">>}],
ejabberd    |     thread = undefined,
ejabberd    |     sub_els =
ejabberd    |         [#xmlel{
ejabberd    |              name = <<"request">>,
ejabberd    |              attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>}],
ejabberd    |              children = []},
ejabberd    |          #xmlel{
ejabberd    |              name = <<"origin-id">>,
ejabberd    |              attrs =
ejabberd    |                  [{<<"xmlns">>,<<"urn:xmpp:sid:0">>},
ejabberd    |                   {<<"id">>,<<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>}],
ejabberd    |              children = []},
ejabberd    |          #stanza_error{
ejabberd    |              type = cancel,code = 503,by = undefined,
ejabberd    |              reason = 'service-unavailable',
ejabberd    |              text =
ejabberd    |                  [#text{lang = <<"en">>,data = <<"User session not found">>}],
ejabberd    |              sub_els = []}],
ejabberd    |     meta =
ejabberd    |         #{ip => {0,0,0,0,0,65535,10605,62329},stanza_id => 1600342437903092}}
ejabberd    | 2020-09-17 11:33:57.906287+00:00 [debug] Running hook sm_receive_packet: mod_mam:sm_receive_packet/1
ejabberd    | 2020-09-17 11:33:57.906606+00:00 [debug] Processing packet to full JID:
ejabberd    | #message{
ejabberd    |     id = <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>,type = error,
ejabberd    |     lang = <<"en">>,
ejabberd    |     from =
ejabberd    |         #jid{
ejabberd    |             user = <<"room">>,server = <<"conference.chat.example.com">>,
ejabberd    |             resource = <<>>,luser = <<"room">>,
ejabberd    |             lserver = <<"conference.chat.example.com">>,lresource = <<>>},
ejabberd    |     to =
ejabberd    |         #jid{
ejabberd    |             user = <<"karim">>,server = <<"chat.example.com">>,
ejabberd    |             resource = <<"chatsecure2084">>,luser = <<"karim">>,
ejabberd    |             lserver = <<"chat.example.com">>,lresource = <<"chatsecure2084">>},
ejabberd    |     subject = [],
ejabberd    |     body = [#text{lang = <<>>,data = <<"d">>}],
ejabberd    |     thread = undefined,
ejabberd    |     sub_els =
ejabberd    |         [#xmlel{
ejabberd    |              name = <<"request">>,
ejabberd    |              attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>}],
ejabberd    |              children = []},
ejabberd    |          #xmlel{
ejabberd    |              name = <<"origin-id">>,
ejabberd    |              attrs =
ejabberd    |                  [{<<"xmlns">>,<<"urn:xmpp:sid:0">>},
ejabberd    |                   {<<"id">>,<<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>}],
ejabberd    |              children = []},
ejabberd    |          #stanza_error{
ejabberd    |              type = cancel,code = 503,by = undefined,
ejabberd    |              reason = 'service-unavailable',
ejabberd    |              text =
ejabberd    |                  [#text{lang = <<"en">>,data = <<"User session not found">>}],
ejabberd    |              sub_els = []}],
ejabberd    |     meta =
ejabberd    |         #{ip => {0,0,0,0,0,65535,10605,62329},stanza_id => 1600342437903092}}
ejabberd    | 2020-09-17 11:33:57.907612+00:00 [debug] Sending to process <0.712.0>:
ejabberd    | #message{
ejabberd    |     id = <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>,type = error,
ejabberd    |     lang = <<"en">>,
ejabberd    |     from =
ejabberd    |         #jid{
ejabberd    |             user = <<"room">>,server = <<"conference.chat.example.com">>,
ejabberd    |             resource = <<>>,luser = <<"room">>,
ejabberd    |             lserver = <<"conference.chat.example.com">>,lresource = <<>>},
ejabberd    |     to =
ejabberd    |         #jid{
ejabberd    |             user = <<"karim">>,server = <<"chat.example.com">>,
ejabberd    |             resource = <<"chatsecure2084">>,luser = <<"karim">>,
ejabberd    |             lserver = <<"chat.example.com">>,lresource = <<"chatsecure2084">>},
ejabberd    |     subject = [],
ejabberd    |     body = [#text{lang = <<>>,data = <<"d">>}],
ejabberd    |     thread = undefined,
ejabberd    |     sub_els =
ejabberd    |         [#xmlel{
ejabberd    |              name = <<"request">>,
ejabberd    |              attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>}],
ejabberd    |              children = []},
ejabberd    |          #xmlel{
ejabberd    |              name = <<"origin-id">>,
ejabberd    |              attrs =
ejabberd    |                  [{<<"xmlns">>,<<"urn:xmpp:sid:0">>},
ejabberd    |                   {<<"id">>,<<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>}],
ejabberd    |              children = []},
ejabberd    |          #stanza_error{
ejabberd    |              type = cancel,code = 503,by = undefined,
ejabberd    |              reason = 'service-unavailable',
ejabberd    |              text =
ejabberd    |                  [#text{lang = <<"en">>,data = <<"User session not found">>}],
ejabberd    |              sub_els = []}],
ejabberd    |     meta =
ejabberd    |         #{ip => {0,0,0,0,0,65535,10605,62329},stanza_id => 1600342437903092}}
ejabberd    | 2020-09-17 11:33:57.907908+00:00 [debug] Running hook c2s_handle_info: ejabberd_sm:c2s_handle_info/2
ejabberd    | 2020-09-17 11:33:57.908560+00:00 [debug] Running hook c2s_handle_info: mod_offline:c2s_handle_info/2
ejabberd    | 2020-09-17 11:33:57.908678+00:00 [debug] Running hook c2s_handle_info: mod_pubsub:c2s_handle_info/2
ejabberd    | 2020-09-17 11:33:57.908815+00:00 [debug] Running hook c2s_handle_info: mod_push_keepalive:c2s_handle_info/2
ejabberd    | 2020-09-17 11:33:57.908900+00:00 [debug] Running hook c2s_handle_info: mod_stream_mgmt:c2s_handle_info/2
ejabberd    | 2020-09-17 11:33:57.909010+00:00 [debug] Running hook c2s_handle_info: ejabberd_c2s:process_info/2
ejabberd    | 2020-09-17 11:33:57.909094+00:00 [debug] Running hook privacy_check_packet: mod_last:privacy_check_packet/4
ejabberd    | 2020-09-17 11:33:57.909230+00:00 [debug] Running hook privacy_check_packet: mod_privacy:check_packet/4
ejabberd    | 2020-09-17 11:33:57.909323+00:00 [debug] Running hook user_receive_packet: mod_caps:user_receive_packet/1
ejabberd    | 2020-09-17 11:33:57.909950+00:00 [debug] Running hook user_receive_packet: mod_mam:user_receive_packet/1
ejabberd    | 2020-09-17 11:33:57.910035+00:00 [debug] Running hook user_receive_packet: mod_carboncopy:user_receive_packet/1
ejabberd    | 2020-09-17 11:33:57.910197+00:00 [debug] Running hook c2s_filter_send: mod_client_state:filter_chat_states/1
ejabberd    | 2020-09-17 11:33:57.910282+00:00 [debug] Running hook c2s_filter_send: mod_client_state:filter_pep/1
ejabberd    | 2020-09-17 11:33:57.910388+00:00 [debug] Running hook c2s_filter_send: mod_client_state:filter_presence/1
ejabberd    | 2020-09-17 11:33:57.910469+00:00 [debug] Running hook c2s_filter_send: mod_client_state:filter_other/1
ejabberd    | 2020-09-17 11:33:57.911432+00:00 [debug] Won't add stanza for karim@chat.example.com/chatsecure2084 to CSI queue
ejabberd    | 2020-09-17 11:33:57.911518+00:00 [debug] Flushing packets of room@conference.chat.example.com from CSI queue of karim@chat.example.com/chatsecure2084
ejabberd    | 2020-09-17 11:33:57.912255+00:00 [notice] (tls|<0.712.0>) Send XML on stream = <<"<message xml:lang='en' to='karim@chat.example.com/chatsecure2084' from='room@conference.chat.example.com' type='error' id='B1668FC8-4AAD-4E8C-9386-EAF947B44770'><request xmlns='urn:xmpp:receipts'/><origin-id xmlns='urn:xmpp:sid:0' id='B1668FC8-4AAD-4E8C-9386-EAF947B44770'/><error code='503' type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>User session not found</text></error><body>d</body></message>">>
ejabberd    | 2020-09-17 11:33:57.912565+00:00 [debug] Running hook c2s_handle_send: mod_push:c2s_stanza/3
ejabberd    | 2020-09-17 11:33:57.912678+00:00 [debug] Running hook c2s_handle_send: mod_push_keepalive:c2s_stanza/3
ejabberd    | 2020-09-17 11:33:57.912762+00:00 [debug] Running hook c2s_handle_send: mod_stream_mgmt:c2s_handle_send/3
ejabberd    | 2020-09-17 11:33:57.912887+00:00 [debug] Running hook c2s_filter_send: mod_client_state:filter_chat_states/1
ejabberd    | 2020-09-17 11:33:57.912970+00:00 [debug] Running hook c2s_filter_send: mod_client_state:filter_pep/1
ejabberd    | 2020-09-17 11:33:57.913672+00:00 [debug] Running hook c2s_filter_send: mod_client_state:filter_presence/1
ejabberd    | 2020-09-17 11:33:57.913776+00:00 [debug] Running hook c2s_filter_send: mod_client_state:filter_other/1
ejabberd    | 2020-09-17 11:33:57.913943+00:00 [notice] (tls|<0.712.0>) Send XML on stream = <<"<r xmlns='urn:xmpp:sm:3'/>">>
ejabberd    | 2020-09-17 11:33:57.914102+00:00 [debug] Running hook c2s_handle_send: mod_push:c2s_stanza/3
ejabberd    | 2020-09-17 11:33:57.914234+00:00 [debug] Running hook c2s_handle_send: mod_push_keepalive:c2s_stanza/3
ejabberd    | 2020-09-17 11:33:57.914315+00:00 [debug] Running hook c2s_handle_send: mod_stream_mgmt:c2s_handle_send/3
ejabberd    | 2020-09-17 11:33:58.282870+00:00 [notice] (tls|<0.712.0>) Received XML on stream = <<"<a xmlns=\"urn:xmpp:sm:3\" h=\"40\"/>">>
ejabberd    | 2020-09-17 11:33:58.283180+00:00 [debug] Running hook c2s_handle_recv: mod_stream_mgmt:c2s_handle_recv/3
ejabberd    | 2020-09-17 11:33:58.283342+00:00 [debug] Running hook c2s_authenticated_packet: mod_client_state:c2s_authenticated_packet/2
ejabberd    | 2020-09-17 11:33:58.283437+00:00 [debug] Running hook c2s_authenticated_packet: mod_stream_mgmt:c2s_authenticated_packet/2
ejabberd    | 2020-09-17 11:33:58.283609+00:00 [debug] karim@chat.example.com/chatsecure2084 acknowledged 40 of 41 stanzas
ejabberd    | 2020-09-17 11:33:58.377974+00:00 [notice] (tls|<0.712.0>) Received XML on stream = <<"<message type=\"error\" to=\"room@conference.chat.example.com\"><received xmlns=\"urn:xmpp:receipts\" id=\"B1668FC8-4AAD-4E8C-9386-EAF947B44770\"/><origin-id xmlns=\"urn:xmpp:sid:0\" id=\"0E861364-CAA9-4B37-8A46-46CCEC05275E\"/></message>">>
ejabberd    | 2020-09-17 11:33:58.378323+00:00 [debug] Running hook c2s_handle_recv: mod_stream_mgmt:c2s_handle_recv/3
ejabberd    | 2020-09-17 11:33:58.378440+00:00 [debug] Running hook c2s_authenticated_packet: mod_client_state:c2s_authenticated_packet/2
ejabberd    | 2020-09-17 11:33:58.378588+00:00 [debug] Running hook c2s_authenticated_packet: mod_stream_mgmt:c2s_authenticated_packet/2
ejabberd    | 2020-09-17 11:33:58.378711+00:00 [debug] Running hook user_send_packet: mod_privacy:user_send_packet/1
ejabberd    | 2020-09-17 11:33:58.378826+00:00 [debug] Running hook user_send_packet: mod_vcard_xupdate:user_send_packet/1
ejabberd    | 2020-09-17 11:33:58.378912+00:00 [debug] Running hook user_send_packet: mod_caps:user_send_packet/1
ejabberd    | 2020-09-17 11:33:58.379059+00:00 [debug] Running hook user_send_packet: mod_mam:user_send_packet/1
ejabberd    | 2020-09-17 11:33:58.379154+00:00 [debug] Running hook user_send_packet: mod_carboncopy:user_send_packet/1
ejabberd    | 2020-09-17 11:33:58.379393+00:00 [debug] Running hook user_send_packet: mod_mam:user_send_packet_strip_tag/1
ejabberd    | 2020-09-17 11:33:58.379485+00:00 [debug] Running hook privacy_check_packet: mod_last:privacy_check_packet/4
ejabberd    | 2020-09-17 11:33:58.379607+00:00 [debug] Running hook privacy_check_packet: mod_privacy:check_packet/4
ejabberd    | 2020-09-17 11:33:58.379866+00:00 [debug] Route:
ejabberd    | #message{id = <<>>,type = error,lang = <<"en">>,
ejabberd    |          from = #jid{user = <<"karim">>,server = <<"chat.example.com">>,
ejabberd    |                      resource = <<"chatsecure2084">>,luser = <<"karim">>,
ejabberd    |                      lserver = <<"chat.example.com">>,
ejabberd    |                      lresource = <<"chatsecure2084">>},
ejabberd    |          to = #jid{user = <<"room">>,server = <<"conference.chat.example.com">>,
ejabberd    |                    resource = <<>>,luser = <<"room">>,
ejabberd    |                    lserver = <<"conference.chat.example.com">>,lresource = <<>>},
ejabberd    |          subject = [],body = [],thread = undefined,
ejabberd    |          sub_els = [#xmlel{name = <<"received">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>},
ejabberd    |                                     {<<"id">>,
ejabberd    |                                      <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>}],
ejabberd    |                            children = []},
ejabberd    |                     #xmlel{name = <<"origin-id">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:sid:0">>},
ejabberd    |                                     {<<"id">>,
ejabberd    |                                      <<"0E861364-CAA9-4B37-8A46-46CCEC05275E">>}],
ejabberd    |                            children = []}],
ejabberd    |          meta = #{ip => {0,0,0,0,0,65535,10605,62329}}}
ejabberd    | 2020-09-17 11:33:58.381877+00:00 [debug] Local route:
ejabberd    | #message{id = <<>>,type = error,lang = <<"en">>,
ejabberd    |          from = #jid{user = <<"karim">>,server = <<"chat.example.com">>,
ejabberd    |                      resource = <<"chatsecure2084">>,luser = <<"karim">>,
ejabberd    |                      lserver = <<"chat.example.com">>,
ejabberd    |                      lresource = <<"chatsecure2084">>},
ejabberd    |          to = #jid{user = <<"room">>,server = <<"conference.chat.example.com">>,
ejabberd    |                    resource = <<>>,luser = <<"room">>,
ejabberd    |                    lserver = <<"conference.chat.example.com">>,lresource = <<>>},
ejabberd    |          subject = [],body = [],thread = undefined,
ejabberd    |          sub_els = [#xmlel{name = <<"received">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>},
ejabberd    |                                     {<<"id">>,
ejabberd    |                                      <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>}],
ejabberd    |                            children = []},
ejabberd    |                     #xmlel{name = <<"origin-id">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:sid:0">>},
ejabberd    |                                     {<<"id">>,
ejabberd    |                                      <<"0E861364-CAA9-4B37-8A46-46CCEC05275E">>}],
ejabberd    |                            children = []}],
ejabberd    |          meta = #{ip => {0,0,0,0,0,65535,10605,62329}}}
ejabberd    | 2020-09-17 11:33:58.382876+00:00 [debug] Running hook sm_receive_packet: mod_mam:sm_receive_packet/1
ejabberd    | 2020-09-17 11:33:58.383757+00:00 [debug] Processing message to bare JID:
ejabberd    | #message{id = <<>>,type = error,lang = <<"en">>,
ejabberd    |          from = #jid{user = <<"karim">>,server = <<"chat.example.com">>,
ejabberd    |                      resource = <<"chatsecure2084">>,luser = <<"karim">>,
ejabberd    |                      lserver = <<"chat.example.com">>,
ejabberd    |                      lresource = <<"chatsecure2084">>},
ejabberd    |          to = #jid{user = <<"room">>,server = <<"conference.chat.example.com">>,
ejabberd    |                    resource = <<>>,luser = <<"room">>,
ejabberd    |                    lserver = <<"conference.chat.example.com">>,lresource = <<>>},
ejabberd    |          subject = [],body = [],thread = undefined,
ejabberd    |          sub_els = [#xmlel{name = <<"received">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:receipts">>},
ejabberd    |                                     {<<"id">>,
ejabberd    |                                      <<"B1668FC8-4AAD-4E8C-9386-EAF947B44770">>}],
ejabberd    |                            children = []},
ejabberd    |                     #xmlel{name = <<"origin-id">>,
ejabberd    |                            attrs = [{<<"xmlns">>,<<"urn:xmpp:sid:0">>},
ejabberd    |                                     {<<"id">>,
ejabberd    |                                      <<"0E861364-CAA9-4B37-8A46-46CCEC05275E">>}],
ejabberd    |                            children = []}],
ejabberd    |          meta = #{ip => {0,0,0,0,0,65535,10605,62329},
ejabberd    |                   stanza_id => 1600342438383007}}
ejabberd    | 2020-09-17 11:33:58.384160+00:00 [debug] Running hook bounce_sm_packet: ejabberd_sm:bounce_sm_packet/1
```

## Bug description

When I try to send a message to any MUC room such as:

```xml
<message to="room@conference.chat.example.com" type="groupchat">
    <body>TEST</body>
</message>
```

The message will not be delivered to the room or other participants and I get this response from the server:
```xml
<message
xmlns="jabber:client" lang="en" to="karim@chat.example.com/resource" from="room@conference.chat.example.com" type="error">
<error code="503" type="cancel">
    <service-unavailable
        xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">
    </service-unavailable>
    <text
        xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" lang="en">User session not found
    </text>
</error>
<body>TEST</body>
```

Im using **ejabberd Community Server v20.07** installed into Docker using the [official image](https://hub.docker.com/r/ejabberd/ecs).
