### ISSUE TITLE
mqtt unregister/kick does not terminate active session(s)

### ISSUE THREAD

**Issue by ajs124** [processone/ejabberd#3426]
## Environment
- ejabberd version: `20.04`
- Erlang version: `Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1]`
- OS: Linux (Alpine Linux v3.11)
- Installed from: docker (ejabberd/ecs)

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
listen:
  -
    port: 1883
    module: mod_mqtt
    backlog: 1000

modules:
  mod_mqtt: {}
```

## Errors from error.log/crash.log
No errors

## Bug description
As the title states, a client connected over MQTT does not have its session(s) terminated when the user it authenticated with is unregistered or kicked.

Maybe this is intended, but I would have assumed these functions to work that way.
