### ISSUE TITLE
@ejabberd_pkix:log_errors:401 Failed to read PEM file /etc/pki/ejabberd/certs/jabber.domain.tld.fullchain.pem: at line 39: no matching private key found for this certificate

### ISSUE THREAD

**Issue by SDuesterhaupt** [processone/ejabberd#3442]
### Environment
ejabberd version: 20.07
Erlang version: ...
OS: CentOS 8 Stream
SELinux: temporarily deactivated (# setenforce 0)
openssl version: OpenSSL 1.1.1g FIPS  21 Apr 2020
Installed from: https://static.process-one.net/ejabberd/downloads/20.07/ejabberd-20.07-0.x86_64.rpm

### Configuration
```
###
###'           ejabberd configuration file
###
### The parameters used in this configuration file are explained at
###
###       https://docs.ejabberd.im/admin/configuration
###
### The configuration file is written in YAML.
### *******************************************************
### *******           !!! WARNING !!!               *******
### *******     YAML IS INDENTATION SENSITIVE       *******
### ******* MAKE SURE YOU INDENT SECTIONS CORRECTLY *******
### *******************************************************
### Refer to http://en.wikipedia.org/wiki/YAML for the brief description.
### However, ejabberd treats different literals as different types:
###
### - unquoted or single-quoted strings. They are called "atoms".
###   Example: dog, 'Jupiter', '3.14159', YELLOW
###
### - numeric literals. Example: 3, -45.0, .0
###
### - quoted or folded strings.
###   Examples of quoted string: "Lizzard", "orange".
###   Example of folded string:
###   > Art thou not Romeo,
###     and a Montague?
###

# SDuesterhaupt: 2019-02-10 - Defines the default language of server strings that can be seen by XMPP clients.
#                If a XMPP client does not support xml:lang, the specified language is used.
#                
#                In order to take effect there must be a translation file Language.msg in ejabberd’s msgs directory.
#                
# default:       language: en
language: "en"

# SDuesterhaupt: 2019-01-24 - Configuring One or Several XMPP Domains
#                ejabberd supports managing several independent XMPP domains
#                on a single ejabberd instance, using a feature called virtual hosting.
#                
#                The option hosts defines a list containing one or more domains that
#                ejabberd will serve.
#                
#                Of course, the hosts list can contain just one domain if you do not want to
#                host multiple XMPP domains on the same instance.
#                
#                The syntax is: ["HostName1", "Hostname2"]
#                
#                Examples:
#                
#                  Serving one domain:
#                  
#                  hosts: ["example.org"]
#                  
#                  Serving three domains:
#                  
#                  hosts:
#                    - "example.net"
#                    - "example.com"
#                    - "jabber.somesite.org"
#                
# default:       hosts: ["localhost"]
#                
hosts:
  #- "XXX.XXXX.de"
  - "XXX.XXXX.de"
  
  
# SDuesterhaupt: 2019-01-27 - Virtual Hosting
#                When managing several XMPP domains in a single instance, those domains are truly independent.
#                It means they can even have different configuration parameters.
#                
#                Options can be defined separately for every virtual host using the host_config option.
#                
#                The syntax is: {HostName: [Option, ...]}
#
# default:       na
#host_config:
  #"XXX.XXXX.de":
    # SDuesterhaupt: 2019-01-30 - Specify a different certificate for each served hostname.
    #                Option 'domain_certfile' is deprecated, use 'certfiles' instead
    #                
    # default:       domain_certfile: Path: Full path to the file containing the SSL certificate for a specific domain.
    #domain_certfile: "/etc/pki/ejabberd/certs/XXX.XXXX.de.fullchain.pem"


# SDuesterhaupt: 2019-02-10 - Use the 'new' MySQL scheme
#                
# default:       new_sql_schema: false
new_sql_schema: true
    
# SDuesterhaupt: 2019-01-24 - Desired authentication backend
#                If you decide to store user password in ejabberd, you need to tell ejabberd to use MySQL
#                instead of internal database for authentication.
#                
# default:       auth_method: internal
auth_method: sql

# SDuesterhaupt: 2019-02-07 - Authentication password format
#                
# default:       auth_password_format: plain
auth_password_format: scram

# SDuesterhaupt: 2019-01-24 - MySQL connection configuration
#                Those parameters are mandatory if you want to use MySQL with ejabberd.
#
# default:       sql_type: mysql
#                sql_server: "localhost"
#                sql_database: "ejabberd"
#                sql_username: "ejabberd"
#                sql_password: "password"
#                sql_port: 3306
sql_type: mysql
sql_server: "127.0.0.1"
sql_database: "ejabberd"
sql_username: "XXXX"
sql_password: "XXXX"
sql_port: 3306
# SDuesterhaupt: 2019-01-24 - Switch modules to use MySQL instead of Mnesia
#                If you want to use MySQL for all modules that support MySQL as db_type,
#                you can simply use global option.
#
# default:       default_db: 
default_db: sql


# SDuesterhaupt: 2019-01-24 - Logging
#                ejabberd configuration can help a lot by having the right
#                amount of logging set up.
#                
#                Here is a few general option to configure logging:
#                
#                loglevel: Number: Verbosity of log files generated by ejabberd. Available levels are.
#                
#                  0: No ejabberd log at all (not recommended)
#                  1: Critical
#                  2: Error
#                  3: Warning
#                  4: Info
#                  5: Debug
#
# default:       loglevel: 4
#                log_rotate_size: 10485760
#                log_rotate_date: "" (deprecated)
#                log_rotate_count: 1
#                log_rate_limit: 100 (deprecated
loglevel: 3
#log_rotate_size: 0          # Disable rotation triggered by log size
log_rotate_size: 10485760   # Rotate the log files when they get grown above a certain size (10Mb)
#log_rotate_date: "$W0D23"   # Rotate every week on Sunday at 23:00 hr
log_rotate_count: 4         # Keep 4 weeks worth of backlogs
#log_rate_limit: 100         # When system is overloaded, you can set a limit


# SDuesterhaupt: 2020-12-05 - Privacy option to disable logging of IP address or sensitive data.
#                
# default:       hide_sensitive_log_data: false
hide_sensitive_log_data: false



### [x] Global TLS options
### ======================
##

## Define common macros
## --------------------
#

define_macro:
  'CIPHERS': "ECDH:DH:!3DES:!aNULL:!eNULL:!MEDIUM@STRENGTH"
  'TLSOPTS':
    - "no_sslv2"
    - "no_sslv3"
    - "no_tlsv1"
    - "no_tlsv1_1"
    - "cipher_server_preference"
  'DHFILE': "/etc/pki/tls/private/dh_2048.pem"
  

# SDuesterhaupt: 2020-12-04 - Path to a file of CA root certificates
#                The default is to use system defined file if possible.
#                For server conections, this ca_file option is overriden
#                by the s2s_cafile option.
#                
# default:       na
#ca_file: "/etc/pki/ejabberd/certs/LE_CA.chain.pem"


## Client to server (c2s)
## ----------------------
#

# SDuesterhaupt: 2020-12-04 - Full path to a file containing one or more CA
#                certificates in PEM format. All client certificates should be
#                signed by one of these root CA certificates and should contain
#                the corresponding JID(s) in subjectAltName field.
#                There is no default value.
#                
#                You can use host_config to specify this option per-vhost.
#                
#                To set a specific file per listener, use the listener’s cafile
#                option. Please notice that c2s_cafile overrides the listener’s
#                cafile option.
#                
# default:       na
#c2s_cafile: "/etc/pki/ejabberd/certs/LE_CA.chain.pem"

# SDuesterhaupt: 2019-01-30 - List of file paths (optionally with wildcards)
#                containing either PEM certificates or PEM private keys
#
# default:       certfiles:
#                  - "/opt/ejabberd-18.12.1/conf/server.pem"
#                  - "/etc/letsencrypt/live/localhost/fullchain.pem"
#                  - "/etc/letsencrypt/live/localhost/privkey.pem"
certfiles:
    #- "/etc/pki/ejabberd/certs/XXX.XXXX.de.fullchain.pem"
    #- "/etc/pki/ejabberd/private/XXX.XXXX.de.cert.pem"
    #- "/etc/pki/ejabberd/private/XXX.XXXX.de.key.pem"
    - "/etc/pki/ejabberd/certs/XXX.XXXX.de.fullchain.pem"
    #- "/etc/pki/ejabberd/certs/XXX.XXXX.de.cert.pem"
    - "/etc/pki/ejabberd/private/XXX.XXXX.de.key.pem"

# SDuesterhaupt: 2019-01-30 - OpenSSL ciphers list in the same format accepted
#                by ‘openssl ciphers’ command.
#
# default:       c2s_ciphers: Ciphers
c2s_ciphers: 'CIPHERS'

# SDuesterhaupt: 2019-01-30 - Perfect Forward Secrecy
#                Full path to a file containing custom DH parameters. Such a file could
#                be created with the command openssl dhparam -out dh.pem 2048. If this option
#                is not specified, default parameters will be used, which might not provide the
#                same level of security as using custom parameters.
#
# default:       c2s_dhfile: ""
c2s_dhfile: 'DHFILE'

# SDuesterhaupt: 2019-01-30 - List of general options relating to SSL/TLS.
#                
# default:       c2s_protocol_options: "no_sslv3|cipher_server_preference|no_compression"
c2s_protocol_options: 'TLSOPTS'

# SDuesterhaupt: 2019-01-30 - Whether to enable or disable TLS compression for c2s connections.
#                
# default:       c2s_tls_compression: false
#c2s_tls_compression: false


## Server to server (s2s)
## ----------------------
#

# SDuesterhaupt: 2020-12-04 - A path to a file with CA root certificates
#                that will be used to authenticate s2s connections.
#                If not set, the value of ca_file will be used.
#                
#                You can use host_config to specify this option per-vhost.
#                
# default:       s2s_cafile: ""
#s2s_cafile: "/etc/pki/ejabberd/certs/LE_CA.chain.pem"

# SDuesterhaupt: 2019-01-30 - Defines if s2s connections don’t use STARTTLS encryption;
#                if STARTTLS can be used optionally; if STARTTLS is required to establish the connection;
#                or if STARTTLS is required and the remote certificate must be valid and trusted.
#                
#                s2s_use_starttls: false|optional|required|required_trusted
#                 
# default:       s2s_use_starttls: false
s2s_use_starttls: required

# SDuesterhaupt: 2019-01-30 - Full path to a file containing a SSL certificate.
#                
# default:       s2s_certfile: ""
#s2s_certfile: ""

# SDuesterhaupt: 2019-01-30 - OpenSSL ciphers list in the same format accepted
#                by ‘openssl ciphers’ command.
#
# default:       s2s_ciphers: Ciphers
s2s_ciphers: 'CIPHERS'

# SDuesterhaupt: 2019-01-30 - Perfect Forward Secrecy
#                Full path to a file containing custom DH parameters. Such a file could
#                be created with the command openssl dhparam -out dh.pem 2048. If this option
#                is not specified, default parameters will be used, which might not provide the
#                same level of security as using custom parameters.
#
# default:       s2s_dhfile: ""
s2s_dhfile: 'DHFILE'

# SDuesterhaupt: 2019-01-30 - List of general options relating to SSL/TLS.
#                
# default:       s2s_protocol_options: "no_sslv3|cipher_server_preference|no_compression"
s2s_protocol_options: 'TLSOPTS'

# SDuesterhaupt: 2019-01-30 - Whether to enable or disable TLS compression for s2s connections.
#                
# default:       s2s_tls_compression: false
#s2s_tls_compression: false

# SDuesterhaupt: 2019-01-30 - Specify which address families to try, in what order.
#                By default it first tries connecting with IPv4, if that fails it tries using IPv6.
#                
# default:       outgoing_s2s_families:
#                  - ipv4
#                  - ipv6
outgoing_s2s_families:
  - ipv4
  - ipv6



### [x] Listening Ports
### ===================
##

# SDuesterhaupt: 2019-01-30 - The option listen defines for which ports, addresses
#                and network protocols ejabberd will listen and what services will be run
#                on them. Each element of the list is an associative array with the following
#                elements:
#                
#                 - Port number. Optionally also the IP address and/or a transport protocol.
#                 - Listening module that serves this port.
#                 - Options for the TCP socket and for the listening module.
#                
# default:       na
listen:
  -
    # SDuesterhaupt: 2019-01-30 - Handles c2s connections.
    #                
    # default:       port: 5222
    port: 5222
    # SDuesterhaupt: 2019-01-30 - Listening on IP(s)
    #                
    # default:       ip: "::"
    #ip: "0.0.0.0"
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    # SDuesterhaupt: 2019-01-31 - This option specifies that STARTTLS encryption is available
    #                on connections to the port. You should also set the certfiles option.
    #                
    # default:       starttls: false
    starttls: true
    # SDuesterhaupt: 2019-01-31 - This option specifies that STARTTLS encryption is required on
    #                connections to the port. No unencrypted connections will be allowed.
    #                You should also set the certfiles option.    
    #                
    # default:       starttls_required: false
    starttls_required: true
  -
    # SDuesterhaupt: 2019-01-30 - Handles incoming s2s connections.
    #                
    # default:       port: 5269
    port: 5269
    # SDuesterhaupt: 2019-01-30 - Listening on IP(s)
    #                
    # default:       ip: "::"
    #ip: "0.0.0.0"
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    # SDuesterhaupt: 2019-01-30 - Handles incoming unsecured HTTP connections.
    #                This module is responsible for serving Web Admin.
    #                !!!depricated!!!
    #                
    # default:       port: 5280
    port: 5280
    # SDuesterhaupt: 2019-01-30 - Listening on IP(s)
    #                
    # default:       ip: "::"
    ip: "127.0.0.1"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
  -
    # SDuesterhaupt: 2019-01-30 - Handles incoming secured HTTP connections.
    #                This module is responsible for serving Web Admin.
    #                
    # default:       port: 5443
    port: 5443
    # SDuesterhaupt: 2019-01-30 - Listening on IP(s)
    #                
    # default:       ip: "::"
    #ip: "0.0.0.0"
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /api: mod_http_api
      /bosh: mod_bosh
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
      /oauth: ejabberd_oauth
    # SDuesterhaupt: 2019-02-08 - Enables the Web Admin for ejabberd administration which is available
    #                at http://server:port/admin/. To login, provide the JID (username@servername) and
    #                password of one of the registered users who are granted access by the ‘configure’ access rule.
    # default:       #  "/admin": ejabberd_web_admin
    #  /admin: ejabberd_web_admin
    captcha: false
    tls: true
  -
    port: 1883
    # SDuesterhaupt: 2019-01-30 - Listening on IP(s)
    #                
    # default:       ip: "::"
    ip: "127.0.0.1"
    module: mod_mqtt
    backlog: 1000
  #-
    # SDuesterhaupt: 2020-0602 - Internal STUN/TURN server
    #                
    # default:       na
    #port: 3478
    #transport: udp
    #use_turn: true
    #turn_ip: xxx.xxx.xxx.xxx  # VS-D-XXXX
    #auth_type: user
    #auth_realm: "XXX.XXXX.de"
    #module: ejabberd_stun



acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
  admin:
    user:
      #- "admin@XXX.XXXX.de"
      - "admin@XXX.XXXX.de"
  poweruser:
    user:
      #- "XX@XXX.XXXX.de"
      - "XX@XXX.XXXX.de"

access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: poweruser
    - 2000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast

max_fsm_queue: 10000

acme:
   contact: "mailto:root@XXXX.de"
   #ca_url: "https://acme-v01.api.letsencrypt.org"
   ca_url: "https://acme-v02.api.letsencrypt.org/directory"

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  # SDuesterhaupt: 2019-02-08 - This module allows for requesting permissions to upload a file
  #                via HTTP as described in XEP-0363. If the request is accepted, the client receives
  #                a URL for uploading the file and another URL from which that file can later be downloaded.
  #                
  #                In order to use this module, it must be configured as a request_handler for an ejabberd_http listener.
  mod_http_upload:
    # SDuesterhaupt: 2019-02-08 - This option defines the JID for the HTTP upload service.
    #                The keyword “@HOST@” is replaced with the virtual host name.
    #                
    # default:       put_url: "upload.@HOST@"
    put_url: "https://@HOST@:5443/upload"
    # SDuesterhaupt: 2019-02-08 - This option defines the access rule to limit who is permitted to use the
    #                HTTP upload service. The default value is local. If no access rule of that name exists,
    #                no user will be allowed to use the service.
    #                
    # default:       access: local
    access: local
    # SDuesterhaupt: 2019-02-08 - This option limits the acceptable file size. Either a number of bytes
    #                (larger than zero) or infinity must be specified.
    #                
    # default:       max_size: 104857600 # 100 MByte
    #max_size: 26214400 # 25 MByte
    max_size: 52428800 # 50 MByte
  # SDuesterhaupt: 2019-02-08 - This module adds quota support for mod_http_upload.
  mod_http_upload_quota:
    # SDuesterhaupt: 2019-04-10 - If a number larger than zero is specified, any files (and directories)
    #                older than this number of days are removed from the subdirectories of the docroot directory,
    #                once per day.
    #                
    # default:       max_days: infinity
    max_days: 30
  mod_last: {}
  # SDuesterhaupt: 2019-06-04 - Message Archive Management as described in XEP-0313
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    ## db_type: sql
    assume_mam_usage: true
    default: always
  #mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      mam: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - "flat"
      - "pep"
    force_node_config:
      ## Change from "whitelist" to "open" to enable OMEMO support
      ## See https://github.com/processone/ejabberd/issues/2425
      "eu.siacs.conversations.axolotl.*":
        access_model: open
      ## Avoid buggy clients to make their bookmarks public
      "storage:bookmarks":
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  #mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ##ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
  mod_stun_disco:
    secret: XXXX
    services:
      -
        host: XXX.XXXX.de
        port: 3478
        type: stun
        transport: udp
        restricted: false
      -
        host: XXX.XXXX.de
        port: 3478
        type: turn
        transport: udp
        restricted: true
      -
        host: XXX.XXXX.de
        port: 5349
        type: stuns
        transport: tcp
        restricted: false
      -
        host: XXX.XXXX.de
        port: 5349
        type: turns
        transport: tcp
        restricted: true
    

## Add module(s) to vhost 'XXX.XXXX.de'
## ------------------------------------
#
#append_host_config:
#  "XXX.XXXX.de":
#    modules:
#      mod_register:
        ## Only accept registration requests from the "trusted"
        ## network (see access_rules section above).
        ## Think twice before enabling registration from any
        ## address. See the Jabber SPAM Manifesto for details:
        ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
#        ip_access: trusted_network
        
        
## Add module(s) to vhost 'XXX.XXXX.de'
## ------------------------------------
#
append_host_config:
  "XXX.XXXX.de":
    modules:
      mod_register:
        ## Only accept registration requests from the "trusted"
        ## network (see access_rules section above).
        ## Think twice before enabling registration from any
        ## address. See the Jabber SPAM Manifesto for details:
        ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
        ip_access: trusted_network
        
        
### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8
```

### Error description
I have configured ejabberd by the configuration file above. I moved a Let's Encrypt certificate/key pair from Debian to the CentOS8 Stream server.

The ejabberd.log shows the following:

```
2020-12-08 08:58:50.632 [error] <0.385.0>@ejabberd_pkix:log_errors:401 Failed to read PEM file /etc/pki/ejabberd/certs/XXX.XXXX.de.fullchain.pem: at line 39: no matching private key found for this certificate
2020-12-08 08:58:50.640 [critical] <0.385.0>@ejabberd_pkix:stop_ejabberd:352 ejabberd initialization was aborted due to invalid certificates configuration
```

### Certificate/key
The certificate/key pair is valid:

```
openssl x509 -noout -modulus -in /etc/pki/ejabberd/certs/XXX.XXXX.de.fullchain.pem | openssl md5
(stdin)= 942c68d45666c4e59fd351f5c24da5ad

openssl x509 -noout -modulus -in /etc/pki/ejabberd/certs/XXX.XXXX.de.cert.pem | openssl md5
(stdin)= 942c68d45666c4e59fd351f5c24da5ad

openssl rsa -noout -modulus -in /etc/pki/ejabberd/private/XXX.XXXX.de.key.pem | openssl md5
(stdin)= 942c68d45666c4e59fd351f5c24da5ad
```

The fullchain is valid:

```
 0: subject=CN = XXX.XXXX.de
issuer=C = US, O = Let's Encrypt, CN = R3
 1: subject=C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
issuer=C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2: subject=C = US, O = Internet Security Research Group, CN = ISRG Root X1
issuer=C = US, O = Internet Security Research Group, CN = ISRG Root X1
 3: subject=C = US, O = Let's Encrypt, CN = R3
issuer=O = Digital Signature Trust Co., CN = DST Root CA X3
 4: subject=O = Digital Signature Trust Co., CN = DST Root CA X3
issuer=O = Digital Signature Trust Co., CN = DST Root CA X3

XXX.XXXX.de.fullchain.pem: OK

```

The same configuration runs in CentOS 7 without any problems.

So I suppose something goes wrong with the PKIX certificates management library for Erlang. Probably in connection with this openssl version.

What's wrong?

Thanks.
