### ISSUE TITLE
Unable to send message to MUC from admin user

### ISSUE THREAD

**Issue by jnmayur** [processone/ejabberd#3474]
## Environment

- ejabberd version: 20.04
- OS: Linux (Debian)
- Installed from: source 

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      mam: true
      persistent: true
      allow_subscription: true
    db_type: sql

acl:
  admin:
    user: "admin@host"
    ip: "0.0.0.0"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.1/8"
      - "::1"
access:
  configure:
    admin: allow
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: loopback
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
              - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
    what:
      - "status"
      - "register"
      - "connected_users_number"
      - "create_room"
      - "set_room_affiliation"
      - "subscribe_room"
      - "unregister"
      - "send_stanza"
      - "send_message"

...
```

## Errors from error.log/crash.log

No errors

## Bug description

We've a use case, wherein we need to send private messages to users in a room and we're using muc-sub.
However, when we use below API, we're not receiving messages unless we subscribe our admin user to the room. No errors observed on the server. It might be related to #2959

```
http://host:5281/api/send_stanza
{
  "from": "admin@host",
  "to": "room@conference.host/user1",
  "stanza":  "<message type='\''chat'\''><body>Recommendation</body></message>"
}
```
