### ISSUE TITLE
"mod_block_strangers" blocking "invates". Allow "invites" from friends (roster list)

### ISSUE THREAD

**Issue by E-404** [processone/ejabberd#3477]
## Environment
- ejabberd version: 20.07
- "Conversations" 2.9.3

The blocking stranges module successfully copes with protection against flood attacks when thousands of unsolicited messages from strangers come to one account.
But there is bug: mod_block_strangers blocking "invates". Invites from friends (roster list) in group chats. The function of Invites is actively used when creating private member-only conferences. Is it possible to fix this error somehow?

**Comment by weiss** [comment]
The module is most probably blocking [mediated invites][1] (sent from the room JID), not [direct invites][2] (sent from the contact's JID).

[1]: https://xmpp.org/extensions/xep-0045.html#registrar-querytypes-invite
[2]: https://xmpp.org/extensions/xep-0249.html

**Comment by E-404** [comment]
Example of a blocked invite:

```
<a xmlns="urn:xmpp:sm:3" h="969" />

<!-- Incoming Tue 12 Jan 2021 02:44:26 PM UTC -->
<message xmlns="jabber:client" to="recipient+of+the+invite@404.city" from="hubobuxa@chat.404.city">
<archived by="recipient+of+the+invite@404.city@404.city" id="1610462665541389" xmlns="urn:xmpp:mam:tmp" />
<stanza-id by="recipient+of+the+invite@404.city@404.city" id="1610462665541389" xmlns="urn:xmpp:sid:0" />
<x xmlns="http://jabber.org/protocol/muc#user">
<invite from="user+who+sent+the+invite@404.city/Conversations.Aqsp" />
</x>
<x jid="hubobuxa@chat.404.city" xmlns="jabber:x:conference" />
<body xml:lang="en">user+who+sent+the+invite@404.city/Conversations.Aqsp invites you to the room hubobuxa@chat.404.city</body>
</message>
```

**Comment by badlop** [comment]
Ah, I see. With this configuration:

```yaml
modules:
  mod_block_strangers:
    allow_local_users: true
    drop: true
    log: true
```

it is allowed that user2 sends a message to user3, but user2 cannot invite user3 to a room:

```
2021-01-12 16:43:59.673408+01:00 [info]
 Rejecting message from stranger room7@conference.localhost to user3@localhost
```

**Comment by badlop** [comment]
For those cases, the `access` option allows more fine-grained configuration:

```yaml
acl:
  localmuc:
    server: conference.localhost

access_rules:
  localmucrule:
    allow: localmuc
    deny: all

modules:  
  mod_block_strangers:
    access: localmucrule
    allow_local_users: true
    drop: true
    log: true
```
