### ISSUE TITLE
Can't send message to MUC room using "ejabberdctl send_message" or REST API since 20.01

### ISSUE THREAD

**Issue by royrwood** [processone/ejabberd#3485]
## Environment

- ejabberd version: 20.02 or later
- Erlang version: 10.3.4 or later
- OS: Linux Debian
- Installed from: official binary installer

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```
hosts:
  - "ejabberd.roy.org"
loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
certfiles:
  - "/home/rrwood/ejabberd-20.02/conf/server.pem"
ca_file: "/home/rrwood/ejabberd-20.02/conf/cacert.pem"
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000
s2s_use_starttls: optional
oauth_expire: 3600
oauth_access: all
acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "admin@ejabberd.roy.org"
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
shaper:
  normal: 1000
  fast: 50000
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast
max_fsm_queue: 10000
acme:
   contact: "mailto:admin@ejabberd.roy.org"
   ca_url: "https://acme-v01.api.letsencrypt.org"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    assume_mam_usage: true
    default: never
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

```

## Errors from error.log/crash.log

No errors shown in log

## Bug description

Please, give us a precise description (what does not work, what is expected, etc.)

In ejabberd 20.01, it was possible to send messages to a MUC room as admin using ejabberdctl or using the Admin REST API.  That stopped working in 20.02, and continues to not work in the latest 20.12.

The following steps indicate how to test and reproduce this problem.  These steps work as expected in 20.01, but stop working in 20.02 and later.

- Download and install Ejabberd in a VirtualBox VM using official installers: https://www.process-one.net/en/ejabberd/archive/
- My virtual system hostname is "debian.roy.org", and that is used in the following steps
- Edit ejabberd.yml and add "oauth_expire: 3600" and "oauth_access: all" to enable OAUTH support
- Start ejabberd: ejabberdctl start
- Add a user: ejabberdctl register user1 debian.roy.org secret
- List users: ejabberdctl registered_users debian.roy.org
- Create a MUC room: ejabberdctl create_room test_room conference.debian.roy.org debian.roy.org
- List rooms: ejabberdctl muc_online_rooms conference.debian.roy.org
- Install and run profanity XMPP client (or whatever XMPP client you prefer)
- In profanity, connect to ejabberd: /connect user1@debian.roy.org server 127.0.0.1 port 5222 tls trust
- In profanity, joint the MUC room: /join test_room@conference.debian.roy.org
- Send a message to the MUC room: ejabberdctl send_message groupchat admin@debian.roy.org test_room@conference.debian.roy.org "" "Test Message via ejabberdctl"
- In profanity, confirm that the "Test Message via ejabberdctl" was received as a room message (this works for ejabberd 20.01 but fails in 20.02 or later)
- Get OAUTH token: curl -k -d grant_type=password -d username=admin@debian.roy.org -d password=admin -d scope=ejabberd:admin https://localhost:5443/oauth/token
- Send message via REST API: curl -k -H 'Authorization: Bearer YOUR-OAUTH-TOKEN-GOES-HERE' -d '{"type":"groupchat", "from":"admin@debian.roy.org", "to":"test_room@conference.debian.roy.org", "subject": "", "body":"Test Message via REST API"}' https://localhost:5443/api/send_message  
- In profanity, confirm that the "Test Message via REST API" was received as a room message (this works for ejabberd 20.01 but fails in 20.02 or later)
