### ISSUE TITLE
Can't connect to PostgreSQL DB if the schema is not "public"

### ISSUE THREAD

**Issue by messagenius-admin** [processone/ejabberd#3500]
## Environment

- ejabberd version: 20.12
- Erlang version: any
- OS: CentOS 8
- Installed from: source (make rel)

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
sql_type: pgsql
sql_server: "database-1.xxxx.eu-west-1.rds.amazonaws.com"
sql_database: "xxxx"
sql_username: "xxxx"
sql_password: "xxxx"
sql_port: 5434
... <<<---- I can't define my schema name here
```

## Errors from error.log/crash.log

2021-01-25 23:20:48.496685+00:00 [warning] pgsql connection failed

## Bug description

In PostgreSQL you can have multiple schemas in the same DB. There is no way in ejabberd.yml to specify which schema to use
