### ISSUE TITLE
Can't send any invites in private rooms to any user

### ISSUE THREAD

**Issue by centertivevier** [processone/ejabberd#3511]
## Environment

- ejabberd version: 20.12
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.2.4
- OS: Linux (Debian)
- Installed from: Debian Buster-Backports

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
  mod_muc:
    host: "conferenz.@HOST@"
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      allow_subscription: true
      mam: true
      persistent: true
      public: false
      public_list: false

...
```

## Errors from error.log/crash.log

No errors

## Bug description

If any user send a invite (Admin or Owner on the private room) to a other JID there get no invite.
If i direclty used the command:

```ejabberdctl send_direct_invitation channelname conferenz@Host none none JID```

The user get not a invite. Anyone a Idea? On the log i see nothing. The are used random clients. I have tested with Siskin, Conversations and Dino.

With the same config on Ejabberd (20.07-1) there is not this problem.
