### ISSUE TITLE
Can't get PUSH-Notifications to work properly

### ISSUE THREAD

**Issue by lovesuper** [processone/ejabberd#3516]
## Environment

- ejabberd version: 21.1.0 (latest on the date)
- Erlang version:Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 11.1.7
- OS: Linux (Ubuntu 20.04.1 LTS 64-bit)
- Installed from: source 

Installation order:

> ./autogen.sh
> ./configure --enable-user=ejabber --enable-odbc --enable-pgsql --enable-latest-deps
> make
> 
> sudo make install

## Configuration:

```yaml
hosts:
  - "localhost"
  - "im.local.com"
auth_method: [external]
extauth_program: "/home/ejabber/auth.py"
auth_use_cache: false
extauth_pool_size: 4
default_db: sql
sql_type: pgsql
sql_server: "127.0.0.1"
sql_database: "ejabberd"
sql_username: "ejabberd"
sql_password: "ejabberd"
new_sql_schema: true
loglevel: 4
log_rotate_size: 10485760
log_rotate_count: 1
certfiles:
  - "/home/ejabber/ejabberd.pem"
listen:
  - port: 5222
    ip: "0.0.0.0"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
    starttls: true
  - port: 5223
    ip: "::"
    tls: true
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  - port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  - port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      /admin: ejabberd_web_admin
      /api: mod_http_api
      /bosh: mod_bosh
      /captcha: ejabberd_captcha
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
  - port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /.well-known/acme-challenge: ejabberd_acme
  - port: 3478
    ip: "::"
    transport: udp
    module: ejabberd_stun
    use_turn: true
  - port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000
s2s_use_starttls: optional
acl:
  admin:
    user:
      - "6baf5ed1-f5d9-4326-acbc-a8a8ad2e828b": "localhost"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback
  s2s:
    - allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"
shaper:
  normal: 1000
  fast: 50000
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_last: {}
  mod_mam:
    assume_mam_usage: true
    default: always
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pubsub: {}
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
```

## Errors from stdout (ejabberdctl foreground)

> 2021-02-05 19:16:16.420918+03:00 [warning] pubsub.localhost rejected notification for c7bd0ee3-84e8-4c27-85d5-15ab3ee996eb@im.local.com (pushnode), disabling push: bad-request (modify)

## Bug description

I can't get push-notifications mech to work. I had created socket listener on 127.0.0.1:80 (with Python 3.7) and send stanza through Psi+ console:
```
<iq id='x-37' type='set'>
  <enable xmlns='urn:xmpp:push:0' jid='pubsub.localhost' node='pushnode'></enable>
</iq>
```
And get proper:

> 2021-02-05 19:14:13.830691+03:00 [info] Enabling push notifications for c7bd0ee3-84e8-4c27-85d5-15ab3ee996eb@im.local.com/Psi+

But next, when I've sent a message to this contact I get Ejabber error like this:

> 2021-02-05 19:16:16.318971+03:00 [warning] pubsub.localhost rejected notification for 33a56a66-f084-4595-85ca-7192079a7c15@im.local.com (pushnode), disabling push: bad-request (modify)

But my listening echo-script didn't catch anything.

## Questions

- **Where** and **what** port Ejabberd had trying to reach to?
- Where does it documented? 
- What does "rejected notification" mean?

I couldn't find out that in whole Internet. Could someone answer this questions? THANKS FOR ANY HELP!
