### ISSUE TITLE
API returning 404 not found

### ISSUE THREAD

**Issue by arn48** [processone/ejabberd#3518]
## Environment

ejabberd version: 20.01
OS: OS X
Installed from: Docker

## Pulled from :  https://hub.docker.com/r/ejabberd/ecs/ 

> docker run --name ejabberd -d -p 5222:5222 -p 5280:5280 ejabberd/ecs
> docker exec -it ejabberd bin/ejabberdctl register admin localhost passw0rd

## Tried to make api calls http://localhost:5280/api/register

```
{
      "user": "bob",
      "host": "localhost",
      "password": "SomEPass44"
}
```
**I am getting this result  which is 404**

```
<?xml version='1.0'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en' lang='en'>
    <head>
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
    </head>
    <body>
        <h1>404 Not Found</h1>
    </body>
</html>
```

## Bug description

I tried to call the api using different port also but its returning the same 404 result.

**Comment by licaon-kter** [comment]
http**S**, right?

**Comment by arn48** [comment]
@licaon-kter thanks for your quick reply. No I am using http.

http://localhost:5280/api/register

I am able to login to the web-admin but api is responding with 404.

**Comment by licaon-kter** [comment]
Umm?

**Comment by arn48** [comment]
This could be an issue with default ejabberd.yml I am not sure.. but I fixed that problem with custom yml file. So I closed this issue.

Thanks for your concern.

**Comment by licaon-kter** [comment]
@arn48 so what's the fix? Is it secret?

**Comment by arn48** [comment]
Lollzz.. I am not sure with the exact problem, I used the below mentioned yml. Although I used 5443, But to use 5280 for api also you can put '/api': mod_http_api within request handler for that port.

>   - port: 5280
>     ip: '::'
>     module: ejabberd_http
>     request_handlers:
>       '/admin': ejabberd_web_admin
>       '/api': mod_http_api

```
hosts:
  - localhost

loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ''
log_rotate_count: 1
log_rate_limit: 100

listen:
  - port: 5222
    ip: '::'
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  - port: 5269
    ip: '::'
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  - port: 5443
    ip: '::'
    module: ejabberd_http
    request_handlers:
      '/admin': ejabberd_web_admin
      '/api': mod_http_api
      '/bosh': mod_bosh
      '/captcha': ejabberd_captcha
      '/upload': mod_http_upload
      '/ws': ejabberd_http_ws
      '/oauth': ejabberd_oauth
  - port: 5280
    ip: '::'
    module: ejabberd_http
    request_handlers:
      '/admin': ejabberd_web_admin
  - port: 1883
    ip: '::'
    module: mod_mqtt
    backlog: 1000
  - port: 3478
    transport: udp
    module: ejabberd_stun
    use_turn: true
    turn_min_port: 49152
    turn_max_port: 65535
    turn_ip: 0.0.0.0
  - port: 5349
    transport: tcp
    module: ejabberd_stun
    use_turn: true
    tls: true
    turn_min_port: 49152
    turn_max_port: 65535
    ip: 0.0.0.0
    turn_ip: 0.0.0.0

s2s_use_starttls: optional

acl:
  local:
    user_regexp: ''
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - 'admin@localhost'

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

api_permissions:
  'console commands':
    from:
      - ejabberd_ctl
    who: all
    what: '*'
  'admin access':
    who:
      access:
        allow:
          acl: admin
      oauth:
        scope: 'ejabberd:admin'
        access:
          allow:
            acl: admin
    what:
      - '*'
      - '!stop'
      - '!start'
  'public commands':
    who:
      ip: 127.0.0.1/8
    what:
      - '*'
      - connected_users_number
  'web admin':
    who:
      - access:
          - allow:
              - acl: loopback
              - acl: admin
      - oauth:
          - scope: 'sasl_auth'
          - access:
              - allow:
                  - acl: loopback
                  - acl: admin
    what:
      - '*'
      - '!stop'
      - '!start'

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10000
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

max_fsm_queue: 10000

acme:
  contact: 'mailto:example-admin@example.com'
  ca_url: 'https://acme-v01.api.letsencrypt.org'

oauth_expire: 31536000
oauth_access: all

modules:
  mod_stun_disco:
    credentials_lifetime: 12h
    services:
      - host: 0.0.0.0
        port: 3478
        type: stun
        transport: udp
        restricted: false
      - host: 0.0.0.0
        port: 3478
        type: turn
        transport: udp
        restricted: true
      - host: rtcdev.site
        port: 5349
        type: stun
        transport: tcp
        restricted: false
      - host: rtcdev.site
        port: 5349
        type: turn
        transport: tcp
        restricted: true
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    db_type: sql
    assume_mam_usage: true
    default: never
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_sip: {}
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
```
