### ISSUE TITLE
Assigning a web admin to a specific domain without access to the administration of other domains

### ISSUE THREAD

**Issue by brahmann** [processone/ejabberd#3523]
Hi
I was very puzzled to learn that I cannot assign an admin with web administration rights for a specific domain in the host _config option to a specific domain, only full access to all xmpp-domains in web admin.

Is it possible to implement an assignment in the ejabberd.yml configuration file of individual admins to separate domains so that they can see and administer only the domain assigned to them in the web admin panel?

Thanks

**Comment by badlop** [comment]
With this configuration, user127@127.0.0.1 will administer 127.0.0.1, and only that vhost. That admin must use the URL http://127.0.0.1:5280/admin/

And user1@localhost will administer the other vhosts.

```yaml
hosts:
  - localhost
  - "example.net"
  - "example.org"
  - "127.0.0.1"

acl:
  admin:
    user:
      - user1@localhost
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128

host_config:
  "127.0.0.1":
    acl:
      admin:
        user:
          - user127@127.0.0.1
```

**Comment by brahmann** [comment]
Thanks but i tryed like that. After login user see his vhost and entering into this vhost only empty page with headline "Administration" and thats all. Before posting here i tryed check documentation.
This case without setting user into first top acl admin. But if i paste user to those acl too like here you wrote, this use can see all domains and perform admin actions on all ejabberd instance domains :(

**Comment by brahmann** [comment]
Forgot to add:
```
ejabberd ~ # ejabberdctl status  
The node ejabberd@localhost is started with status: started  
ejabberd 20.07 is running in that node  
ejabberd ~ #   
```

**Comment by brahmann** [comment]
Could it be working wrong coz ejabberd live after haproxy?   
And if it is and server only see one IP address of connecting(but how? its http its alltime know for what URL come) from and restrict view? 
Thanks for any answer

**Comment by brahmann** [comment]
HAProxy backend config for ejabberd webadmin:
```
backend xmpp_adm_container
        timeout queue 10s
        balance leastconn
        http-request set-header X-Client-IP %[src]
        server web 192.168.0.6:5280 check maxconn 5
```

**Comment by badlop** [comment]
After thinking, I don't like the previous example. I prefer this example configuration, because it allows:
* user1 can administrate the four vhosts
* user6 can administrate example.net
* tom and jan can administrate example.org and 127.0.0.1
* All those users can use any of the valid addresses, for example http://localhost:5280/admin/ or http://example.org:5280/admin/ or...

```yaml
hosts:
  - localhost
  - example.net
  - example.org
  - 127.0.0.1

acl:
  admin:
    user:
      - user1@localhost
  adminnet:
    user:
      - user6@example.net
  adminorg:
    user:
      - tom@example.org
      - jan@example.org

access_rules:
  configure:
    allow: admin

append_host_config:
  example.net:
    access_rules:
      configure:
        allow: admin
        allow: adminnet
  example.org:
    access_rules:
      configure:
        allow: admin
        allow: adminorg
  127.0.0.1:
    access_rules:
      configure:
        allow: admin
        allow: adminorg
```
