### ISSUE TITLE
c2s_self_presence crashed when running mod_offline

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#3529]
## Environment

- ejabberd version: 21.01.18 (e3fd120fd4c9c5a6ab5a32427f11d5beb87a0fd1) but logs show first one was seen at 20.12.69
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.2.4
- OS: Debian Buster, arm64
- Installed from: source

error.log: https://gist.github.com/licaon-kter/658a05ff370a598018d3aa48df63eab7

**Comment by prefiks** [comment]
Hi,

Could you show me config that your have for mod_offline in ejabberd.yml?

**Comment by licaon-kter** [comment]
```
  mod_offline:
    access_max_user_messages: max_user_offline_messages
    store_groupchat: true
    use_mam_for_storage: true
```
