### ISSUE TITLE
mod_push - empty notification stanza (no sender, no message body)

### ISSUE THREAD

**Issue by lovesuper** [processone/ejabberd#3534]
## Environment

- ejabberd version: 21.1.0 (latest on the date)
- Erlang version:Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 11.1.7
- OS: Linux (Ubuntu 20.04.1 LTS 64-bit)
- Installed from: source 

Installation order:

> ./autogen.sh
> ./configure --enable-user=ejabber --enable-odbc --enable-pgsql --enable-latest-deps
> make
> 
> sudo make install

## Configuration:
I've read mod_push [documentation](https://docs.ejabberd.im/admin/configuration/modules/#mod-push) and setup ejabberd according to that doc. Also I setup push-proxy server and connected it to the ejabberd as external ejabberd_service.
```yaml

...

listen:
  - port: 5347
    module: ejabberd_service
    access: all
    shaper: fast
    ip: "127.0.0.1"
    hosts:
      "push17.local":
        password: "1"

...

modules:

...

  mod_push:
    include_body: true
    include_sender: true
  mod_push_keepalive: {}

...

```

## Bug description

I've used push-server external service for push-proxy purpose. And on client side I have enabled push-notifications with the stanza:
```
<iq type='set' id='x43'>
  <enable xmlns='urn:xmpp:push:0' jid='push17.local' node='2yBDoLbLdOQZ'>
    <x xmlns='jabber:x:data' type='submit'>
      <field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field>
      <field var='secret'><value>tfuJbprlHUPpphs/ef1VSRFJ</value></field>
    </x>
  </enable>
</iq>
```
Push-notifications have enabled properly. And next by the next step my push-proxy receives next stanza:
```
<iq from="im.just.ooo" id="rr-1613733899414-7072623629803774221-CcxtTI9+LZ+EiwiZab8pqFglNEg=-55238004" to="push17.local" type="set">
    <pubsub xmlns="http://jabber.org/protocol/pubsub">
        <publish node="2yBDoLbLdOQZ">
            <item>
                <notification xmlns="urn:xmpp:push:0"></notification>
            </item>
        </publish>
        <publish-options>
            <x xmlns="jabber:x:data" type="submit">
                <field var="FORM_TYPE">
                    <value>http://jabber.org/protocol/pubsub#publish-options</value>
                </field>
                <field var="secret">
                    <value>tfuJbprlHUPpphs/ef1VSRFJ</value>
                </field>
            </x>
        </publish-options>
    </pubsub>
</iq>
```
Pubsub stanza is here but where is notification message body, sender’s JID? I have enabled these features in config.yaml.
