### ISSUE TITLE
Your connection is not private

### ISSUE THREAD

**Issue by algosoftech** [processone/ejabberd#3539]
I want to use https with http-bind

**Comment by badlop** [comment]
```yaml
listen:
  -
    port: 5443
    module: ejabberd_http
    tls: true
    request_handlers:
      /bosh: mod_bosh
```
