### ISSUE TITLE
vCard-Based Avatars - mod_vcard_ldap -> PHOTO:TYPE Missing

### ISSUE THREAD

**Issue by cpuvampier** [processone/ejabberd#3541]
## Environment

- ejabberd version: 21.01
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.4
- OS: Linux (CentOS 8)
- Installed from:  official deb/rpm 

## Configuration 
```yaml
         mod_vcard:
            db_type: ldap
            ldap_base: "ou=users,dc=example,dc=com"
            ldap_uids:
               uid: "%u"
            ldap_filter: "(objectClass=inetOrgPerson)"
            ldap_vcard_map:
               NICKNAME: {"%s": [displayName]} 
               GIVEN: {"%s": [givenName]}
               FAMILY: {"%s": [sn]}
               FN: {"%s, %s": [sn, givenName]} 
               LAST: {"%s": [sn]}
               MIDDLE: {"%s": [initials]}
               ORGNAME: {"%s": [o]}
               ORGUNIT: {"%s": [ou]}
               CTRY: {"%s": [c]}
               LOCALITY: {"%s": [l]}
               STREET: {"%s": [street]}
               REGION: {"%s": [st]}
               PCODE: {"%s": [postalCode]}
               TITLE: {"%s": [title]}
               URL: {"%s": [labeleduri]}
               DESC: {"%s": [description]}
               TEL: {"%s": [telephoneNumber]}
               EMAIL: {"%s": [mail]}
               BDAY: {"%s": [birthDay]}
               ROLE: {"%s": [employeeType]}
               PHOTO: {"%s": [jpegPhoto]}
            ldap_search_fields:
               User: "%u"
               Name: givenName
               "Family Name": sn
               Email: mail
               Birthday: birthDay
            ldap_search_reported:
               "Full Name": FN
               Nickname: NICKNAME
               Birthday: BDAY
```

## Errors from error.log/crash.log

No errors

## Bug description

According to XEP-0153 specs. vCard Photo element should have look like:

`<PHOTO>
      <TYPE>image/jpeg</TYPE>
      <BINVAL>
        ...
      </BINVAL>
</PHOTO>
`

Answer from eJabber is look like:
```xml
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">
  ​<iq xmlns=​"jabber:​client" xml:lang=​"en" to=​"user@example.com/​7a909f97" from=​"user@eample.com" type=​"result" id=​"a81adf51-b4ab-4225-b643-569fa30497f3:​sendIQ">​<vCard xmlns=​"vcard-temp">​
   <PHOTO>
       <BINVAL>...snip...​</BINVAL>
  ​</PHOTO>​
  <N>​…​</N>
  ​<FN>​...​</FN>
  ​<TEL>​…​</TEL>
  ​<EMAIL>​…​</EMAIL>
   ​<URL>​</URL>​
   <BDAY>​</BDAY>​
   <ORG>​…​</ORG>​
   <NICKNAME>​...​</NICKNAME>
   ​<TITLE>​...​</TITLE>​
   <ROLE>​</ROLE>​
   <DESC>​</DESC>​
   <ADR>​…​</ADR>​
</vCard>​</iq>​</body>
```
