### ISSUE TITLE
Can't access running server mnesia data using "ejabberdctl debug", though "ejabberdctl live" works

### ISSUE THREAD

**Issue by royrwood** [processone/ejabberd#3546]
## Environment

- ejabberd version: 20.01
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.4
- OS: Linux (Debian)
- Installed from: official binary installer

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
hosts:
  - "ejabberd.roy.org"
loglevel: info
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
certfiles:
  - "/home/rrwood/ejabberd/conf/server.pem"
ca_file: "/home/rrwood/ejabberd/conf/cacert.pem"
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/oauth": ejabberd_oauth
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000
oauth_expire: 3600
oauth_access: all
s2s_use_starttls: optional
acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "admin@ejabberd.roy.org"
default_db: sql
host_config:
  "ejabberd.roy.org":
    sql_type: pgsql
    sql_server: "localhost"
    sql_database: "ejabberd"
    sql_username: "ejabberd"
    sql_password: "ejabberd"
    acl:
      admin:
        user:
          - "admin@ejabberd.roy.org"
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
shaper:
  normal: 1000
  fast: 50000
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast
max_fsm_queue: 10000
acme:
   contact: "mailto:admin@ejabberd.roy.org"
   ca_url: "https://acme-v01.api.letsencrypt.org"
modules:
  mod_unread: { db_type: sql }
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    assume_mam_usage: true
    default: always
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
  mod_hello_world: {}
```

## Errors from error.log/crash.log

No errors

## Bug description

The documentation says that when I execute `ejabberdctl debug`, I should be connected to the live/running ejabberd server.  Given that, I expect to be able to interact with the `mnesia` data of that server.  It seems, however, that I cannot (example output below-- note the empty table list).

If I execute `ejabberdctl live` to start the server and thus remain connected, I can access the server `mnesia` data (example output below-- note the tables listed).

Is there a way to connect to the running server using `ejabberdctl debug`?  That would be much better than using `ejabberdctl live` and having to leave that shell open.

Sample session using `ejabberdctl debug` to connect to a running instance:

```
rrwood@ejabberd:~$ ejabberdctl debug
--------------------------------------------------------------------

IMPORTANT: we will attempt to attach an INTERACTIVE shell
to an already running ejabberd node.
If an ERROR is printed, it means the connection was not successful.
You can interact with the ejabberd node if you know how to use it.
Please be extremely cautious with your actions,
and exit immediately if you are not completely sure.

To detach this shell from ejabberd, press:
  control+c, control+c

--------------------------------------------------------------------
To bypass permanently this warning, add to ejabberdctl.cfg the line:
  EJABBERD_BYPASS_WARNINGS=true
Press return to continue


Eshell V10.3.4  (abort with ^G)
(76dd4ea8-debug-ejabberd@localhost)1> mnesia:info().
===> System info in version {mnesia_not_loaded,
                                '76dd4ea8-debug-ejabberd@localhost',
                                {1614,978706,397550}}, debug level = none <===
opt_disc. Directory "/home/rrwood/ejabberd-21.01/database/ejabberd@localhost/Mnesia.76dd4ea8-debug-ejabberd@localhost" is NOT used.
use fallback at restart = false
running db nodes   = []
stopped db nodes   = ['76dd4ea8-debug-ejabberd@localhost'] 
ok
(76dd4ea8-debug-ejabberd@localhost)2> mnesia:start().
ok
(76dd4ea8-debug-ejabberd@localhost)3> mnesia:info().
---> Processes holding locks <--- 
---> Processes waiting for locks <--- 
---> Participant transactions <--- 
---> Coordinator transactions <---
---> Uncertain transactions <--- 
---> Active tables <--- 
schema         : with 1        records occupying 417      words of mem
===> System info in version "4.15.6", debug level = none <===
opt_disc. Directory "/home/rrwood/ejabberd-21.01/database/ejabberd@localhost/Mnesia.76dd4ea8-debug-ejabberd@localhost" is NOT used.
use fallback at restart = false
running db nodes   = ['76dd4ea8-debug-ejabberd@localhost']
stopped db nodes   = [] 
master node tables = []
remote             = []
ram_copies         = [schema]
disc_copies        = []
disc_only_copies   = []
[{'76dd4ea8-debug-ejabberd@localhost',ram_copies}] = [schema]
2 transactions committed, 0 aborted, 0 restarted, 0 logged to disc
0 held locks, 0 in queue; 0 local transactions, 0 remote
0 transactions waits for other nodes: []
ok
```

Compare this to using `ejabberdctl live` to start and remain connected:

```
rrwood@ejabberd:~$ ejabberdctl stop

rrwood@ejabberd:~$ ejabberdctl live
--------------------------------------------------------------------

IMPORTANT: ejabberd is going to start in LIVE (interactive) mode.
All log messages will be shown in the command shell.
You can interact with the ejabberd node if you know how to use it.
Please be extremely cautious with your actions,
and exit immediately if you are not completely sure.

To exit this LIVE mode and stop ejabberd, press:
  q().  and press the Enter key

--------------------------------------------------------------------
To bypass permanently this warning, add to ejabberdctl.cfg the line:
  EJABBERD_BYPASS_WARNINGS=true
Press return to continue

...
<ALL KINDS OF STARTUP MESSAGES HERE... I AM OMITTING THEM>
...

(ejabberd@localhost)1> mnesia:info().
---> Processes holding locks <--- 
---> Processes waiting for locks <--- 
---> Participant transactions <--- 
---> Coordinator transactions <---
---> Uncertain transactions <--- 
---> Active tables <--- 
route          : with 5        records occupying 411      words of mem
ejabberd_commands: with 154      records occupying 55416    words of mem
mod_register_ip: with 0        records occupying 300      words of mem
bosh           : with 0        records occupying 300      words of mem
mqtt_session   : with 0        records occupying 300      words of mem
mqtt_sub       : with 0        records occupying 94       words of mem
schema         : with 15       records occupying 2159     words of mem
session        : with 0        records occupying 300      words of mem
pubsub_last_item: with 0        records occupying 300      words of mem
bytestream     : with 0        records occupying 300      words of mem
temporarily_blocked: with 0        records occupying 300      words of mem
s2s            : with 0        records occupying 300      words of mem
session_counter: with 0        records occupying 300      words of mem
muc_online_room: with 0        records occupying 94       words of mem
route_multicast: with 0        records occupying 300      words of mem
===> System info in version "4.15.6", debug level = none <===
opt_disc. Directory "/home/rrwood/ejabberd/database/ejabberd@localhost" is used.
use fallback at restart = false
running db nodes   = [ejabberd@localhost]
stopped db nodes   = [] 
master node tables = []
remote             = []
ram_copies         = [bosh,bytestream,ejabberd_commands,mod_register_ip,
                      mqtt_session,mqtt_sub,muc_online_room,pubsub_last_item,
                      route,route_multicast,s2s,session,session_counter,
                      temporarily_blocked]
disc_copies        = [schema]
disc_only_copies   = []
[{ejabberd@localhost,disc_copies}] = [schema]
[{ejabberd@localhost,ram_copies}] = [route_multicast,muc_online_room,
                                     mod_register_ip,session_counter,s2s,
                                     temporarily_blocked,bosh,bytestream,
                                     pubsub_last_item,session,mqtt_sub,
                                     mqtt_session,ejabberd_commands,route]
9 transactions committed, 6 aborted, 0 restarted, 4 logged to disc
0 held locks, 0 in queue; 0 local transactions, 0 remote
0 transactions waits for other nodes: []
ok
```
