### ISSUE TITLE
Can't connect to Microsoft SQL Server 2017 using original driver libmsodbcsql-17.7.so.2.1

### ISSUE THREAD

**Issue by sergeykorobeynikov** [processone/ejabberd#3559]
## Environment

- ejabberd version: 21.01
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.4
- OS: CentOS Linux release 7.9.2009 (Core)
- Installed from: official binary installer

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
...
default_db: sql

sql_type: mssql
sql_server: 172.28.0.3
sql_database: ejabberd
sql_username: ejabberd@microfund1sql1
sql_password: XXX_XXX_XXX
sql_odbc_driver: "/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.7.so.2.1"

loglevel: 4
...
```

## Errors from error.log/crash.log

```
2021-03-25 21:41:57 =ERROR REPORT====
** Generic server <0.531.0> terminating 
** Last message in was {<0.463.0>,{connect,[1,1,2,2,2,1,1,
  "DRIVER=ODBC;SERVER=172.28.0.3;UID=ejabberd@microfund1sql1;
  DATABASE=ejabberd;PWD=XXX_XXX_XXX;PORT=1433;CLIENT_CHARSET=UTF-8;"],on,off},
  5000}
** When Server state == {state,#Port<0.109>,
  {<0.463.0>,#Ref<0.2084870333.111673348.43387>},<0.463.0>,undefined,on,
  undefined,undefined,off,connecting,undefined,0,[#Port<0.107>,#Port<0.108>],
  undefined,undefined}
** Reason for termination == 
** timeout
** Client 'ejabberd_sql_microfund.ru_10' stacktrace
** [{p1_fsm,message_queue_len,2,[{file,"src/p1_fsm.erl"},{line,877}]},
    {p1_fsm,loop,10,[{file,"src/p1_fsm.erl"},{line,427}]},
    {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
2021-03-25 21:41:57 =CRASH REPORT====
  crasher:
    initial call: odbc:init/1
    pid: <0.531.0>
    registered_name: []
    exception exit: {timeout,[{gen_server,handle_msg,6,
        [{file,"gen_server.erl"},{line,704}]},
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [odbc_sup,<0.451.0>]
    message_queue_len: 2
    messages: [{#Port<0.109>,{exit_status,127}},{'EXIT',#Port<0.109>,normal}]
    links: [#Port<0.107>,#Port<0.108>,<0.452.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 2733
  neighbours:
2021-03-25 21:41:57 =SUPERVISOR REPORT====
     Supervisor: {local,odbc_sup}
     Context:    child_terminated
     Reason:     timeout
     Offender:   [{pid,<0.531.0>},{id,[]},{mfargs,{odbc,start_link_sup,undefined}},
       {restart_type,temporary},{shutdown,7000},{child_type,worker}]
```

## Bug description

Connection cannot be established using the original driver. Moreover, by monitoring "tcpdump -ieth0 -n -nn -vvv port 1433" it has been established that there are no attempts to establish a connection. The driver file /opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.7.so.2.1 exists.

**Comment by badlop** [comment]
I'm using the mssql docker image like this:

File docker-compose.yml
```yaml
version: '3.7'

  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    volumes:
      - ../../ejabberd/test/docker/db/mssql/initdb/initdb_mssql.sql:/initdb_mssql.sql:ro
      - ../../ejabberd/sql/mssql.sql:/mssql.sql:ro
    restart: always
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ejabberd_Test1
```


Create container, start it, create the database and tables:

```
docker-compose up
docker exec -it mssql /opt/mssql-tools/bin/sqlcmd -U sa -P ejabberd_Test1 -S localhost -i /initdb_mssql.sql
docker exec -it mssql /opt/mssql-tools/bin/sqlcmd -U ejabberd_test -P ejabberd_Test1 -S localhost -d ejabberd_test -i /mssql.sql
```

I've checked that it has the same file:

```shell
docker exec -it mssql ls -la /opt/microsoft/msodbcsql17/lib64
total 2024
drwxr-xr-x 2 root root    4096 Apr  3 03:26 .
drwxr-xr-x 6 root root    4096 Apr  3 03:26 ..
-rwxr-xr-x 1 root root 2063728 Mar  4 19:23 libmsodbcsql-17.7.so.2.1
```

Then configure ejabberd like this:

```yaml
hosts:
  - localhost
  - mssql.localhost

host_config:
  mssql.localhost:
    sql_port: 1433
    sql_type: mssql
    sql_server: "mssql"
    sql_database: "ejabberd_test"
    sql_username: "ejabberd_test"
    sql_password: "ejabberd_Test1"
    sql_pool_size: 1
    auth_method: sql
    default_db: sql
```

Then ejabberd starts correctly, and I can create an account in that mssql.localhost
