### ISSUE TITLE
Old jabber client Bombus can't get roster

### ISSUE THREAD

**Issue by aleksmisha** [processone/ejabberd#3585]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 21.04
- Erlang version: unknown
- OS: Linux (CentOS 7)
- Installed from: official binary installer

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 3
#mod_share_roster:{}
mod_roster: versioning:true store_local_id:true
...
```

## Errors from error.log/crash.log

No errors

## Bug description

Please, give us a precise description (what does not work, what is expected, etc.)
Jabber client bombus, if there is at least 1 contact, hangs at the step "getting a roster" with the server Ijabberd 21.04. With other servers, this was not noticed.

**Comment by licaon-kter** [comment]
Server logs? Client logs?

**Comment by badlop** [comment]
> With other servers, this was not noticed.

Do you mean previous ejabberd versions worked with Bombus? What versions?

> Old jabber client Bombus

Is there some way to install that client?

**Comment by licaon-kter** [comment]
Bombumod got some updates this month, in F-Droid already.

**Comment by badlop** [comment]
I've installed BombusMod 0.9.1420, ejabberd 21.07 and configured like this:

```yaml
listen:
  -
    port: 5222
    module: ejabberd_c2s
    shaper: c2s_shaper
    access: c2s
    starttls: false

modules:
  ...
  mod_roster:
    versioning: true
    store_current_id: true
```

Then registered two accounts, added them as contacts. BombusMod can login correctly, get the roster, see the contact status and chat.
