### ISSUE TITLE
mod_shared_roster_ldap not work when group member CN have space.

### ISSUE THREAD

**Issue by ryba84** [processone/ejabberd#3614]
Hello.

My users have CN with space (name and surname). When i create user that have CN without space it works correctly.
Same problem here #2795.

Linux Debian 10.
ejabberd version: 21.01

>   mod_shared_roster_ldap:
>     ldap_base: "CN=Users,DC=some,DC=domain,DC=com"
>     ldap_filter: "(objectClass=*)"
>     ldap_rfilter: "(&(objectClass=group)(cn=someGroup))"
>     ldap_gfilter: "(&(objectClass=group)(cn=%g))"
>     ldap_memberattr: "member"
>     ldap_memberattr_format: "CN=%u,CN=Users,DC=some,DC=domain,DC=com"
>     ldap_ufilter: "(&(objectClass=person)(cn=%u))"
>     ldap_userdesc: "displayName"

**Comment by licaon-kter** [comment]
There were same changes regarding shared and LDAP. Can you test with 21.04 too?0

**Comment by ryba84** [comment]
The same behavior with 21.04. List empty when space in CN.

Debug log when only users with space:
2021-05-24 16:00:36.693 [debug] <0.368.0>@ejabberd_access_permissions:handle_call:108 Command 'get_roster' execution allowed by rule 'console commands' (CallerInfo=#{caller_module => ejabberd_ctl})
2021-05-24 16:00:36.693 [debug] <0.582.0>@ejabberd_commands:do_execute_command:250 Executing command mod_admin_extra:get_roster with Args=[<<"myUser1">>,<<"my.test.domain.com">>]
2021-05-24 16:00:36.693 [debug] <0.582.0>@ejabberd_hooks:safe_apply:231 Running hook roster_get: mod_roster:get_user_roster/2
2021-05-24 16:00:36.694 [debug] <0.582.0>@ejabberd_hooks:safe_apply:231 Running hook roster_get: mod_shared_roster_ldap:get_user_roster/2
2021-05-24 16:00:36.695 [debug] <0.477.0>@eldap:send_command:776 {searchRequest,{'SearchRequest',<<"CN=Users,DC=my,DC=test,DC=domain,DC=com">>,wholeSubtree,neverDerefAliases,0,5,false,{and,[{equalityMatch,{'AttributeValueAssertion',<<"objectClass">>,<<"group">>}},{equalityMatch,{'AttributeValueAssertion',<<"cn">>,<<"biuro">>}}]},[<<"cn">>]}}
2021-05-24 16:00:36.697 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResEntry,{'SearchResultEntry',<<"CN=someGroup,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,[{'PartialAttributeList_SEQOF',<<"cn">>,[<<"someGroup">>]}]}}
2021-05-24 16:00:36.698 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResDone,{'LDAPResult',success,<<>>,<<>>,asn1_NOVALUE}}
2021-05-24 16:00:36.698 [debug] <0.477.0>@eldap:send_command:776 {searchRequest,{'SearchRequest',<<"CN=Users,DC=my,DC=test,DC=domain,DC=com">>,wholeSubtree,neverDerefAliases,0,5,false,{and,[{and,[{equalityMatch,{'AttributeValueAssertion',<<"objectClass">>,<<"group">>}},{equalityMatch,{'AttributeValueAssertion',<<"cn">>,<<"someGroup">>}}]},{present,<<"objectClass">>}]},[<<"cn">>,<<"cn">>,<<"member">>]}}
2021-05-24 16:00:36.699 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResEntry,{'SearchResultEntry',<<"CN=someGroup,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,[{'PartialAttributeList_SEQOF',<<"cn">>,[<<"someGroup">>]},{'PartialAttributeList_SEQOF',<<"member">>,[<<"CN=My User,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,<<"CN=Next User,CN=Users,DC=my,DC=test,DC=domain,DC=com">>]}]}}
2021-05-24 16:00:36.699 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResDone,{'LDAPResult',success,<<>>,<<>>,asn1_NOVALUE}}

Debug log with additional users without space:
2021-05-24 16:03:15.934 [debug] <0.368.0>@ejabberd_access_permissions:handle_call:108 Command 'get_roster' execution allowed by rule 'console commands' (CallerInfo=#{caller_module => ejabberd_ctl})
2021-05-24 16:03:15.934 [debug] <0.582.0>@ejabberd_commands:do_execute_command:250 Executing command mod_admin_extra:get_roster with Args=[<<"myUser1">>,<<"my.test.domain.domain">>]
2021-05-24 16:03:15.934 [debug] <0.582.0>@ejabberd_hooks:safe_apply:231 Running hook roster_get: mod_roster:get_user_roster/2
2021-05-24 16:03:15.935 [debug] <0.582.0>@ejabberd_hooks:safe_apply:231 Running hook roster_get: mod_shared_roster_ldap:get_user_roster/2
2021-05-24 16:03:15.936 [debug] <0.477.0>@eldap:send_command:776 {searchRequest,{'SearchRequest',<<"CN=Users,DC=my,DC=test,DC=domain,DC=com">>,wholeSubtree,neverDerefAliases,0,5,false,{and,[{equalityMatch,{'AttributeValueAssertion',<<"objectClass">>,<<"group">>}},{equalityMatch,{'AttributeValueAssertion',<<"cn">>,<<"someGroup">>}}]},[<<"cn">>]}}
2021-05-24 16:03:15.938 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResEntry,{'SearchResultEntry',<<"CN=someGroup,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,[{'PartialAttributeList_SEQOF',<<"cn">>,[<<"someGroup">>]}]}}
2021-05-24 16:03:15.938 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResDone,{'LDAPResult',success,<<>>,<<>>,asn1_NOVALUE}}
2021-05-24 16:03:15.938 [debug] <0.477.0>@eldap:send_command:776 {searchRequest,{'SearchRequest',<<"CN=Users,DC=my,DC=test,DC=domain,DC=com">>,wholeSubtree,neverDerefAliases,0,5,false,{and,[{and,[{equalityMatch,{'AttributeValueAssertion',<<"objectClass">>,<<"group">>}},{equalityMatch,{'AttributeValueAssertion',<<"cn">>,<<"someGroup">>}}]},{present,<<"objectClass">>}]},[<<"cn">>,<<"cn">>,<<"member">>]}}
2021-05-24 16:03:15.940 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResEntry,{'SearchResultEntry',<<"CN=someGroup,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,[{'PartialAttributeList_SEQOF',<<"cn">>,[<<"someGroup">>]},{'PartialAttributeList_SEQOF',<<"member">>,[<<"CN=My User,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,<<"CN=test,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,<<"CN=test2,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,<<"CN=Next User,CN=Users,DC=my,DC=test,DC=domain,DC=com">>]}]}}
2021-05-24 16:03:15.940 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResDone,{'LDAPResult',success,<<>>,<<>>,asn1_NOVALUE}}
2021-05-24 16:03:15.941 [debug] <0.515.0>@eldap:send_command:776 {searchRequest,{'SearchRequest',<<"DC=my,DC=test,DC=domain,DC=com">>,wholeSubtree,neverDerefAliases,0,0,false,{and,[{equalityMatch,{'AttributeValueAssertion',<<"sAMAccountName">>,<<"test">>}},{or,[{and,[{equalityMatch,{'AttributeValueAssertion',<<"objectclass">>,<<"person">>}},{equalityMatch,{'AttributeValueAssertion',<<"memberof">>,<<"CN=someGroup,CN=Users,DC=my,DC=test,DC=domain,DC=com">>}}]},{equalityMatch,{'AttributeValueAssertion',<<"distinguishedName">>,<<"CN=Administrator,CN=Users,DC=my,DC=test,DC=domain,DC=com">>}}]}]},[<<"sAMAccountName">>]}}
2021-05-24 16:03:15.942 [debug] <0.515.0>@eldap:recvd_packet:836 {searchResEntry,{'SearchResultEntry',<<"CN=test,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,[{'PartialAttributeList_SEQOF',<<"sAMAccountName">>,[<<"test">>]}]}}
2021-05-24 16:03:15.942 [debug] <0.515.0>@eldap:recvd_packet:836 {searchResRef,[<<"ldap://my.test.domain.domain/CN=Configuration,DC=my,DC=test,DC=domain,DC=com">>]}
2021-05-24 16:03:15.942 [debug] <0.515.0>@eldap:recvd_packet:836 {searchResRef,[<<"ldap://my.test.domain.domain/DC=DomainDnsZones,DC=my,DC=test,DC=domain,DC=com">>]}
2021-05-24 16:03:15.942 [debug] <0.515.0>@eldap:recvd_packet:836 {searchResRef,[<<"ldap://my.test.domain.domain/DC=ForestDnsZones,DC=my,DC=test,DC=domain,DC=com">>]}
2021-05-24 16:03:15.942 [debug] <0.515.0>@eldap:recvd_packet:836 {searchResDone,{'LDAPResult',success,<<>>,<<>>,asn1_NOVALUE}}
2021-05-24 16:03:15.943 [debug] <0.515.0>@eldap:send_command:776 {searchRequest,{'SearchRequest',<<"DC=my,DC=test,DC=domain,DC=com">>,wholeSubtree,neverDerefAliases,0,0,false,{and,[{equalityMatch,{'AttributeValueAssertion',<<"sAMAccountName">>,<<"test2">>}},{or,[{and,[{equalityMatch,{'AttributeValueAssertion',<<"objectclass">>,<<"person">>}},{equalityMatch,{'AttributeValueAssertion',<<"memberof">>,<<"CN=someGroup,CN=Users,DC=my,DC=test,DC=domain,DC=com">>}}]},{equalityMatch,{'AttributeValueAssertion',<<"distinguishedName">>,<<"CN=Administrator,CN=Users,DC=my,DC=test,DC=domain,DC=com">>}}]}]},[<<"sAMAccountName">>]}}
2021-05-24 16:03:15.944 [debug] <0.515.0>@eldap:recvd_packet:836 {searchResEntry,{'SearchResultEntry',<<"CN=test2,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,[{'PartialAttributeList_SEQOF',<<"sAMAccountName">>,[<<"test2">>]}]}}
2021-05-24 16:03:15.944 [debug] <0.515.0>@eldap:recvd_packet:836 {searchResRef,[<<"ldap://my.test.domain.domain/CN=Configuration,DC=my,DC=test,DC=domain,DC=com">>]}
2021-05-24 16:03:15.945 [debug] <0.515.0>@eldap:recvd_packet:836 {searchResRef,[<<"ldap://my.test.domain.domain/DC=DomainDnsZones,DC=my,DC=test,DC=domain,DC=com">>]}
2021-05-24 16:03:15.945 [debug] <0.515.0>@eldap:recvd_packet:836 {searchResRef,[<<"ldap://my.test.domain.domain/DC=ForestDnsZones,DC=my,DC=test,DC=domain,DC=com">>]}
2021-05-24 16:03:15.945 [debug] <0.515.0>@eldap:recvd_packet:836 {searchResDone,{'LDAPResult',success,<<>>,<<>>,asn1_NOVALUE}}
2021-05-24 16:03:15.945 [debug] <0.477.0>@eldap:send_command:776 {searchRequest,{'SearchRequest',<<"CN=Users,DC=my,DC=test,DC=domain,DC=com">>,wholeSubtree,neverDerefAliases,0,5,false,{and,[{and,[{equalityMatch,{'AttributeValueAssertion',<<"objectClass">>,<<"person">>}},{equalityMatch,{'AttributeValueAssertion',<<"cn">>,<<"test">>}}]},{present,<<"objectClass">>}]},[<<"displayName">>,<<"cn">>]}}
2021-05-24 16:03:15.946 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResEntry,{'SearchResultEntry',<<"CN=test,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,[{'PartialAttributeList_SEQOF',<<"cn">>,[<<"test">>]},{'PartialAttributeList_SEQOF',<<"displayName">>,[<<"test">>]}]}}
2021-05-24 16:03:15.946 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResDone,{'LDAPResult',success,<<>>,<<>>,asn1_NOVALUE}}
2021-05-24 16:03:15.947 [debug] <0.477.0>@eldap:send_command:776 {searchRequest,{'SearchRequest',<<"CN=Users,DC=my,DC=test,DC=domain,DC=com">>,wholeSubtree,neverDerefAliases,0,5,false,{and,[{and,[{equalityMatch,{'AttributeValueAssertion',<<"objectClass">>,<<"person">>}},{equalityMatch,{'AttributeValueAssertion',<<"cn">>,<<"test2">>}}]},{present,<<"objectClass">>}]},[<<"displayName">>,<<"cn">>]}}
2021-05-24 16:03:15.948 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResEntry,{'SearchResultEntry',<<"CN=test2,CN=Users,DC=my,DC=test,DC=domain,DC=com">>,[{'PartialAttributeList_SEQOF',<<"cn">>,[<<"test2">>]},{'PartialAttributeList_SEQOF',<<"displayName">>,[<<"test2">>]}]}}
2021-05-24 16:03:15.948 [debug] <0.477.0>@eldap:recvd_packet:836 {searchResDone,{'LDAPResult',success,<<>>,<<>>,asn1_NOVALUE}}

Additional users are showing in the list.

**Comment by prefiks** [comment]
This probably fails when we try to use that value to generate jid - spaces simply aren't allowed in node part of jid so we get error when we try to create jid for that user - and that make us skip that user.

**Comment by ryba84** [comment]
Problem is within ejabberd. It should search group members by distinguishedName, and return sAMAccountName as useruid.

Workaround to this problem: rename user CN to match user sAMAccountName and use this configuration:
>mod_shared_roster_ldap:
>ldap_base: "CN=Users,DC=some,DC=domain,DC=com"
>ldap_filter: "(objectClass=*)"
>ldap_rfilter: "(&(objectClass=group)(cn=someGroup))"
>ldap_gfilter: "(&(objectClass=group)(cn=%g))"
>ldap_memberattr: "member"
>ldap_memberattr_format: "CN=%u,CN=Users,DC=some,DC=domain,DC=com"
>ldap_ufilter: "(&(objectClass=person)(cn=%u))"
>ldap_useruid: "sAMAccountName"
>ldap_userdesc: "displayName"

This is not a problem when You have small user count.

Active directory server returns members as list of distinguishedName's:
> CN=Name1 Surname1,CN=Users,DC=some,DC=domain,DC=com
> CN=Name2 Surname2,CN=Users,DC=some,DC=domain,DC=com
> CN=Name3 Surname3,CN=Users,DC=some,DC=domain,DC=com

For now I've no more ideas.

**Comment by prefiks** [comment]
If you have something that seems to be compatible with jabber id (aka. no spaces, '@') in your ldap, then you could try using ldap_userjidatrr option, i think this tries to lookup atrribute specified in that option associated with valued from ldap_useruid, possibly you could mange to make it work with your storage. I can't rather help you with defining that, ldap syntax is just black magic for me.

**Comment by ryba84** [comment]
@prefiks bulls eye! Active Directory have attribute like that. It's userPrincipalName.
Now it's working as expected. Config:
>mod_shared_roster_ldap:
>  ldap_base: "DC=some,DC=domain,DC=com"
>  ldap_filter: "(|(objectClass=group)(objectClass=user))"
>  ldap_rfilter: "(&(objectClass=group)(cn=someGroup))"
>  ldap_gfilter: "(&(objectClass=group)(distinguishedName=%g))"
>  ldap_groupattr: "distinguishedName"
>  ldap_groupdesc: "cn"
>  ldap_memberattr: "member"
>  ldap_ufilter: "(&(objectClass=person)(distinguishedName=%u))"
>  ldap_useruid: "distinguishedName"
>  ldap_userjidattr: "userPrincipalName"
>  ldap_userdesc: "displayName"

**Comment by necarnot** [comment]
> @prefiks bulls eye! Active Directory have attribute like that. It's userPrincipalName. Now it's working as expected. Config:
> 
> > mod_shared_roster_ldap:
> > ldap_base: "DC=some,DC=domain,DC=com"
> > ldap_filter: "(|(objectClass=group)(objectClass=user))"
> > ldap_rfilter: "(&(objectClass=group)(cn=someGroup))"
> > ldap_gfilter: "(&(objectClass=group)(distinguishedName=%g))"
> > ldap_groupattr: "distinguishedName"
> > ldap_groupdesc: "cn"
> > ldap_memberattr: "member"
> > ldap_ufilter: "(&(objectClass=person)(distinguishedName=%u))"
> > ldap_useruid: "distinguishedName"
> > ldap_userjidattr: "userPrincipalName"
> > ldap_userdesc: "displayName"

Hello,

May we ask you to post your complete (anonymized) ejabberd.yml file please?
I still cannot make the roster list appear showing nice "FirstName LastName" entries. Only JIDs...

**Comment by Neustradamus** [comment]
@ryba84: Have you seen the @necarnot comment?

**Comment by ryba84** [comment]
Here You have all config with ldap and vcard:

```
## set ldap as default method
auth_method: ldap
auth_use_cache: true
auth_cache_size: 1000
auth_cache_missed: true
auth_cache_life_time: 3600
ldap_servers:
  - ldap.example.com
ldap_encrypt: tls
ldap_tls_cacertfile: /path/to/ca_file
ldap_tls_depth: 2
ldap_tls_verify: hard
ldap_port: 636
ldap_base: "dc=example,dc=com"
ldap_rootdn: "cn=some_user,ou=some_ou,dc=example,dc=com"
ldap_password: 'some_user_password'
ldap_uids:
  "sAMAccountName": "%u"
## allow access for users from some_jabber_group. memberOf is distinguishedName of this group
ldap_filter: "(&(objectClass=person)(memberOf=cn=some_jabber_group,cn=users,dc=example,dc=com))"

modules:
  mod_roster:
    access:
      allow:
        acl: local
    store_current_id: false
    versioning: true
  mod_shared_roster_ldap:
    ldap_userdesc: "displayName"
    ldap_useruid: "distinguishedName"
    ldap_userjidattr: "userPrincipalName"
    ldap_groupdesc: "cn"
    ldap_groupattr: "distinguishedName"
    ldap_memberattr: "member"
    ldap_base: "dc=example,dc=com"
    ldap_filter: "(|(objectClass=group)(objectClass=user))"
    ## in rfilter you can specify which groups You want in roaster
    ldap_rfilter: "(&(objectClass=group)(|(cn=some_group)(cn=next_group)))"
    ldap_gfilter: "(&(objectClass=group)(distinguishedName=%g))"
    ldap_ufilter: "(&(objectClass=person)(distinguishedName=%u))"
    ldap_auth_check: true
    use_cache: true
    cache_life_time: 3600
  mod_vcard:
    db_type: ldap
    allow_return_all: true
    matches: infinity
    search: true
    ldap_vcard_map:
      FN: {"%s": [displayName]}
      FIRST: {"%s": [givenName]}
      MIDDLE: {"%s": [initials]}
      LAST: {"%s": [sn]}
      NICKNAME: {"%u": []}
      ORGNAME: {"%s": [company]}
      ORGUNIT: {"%s": [ou]}
      CTRY: {"%s": [c]}
      LOCALITY: {"%s": [l]}
      STREET: {"%s": [street]}
      REGION: {"%s": [st]}
      PCODE: {"%s": [postalCode]}
      TITLE: {"%s": [title]}
      URL: {"%s": [labeleduri]}
      DESC: {"%s": [description]}
      EMAIL: {"%s": [mail]}
      TEL: {"%s": [telephoneNumber]}
      BDAY: {"%s": [birthDay]}
      ROLE: {"%s": [employeeType]}
      PHOTO: {"%s": [jpegPhoto]}
    ldap_search_fields:
      "Full Name": displayName
      Name: givenName
      "Family Name": sn
      Nickname: "%u"
      Email: mail
      Phone: telephoneNumber
    ldap_search_reported:
      "Full Name": FN
      "Given Name": FIRST
      "Middle Name": MIDDLE
      "Family Name": LAST
      "Nickname": NICKNAME
      "Birthday": BDAY
      "Country": CTRY
      "City": LOCALITY
      "Email": EMAIL
      "Organization Name": ORGNAME
      "Organization Unit": ORGUNIT
  mod_vcard_xupdate:
    use_cache: true
```
But in roster groups defined in rfilter You cannot have computer accounts as a member because mod_shared_roster_ldap will crash:
```
2023-05-20 16:54:49.996755+02:00 [error] <0.718.0>@ejabberd_hooks:safe_apply/4:324 Hook roster_get crashed when running mod_shared_roster_ldap:get_user_roster/2:
** exception error: no case clause matching
                 [{eldap_entry,<<"CN=SOME_COMPUTER,CN=Computers,DC=example,DC=com">>,
                                []}]
   in function  mod_shared_roster_ldap:get_member_jid/3 (mod_shared_roster_ldap.erl, line 397)
   in call from mod_shared_roster_ldap:'-extract_members/5-fun-0-'/5 (mod_shared_roster_ldap.erl, line 417)
   in call from lists:foldl/3 (lists.erl, line 1267)
   in call from mod_shared_roster_ldap:extract_members/5 (mod_shared_roster_ldap.erl, line 415)
   in call from lists:foldl/3 (lists.erl, line 1267)
   in call from mod_shared_roster_ldap:search_group_info/2 (mod_shared_roster_ldap.erl, line 382)
   in call from ets_cache:lookup/3 (ets_cache.erl, line 206)
   in call from mod_shared_roster_ldap:get_group_name/2 (mod_shared_roster_ldap.erl, line 336)
** Arg 1 = [{roster_item,{jid,<<"administrator">>,<<"example.com">>,
                              <<>>,<<"administrator">>,
                              <<"example.com">>,<<>>},
                         <<>>,[],none,subscribe,undefined},
            {roster_item,{jid,<<....
                            ........,[],none,subscribe,undefined}]
** Arg 2 = {<<"some_user">>,<<"example.com">>}
```
