### ISSUE TITLE
Requesting OAuth token is failing

### ISSUE THREAD

**Issue by karimhm** [processone/ejabberd#3655]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: `21.04`
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.5`
- OS: `Alpine Linux (GKE Kubernetes)`
- Installed from: `Docker hub official image`

## Configuration

```yaml
hosts:
  - "staging-***.*******.io"
  - "staging.*******.com"

loglevel: debug
log_rotate_size: 10485760
log_rotate_count: 1
certfiles:
  - "/home/ejabberd/conf/server.pem"
ca_file: /home/ejabberd/conf/cacert.pem
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
    starttls: false
    tls: false
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: false
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5080
    ip: "::"
    module: ejabberd_http
    tls: false
    request_handlers:
      "/.well-known/acme-challenge": ejabberd_acme
s2s_use_starttls: false
acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "admin@staging.*******.com"
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: admin
  pubsub_createnode:
    allow: admin
  trusted_network:
    allow: loopback
  jwt_non_admin_only:
    deny: admin
    allow: all
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
  "api access":
    from:
      - ejabberd_ctl
      - mod_http_api
    who:
      acl: admin
    what: "*"
commands_admin_access: configure
commands:
  - add_commands:
    - user
oauth_expire: 3600
oauth_access: all
shaper:
  normal: 1000
  fast: 50000
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    100000: admin
    100000: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast
max_fsm_queue: 10000
acme:
  contact:
    - "mailto:******@*****.com"
    - "mailto:******@*****.com"
  auto: false
  cert_type: rsa
  ca_url: https://acme-staging-v02.api.letsencrypt.org/directory
sql_type: mysql
sql_server: ***************
sql_database: ejabberd_21_04
sql_username: ejabberd
sql_password: *************************************
new_sql_schema: true
default_db: sql
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    assume_mam_usage: true
    default: always
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true
      public: false
      public_list: false
      anonymous: false
      mam: true
      persistent: true
    history_size: 10000
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push:
    include_body: true
    include_sender: true
  mod_push_keepalive: {}
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
    ack_timeout: 36000000
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
```

## Errors from error.log/crash.log

```
2021-07-30 11:38:54.460481+00:00 [debug] [<<"oauth">>,<<"authorization_token">>] matches [<<"oauth">>]
2021-07-30 11:38:54.461323+00:00 [debug] Option 'oauth_access' is not defined for virtual host 'staging.*******.com'. This is a bug, please report it with the following stacktrace included:
** exception error: bad argument
   in function  ets:lookup_element/3
      called as ets:lookup_element(ejabberd_options,
                                   {oauth_access,<<"staging.*******.com">>},
                                   2)
   in call from ejabberd_config:get_option/1 (src/ejabberd_config.erl, line 162)
   in call from ejabberd_oauth:authenticate_user/2 (src/ejabberd_oauth.erl, line 261)
   in call from oauth2:auth_user/3 (/ejabberd/deps/p1_oauth2/src/oauth2.erl, line 351)
   in call from oauth2:authorize_password/5 (/ejabberd/deps/p1_oauth2/src/oauth2.erl, line 123)
   in call from ejabberd_oauth:process/2 (src/ejabberd_oauth.erl, line 572)
   in call from ejabberd_http:process/2 (src/ejabberd_http.erl, line 373)
   in call from ejabberd_http:process_request/1 (src/ejabberd_http.erl, line 496)
2021-07-30 11:38:54.462158+00:00 [debug] Option 'auth_method' is not defined for virtual host 'staging.*******.com'. This is a bug, please report it with the following stacktrace included:
** exception error: bad argument
   in function  ets:lookup_element/3
      called as ets:lookup_element(ejabberd_options,
                                   {auth_method,<<"staging.*******.com">>},
                                   2)
   in call from ejabberd_config:get_option/1 (src/ejabberd_config.erl, line 162)
   in call from ejabberd_auth:auth_modules/1 (src/ejabberd_auth.erl, line 857)
   in call from ejabberd_auth:check_password_with_authmodule/6 (src/ejabberd_auth.erl, line 258)
   in call from ejabberd_auth:check_password/6 (src/ejabberd_auth.erl, line 223)
   in call from ejabberd_oauth:authenticate_user/2 (src/ejabberd_oauth.erl, line 269)
   in call from oauth2:auth_user/3 (/ejabberd/deps/p1_oauth2/src/oauth2.erl, line 351)
   in call from oauth2:authorize_password/5 (/ejabberd/deps/p1_oauth2/src/oauth2.erl, line 123)
2021-07-30 11:38:54.463114+00:00 [debug] Option 'auth_use_cache' is not defined for virtual host 'staging.*******.com'. This is a bug, please report it with the following stacktrace included:
** exception error: bad argument
   in function  ets:lookup_element/3
      called as ets:lookup_element(ejabberd_options,
                                   {auth_use_cache,
                                       <<"staging.*******.com">>},
                                   2)
   in call from ejabberd_config:get_option/1 (src/ejabberd_config.erl, line 162)
   in call from ejabberd_auth:db_get_password/3 (src/ejabberd_auth.erl, line 608)
   in call from ejabberd_auth:db_check_password/7 (src/ejabberd_auth.erl, line 667)
   in call from ejabberd_auth:'-check_password_with_authmodule/6-fun-0-'/8 (src/ejabberd_auth.erl, line 248)
   in call from lists:foldl/3 (lists.erl, line 1263)
   in call from ejabberd_auth:check_password_with_authmodule/6 (src/ejabberd_auth.erl, line 246)
   in call from ejabberd_auth:check_password/6 (src/ejabberd_auth.erl, line 223)
2021-07-30 11:38:54.464086+00:00 [debug] Option 'auth_password_format' is not defined for virtual host 'staging.*******.com'. This is a bug, please report it with the following stacktrace included:
** exception error: bad argument
   in function  ets:lookup_element/3
      called as ets:lookup_element(ejabberd_options,
                                   {auth_password_format,
                                       <<"staging.*******.com">>},
                                   2)
   in call from ejabberd_config:get_option/1 (src/ejabberd_config.erl, line 162)
   in call from ejabberd_auth:db_check_password/7 (src/ejabberd_auth.erl, line 671)
   in call from ejabberd_auth:'-check_password_with_authmodule/6-fun-0-'/8 (src/ejabberd_auth.erl, line 248)
   in call from lists:foldl/3 (lists.erl, line 1263)
   in call from ejabberd_auth:check_password_with_authmodule/6 (src/ejabberd_auth.erl, line 246)
   in call from ejabberd_auth:check_password/6 (src/ejabberd_auth.erl, line 223)
   in call from ejabberd_oauth:authenticate_user/2 (src/ejabberd_oauth.erl, line 269)
2021-07-30 11:38:54.465032+00:00 [debug] Option 'auth_use_cache' is not defined for virtual host 'staging.*******.com'. This is a bug, please report it with the following stacktrace included:
** exception error: bad argument
   in function  ets:lookup_element/3
      called as ets:lookup_element(ejabberd_options,
                                   {auth_use_cache,
                                       <<"staging.*******.com">>},
                                   2)
   in call from ejabberd_config:get_option/1 (src/ejabberd_config.erl, line 162)
   in call from ejabberd_auth:db_check_password/7 (src/ejabberd_auth.erl, line 671)
   in call from ejabberd_auth:'-check_password_with_authmodule/6-fun-0-'/8 (src/ejabberd_auth.erl, line 248)
   in call from lists:foldl/3 (lists.erl, line 1263)
   in call from ejabberd_auth:check_password_with_authmodule/6 (src/ejabberd_auth.erl, line 246)
   in call from ejabberd_auth:check_password/6 (src/ejabberd_auth.erl, line 223)
   in call from ejabberd_oauth:authenticate_user/2 (src/ejabberd_oauth.erl, line 269)
```

## Bug description

When i try to issue an OAuth token  by going to `https://*******.com/oauth/authorization_token?response_type=token&client_id=ejabberd-service&redirect_uri=https://********.com&scope=ejabberd:admin` the request fail and ejabberd redirect me to the following URL `https://********.com/?error=access_denied&state=`
