### ISSUE TITLE
ejabberd kicking users from MUC

### ISSUE THREAD

**Issue by karimhm** [processone/ejabberd#3661]
## Environment

- ejabberd version: `21.04`
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.5`
- OS: `Alpine Linux (GKE Kubernetes)`
- Installed from: `Docker hub official image`

## Configuration

```yaml
hosts:
  - "staging-***.*******.io"
  - "staging.*******.com"

loglevel: debug
log_rotate_size: 10485760
log_rotate_count: 1
certfiles:
  - "/home/ejabberd/conf/server.pem"
ca_file: /home/ejabberd/conf/cacert.pem
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
    starttls: false
    tls: false
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: false
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5080
    ip: "::"
    module: ejabberd_http
    tls: false
    request_handlers:
      "/.well-known/acme-challenge": ejabberd_acme
s2s_use_starttls: false
acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "admin@staging.*******.com"
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: admin
  pubsub_createnode:
    allow: admin
  trusted_network:
    allow: loopback
  jwt_non_admin_only:
    deny: admin
    allow: all
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
  "api access":
    from:
      - ejabberd_ctl
      - mod_http_api
    who:
      acl: admin
    what: "*"
commands_admin_access: configure
commands:
  - add_commands:
    - user
oauth_expire: 3600
oauth_access: all
shaper:
  normal: 1000
  fast: 50000
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    100000: admin
    100000: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast
max_fsm_queue: 10000
acme:
  contact:
    - "mailto:******@*****.com"
    - "mailto:******@*****.com"
  auto: false
  cert_type: rsa
  ca_url: https://acme-staging-v02.api.letsencrypt.org/directory
sql_type: mysql
sql_server: ***************
sql_database: ejabberd_21_04
sql_username: ejabberd
sql_password: *************************************
new_sql_schema: true
default_db: sql
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    assume_mam_usage: true
    default: always
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true
      public: false
      public_list: false
      anonymous: false
      mam: true
      persistent: true
    history_size: 10000
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push:
    include_body: true
    include_sender: true
  mod_push_keepalive: {}
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
    ack_timeout: 36000000
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
```

## Errors from error.log/crash.log

No errors

## Bug description

ejabberd keep kicking users from MUC (after around 5 minute from disconnecting) rooms with the following description:

> 105532197397386078546@*******.com left the room (It is not allowed to send error messages to the room. The participant  (105532197397386078546@*******.com) has sent an error message (service-unavailable) and got kicked from the room).

The user is offline and disconnected from all devices. Stream management is enabled.

**Comment by licaon-kter** [comment]
Any client gets this? Dino? Conversations?

**Comment by prefiks** [comment]
Probably session gets terminated at this point (probably to what resume_timeout option of mod_stream_mgmt is set), and when next muc message is sent to that user is bounced with error (which will happen because we don't store groupchat messages in offline storage), and that makes user get removed from room.

So all that works as expected. We don't want to drop  "receive error -> kick from room", as this will lead to phantom users (with s2s connection, not receiving presence unavailable can and do happen, and without that behaviour that user can be in room forever). You could however make groupchat message be stored in offline storage by adding `store_groupchat: true` in `mod_offline`.

Now that i written that all i wonder why stream_mgmt didn't cause `<presence type=offline/>' be sent to a room, or it could be just a timing problem with that message arriving just before that presence get sent to room.

**Comment by karimhm** [comment]
> Any client gets this? Dino? Conversations?

A custom client based on [XMPPFramework](https://github.com/robbiehanson/XMPPFramework).

**Comment by karimhm** [comment]
> Probably session gets terminated at this point (probably to what resume_timeout option of mod_stream_mgmt is set), and when next muc message is sent to that user is bounced with error (which will happen because we don't store groupchat messages in offline storage), and that makes user get removed from room.
> 
> So all that works as expected. We don't want to drop "receive error -> kick from room", as this will lead to phantom users (with s2s connection, not receiving presence unavailable can and do happen, and without that behaviour that user can be in room forever). You could however make groupchat message be stored in offline storage by adding `store_groupchat: true` in `mod_offline`.
> 
> Now that i written that all i wonder why stream_mgmt didn't cause `' be sent to a room, or it could be just a timing problem with that message arriving just before that presence get sent to room.

@prefiks Correct, after setting the timeout of stream management the problem was solved.

```yaml
mod_stream_mgmt:
    resend_on_timeout: if_offline
    max_resume_timeoutgit: 36000000
    resume_timeout: 36000000
```
