### ISSUE TITLE
registration_timeout not working with mod_register_web

### ISSUE THREAD

**Issue by ingoj** [processone/ejabberd#3688]
## Environment

- ejabberd version: 21.07-1~bpo11+1
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 11.1.8
- OS: Debian Bullseye
- Installed from: Debian Backports

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
registration_timeout: 3600

host_config:
  hookipa.net:
    auth_password_format: scram

append_host_config:
  hookipa.net:
    modules:
      mod_http_upload: 
        #put_url: "https://@HOST@:5443/upload"
        put_url: "https://files.@HOST@/upload"
        host: "files.hookipa.net"
        external_secret: "redacted"
        max_size: 104857600
        custom_headers:
          "Access-Control-Allow-Origin": "https://files.hookipa.net"
          "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
          "Access-Control-Allow-Headers": "Content-Type"
      mod_register: 
        access:
            deny: blocked_accounts_RFC2142
            allow: all
        captcha_protected: true
        welcome_message:
          subject: "Welcome!"
          body: |-
            Aloha!
        registration_watchers:
          - "ij@mydomain.tld"
      mod_register_web: {}
...
```

## Errors from error.log/crash.log

No errors

## Bug description

Although `registration_timeout: 3600` is configured, there are many registrations from users using mod_register_web within that timeframe: 

![Bildschirmfoto 2021-10-03 um 10 16 26](https://user-images.githubusercontent.com/18173881/135745935-2c9109f9-5d62-4634-9ac0-dbd32e660079.png)

My understanding of registration_timeout being a global setting is, that it should prevent mass registrations across all configured vhosts/domains. But then again it should work across all configured registration forms as well. It appears that it is not working for mod_register_web which renders the option of registration_timeout pretty useless if register_web is also configured. 

Therefore I believe this is a bug and the function of registration_timeout should be extended to mod_register_web as well (or to all ways of registration).
