### ISSUE TITLE
Room creation via API fails

### ISSUE THREAD

**Issue by karimhm** [processone/ejabberd#3700]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: `21.04`
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.5`
- OS: `Alpine Linux (GKE Kubernetes)`
- Installed from: `Docker hub official image`

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
hosts:
  - "******.com"
loglevel: debug
log_rotate_size: 10485760
log_rotate_count: 1
certfiles:
  - "/home/ejabberd/conf/server.pem"
ca_file: /home/ejabberd/conf/cacert.pem
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: false
    starttls: false
    tls: false
    use_proxy_protocol: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: false
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5080
    ip: "::"
    module: ejabberd_http
    tls: false
    request_handlers:
      "/.well-known/acme-challenge": ejabberd_acme
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    tls: false
    request_handlers:
      "/": mod_bosh
s2s_use_starttls: false
acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "admin@******.com"
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: admin
  trusted_network:
    allow: loopback
  jwt_non_admin_only:
    deny: admin
    allow: all
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          - acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
commands_admin_access: configure
oauth_access: all
shaper:
  normal: 1000
  fast: 50000
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    100000: admin
    100000: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast
max_fsm_queue: 10000
acme:
  contact:
    - "mailto:********@******.com"
    - "mailto:*********@******.com"
  auto: false
  cert_type: rsa
  ca_url: https://acme-staging-v02.api.letsencrypt.org/directory
sql_type: mysql
sql_server: 35.241.217.60
sql_database: ejabberd_21_07
sql_username: ejabberd
sql_password: *******************************************
new_sql_schema: true
default_db: sql
auth_method: [jwt, sql, mnesia]
jwt_key: /etc/ejabberd/certs/public.key.jwk
jwt_jid_field: jid
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    assume_mam_usage: true
    default: always
    user_mucsub_from_muc_archive: true
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true
      public: false
      public_list: false
      anonymous: false
      mam: true
      persistent: true
    history_size: 10000
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
    store_groupchat: true
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push:
    include_body: true
    include_sender: true
  mod_push_keepalive: {}
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
    max_resume_timeout: 36000000
    resume_timeout: 36000000
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
```

## Errors from error.log/crash.log

```
2021-10-20 10:56:11.683584+00:00 [debug] <0.14939.2>@ejabberd_http:process/1:362 [<<"api">>,<<"create_room_with_opts">>] matches [<<"api">>]
2021-10-20 10:56:11.684772+00:00 [info] <0.14939.2>@mod_http_api:log/3:510 API call create_room_with_opts [{<<"name">>,<<"rmx4">>},
                                {<<"service">>,
                                 <<"conference.******.com">>},
                                {<<"host">>,<<"******.com">>},
                                {<<"options">>,
                                 {[{<<"password">>,<<"password">>},
                                   {<<"password_protected">>,<<"false">>}]}}] from ::ffff:35.191.2.24:54413
2021-10-20 10:56:11.686042+00:00 [debug] <0.14939.2>@ejabberd_access_permissions:can_access/2:84 Command 'create_room_with_opts' execution allowed by rule 'admin access' (CallerInfo=#{caller_module =>
                                                                                           mod_http_api,
                                                                                       caller_server =>
                                                                                           <<"******.com">>,
                                                                                       ip =>
                                                                                           {0,
                                                                                            0,
                                                                                            0,
                                                                                            0,
                                                                                            0,
                                                                                            65535,
                                                                                            9151,
                                                                                            536},
                                                                                       tag =>
                                                                                           <<>>,
                                                                                       usr =>
                                                                                           {<<"admin">>,
                                                                                            <<"******.com">>,
                                                                                            <<>>}})
2021-10-20 10:56:11.686963+00:00 [debug] <0.14939.2>@ejabberd_commands:do_execute_command/2:250 Executing command mod_muc_admin:create_room_with_opts with Args=[<<"rmx4">>,
                                                                 <<"conference.******.com">>,
                                                                 <<"******.com">>,
                                                                 [{<<"password">>,
                                                                   <<"password">>},
                                                                  {<<"password_protected">>,
                                                                   <<"false">>}]]
2021-10-20 10:56:11.688523+00:00 [debug] <0.576.0>@ejabberd_sql:sql_query_internal/1:659 SQL: "select opts from muc_room where name='rmx4' and host='conference.******.com'"
2021-10-20 10:56:11.691672+00:00 [debug] <0.551.0>@mod_muc:handle_call/3:398 MUC: create new room 'rmx4'

2021-10-20 10:56:11.692860+00:00 [debug] <0.578.0>@ejabberd_sql:sql_query_internal/1:659 SQL: "begin;"
2021-10-20 10:56:11.693890+00:00 [debug] <0.578.0>@ejabberd_sql:sql_query_internal/1:659 SQL: "REPLACE INTO muc_room(name, host, server_host, opts) VALUES ('rmx4', 'conference.******.com', '******.com', '[{allow_subscription,true},{anonymous,false},{mam,true},{password,<<\"password\">>},{password_protected,false},{persistent,true},{public,false},{public_list,false}]');"
2021-10-20 10:56:11.694804+00:00 [debug] <0.578.0>@ejabberd_sql:sql_query_internal/1:659 SQL: "delete from muc_room_subscribers where room='rmx4' and host='conference.******.com'"
2021-10-20 10:56:11.696018+00:00 [debug] <0.578.0>@ejabberd_sql:sql_query_internal/1:659 SQL: "commit;"
2021-10-20 10:56:11.701920+00:00 [error] <0.14939.2>@mod_http_api:handle/4:258 REST API Error: create_room_with_opts([{<<"name">>,<<"rmx4">>},
                                       {<<"service">>,
                                        <<"conference.******.com">>},
                                       {<<"host">>,
                                        <<"******.com">>},
                                       {<<"options">>,
                                        {[{<<"password">>,<<"password">>},
                                          {<<"password_protected">>,
                                           <<"false">>}]}}]) -> error:{badmatch,
                                                                       {atomic,
                                                                        []}} [{mod_muc_admin,
                                                                               maybe_store_room,
                                                                               4,
                                                                               [{file,
                                                                                 "src/mod_muc_admin.erl"},
                                                                                {line,
                                                                                 713}]},
                                                                              {mod_http_api,
                                                                               handle2,
                                                                               4,
                                                                               [{file,
                                                                                 "src/mod_http_api.erl"},
                                                                                {line,
                                                                                 268}]},
                                                                              {mod_http_api,
                                                                               handle,
                                                                               4,
                                                                               [{file,
                                                                                 "src/mod_http_api.erl"},
                                                                                {line,
                                                                                 229}]},
                                                                              {mod_http_api,
                                                                               perform_call,
                                                                               4,
                                                                               [{file,
                                                                                 "src/mod_http_api.erl"},
                                                                                {line,
                                                                                 189}]},
                                                                              {mod_http_api,
                                                                               process,
                                                                               2,
                                                                               [{file,
                                                                                 "src/mod_http_api.erl"},
                                                                                {line,
                                                                                 142}]},
                                                                              {ejabberd_http,
                                                                               process,
                                                                               2,
                                                                               [{file,
                                                                                 "src/ejabberd_http.erl"},
                                                                                {line,
                                                                                 373}]},
                                                                              {ejabberd_http,
                                                                               process_request,
                                                                               1,
                                                                               [{file,
                                                                                 "src/ejabberd_http.erl"},
                                                                                {line,
                                                                                 496}]},
                                                                              {ejabberd_http,
                                                                               process_header,
                                                                               2,
                                                                               [{file,
                                                                                 "src/ejabberd_http.erl"},
                                                                                {line,
                                                                                 293}]}]
2021-10-20 10:56:12.857645+00:00 [info] <0.479.0>@ejabberd_listener:accept/7:273 (<0.14998.2>) Accepted connection [::ffff:130.211.1.168]:32772 -> [::ffff:10.1.2.33]:5443
2021-10-20 10:56:12.857955+00:00 [debug] <0.14998.2>@ejabberd_http:init/3:129 S: [{[<<"admin">>],ejabberd_web_admin},
    {[<<"api">>],mod_http_api},
    {[<<"bosh">>],mod_bosh},
    {[<<"captcha">>],ejabberd_captcha},
    {[<<"upload">>],mod_http_upload},
    {[<<"ws">>],ejabberd_http_ws},
    {[<<"oauth">>],ejabberd_oauth}]
```

## Bug description

When I call the following endpoint `/api/create_room_with_opts` with the following parameters:

```json
{
    "name": "rmx4",
    "service": "conference.******.com",
    "host": "******.com",
    "options": {
        "password": "password",
        "password_protected": "false"
    }
}
```

I get the following response when calling the API for the first time with 500 Internal Server HTTP status code:
```json
"internal_error"
```

I get the following response when calling the API for the second time with 400 Bad Request HTTP status code:
```json
"Room already exists"
```

The room get created at the first call.
