### ISSUE TITLE
vcard handling problem

### ISSUE THREAD

**Issue by sss123next** [processone/ejabberd#3703]
## Environment

- ejabberd version: 4d384b6bf58f8bf68531cee35c3cb394d63e73a3
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 12.1.1
- OS: Linux (Debian) (nix)
- Installed from: patched nix package:
```
 ejabberd-local = (ejabberd.override {
			withMysql = true;
			withPgsql = true;
			withPam = false;
			withZlib = true;
		}).overrideAttrs (
			oldAttrs: rec {
				version = "2021-10-15";
				pname = "ejabberd";
				src = fetchFromGitHub {
                                        owner = "processone";
                                        repo = "ejabberd";
                                        rev = "4d384b6bf58f8bf68531cee35c3cb394d63e73a3";
					sha256 = "02y4kbwkmr723kqhr1zn3ji7275mz8zzf0k2w9dln5vxzixldnhn";
				};
				nativeBuildInputs = [ autoreconfHook makeWrapper ];
			}
		);
```

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

<details>

```yaml
loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

certfiles:
  - "/usr/etc/ejabberd/chain.pem"
  - "/usr/etc/ejabberd/cert.pem"
  - "/usr/etc/ejabberd/key.pem"

c2s_dhfile: "/usr/etc/ejabberd/dhp9998.pem"
s2s_dhfile: "/usr/etc/ejabberd/dhp9998.pem"


listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
    protocol_options:
             - "no_sslv3"
             - "CIPHER_SERVER_PREFERENCE"
             - "no_tlsv1"
    #    ciphers: "LOW:MEDIUM:HIGH"
    ciphers: "ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA"
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    transport: tcp
    tls_compression: false
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin

  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
  -
      port: 3478
      transport: udp
      module: ejabberd_stun
  -
      port: 5349
      module: ejabberd_stun
      transport: tcp
      tls: false

s2s_access: s2s
s2s_use_starttls: required
s2s_protocol_options:
         - "no_sslv3"
         - "no_tlsv1"
         - "no_tlsv1_1"
         - "CIPHER_SERVER_PREFERENCE"
s2s_ciphers: "ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384"


acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
  admin:
access_rules:
  local:
    - allow: local
    - deny
  trusted:
    - allow: local
    - allow: trusted_servers
    - deny
  c2s:
    - deny: blocked
    - allow
  s2s:
    - allow: trusted_servers
    - deny
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  trusted_network:
    - allow: loopback
  register:
    - allow: admin
    - deny

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
        - allow:
          - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 20
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban:
    c2s_auth_ban_lifetime: 7200
    c2s_max_auth_failures: 50
  mod_http_api: {}
  mod_http_upload:
    put_url: "https://@HOST@:5280/upload"
    access: trusted
  mod_last: {}
  mod_mam:
    assume_mam_usage: true
    default: always
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      mam: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping:
    send_pings: true
    ping_interval: 60
    timeout_action: kill
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    host: "proxy.jabber.server"
    access: trusted
    max_connections: 5
    port: 7777
  mod_pubsub:
    access_createnode: pubsub_createnode
    #required for shit like omemo
    ignore_pep_from_offline: false
    last_item_cache: true
    max_subscriptions_node: 100
    plugins:
      - "flat"
      - "pep"
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      "storage:bookmarks":
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_roster:
    versioning: true
    store_current_id: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_legacy_auth: {}
  mod_register:
    access: register
  mod_stun_disco:
    credentials_lifetime: 12h
    services:
        -
          host: 0.0.0.0
          port: 3478
          type: stun
          transport: udp
          restricted: false
        -
          host: 0.0.0.0
          port: 3478
          type: turn
          transport: udp
          restricted: true

allow_contrib_modules: true

```

</details>

## Errors from error.log/crash.log

```
окт 26 06:09:11 ejabberdctl.sh[428]: 2021-10-26 06:09:11.427553+03:00 [error] Hook vcard_iq_set crashed when running mod_vcard:vcard_iq_set/1:
окт 26 06:09:11 ejabberdctl.sh[428]: ** exception error: undefined function stringprep:tolower_nofilter/1
окт 26 06:09:11 ejabberdctl.sh[428]:    in function  mod_vcard:string2lower/1 (src/mod_vcard.erl, line 427)
окт 26 06:09:11 ejabberdctl.sh[428]:    in call from mod_vcard:make_vcard_search/4 (src/mod_vcard.erl, line 355)
окт 26 06:09:11 ejabberdctl.sh[428]:    in call from mod_vcard:set_vcard/3 (src/mod_vcard.erl, line 413)
окт 26 06:09:11 ejabberdctl.sh[428]:    in call from mod_vcard:vcard_iq_set/1 (src/mod_vcard.erl, line 395)
окт 26 06:09:11 ejabberdctl.sh[428]:    in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 236)
окт 26 06:09:11 ejabberdctl.sh[428]:    in call from ejabberd_hooks:run_fold1/4 (src/ejabberd_hooks.erl, line 217)
окт 26 06:09:11 ejabberdctl.sh[428]:    in call from mod_vcard:process_sm_iq/1 (src/mod_vcard.erl, line 225)
окт 26 06:09:11 ejabberdctl.sh[428]: ** Arg 1 = {iq,<<"purplea52f6277">>,set,<<"en">>,
окт 26 06:09:11 ejabberdctl.sh[428]:                {jid,<<"sss">>,<<"jabber.server">>,
окт 26 06:09:11 ejabberdctl.sh[428]:                    <<"741327858017614270155362">>,<<"sss">>,
окт 26 06:09:11 ejabberdctl.sh[428]:                    <<"jabber.server">>,<<"741327858017614270155362">>},
окт 26 06:09:11 ejabberdctl.sh[428]:                {jid,<<"sss">>,<<"jabber.server">>,<<>>,<<"sss">>,
окт 26 06:09:11 ejabberdctl.sh[428]:                    <<"jabber.server">>,<<>>},
окт 26 06:09:11 ejabberdctl.sh[428]:                [{vcard_temp,undefined,undefined,undefined,undefined,
окт 26 06:09:11 ejabberdctl.sh[428]:                     {vcard_photo,<<"image/png">>,
окт 26 06:09:11 ejabberdctl.sh[428]:                         <<137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,
окт 26 06:09:11 ejabberdctl.sh[428]:                           82,0,0,0,82,8,2,0,0,0,72,78,20,204,0,0,0,9,112,72,89,
....
....
окт 26 06:08:44 ejabberdctl.sh[428]: 2021-10-26 06:08:44.376516+03:00 [error] Hook vcard_iq_set crashed when running mod_vcard:vcard_iq_set/1:
окт 26 06:08:44 ejabberdctl.sh[428]: ** exception error: undefined function stringprep:tolower_nofilter/1
окт 26 06:08:44 ejabberdctl.sh[428]:    in function  mod_vcard:string2lower/1 (src/mod_vcard.erl, line 427)
окт 26 06:08:44 ejabberdctl.sh[428]:    in call from mod_vcard:make_vcard_search/4 (src/mod_vcard.erl, line 355)
окт 26 06:08:44 ejabberdctl.sh[428]:    in call from mod_vcard:set_vcard/3 (src/mod_vcard.erl, line 413)
окт 26 06:08:44 ejabberdctl.sh[428]:    in call from mod_vcard:vcard_iq_set/1 (src/mod_vcard.erl, line 395)
окт 26 06:08:44 ejabberdctl.sh[428]:    in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 236)
окт 26 06:08:44 ejabberdctl.sh[428]:    in call from ejabberd_hooks:run_fold1/4 (src/ejabberd_hooks.erl, line 217)
окт 26 06:08:44 ejabberdctl.sh[428]:    in call from mod_vcard:process_sm_iq/1 (src/mod_vcard.erl, line 225)
окт 26 06:08:44 ejabberdctl.sh[428]: ** Arg 1 = {iq,<<"purplea52f6272">>,set,<<"en">>,
окт 26 06:08:44 ejabberdctl.sh[428]:                {jid,<<"sss">>,<<"jabber.server">>,
окт 26 06:08:44 ejabberdctl.sh[428]:                    <<"741327858017614270155362">>,<<"sss">>,
окт 26 06:08:44 ejabberdctl.sh[428]:                    <<"jabber.server">>,<<"741327858017614270155362">>},
окт 26 06:08:44 ejabberdctl.sh[428]:                {jid,<<"sss">>,<<"jabber.server">>,<<>>,<<"sss">>,
окт 26 06:08:44 ejabberdctl.sh[428]:                    <<"jabber.server">>,<<>>},
окт 26 06:08:44 ejabberdctl.sh[428]:                [{vcard_temp,undefined,undefined,undefined,undefined,
окт 26 06:08:44 ejabberdctl.sh[428]:                     {vcard_photo,<<"image/png">>,
окт 26 06:08:44 ejabberdctl.sh[428]:                         <<137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,
окт 26 06:08:44 ejabberdctl.sh[428]:                           82,0,0,0,82,8,2,0,0,0,72,78,20,204,0,0,0,9,112,72,89,
```
