### ISSUE TITLE
PostgreSQL unix socket will not connect and crashes

### ISSUE THREAD

**Issue by Jieiku** [processone/ejabberd#3716]
## Environment

- ejabberd version: 21.07
- Erlang version: `erl +V`: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.6.4
- OS: Linux Ubuntu 20.04.3 LTS (GNU/Linux 5.4.143-1-pve x86_64)
- Installed from: official deb ( https://static.process-one.net/ejabberd/downloads/21.07/ejabberd_21.07-0_amd64.deb )

## Configuration: 

```yaml
loglevel: 5

host_config:
  "example.com":
    sql_type: pgsql
    sql_server: "/run/postgresql"
    sql_database: "ejabberd"
    sql_username: "ejabberd"
    sql_password: ""
    auth_method: sql
    auth_password_format: scram
```

## Errors from error.log/crash.log

ejabberd.log:
```
2021-11-26 19:27:50.986 [warning] <0.622.0>@ejabberd_sql:handle_reconnect:472 pgsql connection failed:
** Reason: {init,{error,nxdomain}}
** Retry after: 30 seconds
```

crash.log:
```
2021-11-26 19:27:50 =CRASH REPORT====
  crasher:
    initial call: pgsql_proto:init/1
    pid: <0.769.0>
    registered_name: []
    exception exit: {{init,{error,nxdomain}},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,358}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: ['ejabberd_sql_example.com_2','ejabberd_sql_sup_example.com',ejabberd_db_sup,ejabberd_sup,<0.107.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 765
  neighbours:
```

error.log:
```
2021-11-26 19:27:50.987 [error] <0.766.0> CRASH REPORT Process <0.766.0> with 0 neighbours exited with reason: {init,{error,nxdomain}} in gen_server:init_it/6 line 358
```

## Bug description

If you configure ejabberd.yaml (as shown above) to use pgsql via unix socket then it will not connect. Crashes are generated in the crash log as well.
