### ISSUE TITLE
mod_muc_log: file_permissions option not working

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#373]
I have mod_muc_log configured to include a file_permissions setting (you can see the full config in our git repository: [modules.yml](https://github.com/jabber-at/config/blob/master/modules.yml#L97)):

```
mod_muc_log:
  access_log: everybody
  timezone: local
  outdir: "/var/www/jabber.at/sites/jabber.at/logs/"
  file_permissions:
    mode: 644
    group: 33
  spam_prevention: true
```

This is the same as [in the documentation](http://www.process-one.net/docs/ejabberd/guide_en.html#modmuclog).

When starting ejabberd, I get the following lines (once for each vhost) in my logs:

```
@ejabberd_config:prepare_opt_val:582 Configuration problem:
** Option: file_permissions
** Invalid value: [{mode, 644}, {group, 33}]
** Using as fallback: {644,33}
```
