### ISSUE TITLE
Password is stored as plain text in Posthres database

### ISSUE THREAD

**Issue by mtangoo** [processone/ejabberd#3746]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 21.12
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.4
- OS: Linux (Ubuntu)
- Installed from: official deb

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
sql_type: pgsql
sql_server: "localhost"
sql_database: "db_name"
sql_username: "..."
sql_password: "..."
default_db: sql
new_sql_schema: true

...
```

## Errors from error.log/crash.log

No errors

## Bug description

Password is saved as plain text. Isn't this security issue?
