### ISSUE TITLE
Cannot access admin dashboard

### ISSUE THREAD

**Issue by ughstudios** [processone/ejabberd#3758]
## Environment

- ejabberd version: 20.01-1
- Erlang version: 10.6.4
- OS: Ubuntu Linux 20.04 focal
- Installed from: sudo apt-get install ejabberd -y

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```
ejabberd@ip-10-0-1-208:/etc/ejabberd$ grep -Ev '^$|^\s*#' ejabberd.yml
---
loglevel: 4
log_rotate_count: 0
log_rotate_date: ""
hosts:
  - localhost
  - xmpp.ughstudios.com
certfiles:
  - "/etc/ejabberd/ejabberd.pem"
define_macro:
  'TLS_CIPHERS': "HIGH:!aNULL:!eNULL:!3DES:@STRENGTH"
  'TLS_OPTIONS':
    - "no_sslv3"
    - "no_tlsv1"
    - "no_tlsv1_1"
    - "cipher_server_preference"
    - "no_compression"
c2s_ciphers: 'TLS_CIPHERS'
s2s_ciphers: 'TLS_CIPHERS'
c2s_protocol_options: 'TLS_OPTIONS'
s2s_protocol_options: 'TLS_OPTIONS'
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
    protocol_options: 'TLS_OPTIONS'
  -
    port: 5223
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    tls: true
    protocol_options: 'TLS_OPTIONS'
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    protocol_options: 'TLS_OPTIONS'
    request_handlers:
      /api: mod_http_api
      /bosh: mod_bosh
      /ws: ejabberd_http_ws
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    tls: true
    protocol_options: 'TLS_OPTIONS'
    request_handlers:
      /admin: ejabberd_web_admin
      /.well-known/acme-challenge: ejabberd_acme
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000
disable_sasl_mechanisms:
  - "digest-md5"
  - "X-OAUTH2"
s2s_use_starttls: required
auth_password_format: scram
acl:
  admin:
     user:
       - ""
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
shaper:
  normal: 1000
  fast: 50000
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_echo: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_last: {}
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      mam: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_pres_counter:
    count: 5
    interval: 60
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: open
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_sic: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_version: {}
```

## Errors from error.log/crash.log

ejabberd@ip-10-0-1-208:/var/log/ejabberd$ cat error.log
ejabberd@ip-10-0-1-208:/var/log/ejabberd$ cat crash.log

**No errors**

## Bug description

Cannot access web admin from browser:
http://xmpp.ughstudios.com:5443/admin
http://xmpp.ughstudios.com:5280/admin

Neither of the above links work.

**Comment by Bdoom** [comment]
The log in `/var/log/ejabberd/ejabberd.log` says that a connection was accepted:

```
2022-01-26 00:11:27.508 [info] <0.2133.0>@ejabberd_listener:accept:256 (<0.2308.                                                                                                                                    0>) Accepted connection MY_IP -> 10.0.1.208:5280
```

**Comment by licaon-kter** [comment]
Try to add a `/` after `admin` ?

**Comment by Bdoom** [comment]
I ended up just installing the latest version on the website from the .deb file and it seems to work now, although the documentation on the website does not seem to match the new file configs for ejabberd.yml and .cfg

**Comment by licaon-kter** [comment]
Match in what way? https://docs.ejabberd.im are pretty complete

**Comment by badlop** [comment]
``` yaml
listen:
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    protocol_options: 'TLS_OPTIONS'
    request_handlers:
      /api: mod_http_api
      /bosh: mod_bosh
      /ws: ejabberd_http_ws
```

This listener doesn't have admin enabled. If you add
```yaml
      /admin: ejabberd_web_admin
```
then it will listen in `https://localhost:5443/admin/`

```yaml
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    tls: true
    protocol_options: 'TLS_OPTIONS'
    request_handlers:
      /admin: ejabberd_web_admin
      /.well-known/acme-challenge: ejabberd_acme
```

This listens in `https://localhost:5280/admin/` Notice you have `tls: true`, so you must use `https`

> Cannot access web admin from browser:
> ```
> http://xmpp.ughstudios.com:5443/admin
> http://xmpp.ughstudios.com:5280/admin
> ```

Right, because those URLs don't match your configuration.

```yaml
acl:
  admin:
     user:
       - ""
```

I guess here you set some username or JID...
