### ISSUE TITLE
Ejabberd ignores sql_pool_size setting

### ISSUE THREAD

**Issue by mkl262** [processone/ejabberd#3774]
## Bug description

I have 3 nodes running in a cluster, with a single host configured.
Lately I noticed that ejabberd creates an extreme amount of connections to the mysql DB, sometimes even more than 500.
I tried to set sql_pool_size to 100, but I still see that ejabberd tries to maintain over 500 connections to DB after some time running.
I attached some errors, but Im not sure they are relevant, because that the DB reaches maximum connections.

## Environment

- ejabberd version: 20.07
- Erlang version: `erl +V`
- OS: Linux Debian
- Installed from: official binary installer

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
language: "en"
hosts:
  - "domain.com"
loglevel: 4
log_rotate_size: 52428800
log_rotate_count: 10
certfiles:
  - "/opt/ejabberd/conf/domain.pem"
ca_file: "/opt/ejabberd/conf/cacert.pem"
sql_type: mysql
sql_server: "db"
sql_database: "ejabberd"
sql_username: "username"
sql_password: "password"
sql_port: 3306
sql_pool_size: 100
sql_keepalive_interval: 1
sql_start_interval: 5
new_sql_schema: false
default_db: sql
default_ram_db: sql
auth_method: sql
allow_contrib_modules: true
cache_size: 20000
max_fsm_queue: 30000
listen:
  - port: 5222
    ip: "::"
    module: ejabberd_c2s
    protocol_options:
      - "no_sslv2"
      - "no_sslv3"
      - "no_tlsv1"
      - "no_tlsv1_1"
    ciphers: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"
    starttls: true
    starttls_required: false
    tls_compression: false
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    use_proxy_protocol: false
  - port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  - port: 5443
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
    captcha: false
    use_proxy_protocol: false
    tls: false
  - port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
    captcha: false
    use_proxy_protocol: false
    tls: false
  - port: 9334
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/metrics": mod_prometheus
    captcha: false
    use_proxy_protocol: false
    tls: false
s2s_use_starttls: optional
acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
  admin:
    user:
      - "admin@domain.com"
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - ip: "127.0.0.1/8"
      - access:
        - allow:
          - acl: loopback
          - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"
shaper:
  normal: 1000
  fast: 50000
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 500
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
acme:
  auto: false
  contact: "mailto:hostmaster@domain.com"
  ca_url: "https://acme-v02.api.letsencrypt.org/directory"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps:
    use_cache: true
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: "https://ejabberd.domain.com/upload"
    max_size: 10485760
    docroot: "/mnt/files"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type"
  mod_last: {}
  mod_mam:
    db_type: sql
    assume_mam_usage: true
    default: always
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      allow_user_invites: false
      allow_subscription: true
      allow_change_subj: false
      allow_query_users: true
      allow_private_messages: true
      mam: true
      members_by_default: true
      members_only: true
      logging: true
      persistent: true
      anonymous: false
      public: false
      presence_broadcast:
        - visitor
    history_size: 0
    max_users: 5000
    max_user_conferences: 5000
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping:
    send_pings: true
    ping_interval: 60
    ping_ack_timeout: 30
    timeout_action: kill
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: false
    last_item_cache: false
    max_items_node: 1000
    plugins:
      - "flat"
      - "pep"
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      "storage:bookmarks":
        access_model: whitelist
      "domain:roster:x":
        access_model: presence
        notification_type: normal
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: false
    db_type: sql
    cache_size: 80000
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: true
    resume_timeout: 30
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
```

## Errors from error.log/crash.log

2022-02-13 09:30:31.286 [error] <0.26027.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:31.288 [error] <0.13698.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:31.289 [error] <0.1740.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:31.291 [error] <0.26118.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:31.292 [error] <0.13645.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:31.294 [error] <0.26146.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:31.298 [error] <0.23195.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:31.298 [error] <0.10538.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:31.299 [error] <0.25863.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:31.303 [error] <0.25809.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:31.303 [error] <0.25881.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.254 [error] <0.25517.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.254 [error] <0.26190.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.256 [error] <0.6184.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.256 [error] <0.1765.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.257 [error] <0.2585.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.258 [error] <0.26506.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.260 [error] <0.13857.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.271 [error] <0.13978.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.273 [error] <0.13899.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.274 [error] <0.13933.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.277 [error] <0.14002.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.277 [error] <0.23248.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.278 [error] <0.25907.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.286 [error] <0.25299.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.288 [error] <0.26826.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.290 [error] <0.14025.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.292 [error] <0.13926.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.292 [error] <0.13996.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.294 [error] <0.26194.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.298 [error] <0.26714.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.298 [error] <0.26704.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.300 [error] <0.14026.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.304 [error] <0.14008.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:32.304 [error] <0.5297.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.254 [error] <0.26597.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.254 [error] <0.5897.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.256 [error] <0.14257.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.256 [error] <0.6183.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.258 [error] <0.26856.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.258 [error] <0.12631.212>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.260 [error] <0.25613.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.271 [error] <0.14296.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.273 [error] <0.14274.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.275 [error] <0.26513.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.277 [error] <0.11111.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.277 [error] <0.28353.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.279 [error] <0.23601.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.284 [error] <0.26816.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.288 [error] <0.14387.214>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.289 [error] <0.23466.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.291 [error] <0.26651.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
2022-02-13 09:30:33.291 [error] <0.26560.213>@ejabberd_sql:keep_alive:160 Keep alive query failed, closing connection: {error,<<"SQL connection failed">>}
