### ISSUE TITLE
The value of public_list (MUC options) auto transform to false

### ISSUE THREAD

**Issue by haithngn** [processone/ejabberd#3775]
## Environment

- ejabberd version: 21.07
- Erlang version: `erl +V`
- OS: Linux (Centos 7)
- Installed from: official rpm

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
mod_muc:
    hosts:
      - conference.@HOST@
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    min_message_interval: 0.4
    ram_db_type: sql
    history_size: 0
    default_room_options:
      allow_subscription: true  # enable MucSub
      allow_query_users: true
      mam: true
      allow_user_invites: true
      max_users: 50
      password_protected: false
      public: false
      public_list: true
      persistent: true
      anonymous: false
      members_by_default: true
      members_only: true
      moderated: false
...
```

## Bug description

The value of MUC option (opts) in the database (MySQL) auto modify, at the created time the public_list is true. After a couple of days, the value auto transforms to false.

Could you please review the configuration and give me any advice?
Regards,
