### ISSUE TITLE
mod_http_upload doesnt working on localhost

### ISSUE THREAD

**Issue by salihgenctan** [processone/ejabberd#3797]
Hello everyone.

I am new in this forum and maybe my question can easy for you :)

I am interested in ejabberd and xmpp server with using conversejs as a web client. I want to enable the http_upload module but i couldnt. Here is my ejabberd.yml and errors. 

Thanks in advance.

ejabberd.yml:

<details>

```yml
hosts:
  - localhost

loglevel: debug

listen:
  - port: 5222
    ip: '::'
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  - port: 5223
    ip: "::"
    tls: true
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  - port: 5269
    ip: '::'
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  - port: 5443
    ip: '::'
    module: ejabberd_http
    tls: true
    request_handlers:
      /admin: ejabberd_web_admin
      /api: mod_http_api
      /bosh: mod_bosh
      /captcha: ejabberd_captcha
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"
      "Access-Control-Allow-Headers": "Content-Type, Origin, X-Requested-With, Authorization"
      "Access-Control-Allow-Credentials": "true"
  - port: 5280
    ip: '::'
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /.well-known/acme-challenge: ejabberd_acme
      ##'/pub/archive': mod_http_fileserver
    web_admin: true
    http_bind: true
  - port: 1883
    ip: '::'
    module: mod_mqtt
    backlog: 1000
  - port: 3478
    transport: udp
    module: ejabberd_stun
    use_turn: true
    turn_min_port: 49152
    turn_max_port: 65535
    turn_ip: 0.0.0.0
  - port: 5349
    transport: tcp
    module: ejabberd_stun
    use_turn: true
    tls: true
    turn_min_port: 49152
    turn_max_port: 65535
    ip: 0.0.0.0
    turn_ip: 0.0.0.0

##auth_method:
##  - sql
##auth_password_format: scram

## postgresql db configuration

##default_db: sql

##sql_type: pgsql
##sql_server: pg_container
##sql_database: test_db
##sql_username: root
##sql_password: root

s2s_use_starttls: optional

acl:
  local:
    user_regexp: ''
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
  admin:
    user:
      - 'admin@localhost'

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

api_permissions:
  'console commands':
    from:
      - ejabberd_ctl
    who: all
    what: '*'
  'admin access':
    who:
      access:
        allow:
          acl: admin
      oauth:
        scope: 'ejabberd:admin'
        access:
          allow:
            acl: admin
    what:
      - '*'
      - '!stop'
      - '!start'
  'public commands':
    who:
      ip: 127.0.0.1/8
    what:
      - '*'
      - connected_users_number

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10000
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

max_fsm_queue: 10000
certfiles:
  - ./certs/privkey.pem
  - ./certs/fullchain.pem
##acme:
  ##contact: 'mailto:admin@localhost'
  ##ca_url: 'https://acme-v01.api.letsencrypt.org'

oauth_expire: 31536000
oauth_access: all

modules:
  mod_stun_disco:
    credentials_lifetime: 12h
    services:
      - host: 0.0.0.0
        port: 3478
        type: stun
        transport: udp
        restricted: false
      - host: 0.0.0.0
        port: 3478
        type: turn
        transport: udp
        restricted: true
      - host: rtcdev.site
        port: 5349
        type: stun
        transport: tcp
        restricted: false
      - host: rtcdev.site
        port: 5349
        type: turn
        transport: tcp
        restricted: true
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_fileserver:
    docroot: opt/ejabberd
    accesslog: opt/ejabberd/logs/access.log
    directory_indices:
      - index.html
      - main.htm
    custom_headers:
      X-Powered-By: Erlang/OTP
      X-Fry: "It's a widely-believed fact!"
    content_types:
      .ogg: audio/ogg
      .png: image/png
      .jpeg: image/jpeg
    default_content_type: text/html
  mod_http_upload:
    access: local
    name: "HTTP File Upload"
    docroot: /home/ejabberd/uploads
    put_url: http://localhost:5443
    max_size: infinity
    jid_in_url: node
    file_mode: "0640"
    dir_mode: "2750"
    rm_on_unregister: false
    thumbnail: false # otherwise needs the identify command from ImageMagick installed
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"
      "Access-Control-Allow-Headers": "content-type"
      "Access-Control-Allow-Credentials": "true"

  mod_last: {}
  mod_mam: {}
    ##    request_activates_archiving: false
    ## iqdisc: one_queue
    ##default: always
    ##default: never
  ##db_type: sql
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_sip: {}
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
```
</details>

error.log:

<details>

```
2022-02-16 14:03:07.378357+03:00 [error] <0.498.0>@ejabberd_acme:issue_request/7:246 Failed to request certificate for example.com, pubsub.example.com and 3 more hosts: HTTP error: unexpected content type: text/html
2022-02-16 14:03:29.253153+03:00 [error] <0.1079.0>@ejabberd_acme:issue_request/7:246 Failed to request certificate for example.com, pubsub.example.com and 3 more hosts: HTTP error: unexpected content type: text/html
2022-02-16 14:09:11.077811+03:00 [error] <0.498.0>@ejabberd_acme:issue_request/7:246 Failed to request certificate for example.com, pubsub.example.com and 3 more hosts: HTTP error: unexpected content type: text/html
2022-02-16 14:20:50.924676+03:00 [critical] <0.115.0>@ejabberd_app:start/2:72 Failed to start ejabberd application: Failed to read YAML file '/usr/local/etc/ejabberd/ejabberd.yml': Syntax error on line 96 at position 11: did not find expected '-' indicator
2022-02-16 14:21:22.053653+03:00 [critical] <0.115.0>@ejabberd_app:start/2:72 Failed to start ejabberd application: Failed to read YAML file '/usr/local/etc/ejabberd/ejabberd.yml': Syntax error on line 96 at position 11: did not find expected '-' indicator
2022-02-16 14:21:49.429429+03:00 [critical] <0.115.0>@ejabberd_app:start/2:72 Failed to start ejabberd application: Failed to read YAML file '/usr/local/etc/ejabberd/ejabberd.yml': Syntax error on line 96 at position 11: did not find expected '-' indicator
2022-02-16 14:24:05.421517+03:00 [critical] <0.115.0>@ejabberd_app:start/2:72 Failed to start ejabberd application: Failed to read YAML file '/usr/local/etc/ejabberd/ejabberd.yml': Syntax error on line 96 at position 11: did not find expected '-' indicator
2022-02-16 14:37:13.744229+03:00 [critical] <0.115.0>@ejabberd_app:start/2:72 Failed to start ejabberd application: Failed to read YAML file '/usr/local/etc/ejabberd/ejabberd.yml': Syntax error on line 96 at position 11: did not find expected '-' indicator
2022-02-16 14:38:05.005923+03:00 [critical] <0.115.0>@ejabberd_app:start/2:72 Failed to start ejabberd application: Failed to read YAML file '/usr/local/etc/ejabberd/ejabberd.yml': Syntax error on line 96 at position 11: did not find expected '-' indicator
2022-02-16 15:04:53.618477+03:00 [error] <0.1749.0>@proc_lib:crash_report/4:508 CRASH REPORT:
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.1749.0>
    registered_name: []
    exception error: no match of right hand side value {error,no_certfile}
      in function  ejabberd_http:init/3 (src/ejabberd_http.erl, line 122)
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.1292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1717.0>,#Port<0.115>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 4602
  neighbours:

2022-02-16 15:04:53.618880+03:00 [error] <0.1750.0>@proc_lib:crash_report/4:508 CRASH REPORT:
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.1750.0>
    registered_name: []
    exception error: no match of right hand side value {error,no_certfile}
      in function  ejabberd_http:init/3 (src/ejabberd_http.erl, line 122)
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.1292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1717.0>,#Port<0.116>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 4589
  neighbours:

2022-02-16 15:04:53.622472+03:00 [error] <0.1717.0>@supervisor:do_restart/3:716 SUPERVISOR REPORT:
    supervisor: {local,ejabberd_http_sup}
    errorContext: child_terminated
    reason: {{badmatch,{error,no_certfile}},
             [{ejabberd_http,init,3,
                             [{file,"src/ejabberd_http.erl"},{line,122}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1749.0>},
               {id,undefined},
               {mfargs,{ejabberd_http,start_link,undefined}},
               {restart_type,temporary},
               {shutdown,5000},
               {child_type,worker}]
2022-02-16 15:04:53.623252+03:00 [error] <0.1717.0>@supervisor:do_restart/3:716 SUPERVISOR REPORT:
    supervisor: {local,ejabberd_http_sup}
    errorContext: child_terminated
    reason: {{badmatch,{error,no_certfile}},
             [{ejabberd_http,init,3,
                             [{file,"src/ejabberd_http.erl"},{line,122}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1750.0>},
               {id,undefined},
               {mfargs,{ejabberd_http,start_link,undefined}},
               {restart_type,temporary},
               {shutdown,5000},
               {child_type,worker}]
2022-02-16 15:04:53.623969+03:00 [error] <0.1751.0>@proc_lib:crash_report/4:508 CRASH REPORT:
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.1751.0>
    registered_name: []
    exception error: no match of right hand side value {error,no_certfile}
      in function  ejabberd_http:init/3 (src/ejabberd_http.erl, line 122)
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.1292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1717.0>,#Port<0.117>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 4589
  neighbours:

2022-02-16 15:04:53.624269+03:00 [error] <0.1752.0>@proc_lib:crash_report/4:508 CRASH REPORT:
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.1752.0>
    registered_name: []
    exception error: no match of right hand side value {error,no_certfile}
      in function  ejabberd_http:init/3 (src/ejabberd_http.erl, line 122)
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.1292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1717.0>,#Port<0.118>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 4589
  neighbours:

2022-02-16 15:04:53.625222+03:00 [error] <0.1717.0>@supervisor:do_restart/3:716 SUPERVISOR REPORT:
    supervisor: {local,ejabberd_http_sup}
    errorContext: child_terminated
    reason: {{badmatch,{error,no_certfile}},
             [{ejabberd_http,init,3,
                             [{file,"src/ejabberd_http.erl"},{line,122}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1751.0>},
               {id,undefined},
               {mfargs,{ejabberd_http,start_link,undefined}},
               {restart_type,temporary},
               {shutdown,5000},
               {child_type,worker}]
2022-02-16 15:04:53.625969+03:00 [error] <0.1717.0>@supervisor:do_restart/3:716 SUPERVISOR REPORT:
    supervisor: {local,ejabberd_http_sup}
    errorContext: child_terminated
    reason: {{badmatch,{error,no_certfile}},
             [{ejabberd_http,init,3,
                             [{file,"src/ejabberd_http.erl"},{line,122}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1752.0>},
               {id,undefined},
               {mfargs,{ejabberd_http,start_link,undefined}},
               {restart_type,temporary},
               {shutdown,5000},
               {child_type,worker}]
2022-02-16 15:04:54.718010+03:00 [error] <0.1753.0>@proc_lib:crash_report/4:508 CRASH REPORT:
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.1753.0>
    registered_name: []
    exception error: no match of right hand side value {error,no_certfile}
      in function  ejabberd_http:init/3 (src/ejabberd_http.erl, line 122)
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.1292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1717.0>,#Port<0.119>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 4589
  neighbours:

2022-02-16 15:04:54.719424+03:00 [error] <0.1754.0>@proc_lib:crash_report/4:508 CRASH REPORT:
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.1754.0>
    registered_name: []
    exception error: no match of right hand side value {error,no_certfile}
      in function  ejabberd_http:init/3 (src/ejabberd_http.erl, line 122)
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.1292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1717.0>,#Port<0.120>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 4591
  neighbours:

2022-02-16 15:04:54.720496+03:00 [error] <0.1717.0>@supervisor:do_restart/3:716 SUPERVISOR REPORT:
    supervisor: {local,ejabberd_http_sup}
    errorContext: child_terminated
    reason: {{badmatch,{error,no_certfile}},
             [{ejabberd_http,init,3,
                             [{file,"src/ejabberd_http.erl"},{line,122}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1753.0>},
               {id,undefined},
               {mfargs,{ejabberd_http,start_link,undefined}},
               {restart_type,temporary},
               {shutdown,5000},
               {child_type,worker}]
2022-02-16 15:04:54.721425+03:00 [error] <0.1717.0>@supervisor:do_restart/3:716 SUPERVISOR REPORT:
    supervisor: {local,ejabberd_http_sup}
    errorContext: child_terminated
    reason: {{badmatch,{error,no_certfile}},
             [{ejabberd_http,init,3,
                             [{file,"src/ejabberd_http.erl"},{line,122}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1754.0>},
               {id,undefined},
               {mfargs,{ejabberd_http,start_link,undefined}},
               {restart_type,temporary},
               {shutdown,5000},
               {child_type,worker}]
2022-02-16 15:04:54.722220+03:00 [error] <0.1755.0>@proc_lib:crash_report/4:508 CRASH REPORT:
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.1755.0>
    registered_name: []
    exception error: no match of right hand side value {error,no_certfile}
      in function  ejabberd_http:init/3 (src/ejabberd_http.erl, line 122)
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.1292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1717.0>,#Port<0.121>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 4589
  neighbours:

2022-02-16 15:04:54.722585+03:00 [error] <0.1756.0>@proc_lib:crash_report/4:508 CRASH REPORT:
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.1756.0>
    registered_name: []
    exception error: no match of right hand side value {error,no_certfile}
      in function  ejabberd_http:init/3 (src/ejabberd_http.erl, line 122)
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.1292.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1717.0>,#Port<0.122>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 4589
  neighbours:

2022-02-16 15:04:54.723537+03:00 [error] <0.1717.0>@supervisor:do_restart/3:716 SUPERVISOR REPORT:
    supervisor: {local,ejabberd_http_sup}
    errorContext: child_terminated
    reason: {{badmatch,{error,no_certfile}},
             [{ejabberd_http,init,3,
                             [{file,"src/ejabberd_http.erl"},{line,122}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1755.0>},
               {id,undefined},
               {mfargs,{ejabberd_http,start_link,undefined}},
               {restart_type,temporary},
               {shutdown,5000},
               {child_type,worker}]
2022-02-16 15:04:54.724298+03:00 [error] <0.1717.0>@supervisor:do_restart/3:716 SUPERVISOR REPORT:
    supervisor: {local,ejabberd_http_sup}
    errorContext: child_terminated
    reason: {{badmatch,{error,no_certfile}},
             [{ejabberd_http,init,3,
                             [{file,"src/ejabberd_http.erl"},{line,122}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1756.0>},
               {id,undefined},
               {mfargs,{ejabberd_http,start_link,undefined}},
               {restart_type,temporary},
               {shutdown,5000},
               {child_type,worker}]
```
</details>
