### ISSUE TITLE
Shared roster with external auth (ejabberd_auth_http)

### ISSUE THREAD

**Issue by cvele** [processone/ejabberd#3803]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: ejabberd/ecs:21.12
- Installed from: Docker

## Configuration:

```yaml
loglevel: 4
...
mod_roster:
    db_type: sql
    versioning: false
mod_shared_roster:
    db_type: sql
auth_use_cache: false
auth_cache_missed: false
host_config:
  localhost:
    auth_method: http
    auth_opts:
      host: "http://app:80"
      connection_pool_size: 10
      connection_opts: []
      basic_auth: ""
      path_prefix: "/_jabber/"
    sql_type: mysql
    sql_server: "db"
    sql_database: "ejabberd"
    sql_username: "root"
    sql_password: "root"
    ## If you want to specify the port:
    sql_port: 3306
...
```

## Errors from error.log/crash.log

No errors

## Bug description

I am trying to create a shared roster group in order to allow all online users to see each other presence. 

Users are managed externally and for integration I am using ejabberd_auth_http - which works great. However, when using this auth I cannot add user to shared roster, it fails silently. Eg:

```/home/ejabberd/bin/ejabberdctl srg_user_add @online@ localhost online localhost```

From reading old issues and forum threads it  seems to be an issue when using shared roster and external authentication. Some of those threads describe using `exauth_cache:`, a deprecated option superseded by `auth_use_cache: true  auth_cache_missed: false` however enabling these creates unpredictable behavior and is supposed by disabled  according  to doc:  https://docs.ejabberd.im/admin/configuration/authentication/#external-script

Could you please advise how to proceed?

**Comment by badlop** [comment]
`ejabberd_auth_http`, similarly to `ejabberd_auth_external` and `ejabberd_auth_jwt`, does not implement the function `get_users/2`. When using those auth methods, some features do not work (number and list of registered accounts, `@all@` in shared roster, ...). In those cases, enabling auth cache helps...


But I think `@online@` should work immediately, no need to enable auth cache. I made a test using extauth, and `@online@` works for me. Maybe you have a different problem?

1. I install ejabberd 22.05 from source code (I think there are no relevant changes since 21.12)

2. Add to the default configuration:

```yaml
auth_method: [external]
extauth_program: /ejabberd/examples/extauth/check_pass_null.pl
extauth_instances: 3
auth_use_cache: false
```

3. Create a shared group, setting itself as "display", and later add as special member `@online@` to that group:
```
ejabberdctl srg_create onli localhost onlinelabel onlinedesc onli
ejabberdctl srg_user_add @online@ localhost onli localhost
```

4. Check the result:
```
$ ejabberdctl srg_get_info onli localhost
label   onlinelabel
displayed_groups        ["onli"]
description     onlinedesc
online_users    true
```

5. Login with a Jabber client to an account (all accounts are accepted)
Nothing is displayed in its roster

6. Login a second client to a second account
This new client gets in the roster the first account.
