### ISSUE TITLE
New docker image build without image converter support

### ISSUE THREAD

**Issue by marzzzello** [processone/ejabberd#3823]
## Environment

- ejabberd version: 22.5.3
- Erlang version: `erl +V`
- OS: Linux (Ubuntu)
- Installed from: ghcr.io/processone/ejabberd:latest
## Configuration

```yaml
[...]
  mod_http_upload:
    put_url: https://xmpp.@HOST@/upload/
    hosts:
      - xmpp.@HOST@
    thumbnail: true
[...]
```

## Errors from error.log

```
2022-05-20 22:24:41.541490+00:00 [critical] Failed to start ejabberd application: Invalid value of option modules->mod_http_upload->thumbnail: ejabberd is built without image converter support
```

## Bug description

Thumbnailing is not working because ejabberd seems to be compiled without image converter support.
Maybe related to #3514
`eimp:supported_formats().` returns `[]`
