### ISSUE TITLE
MUC service not being announced when config included via `append_host_config`

### ISSUE THREAD

**Issue by raucao** [processone/ejabberd#3836]
## Environment

- ejabberd version: 22.05
- OS: Linux (Ubuntu)
- Installed from: official deb

### ejabberd.yml

```yaml
loglevel: 4

hosts:
  - "kosmos.org"
  - "example.com"

include_config_file: "/opt/ejabberd/conf/kosmos.org.yml"
include_config_file: "/opt/ejabberd/conf/example.com.yml"

...

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco:
    server_info:
      -
        modules: all
        name: "abuse-addresses"
        urls: ["mailto:abuse@kosmos.org"]
  mod_bosh: {}
  mod_last: {}
  mod_mam:
    default: always
    request_activates_archiving: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: false
    last_item_cache: false
    max_items_node: 10
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
  mod_push: {}
  mod_push_keepalive: {}
  # Allow existing accounts to change their password
  mod_register:
    access: none
  mod_roster:
    versioning: true
    store_current_id: true
  mod_shared_roster: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_avatar: {}
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
  mod_http_api: {}

allow_contrib_modules: true
```

### kosmos.org.yml

```yaml
...

append_host_config:
  "kosmos.org":
    modules:
      mod_muc:
        host: "kosmos.chat"
        access:
          - allow
        access_admin:
          - allow: admin
        access_create: muc_create
        access_persistent: muc_create
        max_user_conferences: 1000
        default_room_options:
          mam: true
      mod_http_upload:
        put_url: "https://uploads.kosmos.chat/123"
        external_secret: "123"
        max_size: 104857600
        thumbnail: false
```

## Errors from error.log/crash.log

No errors

## Bug description

The MUC service has been running on the configured domain for a couple of years, and everything is working normally. However, it is not being announced in the Service Discovery when querying the XMPP domains of the vhosts.

Thus, clients are unable to discover the domain to create new rooms with, while room creation works fine when manually adding the host. But this is not always possible; for example it isn't supported when creating a private group from Conversations. Also, the XMPP compliance suite [result for our domain](https://compliance.conversations.im/server/kosmos.org/) is claiming that our domains don't support MUC, because it cannot discover the feature.

(Hint: you can join for example the room `kosmos@kosmos.chat` to see that the service is actually running as configured.)
