### ISSUE TITLE
Command need to be run with admin priviledge

### ISSUE THREAD

**Issue by potenzatk** [processone/ejabberd#3839]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 16.09
- Erlang version: `erl +V`
- OS: Amazon Linux release 2 (Karoo)
- Installed from: source https://www.process-one.net/downloads/downloads-action.php?file=/16.09/ejabberd-16.09-linux-x86_64-installer.run

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

When I try to Run below API
http://ec2-3-135-193-140.us-east-2.compute.amazonaws.com:5280/api/register

I Got "Command need to be run with admin priviledge" error please check below link
http://prntscr.com/xXbRVU_nBdYK
http://prntscr.com/bsDYMalBWH1N

My \opt\ejabberd-16.09\conf\ejabberd.yml file details

```yaml
port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/api": mod_http_api
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    ## register: true
    captcha: false

    modules:
      mod_http_api:
        admin_ip_access: admin_ip_access_rule

    access:
      admin_ip_access_rule:
        admin_ip_acl:
          - change password
          - add_rosteritem
          - register
          - delete_rosteritem
          - send_message

    acl:
      admin_ip_acl:
        ip:
         - "3.135.193.140/8"
```

Please help me how I can fix this issue.

**Comment by licaon-kter** [comment]
Latest version is 22.05 can you not use a 6 years (!!) old version?

**Comment by potenzatk** [comment]
I will update latest version but first please help me with this error.

**Comment by prefiks** [comment]
And are you issuing that call from 3.135.193.140?

**Comment by potenzatk** [comment]
Yes, I call http://ec2-3-135-193-140.us-east-2.compute.amazonaws.com:5280/api/register API from  3.135.193.140 server and ejabberd also installed on this server.

**Comment by badlop** [comment]
As I said, it works for me using 16.09, your configuration (changing IP address), and my curl query running on the same machine. I imagine there are several reasons this can fail in your server... so I tried to reproduce that error message:

If I configure
```yaml
acl:
  admin_ip_acl:
    ip:
      - "111.0.0.1/8"
```
Then I run the curl command
```
curl -X GET \
    http://localhost:5280/api/register?user=user1\&host=localhost\&password=asd1
```
And the result is:
```
{"status":"error","code":31,"message":"Command need to be run with admin priviledge."}
```
Why does it fail? Because I told ejabberd to only accept API queries from 111.0.0.1/8, and I send the query from 127.0.0.1.

Can you try setting
```yaml
acl:
  admin_ip_acl:
    ip:
      - "127.0.0.1/8"
```
and run the same curl query that I do in the same machine that runs ejabberd?
