### ISSUE TITLE
error executing export2sql: "module not loaded" 

### ISSUE THREAD

**Issue by sp4ke** [processone/ejabberd#3867]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 22.05
- Erlang version: `erl +24`
- OS: Linux (Debian)
- Installed from: docker image ejabberd/ecs:22.05

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
hosts:
  - ***
loglevel: info
sql_type: sqlite
sql_database: ejabberd.sqlite
hide_sensitive_log_data: true
log_rotate_count: 0
log_rotate_date: ""
log_rotate_size: 1
acme:
  auto: false
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /api: mod_http_api
      /bosh: mod_bosh
      /captcha: ejabberd_captcha
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
      /.well-known/acme-challenge: ejabberd_acme
      /.well-known: mod_http_fileserver
  -
    port: 3478
    ip: "::"
    transport: udp
    module: ejabberd_stun
    use_turn: true
    turn_ipv4_address: "***"
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000
s2s_use_starttls: optional
acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
  admin:
    user:
      - "admin@***"
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          - acl: loopback
          - acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
shaper:
  normal:
    rate: 3000
    burst_size: 20000
  fast: 100000
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    10000: admin
    5000: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco:
      server_info:
          -
            modules: all
            name: "abuse-addresses"
            urls: ["mailto:admin@***"]
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_fileserver:
    docroot: /home/ejabberd/.well-known
    custom_headers:
      "Access-Control-Allow-Origin": "*"
    content_types:
      .json: "application/jrd+json"
    default_content_type: "application/xrd+xml"
  mod_http_upload:
    put_url: https://@HOST@:443/upload
  mod_last: {}
  mod_mam:
    db_type: sql
    assume_mam_usage: true
    default: always
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      mam: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_stun_disco: {}
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

...
```

## Errors from error.log/crash.log

No errors

## Bug description

I am trying to migrate mod_mam archives to use sqlite after I reached the 2G limit. I was originally running on version 21.12. I followed the guide and initialized sqlite schema from `lite.sql` then I ran the export2sql script which I imported to the sqlite database. Only then I enabled `db_type: sql` on *mod_mam* which I realize I should have done before running the script. Anyway the export went well but I noticed that the archives where not migrated and the `archive` table is empty in the sql export. I tried again running the `export2sql` script after enabling sql in mod_mam but I get the same sql file everytime not including the archive. 

For info, mod_mam works without issues with the sqlite db I have no errors. However I lost all the archived messages previous to enabling sqlite, which as I understand must be stored in `archive_msg.DAT`.

I decided to migrate to version 22.05, I applied the updates to the sqlite schema as per the upgrade notes. I can run ejabberd without issues. I tried again the export script `export2sql` but this time I get this error: 

```
Unhandled exception occurred executing the command:
** exception error: {module_not_loaded,mod_muc,<<"ejabberd@ejabberd">>}
   in function  gen_mod:get_module_opts/2 (src/gen_mod.erl, line 338)
   in call from gen_mod:get_module_opt_hosts/2 (src/gen_mod.erl, line 323)
   in call from ejd2sql:export/3 (src/ejd2sql.erl, line 77)
   in call from lists:foreach/2 (lists.erl, line 1342)
   in call from ejd2sql:export/2 (src/ejd2sql.erl, line 70)
   in call from ejabberd_ctl:call_command/4 (src/ejabberd_ctl.erl, line 332)
   in call from ejabberd_ctl:try_call_command/4 (src/ejabberd_ctl.erl, line 297)
   in call from ejabberd_ctl:process2/4 (src/ejabberd_ctl.erl, line 235)
```

Also, I noticed that the command `ejd2sql` in the debug console does not exist.
