### ISSUE TITLE
When mod_stream_mngmt is active, the session never being closed, contrary to xep-198 

### ISSUE THREAD

**Issue by relbraun** [processone/ejabberd#3868]
## Environment

- ejabberd version: 21.12 (Docker image `ejabberd/ecs:21.12`)
- Erlang version: 22
- OS: Linux (Debian) | MacOs
- Installed from: Docker | (also checked on source-code-installed environment)

## Configuration

```yaml

language: "en"

hosts:
  - myhost.com

loglevel: debug
log_rotate_size: 52428800
log_rotate_count: 10

certfiles:
  - "/home/ejabberd/conf/cert.pem"
ca_file: "/home/ejabberd/conf/cert.pem"

sql_type: mysql
sql_server: "127.0.0.1"
sql_database: "ejabberd"
sql_username: "username"
sql_password: "password"
sql_port: 3306
sql_pool_size: 20
sql_keepalive_interval: 10000
sql_start_interval: 5
new_sql_schema: false
default_db: sql
default_ram_db: mnesia
auth_method: sql

allow_contrib_modules: true
cache_size: 20000
max_fsm_queue: 30000


listen:
  - port: 5222
    ip: "::"
    module: ejabberd_c2s
    protocol_options:
      - "no_sslv2"
      - "no_sslv3"
      - "no_tlsv1"
      - "no_tlsv1_1"
    ciphers: "mycipher"
    starttls: true
    starttls_required: false
    tls_compression: false
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    use_proxy_protocol: true

  - port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288

  - port: 5443
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /bosh: mod_bosh
    captcha: false
    use_proxy_protocol: false
    tls: false

  - port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /api: mod_http_api
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
    captcha: false
    use_proxy_protocol: false
    tls: false

  - port: 9334
    ip: "::"
    module: ejabberd_http
    # request_handlers:
    #   /metrics: mod_prometheus
    captcha: false
    use_proxy_protocol: false
    tls: false

s2s_use_starttls: optional


acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - 10.255.0.1/16
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "admin@myhost.com"


access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback


api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - ip: "127.0.0.1/8"
      - ip: "10.255.0.1/16"
      - access:
        - allow:
          - acl: loopback
          - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number


shaper:
  normal:
    rate: 3000
    burst_size: 20000
  fast: 100000


shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 500
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast


acme:
  auto: false
  contact: "mailto:hostmaster@mycompany.io"
  ca_url: "https://ca_url..."


modules:
  mod_adhoc: {}
  # mod_admin_update_sql: {}
  mod_admin_extra: {}

  mod_announce:
    access: announce

  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}

  mod_caps:
    use_cache: true

  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  # mod_fail2ban: {}
  mod_http_api: {}

  mod_http_upload:
    put_url: "https://dev-xmpp.widebridgecloud.com/upload"
    max_size: 10485760
    docroot: "/docrootdir"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type"

  mod_last: {}

  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    db_type: sql
    assume_mam_usage: true
    default: always

  # mod_mqtt: {}

  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_user_invites: false
      allow_subscription: true
      allow_change_subj: false
      allow_query_users: true
      allow_private_messages: true
      mam: true
      members_by_default: true
      members_only: true
      logging: true
      persistent: true
      anonymous: false
      public: false
      presence_broadcast:
        - visitor
    history_size: 0
    max_users: 5000
    max_user_conferences: 5000

  mod_muc_admin: {}

  mod_offline:
    access_max_user_messages: max_user_offline_messages

  mod_ping:
    send_pings: true
    ping_interval: 60
    ping_ack_timeout: 30
    timeout_action: kill

  mod_privacy: {}
  mod_private: {}

  mod_proxy65:
    access: local
    max_connections: 5

  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: false
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    max_items_node: 1000
    plugins:
      - flat
      - pep
    force_node_config:
      ## Change from "whitelist" to "open" to enable OMEMO support
      ## See https://github.com/processone/ejabberd/issues/2425
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
      widebridge:roster:x:
        access_model: presence
        notification_type: normal

  # mod_push: {}
  # mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network

  mod_roster:
    versioning: false
    db_type: sql
    cache_size: 80000

  mod_s2s_dialback: {}
  mod_shared_roster: {}

  mod_stream_mgmt:
    resend_on_timeout: false
    resume_timeout: 30

  # mod_stun_disco: {}
  mod_vcard: {}
  mod_vcard_xupdate: {}

  mod_version:
    show_os: false
```

## Errors from error.log/crash.log

No errors

## Bug description

In [xep-0198 stream closure](https://xmpp.org/extensions/xep-0198.html#closure) :
_If the stream is not cleanly closed then the server SHOULD consider the stream to be unfinished (even if the client closes its TCP connection to the server) and SHOULD maintain the session on behalf of the client **for a limited amount of time**._

There is no such limitation so the session stay alive all the time and the users can't be awared that the user is no longer active (e.g: I was connected with websocket and closed the browser).

In addition, since the `mod_ping` is also active, the server continues to send ping requests to the closed connection and never stops.
