### ISSUE TITLE
How to make users register Jids in English only (Ejabberd 14.12) 

### ISSUE THREAD

**Issue by leonardo-dev** [processone/ejabberd#388]
I'm trying to make user user only English to register on my server using ACL user_regexp: regexp as the following:

```
acl:
  regex:
    user_regexp: "^[s0-9a-za-z-_.]{3,25}$"

access:
  register: 
    all: deny
    regex: allow 
```

But it didn't work and the registration completely stop.
