### ISSUE TITLE
In-Band registeration in Ejabberd 22.05

### ISSUE THREAD

**Issue by Vladimir7i** [processone/ejabberd#3897]
## Environment

- ejabberd version: 22.05
- Erlang version: `erl +V`
- OS: Linux (Debian 11)
- Installed from: official deb

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Issue description

How to enable In-Band registeration for version 22.05?
I use S22.Xmpp(c#) as client for Unity(game)

In version ejabberd version: 18.09 In-Band registeration work as well,
but after update to 22.05 I can't registrate user by using game client because of [Access denied by service policy]

## XML body of error:

<iq xmlns="jabber:client" xml:lang="en-US" from="vmi117915.contaboserver.net" type="error" id="2">
	<query xmlns="jabber:iq:register">
		<username xmlns="jabber:iq:register">
			someUserName
		</username>
		<password xmlns="jabber:iq:register">
			someUserPassword
		</password>
	</query>
	<error xmlns="jabber:client" type="auth">
		<forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
		<text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">
			Access denied by service policy
		</text>
	</error>
</iq>

**Comment by licaon-kter** [comment]
Clean up and put config on https://gist.github.com

Did you read https://docs.ejabberd.im/admin/configuration/modules/#mod-register yet?

**Comment by Vladimir7i** [comment]
<script src="https://gist.github.com/Vladimir7i/00e61c00a92ebf8d884865271d09a1b7.js"></script>

I have default cfg, but I can't add there:

 ## In-band registration allows registration of any possible username.
 ## To disable in-band registration, replace 'allow' with 'deny'.
 register: 
   all: allow

Server wont startup with this parameter, how to enable In-band registration?

**Comment by licaon-kter** [comment]
pls attach config

**Comment by Vladimir7i** [comment]
[https://gist.github.com/Vladimir7i/38774eb7d83afe9fd603c17619e60f6d](url)

**Comment by licaon-kter** [comment]
```
acl:
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128

access_rules:
  trusted_network:
    allow: loopback

  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network
    access: register
```

I see no errors here, you can register new users ONLY FROM 127.0.0.1 via `ejabberdctl register ...` the comment is pretty clear, right?
