### ISSUE TITLE
mod_pubsub force_node_config doesn't override details in the database

### ISSUE THREAD

**Issue by mzealey** [processone/ejabberd#3909]
**Is your feature request related to a problem? Please describe.**

When we change something such as

```
        mod_pubsub:
            force_node_config:
                "urn:xmpp:avatar:*":
                    access_model: open

```

it only applies to newly created items rather than all items that exist

**Describe the solution you'd like**

I believe the `node_config()` merge of data + forced config should happen at retrieval time as well as in `create_node`. 

**Describe alternatives you've considered**

At the very least this non-modification of existing records should be documented behaviour.
