### ISSUE TITLE
ejabberd XEP-0215 support clarification

### ISSUE THREAD

**Issue by cmeng-git** [processone/ejabberd#3926]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 20.12
- Erlang version: `Erlang/OTP 22 [erts-10.6.4]` 
- OS: Linux (Debian) Ubuntu 22.04
- Installed from: source

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml
```
listen:
  ##
  ## ejabberd_stun: Handles STUN Binding requests
  ##
  - 
    port: 3478
    ip: "::"
    transport: udp
    module: ejabberd_stun
    use_turn: true
    turn_min_port: 49152
    turn_max_port: 65535
    auth_type: user
    auth_realm: https://atalk.sytes.net

    ## The server's public IPv4 address:
    turn_ipv4_address: 42.60.99.4
    ## The server's public IPv6 address:
    # turn_ipv6_address: 2001:db8::3

  -
    port: 5349
    transport: tcp
    module: ejabberd_stun
    use_turn: true
    turn_min_port: 49152
    turn_max_port: 65535
    auth_type: user
    auth_realm: https://atalk.sytes.net
    turn_ipv4_address: 42.60.99.4
    certfile: /etc/letsencrypt/live/atalk.sytes.net/cert.pem

  mod_stun_disco:
    access: register
    credentials_lifetime: 12h

    services:
        -
          host: 42.60.99.4
          port: 3478
          type: stun
          transport: udp
          restricted: false
        -
          host: 42.60.99.4
          port: 3478
          type: turn
          transport: udp
          restricted: true
        -
          host: atalk.sytes.net
          port: 5349
          type: stuns
          transport: tcp
          restricted: false
        -
          host: atalk.sytes.net
          port: 5349
          type: turns
          transport: tcp
          restricted: true

``````
## Errors from error.log/crash.log

See aTalk logcat below

## Bug description
Please, give us a precise description (what does not work, what is expected, etc.)

aTalk is trying to implement support for the below XEP Standard.
[XEP-0215: External Service Discovery v1.0.0 (2022-08-23)](https://xmpp.org/extensions/xep-0215.html)
On request for  \<service xmlns='urn:xmpp:extdisco:2'/>, instead of returning the list of services, it gives an error
as shown below. Please advice on a solution if any.

```
2022-10-28 12:02:25.845 8305-8487/org.atalk.android D/SMACK: SENT (0): 
    <iq to='atalk.sytes.net' id='2EDM2-16' type='get'>
      <service xmlns='urn:xmpp:extdisco:2'/>
    </iq>

2022-10-28 12:02:27.180 8305-8488/org.atalk.android D/SMACK: RECV (0): 
    <iq xml:lang='en-US' to='abc123@atalk.sytes.net/atalk' from='atalk.sytes.net' type='error' id='2EDM2-16'>
      <service xmlns='urn:xmpp:extdisco:2'/>
      <error code='400' type='modify'>
        <bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
        <text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>
          Missing attribute &apos;host&apos; in tag &lt;service/&gt; qualified by namespace &apos;urn:xmpp:extdisco:2&apos;
        </text>
      </error>
    </iq>
```
