### ISSUE TITLE
using mod_offline

### ISSUE THREAD

**Issue by mkassir95** [processone/ejabberd#3962]
Hello, how to use mod_offline?
I am not receiving any messages from smack library after sending a message to an offline user and then reconnecting this user
This my ejabberd.yml:

```yaml
hosts:
  - localhost

loglevel: info


  
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    #starttls: true
    #certfile: "./xmpp_example_com.pem"
    

  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /.well-known/acme-challenge: ejabberd_acme
  
  -
    port: 5281
    module: ejabberd_http
    ip: "::"
    request_handlers:
      /api: mod_http_api
      /oauth: ejabberd_oauth
  

     
acl:
 exampleorg:
   server: localhost
    
api_permissions:
  "some playing":
    from:
      - ejabberd_ctl
      - mod_http_api
    who:
      acl: exampleorg
    what: "*"
shaper_rules:
  max_user_offline_messages:
    - 5000: poweruser
    - 2000: admin
    - 100
    
modules:
  mod_admin_extra: {}
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      allow_private_messages: true
      allow_user_invites: true
      mam: true
      persistent: true
  mod_muc_admin: {}
  mod_push: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
```
