### ISSUE TITLE
PostgreSQL Missing Column

### ISSUE THREAD

**Issue by levniko** [processone/ejabberd#3993]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 23.01
- Erlang version: `erl + "24"`
- OS: WSL2 Linux (Ubuntu 22.04)
- Installed from: official binary installer

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
auth_method: [jwt, sql]
jwt_key: /etc/ejabberd/secret.jwk
default_db: sql
new_sql_schema: true
sql_type: pgsql
sql_server: "localhost"
sql_database: "ejabberddb"
sql_username: "admin"
sql_password: "password"
sql_port: 5432
access_rules:
  jwt_only:
    deny: admin
    allow: all
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

jwt_auth_only_rule: jwt_only
...
...
...
  mod_push_keepalive: {}
  ## mod_register:
  ##   ## Only accept registration requests from the "trusted"
  ##   ## network (see access_rules section above).
  ##   ## Think twice before enabling registration from any
  ##   ## address. See the Jabber SPAM Manifesto for details:
  ##   ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
  ##   ip_access: trusted_network
  mod_roster:
    db_type: sql
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_sic: {}
  mod_stream_mgmt:

```

## Errors from error.log
```
2023-02-14 16:17:07.443024+03:00 [error] <0.454.0>@ejabberd_sql:check_error/2:1236 SQL query 'Q22045648' at {mod_mqtt_sql,{112,10}} failed: [{severity,'ERROR'},
                                                          {86,<<"ERROR">>},
                                                          {code,<<"42703">>},
                                                          {message,
                                                           <<"column \"server_host\" does not exist">>},
                                                          {position,34},
                                                          {file,
                                                           <<"parse_relation.c">>},
                                                          {line,3633},
                                                          {routine,
                                                           <<"errorMissingColumn">>}]
```

## Bug description
I made the necessary setups in the ejabberd.yml file to connect psql. Host port user database etc.
https://raw.githubusercontent.com/processone/ejabberd/master/sql/pg.sql I downloaded the required schemas from here and checked. But I am getting errorMissingColumn error above.
How can I fix this ?
