### ISSUE TITLE
mod_mam with external authentication, unable to retrieve all chat messages 

### ISSUE THREAD

**Issue by dkliss** [processone/ejabberd#3999]
Hi,

I have external authentication & have following configuration in ejabberd.yml. Default db is SQL.

Ejabberd Version: 23.01 

```
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    ## db_type: sql
    assume_mam_usage: true
    default: always
  mod_offline:
    access_max_user_messages: max_user_offline_messages

```

Using above config, when I send a message, received message stanza show "archived" flag. But when I query the server archive, I do not see any historical or recent chat messages at all. 

I came across similar issue in  here https://github.com/processone/ejabberd/issues/3377 , which was raised 3 years ago. It talks about JWT auth being a reason for a client not to be able to retrieve server messages as user tables are missing from SQL due to external auth. My offline message delivery however works with no issues.  Based on that link does it mean, if we use ext auth, we cannot use mom_mam to store chat history? Or, if I need to configure something else to set this up.

Thanks for your help!

Before creating a ticket, please consider if this should fit the [discussion forum](https://github.com/processone/ejabberd/discussions) better.

## Environment

- ejabberd version: 18.09
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

Please, give us a precise description (what does not work, what is expected, etc.)

**Comment by prefiks** [comment]
If your external script properly implement `isuser` query, then both mam and offline should be working for a user. 

Problems is only with methods that can't tell is given user exists or not (like various cert authentication or jwt, where tokens are created on the fly) - but external auth is not one of that. But your script must be able to correctly responds to `isuser` requests.

**Comment by dkliss** [comment]
> If your external script properly implement `isuser` query, then both mam and offline should be working for a user.
> 
> Problems is only with methods that can't tell is given user exists or not (like various cert authentication or jwt, where tokens are created on the fly) - but external auth is not one of that. But your script must be able to correctly responds to `isuser` requests.

The issue I have is bit confusing. I did not receive archived messages which I sent recently when i sent request to mam. But upon that query, i did received 50 or so messages, few weeks old. My guess is, those messages were because of server handling "unacknowledged messages when the connection is lost". Not sure, if being able to receive those message confirms if my isUser setup is correct.  


```
assume_mam_usage: true | false
This option determines how ejabberd’s stream management code (see [mod_stream_mgmt](https://docs.ejabberd.im/admin/configuration/modules/#mod-stream-mgmt)) handles unacknowledged messages when the connection is lost. Usually, such messages are either bounced or resent. However, neither is done for messages that were stored in the user’s MAM archive if this option is set to true. In this case, ejabberd assumes those messages will be retrieved from the archive. The default value is false.
```

**Comment by dkliss** [comment]
> If your external script properly implement `isuser` query, then both mam and offline should be working for a user.
> 
> Problems is only with methods that can't tell is given user exists or not (like various cert authentication or jwt, where tokens are created on the fly) - but external auth is not one of that. But your script must be able to correctly responds to `isuser` requests.

I did some more tests. The script I used for auth is from below link.

https://www.npmjs.com/package/ejabberd-auth

And it does respond to isUser requests but it will only confirm if user exists but will not return anything (i.e. username).

The issue I have is still same. Every time I call query MAM, i keep on receiving same set of 50 or so old messages repeatedly and none of my latest sent, received messages are being retrieved even though I can see in stanza of my received messaged tagged as "archived".  Offline messages does work as expected. Only chat history retrieval does not work on request.  

Test 1: Same Result. 

```
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    ## db_type: sql
    access_preferences: all
    assume_mam_usage: true
    compress_xml: true
    use_cache: true
    cache_size: 20000
    default: always
```

 Test 2: Same Result.

```
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    ## db_type: sql
    assume_mam_usage: true
    compress_xml: true #Only for MySQL
    default: always 
```

**Comment by dkliss** [comment]
> If your external script properly implement `isuser` query, then both mam and offline should be working for a user.
> 
> Problems is only with methods that can't tell is given user exists or not (like various cert authentication or jwt, where tokens are created on the fly) - but external auth is not one of that. But your script must be able to correctly responds to `isuser` requests.

After some more tests, interestingly, the mom_mam works if i change default_db to mnesia. It however does not work, if the database is My SQL. I also tried to revert back from 23.01 to 22.10 and still the MySQL archive does not work.

I can also confirm that the archive tables are moved to mySQL as I I no longer see below lines in installation  logs created after changing default db to MySQL.

Not sure if the issue is in MySQL\TLS\Tables or any other place. My MySQL config is also copied below. 

TEST SETUP: TEST PASSED

1. Keep default db as MySQL.
2. Change default db for mod_mam module to mnesia.
3. Rest is all same. 

RESULTS: mod_mam works as expected if default db is  mnesia i.e. I can see recent chat history when retrieved. TEST PASS.

```

2022-10-29 13:49:01.760767+00:00 [warning] Mnesia backend for mod_mam is not recommended: it's limited to 2GB and often gets corrupted when reaching this limit. SQL backend is recommended. Namely, for small servers SQLite is a preferred choice because it's very easy to configure.
2022-10-29 13:49:01.761057+00:00 [info] Creating Mnesia disc_only table 'archive_msg'
2022-10-29 13:49:01.769442+00:00 [info] Creating Mnesia disc_only table 'archive_prefs'
```

mod_mam configuration.

```
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    #db_type: sql
    db_type: mnesia
    request_activates_archiving: false
    assume_mam_usage: true
    compress_xml: true #Only for MySQL
    default: always
```

My SQL Setup

```
  default_db: sql
  sql_type: mysql
  sql_server: "10.250.191.81"
  sql_database: "ejabberd"
  sql_username: "ejabberd"
  sql_password: "Password123"
  sql_port: 3306
  sql_ssl: true. 
  sql_ssl_verify: false
  sql_ssl_cafile: "/opt/ejabberd/conf/mysql-ca.pem"
  sql_ssl_certfile: "/opt/ejabberd/conf/mysql-client-cert.pem". 
  sql_connect_timeout: 10
  sql_keepalive_interval: 1
```


Current SQL Tables

```
mysql> SHOW TABLES;
+-------------------------+
| Tables_in_ejabberd      |
+-------------------------+
| archive                 |
| archive_prefs           |
| bosh                    |
| caps_features           |
| last                    |
| mix_channel             |
| mix_pam                 |
| mix_participant         |
| mix_subscription        |
| motd                    |
| mqtt_pub                |
| muc_online_room         |
| muc_online_users        |
| muc_registered          |
| muc_room                |
| muc_room_subscribers    |
| oauth_client            |
| oauth_token             |
| privacy_default_list    |
| privacy_list            |
| privacy_list_data       |
| private_storage         |
| proxy65                 |
| pubsub_item             |
| pubsub_node             |
| pubsub_node_option      |
| pubsub_node_owner       |
| pubsub_state            |
| pubsub_subscription_opt |
| push_session            |
| roster_version          |
| rostergroups            |
| rosterusers             |
| route                   |
| sm                      |
| spool                   |
| sr_group                |
| sr_user                 |
| users                   |
| vcard                   |
| vcard_search            |
+-------------------------+
41 rows in set (0.00 sec)
```
