### ISSUE TITLE
Cannot give REST API access to admin

### ISSUE THREAD

**Issue by greffgreff** [processone/ejabberd#4008]
I will eventually move ejabberd to another machine and would like to perform room creation along other command over http with admin credentials.

To create a room, I perform a `POST to https://localhost:5443/api/create_room` with body:
```json
{
    "name": "happiness",
    "host": "localhost",
    "service": "conference.localhost"
}
```
and with basic auth set with the right credentials (admin, admin). However, I get the following error response:
```json
{
    "status": "error",
    "code": 10,
    "message": "You are not authorized to call this command."
}
```

I tried fiddling with admin access in the config file a bit but reverted all changes to the following:
```yml
hosts:
  - localhost

loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

certfiles:
  - /home/ejabberd/conf/server.pem

ca_file: "/home/ejabberd/conf/cacert.pem"

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000

s2s_use_starttls: optional

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "admin@localhost"

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: 
      - local
      - admin
  pubsub_createnode:
    allow: 
      - local
      - admin
  trusted_network:
    allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
    from:
      - ejabberd_ctl
      - mod_http_api
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
...
```

Thanks in advance! ✌
