### ISSUE TITLE
MAM delete messages after certain period of time

### ISSUE THREAD

**Issue by Musacca** [processone/ejabberd#4009]
I would like my messages to be deleted from the archive table after 90 days automatically?. As I see, there is an API delete_old_mam_messages for deleting the old messages. 

Is there any property that I can set in the ejabberd.yml file which will delete the messages after 90 days?

**Comment by licaon-kter** [comment]
https://github.com/processone/ejabberd-contrib/tree/master/mod_cron

**Comment by badlop** [comment]
Right, in fact there's an example that mentions that API in
https://github.com/processone/ejabberd-contrib/tree/master/mod_cron#ctl

For example, this deletes everyday the messages that are older than 90 days:

```yaml
modules:
  mod_cron:
    tasks:
      - time: 1
        units: days
        ctl: delete_old_mam_messages
        arguments:
          - "all"
          - "90"
```
