### ISSUE TITLE
In Client application if we do suddenly Internet data  -OFF  the Presence status not reflected to opponents 

### ISSUE THREAD

**Issue by prabhugithubme** [processone/ejabberd#4013]
In Client application if we do suddenly Internet data  -OFF  the Presence status not reflected to opponents.

 In this case after around 2 minutes only server side socket( client App to server socket)  getting closed.  So until that in others roaster list about this user presence status is online.
    pls guide me to resolve this issue.

I am sharing module config details from ejabberd.yml .

## Environment

- ejabberd version: 21.12
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from:  official deb/rpm | official binary installer | other

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

<details>

```yaml
modules:
  mod_trago_push:
    db_type: sql
  mod_adhoc: {}
  mod_cron:
    tasks:
      - time: 2
        units: days
        ctl: delete_old_mam_messages
        arguments:
          - "all"
          - "20"
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://test.test.net:6775
    external_secret: "test-secret"
    max_size: 204857600
    thumbnail: true 
  mod_last:
    db_type: sql
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    db_type: sql
    assume_mam_usage: true
    default: always
  mod_mqtt: {}
  mod_muc:
    db_type: sql
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: true
    history_size: 0
  mod_muc_admin: {}
  mod_ping: {}
  mod_privacy:
    db_type: sql
  mod_private:
    db_type: sql
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    db_type: sql
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: false          ## true
    last_item_cache: false
    plugins:
      - flat
      - hometree
      - pep
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network
  mod_roster:
    db_type: sql
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster:
    db_type: sql
  mod_vcard:
    db_type: sql
    search: true
    allow_return_all: true
  mod_vcard_xupdate:
    use_cache: false
  mod_version:
    show_os: false
```
</details>
