### ISSUE TITLE
mod_mam_sql - Malformed 'peer' field 

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#4083]
#### Environment

- ejabberd version: 00c76003cbd3ad81762bd581e878f15b6fc51036
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 14.0.2`
- OS: Linux arm64 (Debian)
- Installed from: source

`[error] <0.XXX.0>@mod_mam_sql:make_archive_el/9:597 Malformed 'peer' field with value '' detected for user MUCNAME@conference.mydomain.tld in table 'archive': invalid JID`

Did I miss any new sql change?

Parts of the config:

```
default_db: sql
sql_type: pgsql
...
new_sql_schema: true
sql_pool_size: 2
...
modules:
  mod_offline:
    access_max_user_messages: max_user_offline_messages
    store_groupchat: true
    use_mam_for_storage: true
...
append_host_config:
  "mydomain.tld":
    modules:
      mod_mam:
        assume_mam_usage: true
        default: always
        clear_archive_on_room_destroy: false
        compress_xml: true
      mod_muc:
        host: "conference.@HOST@"
        access:
          - allow
        access_admin:
          - allow: admin
        access_create: muc_create
        access_persistent: muc_create
        default_room_options:
          mam: true
          allow_subscription: true
        history_size: 1000
```
