### ISSUE TITLE
23.10 update broke ldaps

### ISSUE THREAD

**Issue by luizluca** [processone/ejabberd#4110]
Before creating a ticket, please consider if this should fit the [discussion forum](https://github.com/processone/ejabberd/discussions) better.

## Environment

- ejabberd version: 23.10
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.7
- OS: Linux (Debian)
- Installed from: official deb/rpm

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
auth_method: [ldap]
ldap_servers:
  - "exampe.com"
ldap_encrypt: tls
ldap_base: "dc=example,dc=com"
ldap_uids: {
    mail: "%u@example.com",
    samAccountName: "%u"
}
ldap_filter: "(!(samAccountName=*-*))"
ldap_tls_verify: hard
ldap_tls_cacertfile: "/etc/ssl/certs/MyExampleCA.pem"
```

## Errors from error.log/crash.log

```
LDAP connection to example.com:636 failed: Invalid option fail_if_no_peer_cert server_only
```

## Bug description

Our jabber stopped to work after we updated to ejabberd-23.10-1.x86_64. I couldn't find a specific option that could change the error.
