### ISSUE TITLE
oauth token cannot take effect

### ISSUE THREAD

**Issue by Ltianci** [processone/ejabberd#4148]
（https://github.com/processone/ejabberd/discussions）。
```
## env- ejabberd
version：the news
os：Linux（ubuntu）

Is my conf：
oauth_expire: 2592000
oauth_access: all

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
              - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"   

acl:
  admin:
    user: admin@ejabberd.qaq.cn
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128

  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /api: mod_http_api
      /oauth: ejabberd_oauth
      /admin: ejabberd_web_admin
      /.well-known/acme-challenge: ejabberd_acme
```
my configuration is already the same as on the official website. why I get err : 
{
    "status": "error",
    "code": 32,
    "message": "AccessRules: Account does not have the right to perform the operation."
}
