### ISSUE TITLE
reload_config doesn't reload TLS certificates at globbed paths

### ISSUE THREAD

**Issue by Amolith** [processone/ejabberd#4157]
I would have commented on #1109 because it's exactly what I'm experiencing and there's no sense in duplicating the issue, but it's locked.

## Environment

- ejabberd version: `23.10-1`
- Erlang version: `11.1.8`
- OS: `Debian 11`
- Installed from: `https://repo.process-one.net/deb`

## Relevant portions of config

```yaml
hosts:
  - "nixnet.services"
  - "secluded.site"
  - "pwned.life"
  - "paranoid.network"
  - "linux.monster"

certfiles:
  # Certs are stored as /opt/ejabberd/certs/<HOST>/<HOST>.{crt,key}
  - "/opt/ejabberd/certs/*/*"

acme:
  auto: false
```

## Bug description

ejabberd doesn't seem to notice when certificate files change, even when issued a `reload_config`; I have to fully restart ejabberd.
