### ISSUE TITLE
exception error: {unregistered_route,<<"pubsub.domain.tld">>}

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#4190]
## Environment

- ejabberd version: 24.02
- Erlang version: `13.1.5`
- OS: Linux (Debian)
- Installed from: official deb/rpm

## Errors from error.log/crash.log

<details>

```
2024-04-04 09:00:48.178725+02:00 [error] <0.2810.0>@mod_pubsub:get_transaction_response/1:3969 Transaction aborted:
** exception error: {unregistered_route,<<"pubsub.domain.tld">>}
   in function  ejabberd_router:host_of_route/1 (src/ejabberd_router.erl, line 280)
   in call from mod_pubsub:submodule/3 (src/mod_pubsub.erl, line 3712)
   in call from mod_pubsub:node_call/4 (src/mod_pubsub.erl, line 3872)
   in call from mod_pubsub:'-do_transaction/4-fun-0-'/3 (src/mod_pubsub.erl, line 3930)
   in call from ejabberd_sql:execute_bloc/1 (src/ejabberd_sql.erl, line 637)
   in call from ejabberd_sql:run_sql_cmd/4 (src/ejabberd_sql.erl, line 519)
   in call from p1_fsm:handle_msg/10 (/home/runner/work/ejabberd/ejabberd/deps/p1_utils/src/p1_fsm.erl, line 582)
   in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 241)
2024-04-04 09:00:48.179568+02:00 [error] <0.2810.0>@ejabberd_hooks:safe_apply/4:324 Hook c2s_self_presence crashed when running mod_pubsub:on_self_presence/1:
** exception error: {unregistered_route,<<"pubsub.domain.tld">>}
   in function  ejabberd_router:host_of_route/1 (src/ejabberd_router.erl, line 280)
   in call from mod_pubsub:transaction/3 (src/mod_pubsub.erl, line 3922)
   in call from mod_pubsub:get_subscriptions_for_send_last/6 (src/mod_pubsub.erl, line 2573)
   in call from mod_pubsub:'-send_last_items/1-fun-1-'/6 (src/mod_pubsub.erl, line 3148)
   in call from lists:foreach_1/2 (lists.erl, line 1686)
   in call from mod_pubsub:on_self_presence/1 (src/mod_pubsub.erl, line 595)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 320)
   in call from ejabberd_hooks:run_fold1/4 (src/ejabberd_hooks.erl, line 301)
2024-04-04 09:00:48.186284+02:00 [error] <0.749.0>@ejabberd_hooks:safe_apply/4:324 Hook presence_probe_hook crashed when running mod_pubsub:presence_probe/3:
** exception error: {unregistered_route,<<"pubsub.domain.tld">>}
   in function  ejabberd_router:host_of_route/1 (src/ejabberd_router.erl, line 280)
   in call from mod_pubsub:tree_action/3 (src/mod_pubsub.erl, line 3827)
   in call from mod_pubsub:send_last_pep/3 (src/mod_pubsub.erl, line 3201)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 320)
   in call from ejabberd_hooks:run1/3 (src/ejabberd_hooks.erl, line 287)
   in call from ejabberd_c2s:route_probe_reply/2 (src/ejabberd_c2s.erl, line 711)
   in call from ejabberd_c2s:process_presence_in/2 (src/ejabberd_c2s.erl, line 679)
   in call from ejabberd_c2s:process_info/2 (src/ejabberd_c2s.erl, line 232)
** Arg 1 = {jid,<<"user1">>,<<"domain.tld">>,<<"gajim.XXX">>,
                <<"user1">>,<<"domain.tld">>,<<"gajim.XXX">>}
** Arg 2 = {jid,<<"user2">>,<<"domain.tld">>,<<"gajim.XXX">>,
                <<"user2">>,<<"domain.tld">>,<<"gajim.XXX">>}
** Arg 3 = <0.749.0>
2024-04-04 09:00:48.190507+02:00 [error] <0.2810.0>@ejabberd_hooks:safe_apply/4:324 Hook caps_add crashed when running mod_pubsub:caps_add/3:
** exception error: {unregistered_route,<<"pubsub.domain.tld">>}
   in function  ejabberd_router:host_of_route/1 (src/ejabberd_router.erl, line 280)
   in call from mod_pubsub:tree_action/3 (src/mod_pubsub.erl, line 3827)
   in call from mod_pubsub:send_last_pep/3 (src/mod_pubsub.erl, line 3201)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 320)
   in call from ejabberd_hooks:run1/3 (src/ejabberd_hooks.erl, line 287)
   in call from mod_caps:c2s_presence_in/2 (src/mod_caps.erl, line 265)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 320)
   in call from ejabberd_hooks:run_fold1/4 (src/ejabberd_hooks.erl, line 301)
** Arg 1 = {jid,<<"user1">>,<<"domain.tld">>,<<"gajim.XXX">>,
                <<"user1">>,<<"domain.tld">>,<<"gajim.XXX">>}
** Arg 2 = {jid,<<"user1">>,<<"domain.tld">>,<<"gajim.XXX">>,
                <<"user1">>,<<"domain.tld">>,<<"gajim.XXX">>}
** Arg 3 = [<<"http://jabber.org/protocol/bytestreams">>,
            <<"http://jabber.org/protocol/muc">>,
            <<"http://jabber.org/protocol/commands">>,
            <<"http://jabber.org/protocol/disco#info">>,<<"jabber:iq:last">>,
            <<"jabber:x:data">>,<<"jabber:x:encrypted">>,<<"urn:xmpp:ping">>,
            <<"http://jabber.org/protocol/chatstates">>,
            <<"urn:xmpp:receipts">>,<<"urn:xmpp:time">>,
            <<"jabber:iq:version">>,<<"http://jabber.org/protocol/rosterx">>,
            <<"urn:xmpp:sec-label:0">>,<<"jabber:x:conference">>,
            <<"urn:xmpp:message-correct:0">>,<<"urn:xmpp:chat-markers:0">>,
            <<"urn:xmpp:eme:0">>,<<"http://jabber.org/protocol/xhtml-im">>,
            <<"urn:xmpp:hashes:2">>,
            <<"urn:xmpp:hash-function-text-names:md5">>,
            <<"urn:xmpp:hash-function-text-names:sha-1">>,
            <<"urn:xmpp:hash-function-text-names:sha-256">>,
            <<"urn:xmpp:hash-function-text-names:sha-512">>,
            <<"urn:xmpp:hash-function-text-names:sha3-256">>,
            <<"urn:xmpp:hash-function-text-names:sha3-512">>,
            <<"urn:xmpp:hash-function-text-names:id-blake2b256">>,
            <<"urn:xmpp:hash-function-text-names:id-blake2b512">>,
            <<"urn:xmpp:jingle:1">>,
            <<"urn:xmpp:jingle:apps:file-transfer:5">>,
            <<"urn:xmpp:jingle:transports:s5b:1">>,
            <<"urn:xmpp:jingle:transports:ibb:1">>,
            <<"urn:xmpp:avatar:metadata+notify">>,
            <<"urn:xmpp:message-moderate:0">>,
            <<"http://jabber.org/protocol/tune+notify">>,
            <<"http://jabber.org/protocol/geoloc+notify">>,
            <<"http://jabber.org/protocol/nick+notify">>,
            <<"urn:xmpp:bookmarks:1+notify">>,
            <<"urn:xmpp:jingle:apps:rtp:1">>,
            <<"urn:xmpp:jingle:apps:rtp:audio">>,
            <<"urn:xmpp:jingle:apps:rtp:video">>,
            <<"urn:xmpp:jingle:transports:ice-udp:1">>,
            <<"eu.siacs.conversations.axolotl.devicelist+notify">>]
2024-04-04 09:00:50.733085+02:00 [error] <0.2844.0>@ejabberd_hooks:safe_apply/4:324 Hook disco_local_features crashed when running mod_pubsub:disco_local_features/5:
** exception error: {unregistered_route,<<"pubsub.domain.tld">>}
   in function  ejabberd_router:host_of_route/1 (src/ejabberd_router.erl, line 280)
   in call from mod_pubsub:submodule/3 (src/mod_pubsub.erl, line 3712)
   in call from mod_pubsub:plugin_features/2 (src/mod_pubsub.erl, line 3781)
   in call from mod_pubsub:'-features/2-fun-0-'/3 (src/mod_pubsub.erl, line 3790)
   in call from lists:foldl/3 (lists.erl, line 1594)
   in call from mod_pubsub:features/2 (src/mod_pubsub.erl, line 3789)
   in call from mod_pubsub:disco_local_features/5 (src/mod_pubsub.erl, line 422)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 320)
** Arg 1 = {result,[<<"urn:xmpp:extdisco:2">>,<<"jabber:iq:privacy">>,
                    <<"urn:xmpp:jidprep:0">>,<<"urn:xmpp:carbons:2">>,
                    <<"urn:xmpp:carbons:rules:0">>,<<"urn:xmpp:blocking">>,
                    <<"msgoffline">>,
                    <<"http://jabber.org/protocol/offline">>]}
** Arg 2 = {jid,<<>>,<<"domain.tld">>,<<>>,<<>>,<<"domain.tld">>,<<>>}
** Arg 3 = {jid,<<>>,<<"domain.tld">>,<<>>,<<>>,<<"domain.tld">>,<<>>}
** Arg 4 = <<>>
** Arg 5 = <<>>
2024-04-04 09:00:50.774693+02:00 [error] <0.2810.0>@ejabberd_hooks:safe_apply/4:324 Hook c2s_terminated crashed when running mod_pubsub:on_user_offline/2:
** exception error: {unregistered_route,<<"pubsub.domain.tld">>}
   in function  ejabberd_router:host_of_route/1 (src/ejabberd_router.erl, line 280)
   in call from mod_pubsub:submodule/3 (src/mod_pubsub.erl, line 3712)
   in call from mod_pubsub:plugin_features/2 (src/mod_pubsub.erl, line 3781)
   in call from mod_pubsub:'-purge_offline/1-fun-0-'/4 (src/mod_pubsub.erl, line 4115)
   in call from lists:foldl/3 (lists.erl, line 1594)
   in call from mod_pubsub:purge_offline/1 (src/mod_pubsub.erl, line 4113)
   in call from mod_pubsub:on_user_offline/2 (src/mod_pubsub.erl, line 602)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 320)
** Arg 1 = #{mgmt_resend => if_offline,csi_state => active,
             owner => <0.2810.0>,stream_state => disconnected,
             replaced => true,resource => <<"gajim.XXX">>,
             shaper => c2s_shaper,
             codec_options => [ignore_els],
             lserver => <<"domain.tld">>,xmlns => <<"jabber:client">>,
             auth_module => ejabberd_auth_sql,access => local,
             mgmt_timeout => 300000,stream_compressed => false,
             stream_version => {1,0},
             pres_a => {0,nil},
             tls_enabled => false,conn => c2s_tls,
             jid =>
                 {jid,<<"user1">>,<<"domain.tld">>,<<"gajim.XXX">>,
                     <<"user1">>,<<"domain.tld">>,<<"gajim.XXX">>},
             pres_timestamp => {1712,214048,182136},
             socket_monitor => #Ref<0.250781615.971243521.57079>,
             mgmt_queue_type => ram,stream_authenticated => true,
             server => <<"domain.tld">>,
             tls_options => [compression_none],
             sasl_channel_bindings =>
                 #{<<"tls-exporter">> =>
                       <<126,210,9,54,120,253,55,32,112,44,47,173,72,180,129,
                         98,75,227,46,236,75,235,187,149,109,214,74,33,33,37,
                         58,203>>,
                   <<"tls-server-end-point">> =>
                       <<93,147,253,19,110,196,118,153,166,206,104,171,200,
                         117,138,167,88,69,46,65,233,3,188,103,170,165,78,202,
                         177,129,33,176>>},
             zlib => true,stream_header_sent => true,
             mgmt_ack_timeout => 60000,lang => <<"en">>,
             mgmt_max_queue => 5000,mgmt_stanzas_in => 20,
             ip => {{85,221,161,130},55062},
             mgmt_state => active,
             pres_last =>
                 {presence,<<"6000f890-3920-4ac2-a196-d7fa3aed585b">>,
                     available,<<"en">>,
                     {jid,<<"user1">>,<<"domain.tld">>,
                         <<"gajim.XXX">>,<<"user1">>,
                         <<"domain.tld">>,<<"gajim.XXX">>},
                     {jid,<<"user1">>,<<"domain.tld">>,<<>>,<<"user1">>,
                         <<"domain.tld">>,<<>>},
                     undefined,[],undefined,
                     [{xmlel,<<"c">>,
                          [{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},
                           {<<"hash">>,<<"sha-1">>},
                           {<<"node">>,<<"https://gajim.org">>},
                           {<<"ver">>,<<"vIHl9gQa/5BW5FeGc6bpAgXcxmY=">>}],
                          []},
                      {vcard_xupdate,undefined}],
                     #{ip => {85,221,161,130}}},
             stream_timeout => infinity,tls_verify => false,
             mgmt_id => <<57,51,151,23,62,183,229,47>>,
             stream_direction => in,
             socket =>
                 {socket_state,fast_tls,
                     {tlssock,#Port<0.3093>,#Ref<0.250781615.971374593.57080>},
                     1048576,#Ref<0.250781615.971374593.57078>,
                     {state,512000,512000,512000,1712214049230791},
                     {{{51,89,22,123},443},{{85,221,161,130},55062}},
                     <<"/opt/ejabberd/database/ejabberd@localhost/certs/c45c77a01c76433d03b47a3af24d0f4d5d443663">>},
             mgmt_stanzas_req => 22,tls_required => false,
             mgmt_queue => {{[],[]},0,unlimited},
             stop_reason =>
                 {stream,
                     {out,
                         {stream_error,conflict,
                             [{text,<<"en">>,
                                  <<"Replaced by new connection">>}]}}},
             stream_encrypted => true,user => <<"user1">>,
             mgmt_stanzas_out => 22,
             caps_resources =>
                 {2,
                  {{<<"user1">>,<<"domain.tld">>,<<"gajim.XXX">>},
                   {caps,<<"https://gajim.org">>,
                       <<"vIHl9gQa/5BW5FeGc6bpAgXcxmY=">>,<<"sha-1">>,[]},
                   nil,
                   {{<<"user2">>,<<"domain.tld">>,<<"gajim.XXX">>},
                    {caps,<<"https://gajim.org">>,
                        <<"vIHl9gQa/5BW5FeGc6bpAgXcxmY=">>,<<"sha-1">>,[]},
                    nil,nil}}},
             sid => {{1712,214044,29952},<0.2810.0>},
             csi_queue => {0,#{}},
             stream_restarted => true,mgmt_max_timeout => 300000,
             stream_id => <<"2134850421482982730">>,mod => ejabberd_c2s,
             mgmt_xmlns => <<"urn:xmpp:sm:3">>}
** Arg 2 = normal
``` 
</details>

## Bug description

I have a lot of errors in error.log with message "exception error: {unregistered_route,<<"pubsub.domain.tld">>}". Server works fine but sometimes I see in logs error "exception error: {unregistered_route,<<"domain.tld">>}" and users can't login to such domain (only 1, I have 2 another vhosts). Connections errors disappear itself after some time (~1h) or when I restart ejabberd.

I don't know how to fix it :/ The problem probably occurred with the version 24.02, previously there were no such errors in the logs.

**Comment by prefiks** [comment]
You have that "domain.tld" defined in your config file hosts: section? Are you using multiple cluster with multiple nodes, or is that just single server? Could you show your ejabberd.yml config file?

**Comment by beherit** [comment]
I have defined all domains in hosts section, this is just single server. Here is my config file:
```
######################
### Global Section ###
######################
hosts:
  - beherit.pl
  - jabber.eu.org
  - jix.im

auth_method: sql
auth_password_format: scram
captcha_cmd: /root/php-captcha.sh
captcha_url: https://xmpp.jix.im/captcha
default_db: sql
default_ram_db: sql
update_sql_schema: true

# Logging
loglevel: error
## log_modules_fully: [ejabberd_sm, mod_client_state]
hide_sensitive_log_data: true

# Disable X-OAUTH2 SASL mechanism
disable_sasl_mechanisms:
  - x-oauth2

# Certificates
acme:
  auto: false
certfiles:
  - "/opt/ejabberd/conf/ssl/*.pem"

#####################
### Define macros ###
#####################
define_macro:
  TLS_CIPHERS: ECDH:DH:!CAMELLIA128:!3DES:!MD5:!RC4:!aNULL:!NULL:!EXPORT:!LOW:!MEDIUM
  TLS_OPTIONS:
    - no_sslv2
    - no_sslv3
    - no_tlsv1
    - no_tlsv1_1
    - cipher_server_preference
    - no_compression
  DHPARAM_FILE: /opt/ejabberd/conf/dhparam.pem
  DISCO_EXTRA_DOMAINS:
    - upload.jix.im
    - muc.jix.im
    - fb.jix.im
    - gg.jix.im
    - icq.jix.im
    - skype.jix.im
  FB_JIX_IM_PASSWORD: moderated
  GG_JIX_IM_PASSWORD: moderated
  ICQ_JIX_IM_PASSWORD: moderated
  SKYPE_JIX_IM_PASSWORD: moderated

#####################
### Include files ###
#####################
include_config_file:
  - /opt/ejabberd/conf/acl.yml
  - /opt/ejabberd/conf/access.yml
  - /opt/ejabberd/conf/ports.yml
  - /opt/ejabberd/conf/modules.yml

############################
### OAuth2 configuration ###
############################
#oauth_expire: 2592000
#oauth_access: all
#oauth_client_id_check: db

##############################
### ReST API configuration ###
##############################
api_permissions:
  "console":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "php":
    from:
      - mod_http_api
    who:
      - ip: 127.0.0.1
    what:
      - registered_vhosts
      - reload_config
  "api":
    from:
      - mod_http_api
    who:
      - user: bot@jix.im
    what:
      - ban_account
      - change_password
      - check_account
      - check_password
      - get_presence
      - get_vcard
      - get_vcard2
      - incoming_s2s_number
      - kick_user
      - outgoing_s2s_number
      - private_get
      - private_set
      - register
      - registered_vhosts
      - send_message
      - set_last
      - stats
      - status
      - unban_ip
      - unregister

###########################
### MySQL configuration ###
###########################
host_config:
  beherit.pl:
    sql_type: mysql
    sql_server: localhost
    sql_port: 3306
    sql_database: beherit_pl
    sql_username: ejabberd
    sql_password: moderated
    sql_pool_size: 5
    sql_keepalive_interval: 600
  jabber.eu.org:
    sql_type: mysql
    sql_server: localhost
    sql_port: 3306
    sql_database: jabber_eu_org
    sql_username: ejabberd
    sql_password: moderated
    sql_pool_size: 5
    sql_keepalive_interval: 600
  jix.im:
    sql_type: mysql
    sql_server: localhost
    sql_port: 3306
    sql_database: jix_im
    sql_username: ejabberd
    sql_password: moderated
    sql_pool_size: 5
    sql_keepalive_interval: 600

``` 

acl.yml:
``` 
acl:
  admin:
    user:
      - im@beherit.pl
  anymuc:
    server_regexp:
      - "^conference\\."
      - "^muc\\."
  blocked:
##    server:
##      - example.org
    user:
      - user@example.org
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  poweruser:
    user:
      - deadmaster@jix.im
  transports:
    server:
      - xmpp.krzyssiek.waw.pl
  vip:
    user:
      - test@jix.im

append_host_config:
  jabber.eu.org:
    acl:
      host_admin:
        user:
          - admin@jabber.eu.org

``` 

access.yml:
```
access_rules:
  admin:
    - allow: admin
    - allow: host_admin
  authenticated:
    - deny: blocked
    - allow
  anymuc:
    - allow: anymuc
  configure:
    - allow: admin
    - allow: host_admin
  local:
    - allow: local
  muc_admin:
    - allow: admin
    - allow: host_admin
    - allow: poweruser
  transports:
    - allow: local
    - allow: transports

shaper_rules:
  soft_upload_quota: 120
  hard_upload_quota: 150
  max_user_offline_messages:
    - 4000: admin
    - 4000: host_admin
    - 2000: poweruser
    - 2000: vip
    - 1000
  max_user_sessions: 5
  c2s_shaper:
    - normal
  s2s_shaper: fast
  proxy_shaper:
    - none: admin
    - none: host_admin
    - none: poweruser
    - none: vip
    - proxy

shaper:
  normal: 512000
  proxy: 10485760
  fast: 1024000

```

ports.yml:
```
listen:
  -
    ip: "::"
    port: 3478
    module: ejabberd_stun
  -
    ip: "::"
    port: 5349
    module: ejabberd_stun
    turn_ipv4_address: "51.254.125.251"
    turn_ipv6_address: "2001:41d0:401:3000:0:0:0:5c50"
    use_turn: true
    tls: true
  -
    ip: 127.0.0.1
    port: 5443
    module: ejabberd_http
    ## use_proxy_protocol: true
    request_handlers:
      /admin: ejabberd_web_admin
      /v0/api: mod_http_api
      /api: mod_http_api
      /bosh: mod_bosh
      /captcha: ejabberd_captcha
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
      ## /oauth: ejabberd_oauth
  -
    ip: "::"
    port: 5222
    module: ejabberd_c2s
    max_stanza_size: 1048576
    shaper: c2s_shaper
    access: local
    starttls_required: true
    zlib: true
  -
    ip: 127.0.0.1
    port: 5223
    module: ejabberd_c2s
    use_proxy_protocol: true
    max_stanza_size: 1048576
    shaper: c2s_shaper
    access: local
    tls: true
    zlib: true
  -
    ip: "::"
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 5242880
    shaper: s2s_shaper
  ## Transports
  -
    ip: 127.0.0.1
    port: 5401
    module: ejabberd_service
    hosts:
      fb.jix.im:
        password: FB_JIX_IM_PASSWORD
    access: local
  -
    ip: 127.0.0.1
    port: 5403
    module: ejabberd_service
    hosts:
      gg.jix.im:
        password: GG_JIX_IM_PASSWORD
    access: local
  -
    ip: 127.0.0.1
    port: 5405
    module: ejabberd_service
    hosts:
      icq.jix.im:
        password: ICQ_JIX_IM_PASSWORD
    access: local
  -
    ip: 127.0.0.1
    port: 5407
    module: ejabberd_service
    hosts:
      skype.jix.im:
        password: SKYPE_JIX_IM_PASSWORD
    access: local
  ## port 7777 is configured by mod_proxy65

s2s_access: authenticated
s2s_ciphers: TLS_CIPHERS
s2s_dhfile: DHPARAM_FILE
s2s_protocol_options: TLS_OPTIONS
s2s_use_starttls: required

c2s_ciphers: TLS_CIPHERS
c2s_dhfile: DHPARAM_FILE
c2s_protocol_options: TLS_OPTIONS

#trusted_proxies: [127.0.0.1]

websocket_timeout: 3600
```

modules.yml:
```
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: admin
  mod_avatar:
    convert:
      webp: jpeg
      ## default: png
  mod_block_strangers:
    access: anymuc
    captcha: true
  mod_blocking: {}
  mod_bosh:
    max_inactivity: 300
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco:
    extra_domains: DISCO_EXTRA_DOMAINS
    server_info:
      -
        modules: all
        name: abuse-addresses
        urls:
          - mailto:abuse@jix.im
      -
        modules:
          - mod_disco
          - mod_vcard
        name: admin-addresses
        urls:
          - mailto:contact@jix.im
          - xmpp:im@beherit.pl
      -
        modules: all
        name: support-addresses
        urls:
          - mailto:contact@jix.im
          - xmpp:support@muc.jix.im?join
  mod_fail2ban:
    c2s_auth_ban_lifetime: 3600
    c2s_max_auth_failures: 5
  mod_http_api: {}
  mod_jidprep: {}
  mod_last: {}
  mod_mam:
    assume_mam_usage: true
    compress_xml: true
    default: always
    request_activates_archiving: true
    user_mucsub_from_muc_archive: true
  mod_offline:
    access_max_user_messages: max_user_offline_messages
    use_mam_for_storage: true
  mod_ping:
    ping_interval: 300
    send_pings: true
    timeout_action: kill
  mod_pres_counter: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    hostname: 51.254.125.251
    ip: "::"
    max_connections: 10
    shaper: proxy_shaper
  mod_pubsub:
    access_createnode: local
    plugins:
      - flat
      - pep
    force_node_config:
      "storage:bookmarks":
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_roster:
    store_current_id: true
    versioning: true
  mod_s2s_dialback: {} ## Legacy
  mod_stats: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_stun_disco:
    services:
      -
        host: xmpp.jix.im
        port: 3478
        type: stun
        transport: tcp
      -
        host: xmpp.jix.im
        port: 5349
        type: turns
        transport: tcp
  mod_time: {}
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version: {}

append_host_config:
  beherit.pl:
    modules:
      mod_register:
        access: none
        password_strength: 32
  jix.im:
    modules:
      mod_http_upload:
        custom_headers:
          Access-Control-Allow-Origin: "*"
          Access-Control-Allow-Methods: "OPTIONS, HEAD, GET, PUT"
          Access-Control-Allow-Headers: "Content-Type"
        dir_mode: "0755"
        file_mode: "0644"
        max_size: 20971520 ## 20 MB  
        put_url: https://xmpp.jix.im/upload
        thumbnail: true
      mod_http_upload_quota:
        max_days: 14
      mod_muc:
        access: all
        access_admin: muc_admin
        access_create: local
        access_persistent: muc_admin
        default_room_options:
          allow_change_subj: false
          allow_subscription: true
          allow_user_invites: true
          mam: true
          ## max_users: 50
          moderated: false
        hosts:
          - "muc.@HOST@"
        max_room_desc: 300
        max_room_id: 20
        max_room_name: 40
        ## max_users: 50
        min_message_interval: 0.4
        min_presence_interval: 4
      mod_muc_admin: {}
      mod_muc_occupantid: {}
      mod_muc_rtbl: {}
      mod_register:
        redirect_url: https://jix.im/signup/
        access: none
        password_strength: 32
  jabber.eu.org:
    modules:
      mod_muc:
        access: all
        access_admin: muc_admin
        access_create: local
        access_persistent: muc_admin
        default_room_options:
          allow_change_subj: false
          allow_subscription: true
          allow_user_invites: true
          mam: true
          ## max_users: 50
          moderated: false
        hosts:
          - "conference.@HOST@"
        max_room_desc: 300
        max_room_id: 20
        max_room_name: 40
        ## max_users: 50
        min_message_interval: 0.4
        min_presence_interval: 4
      mod_muc_admin: {}
      mod_muc_occupantid: {}
      mod_muc_rtbl: {}
      mod_register:
        redirect_url: https://jabber.eu.org/
        access: none
        password_strength: 32
```
