### ISSUE TITLE
Storage failures when prepared statements are enabled for MySQL

### ISSUE THREAD

**Issue by weiss** [processone/ejabberd#4226]
## Environment

- ejabberd version: ejabberd 24.02.131
- Erlang version: Erlang 14.2.5 (OTP 26.2.5)
- OS: Linux (Debian 12.5)
- DB: MariaDB 10.11.6 (Debian version: 1:10.11.6-0+deb12u1)
- Installed from: source

## SQL configuration

```yaml
sql_type: mysql
sql_server: localhost
sql_port: 3306
sql_username: ****************
sql_password: ****************
sql_pool_size: 4
sql_keepalive_interval: 3600
# […]
```

## Errors from error.log

```
[error] <0.1293.0>@ejabberd_sql:check_error/2:1393 SQL query 'Q122372114' at {mod_mam_sql,{325,11}} failed: <<>>
```

## Bug description

I'm running into failures [storing MAM messages][1] when [prepared statements][2] are enabled with MySQL/MariaDB (which is the default).  Unfortunately I don't know how to reproduce.  My impression is that it's unrelated to the MAM payload: I checked some of the failed cases, the payloads don't look unusual in any way, and I can't see an obvious pattern.  However, it happens once every few minutes on our production server, so I could easily test (debugging) patches.

I'm assuming it's not actually specific to MAM (it's probably just MAM being a busy table), as I've seen one or two cases of PubSub storage failures as well, but I'm not entirely sure here.

Setting `sql_prepared_statements: false` makes the errors go away.

[1]: https://github.com/processone/ejabberd/blob/7ba9f2e4e8c56cf109395b6cfa15466d02053ec0/src/mod_mam_sql.erl#L317C1-L328C47
[2]: https://github.com/processone/ejabberd/blob/7ba9f2e4e8c56cf109395b6cfa15466d02053ec0/src/ejabberd_sql.erl#L880C1-L897C39
