### ISSUE TITLE
mod_gw_matrix causing delay during login due to no answer to disco request

### ISSUE THREAD

**Issue by github-k8n** [processone/ejabberd#4310]
Before creating a ticket, please consider if this should fit the [discussion forum](https://github.com/processone/ejabberd/discussions) better.

## Environment

- ejabberd version: 24.10
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 15.0.1
- OS: Linux (Gentoo)
- Installed from: distro package

## Configuration
```

listen:
  -
    port: 8448 # Matrix federation
    ip: ADDRESSV4
    module: ejabberd_http
    tls: true
    request_handlers:
      "/_matrix": mod_matrix_gw
  -
    port: 8448 # Matrix federation
    ip: ADDRESSV6
    module: ejabberd_http
    tls: true
    request_handlers:
      "/_matrix": mod_matrix_gw

modules:
  mod_matrix_gw:
    key_name: "key1"
    key: "MYKEY XXXXX"
```

## Errors from error.log/crash.log

No errors

## Bug description

When enabling mod_matrix_gw, login with Conversations takes a long time (10-20s) until it shows "Online".
Without mod_matrix_gw, login is almost instantaneous.

Looking through the logs it seems that the module does not respond to disco requests.
It should at least return an empty disco#info response.

This missing response seems to cause the delay during login.
