### ISSUE TITLE
Sending messages to matrix lead to `exception error: no try clause matching false`

### ISSUE THREAD

**Issue by catap** [processone/ejabberd#4312]
## Environment

- ejabberd version: 24.10
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 14.2.5.3`
- OS: OpenBSD 7.6
- Installed from: source

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
...
listen:
...
  -
    port: 8448
    ip: "0.0.0.0"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/_matrix": mod_matrix_gw
  -
    port: 8448
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/_matrix": mod_matrix_gw
s2s_use_starttls: optional
s2s_access: s2s # to allow Matrix federation
...
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  s2s:
    - allow # to allow Matrix federation
...
modules:
...
  mod_matrix_gw:
    key_name: "REDACTED"
    key: "REDACTED"
...
```

## Errors from error.log/crash.log
```
2024-11-15 21:44:02.313508+01:00 [error] <0.2576.0>@ejabberd_hooks:safe_apply/4:460 Hook s2s_out_unauthenticated_features crashed when running mod_s2s_bidi:s2s_out_unauthenticated_features/2:
** exception error: no try clause matching false
   in function  mod_s2s_bidi:s2s_out_unauthenticated_features/2 (/usr/ports/pobj/ejabberd-24.10/ejabberd-24.10/src/mod_s2s_bidi.erl, line 85)
   in call from ejabberd_hooks:safe_apply/4 (/usr/ports/pobj/ejabberd-24.10/ejabberd-24.10/src/ejabberd_hooks.erl, line 456)
   in call from ejabberd_hooks:run_fold1/4 (/usr/ports/pobj/ejabberd-24.10/ejabberd-24.10/src/ejabberd_hooks.erl, line 403)
   in call from xmpp_stream_out:process_features/2 (/usr/ports/pobj/ejabberd-24.10/ejabberd-24.10/_checkouts/xmpp/src/xmpp_stream_out.erl, line 614)
   in call from xmpp_stream_out:handle_info/2 (/usr/ports/pobj/ejabberd-24.10/ejabberd-24.10/_checkouts/xmpp/src/xmpp_stream_out.erl, line 437)
   in call from p1_server:handle_msg/8 (/usr/ports/pobj/ejabberd-24.10/ejabberd-24.10/_checkouts/p1_utils/src/p1_server.erl, line 696)
   in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 241)
** Arg 1 = #{owner => <0.2576.0>,user => <<>>,
             socket =>
                 {socket_state,fast_tls,
                     {tlssock,#Port<0.439>,
                         #Ref<0.3363506774.4005953539.50943>},
                     infinity,#Ref<0.3363506774.4005953539.50927>,none,none,
                     <<"/var/db/ejabberd/certs/48c87d5889d2e6842df32b461f78aaa9117c8069">>},
             ip => {{94,237,52,46},5269},
             queue =>
                 {{[{message,<<"4144ae8e-ca5e-4867-9a76-be8c4ded585b">>,chat,
                        <<"en">>,
                        {jid,<<"kirill">>,<<"korins.ky">>,
                            <<"dino.d9c7fba2">>,<<"kirill">>,<<"korins.ky">>,
                            <<"dino.d9c7fba2">>},
                        {jid,<<"kirill.korinsky">>,<<"matrix.org">>,<<>>,
                            <<"kirill.korinsky">>,<<"matrix.org">>,<<>>},
                        [],[],undefined,
                        [{xmlel,<<"composing">>,
                             [{<<"xmlns">>,
                               <<"http://jabber.org/protocol/chatstates">>}],
                             []},
                         {xmlel,<<"no-store">>,
                             [{<<"xmlns">>,<<"urn:xmpp:hints">>}],
                             []}],
                        #{ip => {90,187,54,213}}}],
                   []},
                  1,unlimited},
             mod => ejabberd_s2s_out,server => <<"korins.ky">>,
             resource => <<>>,password => <<>>,
             codec_options => [ignore_els],
             shaper => none,lang => <<"en">>,stream_encrypted => true,
             remote_server => <<"matrix.org">>,server_host => <<"korins.ky">>,
             xmlns => <<"jabber:server">>,db_enabled => true,
             on_route => queue,stream_id => <<"5705784370585570676">>,
             stream_remote_id => <<"c1cbade5-887a-4a74-bb87-ac185c36128c">>,
             stream_state => wait_for_features,
             stream_version => {1,0},
             stream_timeout => -576433022578,
             socket_monitor => #Ref<0.3363506774.4005822467.50928>,
             stream_authenticated => false,stream_direction => out,
             stream_restarted => true,stream_verified => false}
** Arg 2 = {stream_features,
               [{xmlel,<<"mechanisms">>,
                    [{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>}],
                    [{xmlel,<<"mechanism">>,[],[{xmlcdata,<<"EXTERNAL">>}]}]},
                {xmlel,<<"dialback">>,
                    [{<<"xmlns">>,<<"urn:xmpp:features:dialback">>}],
                    []}]}
```

## Bug description

An attemp to send message to `kirill.korinsky@matrix.org` leafs to this crash.
