### ISSUE TITLE
Message archive isn't sync between two nodes.

### ISSUE THREAD

**Issue by catap** [processone/ejabberd#4325]
## Environment

- ejabberd version: 24.10
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 14.2.5.3`
- OS: OpenBSD 7.6
- Installed from: distro package

## Configuration (only if needed):

```yaml
modules:
  ...
  mod_mam:
    assume_mam_usage: true
    default: always
  mod_offline:
    access_max_user_messages: max_user_offline_messages
...
```

## Errors from error.log/crash.log

No errors

## Bug description

I run small jabber with two nodes and use two different clients (Monal on phone, and Dino on laptop), and just discovered that some messages from a user from the same jabber server available only on Monal, and some on Dino.

`ejabberdctl mnesia_table_info archive_msg` has a bit different output on nodes, differences are:
mx1:
```
...
 {load_reason,{active_remote,'ejabberd@mx2.catap.net'}},
...
 {memory,6396293},
...
 {size,2408},
...
```
vs mx2:
```
...
 {load_reason,initial},
...
 {memory,6402889},
...
 {size,2419},
...
```
Interesting that restart of ejabberd on mx1 leads to sync it. And after restart both one-by-one the only differences is:
```
...
 {load_node,'ejabberd@mx1.catap.net'},
...
 {load_reason,{active_remote,'ejabberd@mx1.catap.net'}},
...
```
vs
```
...
 {load_node,'ejabberd@mx2.catap.net'},
...
 {load_reason,{active_remote,'ejabberd@mx2.catap.net'}},
...
```
everything else is the same.
