### ISSUE TITLE
get_auto_url doesn't work with unix sockets

### ISSUE THREAD

**Issue by andreymal** [processone/ejabberd#4345]
Not sure if this is a bug report or a feature request, but after upgrading to Ubuntu 24.04 and ejabberd 23.10 I tried to use a unix socket with `ejabberd_http` because it is behind nginx and there is no point in using TCP:

```yaml
listen:
  -
    port: "unix://run/ejabberd/ejabberd_http.socket"
    unix_socket:
      mode: "0660"
    module: ejabberd_http
    tls: false  # handled by nginx
    request_handlers:
      /bosh: mod_bosh
      /captcha: ejabberd_captcha
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
      /admin: ejabberd_web_admin
    register: false
```

Unfortunately, this doesn't work:

```
[error] CRASH REPORT:
  crasher:
ejabberd_captcha:init/1
<0.392.0>
[]
bad argument
      in function  integer_to_binary/1
         called as integer_to_binary(<<"unix://run/ejabberd/ejabberd_http.socket">>)
not an integer
      in call from ejabberd_captcha:get_auto_url/3 (ejabberd_captcha.erl, line 515)
      in call from ejabberd_captcha:maybe_warning_norequesthandler/0 (ejabberd_captcha.erl, line 456)
      in call from ejabberd_captcha:get_prog_name/0 (ejabberd_captcha.erl, line 450)
      in call from ejabberd_captcha:is_feature_available/0 (ejabberd_captcha.erl, line 617)
      in call from ejabberd_captcha:check_captcha_setup/0 (ejabberd_captcha.erl, line 624)
      in call from ejabberd_captcha:init/1 (ejabberd_captcha.erl, line 294)
      in call from gen_server:init_it/2 (gen_server.erl, line 851)
```

I see two `get_auto_url` functions in the ejabberd code, both require `Port` to be an integer:

- https://github.com/processone/ejabberd/blob/a19ab9f4e3586d6298f739b88b9e624bc282f815/src/ejabberd_captcha.erl#L516
- https://github.com/processone/ejabberd/blob/a19ab9f4e3586d6298f739b88b9e624bc282f815/src/mod_host_meta.erl#L161

Is it technically possible to refactor `get_auto_url` so that I manually set the base url so that it no longer tries to interpret `Port` as an integer?

I already did this for captcha and http upload, but it would be nice to configure the whole `ejabberd_http` module.

```yaml
modules:
  mod_http_upload:
    put_url: "https://xmpp.andreymal.org/upload"
    get_url: "https://xmpp.andreymal.org/files"

captcha_url: "https://xmpp.andreymal.org/captcha"
```

**Comment by badlop** [comment]
> `port: "unix://run/ejabberd/ejabberd_http.socket"`

The syntax is unix: + path, for example: `port: "unix:/run/ejabberd/ejabberd_http.socket"`

> `register: false`

What is that? Where did you get the idea to add it?

> [error] CRASH REPORT:

Oops, it should handle that case and give a nice error message, instead of crashing like that. This can be considered a bug in ejabberd.

> Is it technically possible to refactor get_auto_url so that I manually set the base url 

Notice that get_url and put_url options in [mod_http_upload](http://127.0.0.1:8000/admin/configuration/modules/#mod_http_upload) support `@HOST@`, so you can configure something like this:
```yaml
put_url: "https://@HOST@:5443/upload"
```

Maybe captcha_url should support `@HOST@` too?

**Comment by andreymal** [comment]
> The syntax is `unix:` + path, for example: `port: "unix:/run/ejabberd/ejabberd_http.socket"`

If you're complaining about that double slash, I copied it from the official example https://www.process-one.net/blog/ejabberd-23-10/#new-unixsocket-listener-option

> What is that? Where did you get the idea to add it?

From the official example https://github.com/processone/ejabberd/blob/18.06/ejabberd.yml.example#L192

(I see this was removed in https://github.com/processone/ejabberd/commit/77163c43d243daadcc351a8b26ed3b285d379d80 but I created my ejabberd configuration in 2015 so it's been here all these 10 years 🙃)

> `@HOST@`

Not in my case, `@HOST@` is `andreymal.org` but I've published ejabberd http at `xmpp.andreymal.org`

**Comment by badlop** [comment]
> I copied it from the official example https://www.process-one.net/blog/ejabberd-23-10/#new-unixsocket-listener-option

Aha, thanks! I've fixed that example to match the syntax described in the documentation.

> From the official example https://github.com/processone/ejabberd/blob/18.06/ejabberd.yml.example#L192

Wow, I completely forgot that was supported in the past, and it's surprising that it's still supported.

I see it emits a warning since several years ago: https://github.com/processone/ejabberd/commit/a02cff0e780bb735531594c4ece81e8628f79782

```shell
2025-01-27 13:13:08.050728+01:00 [warning]
  Listening option 'register' is deprecated and was automatically
  replaced by HTTP request handler: "/register" -> mod_register_web.
  Please adjust your configuration file accordingly.
  Hint: run `ejabberdctl dump-config` command to view
  current configuration as it is seen by ejabberd.
```

Using deprecated options in a recent version reduces legibility of the configuration file, can you follow this and any other recommendations mentioned in the logs? At least if you share that configuration with other people and expect them to read it.

> `@HOST@` is `andreymal.org` but I've published ejabberd http at `xmpp.andreymal.org`

Ohh, ok. In that case it's impossible for `auto` to determine correctly the URL. For such scenarios, the solution is to set the URL manually, as you did.

---

If I understand correctly, you are thinking in some way of semi-automated option, right? That would be a new feature... let's imagine how it could be used, and later see what implementation work would require and if it's worth.

For example, that example configuration is not supported at all. If this were supported, would it be useful for your case?

```yaml
hosts:
 - andreymal.org
 - example.org

define_macro:
  HOST_NGINX: "xmpp.andreymal.org"

modules:
  mod_http_upload:
    put_url: "https://@HOST_NGINX@/upload"
    get_url: "https://@HOST_NGINX@/files"

captcha_url: "https://@HOST_NGINX@/captcha"
```

**Comment by andreymal** [comment]
My primary goal is to get the unix socket working, setting the base url is more of a “nice to have” to reduce duplication in the config, but this is not really important to me

In fact, my ejabberd configuration is generated by Ansible, and the source looks like `captcha_url: "https://{{ ejabberd_http_host }}/captcha"` where `ejabberd_http_host` is an Ansible variable, so I personally don't really need to use a macro ¯\\\_(ツ)_/¯

But I think your idea might be useful for other users who don't use Ansible

> At least if you share that configuration with other people and expect them to read it.

Good point, I removed `register:` from the issue text so as not to confuse other users

**Comment by zhidobandera** [comment]
I'm not sure if I should create a separate issue, but it seems like the unix socket isn't working at all. For example, I tried to set up a jabber server in the onion network with the following configuration:

**$ cat /etc/tor/torrc**
```
User tor
DataDirectory /var/lib/tor
HiddenServiceDir /var/lib/tor/hidden_service/
HiddenServicePort 5222 unix:/tmp/c2s.sock
HiddenServicePort 5269 unix:/tmp/s2s.sock
```
**$ cat /etc/ejabberd/ejabberd.yml**
```
hosts:
  - "abc.onion"

listen:
  -
    port: "unix:/tmp/c2s.sock"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: false
  -
    port: "unix:/tmp/s2s.sock"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
    shaper: s2s_shaper
```

The jabber client is configured to use the tor proxy (of course), but the connection doesn't work, and there are no attempts in the logs. I tried experimenting with the unix_socket option (which, by the way, has no documentation, only a mention in the changelog, which is strange lol). These experiments didn't lead to any result.
