### ISSUE TITLE
Empty database and missing users after upgrade "ecs" container to 25.03

### ISSUE THREAD

**Issue by Outsidewall** [processone/ejabberd#4366]
Docker environment
ejabber 24.12 -> 25.03 update. (from ejabberd/ecs)

Note have a small ejabber environment, approx 40 devices, internal network, not internet facing, all plain authed (scram).

Ejabber 24.12: Working fine, all client authenticating ok.

Did a docker image update to ejabberd 25.03, usuall restarts.

Now no clients authenticating, log excerpt:
Failed c2s PLAIN authentication for user@mysite from <IPAddress> Invalid username or password

Has there been a plain auth change/scam crypto change?
Have not found anything obvious in the change logs

Can anyone help. Thank you.

**Comment by ChaosKid42** [comment]
Might be related to https://github.com/processone/ejabberd/issues/4365.

**Comment by Outsidewall** [comment]
> Might be related to [#4365](https://github.com/processone/ejabberd/issues/4365).

Hello, Thank you, that is quite interesting. I'm however using files, rather than a sql db. Thus I wonder if there is something changed int the structure of the contents of the file. I suspect the only way is to recreate the file from new, add users and see if that fixes it.

**Comment by Outsidewall** [comment]
Just did a basic test, created a separate docker container, trashed the passwd.DAT file. Added a user. 
Result, works. A pain if you have a lot of users that you do not have control off, I do as they are bots running on my network, for my network, 25 raspberry pis :-)

So there must be a change to the passwd.DAT format.

**Comment by Neustradamus** [comment]
@Outsidewall: Can you replace all your "ejabber" to "ejabberd"?

**Comment by badlop** [comment]
I can reproduce the problem, it's present in the ecs container image, not in ejabberd image or binary installer or source.

The problem is not related to the mnesia tables content, just about the mnesia directory path, and was introduced in commit https://github.com/processone/docker-ejabberd/commit/339f7900a169c88e4ee0e80ecdd65a3cd08e1e41

Basically, the old mnesia database is available in the old path (`database/$NODENAME/`), ejabberd expects it in the new path (`database/`) which is empty, but the backwards-compatibility code doesn't work correctly. As a result, ejabberd finds an empty mnesia directory and creates a new mnesia database.

I'm looking for a workaround that you can apply easily.

**Comment by badlop** [comment]
The temporary workaround is to change this line in the file `/opt/ejabberd-25.03/bin/ejabberdctl` inside the contaier:
```diff
-: "${SPOOL_DIR:="$HOME_DIR/database"}"
+: "${SPOOL_DIR:="$HOME_DIR/database/$ERLANG_NODE"}"
```

One method for this is to download a copy of the `ejabberdctl` script which still didn't include the problematic change:

```bash
wget https://raw.githubusercontent.com/processone/docker-ejabberd/3019cb0faa90e95fb757cc57b9bf8e2ad52c17ec/ecs/bin/ejabberdctl
chmod +x ejabberdctl
```

and then use that script in your container.

Example, if you are using a kubernetes file in podman:

<details>

```yaml
apiVersion: v1

kind: Pod

metadata:
  name: ejabberd

spec:
  containers:

  - name: ejabberd
    image: ghcr.io/processone/ecs:25.03
    ports:
    - containerPort: 5222
      hostPort: 5222
    - containerPort: 1880
      hostPort: 1880
    volumeMounts:
    - mountPath: /home/ejabberd/database
      name: db
    - mountPath: /opt/ejabberd-25.03/bin/ejabberdctl
      name: ctl

  volumes:
  - name: db
    hostPath:
      path: database
      type: DirectoryOrCreate
  - name: ctl
    hostPath:
      path: ejabberdctl
      type: File
```
</details>
