### ISSUE TITLE
Oauth generation error in Docker image

### ISSUE THREAD

**Issue by timpisti** [processone/ejabberd#4390]
## Environment

- ejabberd version: 25.04
- Installed from: docker

## Bug description
After successful registering admin, and login to the web interface, the oauth token generation fail:
JID: Admin@localhost
TTL: 3600
Scope: *

Result: Error: badpass

default eyabberd.yml

**Comment by timpisti** [comment]
[SOLUTION] Since the documentation doesn't have one comprehend list of needed setups for oauth, I collect it:

```yaml

listen:
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /oauth: ejabberd_oauth
      /.well-known/acme-challenge: ejabberd_acme
  -
    port: "unix:sockets/ctl_over_http.sock"
    module: ejabberd_http
    tag: "ctl_over_http"
    unix_socket:
      mode: '0600'
    request_handlers:
      /ctl: ejabberd_ctl


oauth_expire: 3600
oauth_access: all

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
  admin:
    user: admin@example.com
    
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

api_permissions:
  "console commands over http":
    from:
      - tag: "ctl_over_http"
    who: all
    what: "*"
  "console commands":
    from: ejabberd_ctl
    who: all
    what: "*"
  "webadmin commands":
    from: ejabberd_web_admin
    who: admin
    what: "*"
  "adhoc commands":
    from: mod_adhoc_api
    who: admin
    what: "*"
  "http access":
    from: mod_http_api
    who:
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            - acl: admin
    what:
      - "*"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
  "admin access":
    who:
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
```

Now I able to generate oauth token.
