### ISSUE TITLE
Internal error of module mod_proxy65

### ISSUE THREAD

**Issue by hvostat** [processone/ejabberd#4395]
Hello dear eJabberD team,

## Environment

- ejabberd version: 25.04
- OS: Linux (Debian 12, Docker v.20.10.24)
- Installed from: ghcr.io/processone/ejabberd:25:04

## Configuration

```yaml
[...]
mod_proxy65:
  host: "proxy.domain.org"
  port: 8080
  access: local
```

## Errors from error.log/crash.log

2025-06-06 15:14:39.602 [debug] Loading mod_proxy65 at domain.org
2025-06-06 15:14:39.611 [critical] Internal error of module mod_proxy65
has occurred during start:
** Options: #{access => local,name => <<"SOCKS5 Bytestreams">>,port => 8080,
               recbuf => 65536,sndbuf => 65536,hosts => [],
               host => <<"proxy.domain.org">>,ip => undefined,
               hostname => undefined,shaper => none,ram_db_type => sql,
               vcard => undefined,auth_type => anonymous,
               max_connections => infinity}
** exception error: {module_not_loaded,mod_proxy65,<<"localhost">>}
    in function  gen_mod:get_module_opts/2 (src/gen_mod.erl, line 430)
    in call from gen_mod:get_module_opt/3 (src/gen_mod.erl, line 410)
    in call from gen_mod:db_mod/3 (src/gen_mod.erl, line 444)
    in call from mod_proxy65:start/2 (src/mod_proxy65.erl, line 59)
    in call from gen_mod:start_module/4 (src/gen_mod.erl, line 174)
    in call from lists:foreach_1/2 (lists.erl, line 2310)
    in call from gen_mod:start_link/0 (src/gen_mod.erl, line 101)
    in call from supervisor:do_start_child_i/3 (supervisor.erl, line 959)
2025-06-06 15:14:39.612 [critical] ejabberd initialization was aborted
because a module start failed.

## Bug description

After upgrading EJD to v.24.04 from v.18 the service fails to start with the error shown above.
Any changes in mod_proxy65 has no effect - the only way to make EJD to start is to remove mod_proxy65 directive completely.

**Comment by prefiks** [comment]
Hi,
Could you post your ejabberd.yml config file? Do you have this module declared only in host_config section?

**Comment by hvostat** [comment]
Hello Prefiks,
thanks for the swift reply.

Here is our conf file, please kindly take a look:

<details>

```yaml
#hosts:
#  - "localhost"

include_config_file: "/etc/ejabberd/hosts.yml"


auth_method: [ldap]
ldap_servers:
  - "ldap.domain.com"
ldap_base: "ou=it,o=domain,c=com"
[...]

default_db: sql
[...]

disable_sasl_mechanisms: ["X-OAUTH2"]

loglevel: 5
[...]

max_fsm_queue: 10000
cache_size: 20000

certfiles:
  - "/etc/ejabberd/certs/*.pem"

s2s_use_starttls: required

[...]
[...]
[...]

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco:
    extra_domains:
       - "conference.domain.org"
       - "proxy.domain.org"
    server_info:
       -
         modules: all
         name: "abuse-addresses"
         urls: ["mailto:abuse@domain.com"]
       -
         modules: all
         name: "admin-addresses"
         urls: ["mailto:p.admin@domain.com"]
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: "https://xmpp-share.domain.org/upload/@HOST@"
    docroot: "/srv/www/htdocs/xmpp-share.domain.org/upload/@HOST@"
    max_size: 10000000
    access: local
  mod_last: {}
  mod_mam:
    assume_mam_usage: true
    default: always
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - "flat"
      - "pep"
    force_node_config:
      "aaa.bbbs.conversations.ddd.*":
        access_model: open
      "storage:bookmarks":
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_roster:
    versioning: true
    cache_size: 100000
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

append_host_config:
  "domain.org":
    modules:
      mod_muc_admin: {}
      mod_muc:
        access:
          - allow
        access_admin:
          - allow: admin
        access_create: muc_create
        access_persistent: muc_create
        default_room_options:
          public: false
          public_list: false
          mam: false
        max_user_conferences: 100
        min_presence_interval: 4
      mod_proxy65:
        host: "proxy.domain.org"
        port: 8080
        access: local
        ip: "10.10.20.30"
```
</details>
