### ISSUE TITLE
Upgrading to 24.12 caused 5x memory consumption

### ISSUE THREAD

**Issue by obarash** [processone/ejabberd#4396]
## Environment

- ejabberd version: 24.12
- Erlang version: 14.2.1
- OS: Linux (Debian)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

## Bug description

After upgrading ejabberd from v22.10 to v24.12, we are seeing a major increase in memory consumption, making the system unstable without additional hardware.

System Setup:
	•	Cluster: 3 nodes initially, expanded to 6 nodes to mitigate issue
	•	Concurrent Users: ~3600 users total
	•	Previous Version: 22.10
	•	Current Version: 24.12
	•	Hardware: Each node with sufficient CPU and RAM capacity
	•	Database: AWS RDS (MySql)

Observed Behavior:

| State                                                     Number of Nodes | Total Memory Used | Memory per Node |
|-------------------------------------|-------------------|-------------------|--------------------|
| v22.10 (before upgrade)                    | 3                              | ~1.6 GB                  | < 1 GB                     |
| v24.12 (immediately after upgrade) | 3                              | ~2 GB                     | ~2 GB                      |
| v24.12 (after 4 hours)                        | 3                              | ~5 GB                     | ~1.7 GB                   |
| v24.12 (after scaling to 6 nodes)      | 6                             | ~9.4 GB                  | ~1.5 GB                    |

Steps Taken to Mitigate:
	•	Scaled cluster from 3 nodes → 6 nodes
	•	Performed rolling restarts to balance users across 6 nodes
	•	Current state is somewhat stable, but total memory use has increased nearly 6x compared to previous version (9.4 GB vs. 1.6 GB).

Notes:
	•	No significant change in number of concurrent users or traffic pattern.
	•	No configuration changes except for the version upgrade.

We need Guidance, is this  a known issue or configuration change required in v24.12 ?
Maybe some core module have new behavior that we need to consider ?

Here are some images to show the issues:

The change happened on 12:30:

![Image](https://github.com/user-attachments/assets/3f03e3d7-3f6e-4ff7-90ff-d2254ef45ac4)

Right before the changes:

![Image](https://github.com/user-attachments/assets/05ed2384-441c-4599-8d60-4cdb03af825f)

after a few hours:

![Image](https://github.com/user-attachments/assets/7f883792-5f04-4b00-8e93-7b02be8a4af6)

After we added 3 more machines, and reset the existing ones:

![Image](https://github.com/user-attachments/assets/9200850c-9e5e-4463-bd40-51c077abef15)

**Comment by licaon-kter** [comment]
Cleaned up config? SQL used? Details?

**Comment by obarash** [comment]
Regarding SQL I mentioned the DB used it AWS RDS, please aim me for specific details.

Previous Ejabberd version was **23.01** (not 22.10), I updated the orgiainl content

Config:

<details>

```yaml
###
###              ejabberd configuration file
###
### The parameters used in this configuration file are explained at
###
###       https://docs.ejabberd.im/admin/configuration
###
### The configuration file is written in YAML.
### *******************************************************
### *******           !!! WARNING !!!               *******
### *******     YAML IS INDENTATION SENSITIVE       *******
### ******* MAKE SURE YOU INDENT SECTIONS CORRECTLY *******
### *******************************************************
### Refer to http://en.wikipedia.org/wiki/YAML for the brief description.
###

language: "en"

hosts:
  - obarash.com

loglevel: info
log_rotate_size: 1048576000
log_rotate_count: 7

certfiles:
  - "/home/ejabberd/conf/domain.pem"
ca_file: "/home/ejabberd/conf/cacert.pem"

sql_type: mysql
sql_server: "mysql"
sql_database: "ejabberd"
sql_username: "ejabberd"
sql_password: "passwsord"
sql_port: 3306
sql_pool_size: 20
sql_keepalive_interval: 1
sql_start_interval: 5
sql_ssl: false
sql_ssl_verify: false
sql_ssl_cafile: "/tmp/cacert.crt"
new_sql_schema: false
update_sql_schema: false
default_db: sql
default_ram_db: mnesia
auth_method: sql

allow_contrib_modules: true
cache_size: 20000
max_fsm_queue: 30000


listen:
  - port: 5222
    ip: "::"
    module: ejabberd_c2s
    protocol_options:
      - "no_sslv2"
      - "no_sslv3"
      - "no_tlsv1"
      - "no_tlsv1_1"
    ciphers: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"
    starttls: true
    starttls_required: false
    tls_compression: false
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    use_proxy_protocol: false

  - port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288

  - port: 5443
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /upload: mod_upload
      /ws: ejabberd_http_ws
      /bosh: mod_bosh
    captcha: false
    use_proxy_protocol: false
    tls: false

  - port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /api/v0: mod_http_api
      /api: mod_http_api
    captcha: false
    use_proxy_protocol: false
    tls: false

  - port: 1111
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /metrics: mod_obarash_custom-1
    captcha: false
    use_proxy_protocol: false
    tls: false

s2s_use_starttls: optional


acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
  admin:
    user:
      - "admin@obarash.com"
      - "bot@obarash.com"


access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  register:
    allow: local
  trusted_network:
    allow: loopback


api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      # - ip: "172.19.170.0/24"
      # - ip: "172.19.140.0/24"
      # - ip: "172.18.64.0/23"
      - ip: "127.0.0.0/8"
      - access:
        - allow:
          - acl: loopback
          - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number


shaper:
  normal:
    rate: 3000
    burst_size: 20000
  fast: 100000


shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    500: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast


acme:
  auto: false
  contact: "mailto:hostmaster@obarash.com"
  ca_url: "https://acme-v02.api.letsencrypt.org/directory"


modules:
  mod_adhoc: {}
  # mod_admin_update_sql: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce

  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps:
    use_cache: true

  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  # mod_fail2ban: {}
  mod_http_api: 
    default_version: 0
  # mod_http_upload: {}
  mod_last: {}
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    db_type: sql
    assume_mam_usage: true
    default: always
    user_mucsub_from_muc_archive: true

  # mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: 
      - allow: admin
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_user_invites: false
      allow_subscription: true
      allow_change_subj: false
      allow_query_users: true
      allowpm: anyone
      mam: true
      members_by_default: true
      members_only: false
      logging: true
      persistent: true
      anonymous: false
      public: false
      presence_broadcast:
        - visitor
    history_size: 0
    max_users: 5000
    max_user_conferences: 5000
    preload_rooms: false

  mod_muc_admin: {
    subscribe_room_many_max_users: 4000
  }
  mod_offline:
    access_max_user_messages: max_user_offline_messages

  mod_ping:
    send_pings: true
    ping_interval: 60
    ping_ack_timeout: 30
    timeout_action: kill

  mod_privacy: {}
  # mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5

  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: false
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    max_items_node: 1000
    plugins:
      - flat
      - pep
    force_node_config:
      ## Change from "whitelist" to "open" to enable OMEMO support
      ## See https://github.com/processone/ejabberd/issues/2425
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
      obarash:roster:x:
        access_model: presence
        notification_type: normal

  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network

  mod_roster:
    versioning: true
    store_current_id: true
    db_type: sql
    cache_size: 80000

  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: true
    resume_timeout: 30
    max_ack_queue: 10000

  # mod_stun_disco: {}
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

  mod_obarash_custom-1: {}
  mod_obarash_custom-2: {}
  mod_obarash_custom-3: {}
  mod_obarash_custom-4: {}
  mod_obarash_custom-5: {}
  mod_obarash_custom-6: {}
  mod_obarash_custom-7: {}
  mod_obarash_custom-8: {}
  mod_obarash_custom-9: {}
  mod_obarash_custom-10: {}
  mod_obarash_custom-11: {}
  mod_obarash_custom-12: {}
  mod_obarash_custom-13: {}


### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8
```

</details>
