### ISSUE TITLE
Formatter crash in anonymous turn server

### ISSUE THREAD

**Issue by shibaobun** [processone/ejabberd#4403]
## Environment

- ejabberd version: `25.4.0`
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 14.2.1`
- Installed from: Docker (`ejabberd/ecs`)

## Relevant Configuration

```yaml
  -
    port: 3478
    ip: "::"
    transport: udp
    module: ejabberd_stun
    use_turn: true
    turn_min_port: 49950
    turn_max_port: 50059
    turn_ipv4_address: 184.105.31.71
    auth_type: anonymous
```

## Example of Errors from error.log/crash.log

```
ejabberd  | 2025-06-18T00:20:03.860333+00:00 notice: FORMATTER CRASH: {"~s [~s, session ~s, ~s, client ~s, relay ~s]",["Creating TURN allocation (lifetime: 599 seconds)",<<"UDP">>,<<"onnbl133keqw">>,[<<"user ">>,undefined],["xxx.xxx.xxx.xxx",":48362"],["184.105.31.71",":49956"]]}
ejabberd  | 2025-06-18T00:20:03.900255+00:00 notice: FORMATTER CRASH: {"~s [~s, session ~s, ~s, client ~s, relay ~s]",["Creating TURN allocation (lifetime: 599 seconds)",<<"UDP">>,<<"p1i4vheoro9a">>,[<<"user ">>,undefined],["xxx.xxx.xxx.xxx",":38553"],["184.105.31.71",":49958"]]}
ejabberd  | 2025-06-18T00:18:43.237159+00:00 notice: FORMATTER CRASH: {"~s [~s, session ~s, ~s, client ~s, relay ~s]",["Relayed 0 KiB (in 0 B / 0 packets, out 0 B / 0 packets), duration: 600 seconds",<<"UDP">>,<<"6irhpjom6ua4">>,[<<"user ">>,undefined],["xxx.xxx.xxx.xxx",":47919"],["184.105.31.71",":49978"]]}
ejabberd  | 2025-06-18T00:18:43.277164+00:00 notice: FORMATTER CRASH: {"~s [~s, session ~s, ~s, client ~s, relay ~s]",["Relayed 0 KiB (in 0 B / 0 packets, out 0 B / 0 packets), duration: 600 seconds",<<"UDP">>,<<"jfhtwoik8yql">>,[<<"user ">>,undefined],["xxx.xxx.xxx.xxx",":47776"],["184.105.31.71",":50028"]]}
```

## Bug description

This formatter crash happens on both udp or tcp with turn enabled, it seems to only be related to using `auth_type: anonymous`.

Please let me know if you need any additional information from my setup if this bug isn't reproducible. Hopefully it is straightforward to fix 😄
