### ISSUE TITLE
Fix nick logging in mod_muc_log plaintext

### ISSUE THREAD

**Issue by litewhatever** [processone/ejabberd#522]
Hello

If I configure mod_muc_log with file_format set to plaintext, then username/jid isn't logged to logfile. Logging works fine with file_format set to html.

I use following configuration

```
mod_muc_log:
  file_format: plaintext
  file_permissions:
    mode: 640
    group: 997
  outdir: "/some/directory/logs"
```

ejabberd version is 15.03

Regards,
Kristjan
