### ISSUE TITLE
Reloading MUC configuration doesn't seem to be working

### ISSUE THREAD

**Issue by scrogson** [processone/ejabberd#534]
I'm running ejabberd 14.07. I've added the `max_user_conferences` option to the `mod_muc` config because the default of `10` is too low. Here is the updated config in ejabberd.yml:

```yml
append_host_config:
  "im.host.com":
    modules:
      mod_register:
        access:
          all: deny
      mod_pubsub: []
      mod_muc:
        access: muc_admin
        access_create: muc_create
        access_persistent: muc_create
        access_admin: muc_admin
        max_user_conferences: 30
```

I attach to the debug console and reload the config:

```erlang
(ejabberd@localhost)1> ejabberd_config:load_file(<<"/etc/ejabberd/ejabberd.yml">>).
ok
```

Then check that the new value has been updated:

```erlang
(ejabberd@localhost)2> gen_mod:get_module_opt(<<"im.host.com">>, mod_muc, max_user_conferences, fun(I) -> I end, 10).
10
```

The default is still being returned rather than the updated value. Not sure how to fix this. If I restart the server it will pick up the change. I need to make this change in production and would prefer to keep the server running.

Is this a bug?
