### ISSUE TITLE
PEP issue

### ISSUE THREAD

**Issue by murugaprabum** [processone/ejabberd#615]
##### PROBLEM

I use PEP to broadcast profile picture and status updates to all contacts in a user's roster. Assume the user Alice publishes an event. All contacts in Alice's roster who are online receives the event immediately. The contacts in Alice's roster who are offline receive the event once they come online. 

The problem is that the published item of Alice is being broadcasted when ever a contact in Alice's roster comes online. 

Is it possible to stop delivering the same event to a contact if it has been already delivered ? 
 
##### EJABBERD CONFIGURATION

The ejabberd version is 15.04

```
mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ##ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ignore_pep_from_offline: false
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
```
