### ISSUE TITLE
Chat history not saving in database (PostgreSQL)

### ISSUE THREAD

**Issue by yashwanthbabu** [processone/ejabberd#627]
I am using postgres as my backend and connected to ejabberd. I created `ejabberd` database and created tables using `pg.sql` file in the database and in my configuration file i have done this:
```
odbc_type: pgsql
odbc_server: "localhost"
odbc_database: "ejabberd"
odbc_username: "ejabberd"
odbc_password: "ejabberd"
odbc_port: 5432
```
And I installed `mod_archive_odbc` module and using that as:
```
  mod_archive_odbc:
    database_type: pgsql
    default_auto_save: true
    enforce_default_auto_save: true
    default_expire: infinity
    enforce_min_expire: 0
    enforce_max_expire: infinity
    replication_expire: 31536000
```
Problem is I can see the `archive_messages` table in my DB and I can see the data in the table, i mean chat messages are not saving in the table. Archive related tables are:
```
archive
archive_collections
archive_global_prefs
archive_jid_prefs
archive_messages
archive_prefs 
```
How can I save the chat messages in the DB using PostgreSQL? Is the table which i am telling is correct?

Please help
