### ISSUE TITLE
xmlrpc no longer working

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#759]
We can no longer get xmlrpc to work. Something somewhere is broken. As far as I can tell, ejabberd always, for every command, answers:

```
Error -118
A problem '{error,account_unprivileged}' occurred executing the command check_account with arguments
[{host,<<"jabber.at">>},{user,<<"...">>}]
```

There is a matching entry in the logs:

```
2015-10-01 13:21:22.337 [warning] <0.28008.0>@ejabberd_xmlrpc:build_fault_response:386 Error -118
A problem '{error,account_unprivileged}' occurred executing the command check_account with arguments
[{host,<<"jabber.at">>},{user,<<"...">>}]
```

We use `include_config_file` to configure the module, the file can be found [here](https://github.com/jabber-at/config/blob/master/xmlrpc.cfg). With this config, we used this python code for the above call:

```
client.check_account({u'password': '....', u'user': '...', u'server': 'jabber.at'}, 
                     {'host': 'jabber.at', 'user': '...'})
```

One thing to note (with respect to #758) is that the ACL "xmlrpc" is also included from another config file.

We also tried restarting the module with just this configuration:

```
[{maxsessions, 10}, {timeout, 5000}]
```

and connect like above but without the first parameter (the authentication), and got exactly the same result and log entry from ejabberd.

Note that we have used the same Python client code for years, so I don't see how that code could be an issue.

**Comment by prefiks** [comment]
Hello Mathias,

You would probably need to add fragment like this somewhere in your config file:
```
acl:
  admin:
    user:
      - "username": "my.server.org"

...

access:
  xmlrpc_access:
    admin: allow

...

commands_admin_access:   xmlrpc_access
```

You can of course use existing access rule name for that instead of adding one.

**Comment by mathiasertl** [comment]
Hello,

Thanks for your reply. We already have an ACL and a access list. Note that both ACLs and access lists are included from another config file (if this is affected by #758?):

```
acl:
  xmlrpc:
    user:
      - "xmlrpc": "jabber.at"
access:
  xmlrpc:
    xmlrpc: allow
```

and then xmlrpc.cfg:

```
{listen, [
  {{4560, "fd00::63"}, ejabberd_xmlrpc, [{maxsessions, 10}, {timeout, 5000},
    {access_commands, [
      {xmlrpc, [register, set_last, check_account, check_password, change_password, send_message, registered_users, unregister], []}
    ]}
  ]}
]}.
```

The `commands_admin_access` option isn't documented anywhere - is this a new option?

**Comment by beherit** [comment]
I have similar problem with module mod_rest and commands_admin_access doesen't work.

**Comment by prefiks** [comment]
Yes `commands_admin_access` was added in 15.9 as part of adding oauth authentication to various commands consumers.

I will take look at `mod_rest`, it may need some changes to make it work with latest version.

**Comment by prefiks** [comment]
Krzysztofie could you please tell me what errors are you getting from mod_rest? I just tried it, and it works, even without setting `commands_admin_access` option.

**Comment by beherit** [comment]
I have such error (when executing check_account but problem is with all commands):
`
Problem 'error function_clause' occurred executing the command. Stacktrace: [{ejabberd_commands,is_admin, [check_account, {<<"bot">>,<<"mylogin">>, <<"mypassword">>}], [{file,"src/ejabberd_commands.erl"}, {line,578}]}, {ejabberd_commands,get_command_format,2, [{file,"src/ejabberd_commands.erl"}, {line,291}]}, {ejabberd_ctl,call_command,3, [{file,"src/ejabberd_ctl.erl"},{line,286}]}, {ejabberd_ctl,try_call_command,3, [{file,"src/ejabberd_ctl.erl"},{line,268}]}, {ejabberd_ctl,process2,3, [{file,"src/ejabberd_ctl.erl"},{line,217}]}, {mod_rest,maybe_post_request,3, [{file,"src/mod_rest.erl"},{line,92}]}, {mod_rest,process,2,[{file,"src/mod_rest.erl"},{line,52}]}, {ejabberd_http,process,5, [{file,"src/ejabberd_http.erl"},{line,371}]}]
`
In previous version everything working ok.

**Comment by prefiks** [comment]
Could you please include options that you have in `modules` section for `mod_rest`?

**Comment by beherit** [comment]
Maybe the problem is because the mod_rest requires authorization?
```
  mod_rest:
    allowed_ips:
      - "::FFFF:xxx.xxx.xxx.xxx"
    access_commands:
      bot:
        - change_password
        - check_account
        - check_password
        - getstatsdx
        - private_get
        - private_set
        - register
        - send_message
        - set_last
        - stats
        - unregister
    allowed_destinations: []
    allowed_stanza_types: []
```

**Comment by mathiasertl** [comment]
@prefiks Ok, I will try this on our next restart (saturday). If there are any fixes attached to this ticket, they will be included in that version. However please document `commands_admin_access` properly - and add a note to the release notes!

**Comment by prefiks** [comment]
Krzysztof, i think you aren't using mod_rest from https://github.com/processone/ejabberd-contrib/blob/master/mod_rest/src/mod_rest.erl but some modified version of that, can you confirm?

At lest i can't see how that version could lead to that crash you pasted earlier. I could probably help you with that, but would need to see your modifications.

**Comment by beherit** [comment]
@prefiks I don't use modified version. Module doesn't crash, it just don't return bad values (above is what I got after post data, in ejabberd 15.07 everything works).

**Comment by beherit** [comment]
@prefiks Problem doesn't occur when I turn off authorization (change access_commands to all).

**Comment by prefiks** [comment]
Ok, was able to reproduce when adding --auth to rest payload

**Comment by prefiks** [comment]
I just commited fix for that `mod_rest` problem. You would also need to setup `commands_admin_access` option with access rule that would grant permissions for user that you are using to make this work properly.

**Comment by beherit** [comment]
Thank you :)

**Comment by mathiasertl** [comment]
After restarting ejabberd 15.09 and adding the `commands_admin_access` option (I also have 24fa95fd60b139d17417aad932c89cf72f28c938 applied), I get the following error with my configuration:

```
CRASH REPORT Process <0.37.0> with 0 neighbours exited with reason: no function clause matching lists:foldl(#Fun<ejabberd_config.14.66512804>, {5222,{0,0,0,0},tcp,ejabberd_c2s}, {{4560,<<"fd00::63">>},ejabberd_xmlrpc,[{maxsessions,10},{timeout,5000},{access_commands,[{xmlrpc,...}]}]}) line 1260 in application_master:init/4 line 133
2015-10-08 08:36:27.727 [info] <0.7.0> Application ejabberd exited with reason: no function clause matching lists:foldl(#Fun<ejabberd_config.14.66512804>, {5222,{0,0,0,0},tcp,ejabberd_c2s}, {{4560,<<"fd00::63">>},ejabberd_xmlrpc,[{maxsessions,10},{timeout,5000},{access_commands,[{xmlrpc,...}]}]}) line 1260
```

Not including my xmlrpc.cfg fixes the issue. The file hasn't changed.

**Comment by mathiasertl** [comment]
PS: current config is current HEAD here: https://github.com/jabber-at/config

**Comment by prefiks** [comment]
I can reproduce this, switching xmlrpc to yaml (and adding definitions for some missing macros) allows loading this config, at least in current master version. Will try to see what broke old style config loading in included_files

**Comment by mathiasertl** [comment]
@prefiks according to the current docs, this config is not possible with YAML. But I'd obviously be happy to switch to it, if it happens to work. Can you show me what YAML config you used?

**Comment by prefiks** [comment]
That would be something like that:
```
listen:
  -
    port: 4560
    ip: "fd00::63"
    module: ejabberd_xmlrpc
    maxsessions: 10
    timeout: 5000
    access_commands:
      xmlrpc:
        commands:
          - register
          - set_last
          - check_account
          - check_password
          - change_password
          - send_message
          - registered_users
          - unregister
        options: []
```
