### ISSUE TITLE
Suggestion: ejabberd_http request_handlers, filter by request type.

### ISSUE THREAD

**Issue by LogicParrot** [processone/ejabberd#762]
Currently, ejabberd_http's `request_handlers` can filter requests by path, for instance:

```
    port: 5280
    module: ejabberd_http
    request_handlers:
       "/upload": mod_http_upload
```

However, filtering by request type is impossible. If I'd like to forward `put` requests to `mod_http_upload` but not `get` requests, I cannot achieve that.

A use case is described in https://github.com/processone/ejabberd-contrib/issues/126.
