### ISSUE TITLE
ODBC connection fails on default installation

### ISSUE THREAD

**Issue by skippy** [processone/ejabberd#891]
I am using the handy docker image created by [rroemhild](https://hub.docker.com/r/rroemhild/ejabberd) , which is a great way to get started with ejabberD.  This makes getting ejabberD setup with the default mysql driver fairly easy (though see https://github.com/processone/mysql/issues/7 for some timeout challenges with AWS RDS).  

However, I need to have ssl encryption for compliance purposes, but I'm having no luck using the ODBC driver.  

If my config includes the following, which uses the p1_mysql driver, it works like a charm (except the AWS timeout issue)

``` yml
host_config:
  "my_domain":
    odbc_type: mysql
    odbc_server: "{{ env['MYSQL_SERVER'] }}"
    odbc_port: 3306 # the default
    odbc_database: "ejabberd_{{ xmpp_domain }}"
    odbc_username: "{{ env['MYSQL_USERNAME'] }}"
    odbc_password: "{{ env['MYSQL_PASSWORD'] }}"
    odbc_keepalive_interval: 3600
    odbc_start_interval: 30
    odbc_pool_size: 5
```

But if I change it to:

``` yml
host_config:
  "my_domain":
    odbc_type: odbc
    odbc_server: "dsn=mysqldb;Database=ejabberd;Server={{ env['MYSQL_SERVER'] }};User={{ env['MYSQL_USERNAME'] }};Password={{ env['MYSQL_PASSWORD'] }}"
    odbc_keepalive_interval: 3600
    odbc_start_interval: 30
    odbc_pool_size: 5
```

or (with ssl)

``` yml
host_config:
  "my_domain":
    odbc_type: odbc
    odbc_server: "dsn=mysqldb;Database=ejabberd;Server={{ env['MYSQL_SERVER'] }};User={{ env['MYSQL_USERNAME'] }};Password={{ env['MYSQL_PASSWORD'] }};sslca=/opt/ejabberd/conf/rds-combined-ca-bundle.pem;sslverify=1"
    odbc_keepalive_interval: 3600
    odbc_start_interval: 30
    odbc_pool_size: 5
```

the logs explode with these error msgs:
(this is for the ssl version, but the error is exactly the same when sslca and sslverify are not included in the ODBC connection string)

```
2016-01-01 20:51:21 =ERROR REPORT====
** Generic server <0.448.0> terminating 
** Last message in was {<0.315.0>,{connect,[1,1,2,2,2,1,2,"dsn=mysqldb;Database=ejabberd;Server=chat-mysql.[KEY].us-west-2.rds.amazonaws.com;User=ejabberd;Password=LONG_PASSWORD;sslca=/opt/ejabberd/conf/rds-combined-ca-bundle.pem;sslverify=1"],on,off},infinity}
** When Server state == {state,#Port<0.4383>,{<0.315.0>,#Ref<0.0.0.11016>},<0.315.0>,undefined,on,undefined,undefined,off,connecting,undefined,0,[#Port<0.4381>,#Port<0.4382>],undefined,undefined}
** Reason for termination == 
** timeout
2016-01-01 20:51:21 =CRASH REPORT====
  crasher:
    initial call: odbc:init/1
    pid: <0.448.0>
    registered_name: []
    exception exit: {timeout,[{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,655}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [odbc_sup,<0.296.0>]
    messages: [{'EXIT',#Port<0.4383>,normal}]
    links: [#Port<0.4382>,<0.297.0>,#Port<0.4381>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 1532
  neighbours:
2016-01-01 20:51:21 =SUPERVISOR REPORT====
     Supervisor: {local,odbc_sup}
     Context:    child_terminated
     Reason:     timeout
     Offender:   [{pid,<0.448.0>},{name,[]},{mfargs,{odbc,start_link_sup,undefined}},{restart_type,temporary},{shutdown,7000},{child_type,worker}]
```

what is odd is that if I log into the docker container, open up `erl` and take the ODBC string outputted by the err msg and make a direct ODBC call... it connects without a problem.  example:

``` erlang
application:start(odbc).

{ok,Ref} = odbc:connect("dsn=mysqldb;Database=ejabberd;Server=chat-mysql.[KEY].us-west-2.rds.amazonaws.com;User=ejabberd;Password=LONG_PASSWORD;sslca=/opt/ejabberd/conf/rds-combined-ca-bundle.pem;sslverify=1", [{}]).

odbc:sql_query(Ref, "select version();").

odbc:sql_query(Ref, "show tables;").

odbc:disconnect(Ref).
q().
```

This seems like a bug within ejabberd, but i'm an erlang n00b, so I'm still learning about erlang (for example, it says it fails at `odbc:init` yet I can't find that call in the code base nor on http://www.erlang.org/doc/man/odbc.html).  Any thoughts/guidance?
