### ISSUE TITLE
Pubsub: Bug when defining the custom host and db_type as odbc 

### ISSUE THREAD

**Issue by beam-me-up** [processone/ejabberd#902]
```
mod_pubsub:
    db_type: odbc
    host: "dhinesh.@HOST@"
    access_createnode: pubsub_createnode
    plugins:
      - "hometree"
```
If I define a hostname other than pubsub, the code does not use the right db_type. it takes the default mnesia.

The function below is the root cause
```
serverhost(Host) ->
    case binary:match(Host, <<"pubsub.">>) of
	{0,7} ->
	    [_,ServerHost] = binary:split(Host, <<".">>),
	    ServerHost;
	_ ->
	    Host
    end.
```
