### ISSUE TITLE
Ping Manager giving 503 error

### ISSUE THREAD

**Issue by bangarharshit** [processone/ejabberd#939]
Hi Guys,

I am using ejabberd 15.11 with smack client 4.2 but it is giving 503 service-unavailable in server logs.

```
 packet {xmlel,<<"iq">>,[{<<"type">>,<<"error">>},{<<"to">>,<<"ejabberd.sandwitch.in">>},{<<"from">>,<<"ce22bf7d-2aeb-43a4-970b-c192b57a6652@ejabberd.sandwitch.in/smack">>},{<<"id">>,<<"821116761">>}],[{xmlel,<<"ping">>,[{<<"xmlns">>,<<"urn:xmpp:ping">>}],[]},{xmlel,<<"error">>,[{<<"code">>,<<"503">>},{<<"type">>,<<"cancel">>}],[{xmlel,<<"service-unavailable">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]}]}]} from {jid,<<"ce22bf7d-2aeb-43a4-970b-c192b57a6652">>,<<"ejabberd.sandwitch.in">>,<<"smack">>,<<"ce22bf7d-2aeb-43a4-970b-c192b57a6652">>,<<"ejabberd.sandwitch.in">>,<<"smack">>}
```

I am sending the pings from smack client every 7 minutes using alarm manager but it is disconnected by then.

```
mod_ping:
    send_pings: true
    ping_interval: 720
    ping_ack_timeout: 60
```

Let me know if you need more logs.

**Comment by mremond** [comment]
Are you sure the mod_ping is define in the correct module section ?
It does not seem indented in your example, which seems wrong.

**Comment by bangarharshit** [comment]
It is at one level of indentation. Since I just copied it the indentation went. I can see in logs that these values are loaded.

We are getting really strange issues now - when we are doing ping every 3 minute it is working fine but it is draining away battery. When we are pinging every 7 minutes now it is breaking the connection. The next time client sends the ping the server doesn't receive it (Sometimes we are getting the issue above 503. Strangely on all other occasions when we look up the server logs we can find the same packet id from previous session ping with a proper result result). We suspect two things now - a) ejabberd kills the connection. We are thinking of monitoring the c2s process using http://erlang.org/doc/apps/observer/observer_ug.html. Do you know any better tool or some better way of debugging? b) Our ISPs and router kill the connection idle for more than x minutes where x<7 but 7 minutes seems to be a good ping interval. 

```
  mod_offline: 
    access_max_user_messages: max_user_offline_messages
    db_type: odbc
  ## mod_ping: {}
  ## mod_pres_counter:
  ##   count: 5
  ##   interval: 60
  mod_ping:
    send_pings: true
    ping_interval: 720
    ping_ack_timeout: 60
```
