### ISSUE TITLE
problem with mod_pubsub in append_host_config

### ISSUE THREAD

**Issue by sezuan** [processone/ejabberd#955]
The following configuration doesn't work properly:

    append_host_config:
      "doma.in":
        modules:
          mod_pubsub:
            plugins:
              - "flat"
              - "pep"
    modules:
      mod_caps: {}

The log shows:

2016-02-15 10:04:32.217 [warning] <0.31597.4>@node_pep:complain_if_modcaps_disabled:258 The PEP plugin is enabled in mod_pubsub of host <<"doma.in">>. This plugin requires mod_caps to be enabled, but it isn't.

**Comment by badlop** [comment]
mod_pubsub's node_pep checks what modules are already loaded and started, not what ones are enabled in the config. And using append_host_config makes that mod_pubsub is enabled before the general modules (where you enabled mod_caps).

A workaround is to enable mod_caps in append_host_config too, that way it will be enabled even before mod_pubsub, and it won't complain:
```
append_host_config:
  "capulet.com":
    modules:
      mod_caps: {}
      mod_pubsub:
        plugins:
          - "flat"
          - "pep"
```
Another solution would be that mod_pubsub checks modules enabled in the config, regardless if they are already started ot not yet.
