### ISSUE TITLE
http-bind do not work with tls

### ISSUE THREAD

**Issue by kamenik** [processone/ejabberd#96]
Hi,

i am trying trunk version of ejabberd. I initialised tsl for http-bind as:

```
  -
    port: 5281
    module: ejabberd_http
    request_handlers:
       "http-bind": mod_http_bind
    certfile: "/srv/woc/ssl/keystore.pem"
    tls: true
```

when i access http://xxx.xxx.xxx:5281/http-bind

it returns no data and crash with this in log:

```
=CRASH REPORT==== 16-Sep-2013::15:45:33 ===
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.439.0>
    registered_name: []
    exception error: bad argument
      in function  binary_to_list/1
         called as binary_to_list("keep-alive")
      in call from jlib:tolower/1 (src/jlib.erl, line 293)
      in call from ejabberd_http:process_header/2 (src/ejabberd_http.erl, line 242)
      in call from ejabberd_http:parse_headers/1 (src/ejabberd_http.erl, line 209)
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.38.0>]
    messages: []
    links: [#Port<0.5193>,<0.330.0>,#Port<0.5190>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 1277
  neighbours:
```
