### ISSUE TITLE
v16.01 and mod_rest not working as it did in v15.07

### ISSUE THREAD

**Issue by abes-dabir** [processone/ejabberd#967]
Hi,

I've got a server running v15.07 and it is working exactly as I'd expect.  I've installed and enabled mod_rest on it.  I've defined a few commands in the access_commands that can only be accessed by admin.  A rest client can only access these by providing the correct authentication credentials.

Now for the problem.  I'm trying to setup a new v16.01 server that does the same as above, but it is behaving in the opposite manner to what I expect.  The commands that I've restricted can be accessed through REST **without** providing the authentication credentials.  Providing the credentials results in an error:
"Error: account_unprivileged"

I've got pretty much identical configuration on both servers, accounting for the different versions, hostnames, etc.  There are no errors or useful messages in any of the logs.  Here is the relevant fields:

```
acl:
  admin:
    user:
      - "admin": "<my_hostname>"

access:
  configure:
    admin: allow

modules:
  mod_rest:
    access_commands:
      configure:
        - registered_users
        - connected_users
        - register
        - unregister
```

The mod_rest configuration works.  I can't access any commands not listed there.  The only problem is the authentication.  I've spent more than an hour trying to jiggle the configuration into working, and I'm out of ideas.

HELP!
Thanks
