### ISSUE TITLE
mod_http_ws gives 502 gateway error when proxypassed by nginx

### ISSUE THREAD

**Issue by kamijoutouma** [processone/ejabberd#968]
isn't the page for it supposed to give an informative page to say its working and that only xmpp clients can use it?

```
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    http_bind: true
    request_handlers:
    ##   "/pub/archive": mod_http_fileserver
         "/http-ws": ejabberd_http_ws
    web_admin: true
    http_poll: true
    ## register: true
    captcha: true
```
https://im.ilp.moe/http-ws/
